### ISSUE TITLE
Question - Two images in horizontal block grammar

### ISSUE THREAD

**Issue by SCrolem** [LLK/scratch-blocks#1013]
Hi, i wanna know if it's possibel to have 2 images field on one motion block ? if yes, someone can give me some steps to get it working ? :) I was trying to make changes on block_render_svg_horizontal but although the idea is simple, it is confusing to me for make it work. like that
![motion_block](https://user-images.githubusercontent.com/15913751/28295029-b5bebf40-6b55-11e7-94dc-7849ce4dfd76.png)

(if it's to dificult dont worry i can figure out other way, but if it's simple help me plz)
thanks

**Comment by ericrosenbaum** [comment]
Sorry- this specific thing, displaying two images in one horizontal block, is not supported. The rendering code for horizontal blocks is designed to show a single icon.

Maybe you could display a single image that has two icons in it?

Can you say more about what you want to make?

**Comment by SCrolem** [comment]
thanks, and sorry taking so much time to answer it. I just wanted to know
if it was prepared to easly put one other img with the same dimensions ,
making that way 1 block with 2 imgs one only img and the other one with a
dropdown menu. The objective was to get 1 img static and the other one
changing with what was selected on the dropdown, In xml the objective was
to have the array arg0 for img 1 and array arg1 for the other img. Making 1
img with 2 icons it's a good solution but blocks img are 40x40 and changing
it the dropdown button will not be centered with that img :/, a fact is i
dont know well the blockly program and chaging it more than the basics make
alot bug's and errors come out and it's confuse me   I guess it's not
something easy to add if the program are not prepared. Who knows if it will
not be a good idea adding this feature to scratch horizontal blocks :) .
thanks anyway for the support :)


2017-07-28 18:47 GMT+01:00 Eric Rosenbaum <notifications@github.com>:

**Comment by ericrosenbaum** [comment]
In case you haven't looked at it, the "horizontal playground" example includes blocks that have an image on the block, and a dropdown menu. One of these is the "broadcast" block, which has a menu that lets you select a colored envelope. When you select one, the image on the block changes to that color. I guess this is similar to but not exactly the same as what you would like to do. I hope you can find a good workaround. Thanks!
