### ISSUE TITLE
Hidden workspace still responds to keyboard events

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1019]
### Expected Behavior

_Please describe what should happen_

A hidden workspace should not respond to keyboard undo/redo. 

### Actual Behavior

_Describe what actually happens_

After a call to `workspace.setVisible(false)`, you can still undo/redo using the keyboard. 

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Open the [vertical playground](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html)
2. Add some blocks, move some things around.
3. Press "Hide"
4. Undo using the keyboard (<kbd>cmd + z</kbd>)
5. Press "Show"
6. The last operation has been undone while the workspace was hidden.

**Comment by paulkaplan** [comment]
@rachel-fenichel  is there any legit use case for keeping that behavior? If not, should this be filed as a bug upstream on blockly?

**Comment by paulkaplan** [comment]
_update: submitted the following as https://github.com/LLK/scratch-blocks/pull/1020_

First impression fix would be to add a third short-circuit condition to `Blockly.onKeyDown_`, changing 
```javascript
Blockly.onKeyDown_ = function(e) {
  if (Blockly.mainWorkspace.options.readOnly || Blockly.utils.isTargetInput(e)) { ...
```
to 
```javascript
Blockly.onKeyDown_ = function(e) {
  if (Blockly.mainWorkspace.options.readOnly || Blockly.utils.isTargetInput(e) ||
    !Blockly.mainWorkspace.rendered) { ...
```

But it doesn't seem that `workspace.setVisible` sets the `rendered` property to false. Is that by design? Is there a different visibility check I could do? Or should I added `this.rendered = isVisible` to the end of the `setVisible` function?

**Comment by rachel-fenichel** [comment]
I need to check whether that's a valid use of `rendered`.  The comment on it says 
```
/**
 * The render status of an SVG workspace.
 * Returns `true` for visible workspaces and `false` for non-visible,
 * or headless, workspaces.
 * @type {boolean}
 */
Blockly.WorkspaceSvg.prototype.rendered = true;
```
but I'm not convinced that hidden rendered workspaces are the same as non-rendered workspaces at this point.  I'd rather have a `visible` attribute and have `rendered` only cover the difference between a `workspace` and a `workspaceSvg`.

**Comment by fsih** [comment]
I was pretty confused about the difference between rendered and isVisible when I was in this code before. When is a hidden rendered workspace supposed to exist?

**Comment by rachel-fenichel** [comment]
If you open the blockly playground and then click "hide", you have a hidden rendered workspace.

**Comment by ericrosenbaum** [comment]
I finally found a repro for the situation where this causes blocks to disappear unexpectedly:

- Click and drag a block or stack on the workspace
- Switch to costume editor (vector)
- Click a shape to select it
- Press the "delete" key to delete it
- Switch back to workspace, block or stack is gone!

**Comment by fsih** [comment]
@rachel-fenichel do you know if this issue is fixed? Is it something we still need to pull down from Blockly? Trying to figure out whether keyboard shortcut work in the costume/sound editors is still blocked.

**Comment by rachel-fenichel** [comment]
Not fixed, and not currently on anyone's schedule.  

It's a pretty straightforward problem; I recommend resurrecting my PR for this (google/blockly#1819) and fixing up what Andrew commented on, then submitting it as a PR on Blockly.

More discussion of it on the forum [here](https://groups.google.com/d/msg/blockly/wKt3J9xJeoA/c1o6P1zXAAAJ).
