### ISSUE TITLE
WidgetDiv height causes the page to scroll

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1023]
### Expected Behavior

_Please describe what should happen_

The widget div used for the color menu should not be tall enough to cause the page to scroll. This only happens in the GUI (not the vertical playground) because of css that is preventing it, but you can still see that the widget div height is very tall. 

### Actual Behavior

_Describe what actually happens_

the widget div seems to get a height about equal to the window height?
![image](https://user-images.githubusercontent.com/654102/28525099-12d4896c-7051-11e7-992c-3d6f31314247.png)

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Open the color menu and inspect the wrapping div, it has javascript height set on it. 

This was originally reported in https://github.com/LLK/scratch-gui/issues/560

**Comment by paulkaplan** [comment]
@rachel-fenichel It looks like the `WidgetDiv` component always uses the windowSize that is passed to it to set the height: https://github.com/LLK/scratch-blocks/blob/develop/core/widgetdiv.js#L221

The color menu knows the actual menu width/height, so we could allow those to be passed to WidgetDiv#position as well? 

I'm pretty suspicious of that line in general, git-blame shows it was added for a specific use-case (modals)?

Thoughts?

**Comment by rachel-fenichel** [comment]
I'm looking at this and https://github.com/google/blockly/issues/1242 because I think they're related.

**Comment by kyleplo** [comment]
Use `html, body {overflow: hidden}`

**Comment by towerofnix** [comment]
@kyleplo That would just be obscuring the problem, not solving it. And then it would be impossible to scroll on pages where Scratch 3.0 is embedded (e.g. microworlds).

**Comment by rachel-fenichel** [comment]
Fixed upstream.

**Comment by rachel-fenichel** [comment]
Should be fixed from the most recent merge.
