### ISSUE TITLE
[Design] When hovering sticky duplicated blocks over other blocks the gray shadow only shows one block instead of all of them

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-blocks#1027]
### Expected Behavior

After duplicating blocks, as the blocks follow the mouse, when you hover the blocks over other blocks the gray shadow that indicates where they're going to go should show all of the blocks, instead of just one block.

### Actual Behavior

Only one block appears

### Steps to Reproduce

![only one block](https://user-images.githubusercontent.com/28599280/28604357-b0db3046-71fc-11e7-8069-f53dd7bfe709.gif)

1. Right click a stack of blocks and select duplicate
2. Hover the sticky duplicated blocks over the original stack
3. There is a shadow that's the size of only one block

**Comment by thisandagain** [comment]
That happens in all instances of multiple blocks (a stack) being dragged into another stack. This was a conscious design decision to avoid issues where the stack being inserted can cause the target stack to move great distances on mouse over making it difficult to insert.
