### ISSUE TITLE
Toolbox lablels can cause flyout exception

### ISSUE THREAD

**Issue by Micircle** [LLK/scratch-blocks#1031]
![2017-07-31 16 02 26](https://user-images.githubusercontent.com/13041273/28768467-4d0d30d4-760a-11e7-8f69-bbf1dd51a116.png)
![2017-07-31 16 02 45](https://user-images.githubusercontent.com/13041273/28768468-4d3d372a-760a-11e7-9d8d-024984db24fb.png)
![2017-07-31 16 13 32](https://user-images.githubusercontent.com/13041273/28768709-3fee08fa-760b-11e7-97ed-e90ebd1ea49e.png)

When I use the label in the toolbox，the flyout‘s backgroundButtons_ will contain 'undefined' item.

**Comment by Kenny2github** [comment]
...why'd you immediately close this issue?

**Comment by Micircle** [comment]
I saw that the code had changed a lot.
I am not sure whether the problem still exists.
