### ISSUE TITLE
Toolbox layouts "top" and "bottom" are broken in toolboxes with categories

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-blocks#1038]
### Expected Behavior

_Please describe what should happen_
The blocks in the toolbox should be laid out when using "top" or "bottom" toolbox layouts with categories.

### Actual Behavior

_Describe what actually happens_
All of the blocks are rendered at the same coordinates, and are covered by the categories menu.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_
Visit any of these links:
* [Vertical Top LTR](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html?dir=ltr&toolbox=categories&side=top)
* [Vertical Bottom LTR](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html?dir=ltr&toolbox=categories&side=bottom)
* [Vertical Top RTL](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html?dir=rtl&toolbox=categories&side=top)
* [Vertical Bottom RTL](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html?dir=rtl&toolbox=categories&side=bottom)
* [Horizontal Top LTR](http://llk.github.io/scratch-blocks/playgrounds/tests/horizontal_playground.html?dir=ltr&toolbox=categories&side=top)
* [Horizontal Bottom LTR](http://llk.github.io/scratch-blocks/playgrounds/tests/horizontal_playground.html?dir=ltr&toolbox=categories&side=bottom)
* [Horizontal Top RTL](http://llk.github.io/scratch-blocks/playgrounds/tests/horizontal_playground.html?dir=rtl&toolbox=categories&side=top)
* [Horiztontal Bottom RTL](http://llk.github.io/scratch-blocks/playgrounds/tests/horizontal_playground.html?dir=rtl&toolbox=categories&side=bottom)

**Comment by rschamp** [comment]
@paulkaplan @rachel-fenichel Any hunches on when this broke?

**Comment by rachel-fenichel** [comment]
Probably when I implemented the two-column toolbox.

**Comment by RoboErikG** [comment]
Related, your multi-playground demo is completely broken...https://llk.github.io/scratch-blocks/playgrounds/tests/multi_playground.html

**Comment by rschamp** [comment]
Thanks @RoboErikG — that's logged at https://github.com/LLK/scratch-blocks/issues/764
