### ISSUE TITLE
Blocks menu with all the blocks in one flyout

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1040]
The new design for the blocks palette includes a single vertical scrolling flyout containing the blocks from all the categories, with labels and separators. This design works well with the vertical category menu (https://github.com/LLK/scratch-blocks/issues/1039).

Here's a [prototype](https://ericrosenbaum.github.io/scratch-gui/extension-categories/) version that includes both the vertical category menu and flyout containing all the blocks. And here's a gif:
 
![vert-toolbox-demo](https://user-images.githubusercontent.com/567844/28943848-4a8d3db6-786e-11e7-8f82-c61abd9585f0.gif) 

Implementation notes:

- [x] **Concatenate all the blocks** (like [this](https://github.com/ericrosenbaum/scratch-blocks/blob/78cd82f033429999b7617cc95049d0f6df27359a/core/toolbox.js#L191))

- [x] When you select a category by clicking the button, **auto-scroll** to the category, quickly but with easing so it slows down as it arrives. Note that the easing requires a magic number, which is the fraction of the remaining distance to cover at each animation step (0.3 seems pretty good). Also, the target position for the animation is cleared by scrollbar move events, so that you can interrupt the auto-scrolling. Commit [here](https://github.com/ericrosenbaum/scratch-blocks/commit/91bff9a5eb2f326430e33aae0faa5ea1bb437ba9).

- [x] **Update the selected item** in the category menu as the flyout scrolls into a new category. I implemented this by storing an array of objects with category position and category name fields, in flyout.show(). At each scroll event, I walk backwards down this array (i.e. starting with the bottom-most category) and check if the scroll position is below it, then set the selection state using the category name. Commit [here](https://github.com/ericrosenbaum/scratch-blocks/commit/a516a7e278eec9c418c9b9d61cd18eff30f475cf). Perhaps there's a better way to do this? 

- [ ] Showing all the blocks is slow. We should call flyout.show as few times as possible (ideally only once at startup). If we're not updating all the blocks when switching sprites, we need to make some **updates to the displayed value on sound, costume, and backdrop menus** (note that changes from the sound and costume editors will also need to trigger these updates). This is not an update to the full menu contents (that happens each time you click the menu): it only requires finding the first (or default) value of the menu.  Note that some dynamic menus do not require this update because their first item never changes (such as the “touching?” reporter and the “distance to” reporter, which always start with “mouse-pointer”). These changes are in the GUI, like [this](https://github.com/ericrosenbaum/scratch-gui/commit/0faca412f91858b54a3f66c76c6c2cf1f88cf9ef).

- [ ] We will need a **new strategy for adding and removing blocks** when switching to or from the stage, creating a variable, switching sprites to update the displayed local variable reporter blocks, and adding an extension. I think this will require a strategy that lets us update a single category, calculate its height, and re-position the rest of the categories without otherwise updating them. See notes from @rachel-fenichel in the doc [here](https://docs.google.com/document/d/1AHCxd481-eOD0FxDdLAxHWpJanwx62WiXoAnKGWGnDA/edit?usp=sharing).

**Comment by kyleplo** [comment]
I think this would be annoying and hard for new scratchers to use. See https://scratch.mit.edu/projects/172320061/

**Comment by maxiostro** [comment]
Perfect!

**Comment by ericrosenbaum** [comment]
Closing this because the changes were merged and the performance-related issues are tracked in https://github.com/LLK/scratch-blocks/issues/1069

**Comment by yi-jy** [comment]
Hi, Containing all the blocks in one flyout is a great feature. But i wonder Is there any way or variable to separate these blocks again?
