### ISSUE TITLE
 Dropping a duplicated block directly in the delete area will be error

### ISSUE THREAD

**Issue by Micircle** [LLK/scratch-blocks#1043]
![2017-08-10 16 54 47](https://user-images.githubusercontent.com/13041273/29162751-e8e34784-7dec-11e7-8b6c-da93de94938f.png)

### Operating System and Browser

_e.g. Mac OS 10.11.6 Chrome

@rachel-fenichel

**Comment by DIYOSEPP** [comment]
duplicateAndDrag violates the Gesture mechanism
whatever
This modification keeps the system working
https://github.com/DIYOSEPP/oseppBlock/commit/c5a567c182f749a702f08fa981174dc018db7a82

**Comment by rachel-fenichel** [comment]
Fixed by #1090
