### ISSUE TITLE
Flyout buttons and labels not correctly aligned for RTL

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1060]
### Expected Behavior

In the right-to-left language layout, elements are generally aligned to the right rather than the left.

### Actual Behavior

Buttons and labels in the flyout are still aligned left. For example, the "create variable" button here should be aligned to the right:

<img width="319" alt="screen shot 2017-08-28 at 3 24 45 pm" src="https://user-images.githubusercontent.com/567844/29789882-8bf5181e-8c05-11e7-9af8-2be2bfb76b91.png">

### Steps to Reproduce

Load the vertical blocks [playground](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html?dir=rtl&toolbox=categories&side=start) and select the "data" category.

### Operating System and Browser

Mac OS 10.11.6 Chrome 60.0

**Comment by rachel-fenichel** [comment]
Probably also an upstream issue.

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/issues/1208

**Comment by rachel-fenichel** [comment]
Fixed upstream.

**Comment by kchadha** [comment]
Resolved with #1668
