### ISSUE TITLE
Vertical category menu order is non-intuitive

### ISSUE THREAD

**Issue by ed-cooper** [LLK/scratch-blocks#1061]
### Current order

- Motion
- Looks
- Sound
- Pen
- Data
- Events
- Control
- Sensing
- Operators

### Proposed new order

- Events
- Control
- Motion
- Looks
- Sound
- Pen
- Sensing
- Operators
- Data

### Justification

Events are logically the first blocks you are going to need - they go at the top every script. Therefore they deserve to be at the top of the palette.
Then, I'd say control should go underneath as it contains all the fundamental control flow related blocks.
After those first 2 categories, the order is pretty much based around usage.

(Original proposal by infinitytec at https://scratch.mit.edu/discuss/post/2801592/ )

**Comment by Kenny2github** [comment]
The current order seems to be just going down the two previous colums - how about an order going across the rows?
* Motion
* Events
* Looks
* Control
* Pen
* Operators
* Data
* More?

**Comment by ericrosenbaum** [comment]
I made a PR for a temporary fix (not the final ordering, just an improvement): https://github.com/LLK/scratch-blocks/pull/1064

We'll track the design discussion in the future here: https://github.com/LLK/scratch-blocks/issues/1063
