### ISSUE TITLE
Duplicate variable monitors are created when switching to/from the Data category

### ISSUE THREAD

**Issue by Micircle** [LLK/scratch-blocks#1066]
![img](https://user-images.githubusercontent.com/13041273/29862962-c48d028a-8da0-11e7-9232-144be9d4c3f2.png)

**Comment by Kenny2github** [comment]
I was able to reproduce this:
1. Switch to the Data category.
2. Create a variable
3. Check the box to show it on the Stage.
4. Switch to a different category then switch back.
5. *The checkbox will be unchecked* and if you check it a *second watcher will appear* on the Stage.
6. Repeat 3-5 n times and n copies of the same watcher will show up on the Stage.
Interestingly, if you set the variable's value then the value will update for all of the watchers.

Repro-ed on Chrome 57 Raspbian Pixel Desktop.

**Comment by Kenny2github** [comment]
0.0 Furthermore, if you do it enough the monitors *leak outside the stage*??
![what](https://user-images.githubusercontent.com/28599280/29863877-8baaefd8-8da3-11e7-83e4-cc9d85d7fb59.png)
It also seems like creating a variable has the same effect as switching categories - and if you create more than 13-14 variables the watchers leak if you show them all:
![what](https://user-images.githubusercontent.com/28599280/29864084-403e9f3a-8da4-11e7-84f9-dc9124074196.png)

**Comment by rschamp** [comment]
@Kenny2github The monitor overflow issue is being tracked in https://github.com/LLK/scratch-gui/issues/463

**Comment by rschamp** [comment]
Moved to LLK/scratch-gui#658
