### ISSUE TITLE
text field in blocks just don't update after typed in a new number in example(need vm?)

### ISSUE THREAD

**Issue by joseeph** [LLK/scratch-blocks#1072]
Hi everyone,

I very new to blocky&scratch blocks's development, so if I said something silly, you guys could just ignore it.

I just compiled and running example('horizontal_playground.html'), anything is fine except for some blocks which got a text input field, it just don't update after typed in a new number.

This doesn't happen in pure blockly, do I need to include the 'VM' module?

best,
Joseph

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Chrome

**Comment by thisandagain** [comment]
Hi @joseeph I think this may be a bug with inputs in the horizontal grammar.

/cc @paulkaplan @rachel-fenichel @rschamp

**Comment by joseeph** [comment]
Hi @thisandagain, thank you for helping, if there is anything I could help, could you give me more details about how to fix it, I would like to share my effort. :p

**Comment by smaameri** [comment]
Hello, 

Experiencing this problem also. Happens in the horizontal playground. If you update an input, and remove focus from it, the input goes back to the original value. But then if you focus on it again, it shows you the value you put in.

Also if you generate the XML for the block, the input value in the XML shows the actual value that you have entered, not the original which is still being shown on the block input in the workspace.

**Comment by joseeph** [comment]
@smaameri once you changed the input value, could you get the updated value with generator?

**Comment by smaameri** [comment]
@joseeph yes the new input value is loaded in the generator

**Comment by joseeph** [comment]
@smaameri I couldn't get value from the generator, it shows error on the console, could you help to solve it? you could give more detail of how to implement generator under [#1086](https://github.com/LLK/scratch-blocks/issues/1086)

**Comment by joseeph** [comment]
@smaameri try this, see how magic happen.  seems like this issue has been solved [#826](https://github.com/LLK/scratch-blocks/issues/826)
