### ISSUE TITLE
Moving into "Create Variable" button a certain way makes it unclickable

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1073]
### Expected Behavior

When you place your mouse pointer outside the "Create Variable" button, just below the right padding, and quickly move it into the button, into the right padding, then the cursor should become "pointer" and the button should be clickable

### Actual Behavior

The button isn't clickable and the pointer remains on the default. It only switches cursor and becomes clickable when you hover over the actual text, and then you can move the cursor back to where it was (over the right padding) and it'll still be clickable there too

### Steps to Reproduce

1) Visit https://llk.github.io/scratch-gui/develop/
2) Click on the "Data" category
3) Hover your mouse just below the right padding (red dot)
4) Move it sharply up (if you let the pointer sit on the border, it won't work)
5) The cursor should now be on the right padding
6) The button isn't clickable (try clicking)
7) The cursor isn't a pointer (indicating it's not clickable)

It will however work if you

8) Move the cursor left, over the text
9) Move it back

### Operating System and Browser

Windows 10 Chrome 60.0.3112.113

---
Moved from LLK/scratch-gui#662
/cc @joker314 @fsih @paulkaplan @rschamp

**Comment by rachel-fenichel** [comment]
Possible dupe of https://github.com/LLK/scratch-blocks/issues/941

**Comment by Kenny2github** [comment]
@rachel-fenichel yeah, I’m pretty sure this is a duplicate.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/941

**Comment by msintov** [comment]
@thisandagain #1205 is also a dupe of this issue.
