### ISSUE TITLE
watch file changed and execute build.py

### ISSUE THREAD

**Issue by weishiji** [LLK/scratch-blocks#1076]
How can execute `python build.py` when the javascript file in blocks_vertical folder changed

**Comment by fsih** [comment]
There's no script to automate it currently. You have to run `npm run prepublish` after every change.

**Comment by weishiji** [comment]
but when i Frequently execute this command ,the server side tell me Compile failed

**Comment by thisandagain** [comment]
@weishiji Unfortunately the Closure Compiler that is hosted by Google is rate limited. Sorry about that. We are hoping to swap out the build system with something that does not require a network connection in the future.
