### ISSUE TITLE
In RTL, flyout labels and buttons should be right-aligned

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1077]
### Expected Behavior

In the right-to-left (RTL) language layout, the labels and buttons in the flyout should be right aligned, so that they mirror the style of the LTR flyout. 

### Actual Behavior

They remain left-aligned:

<img width="311" alt="screen shot 2017-09-07 at 5 00 49 pm" src="https://user-images.githubusercontent.com/567844/30185107-27cf827a-93ee-11e7-8d4a-40cefacae297.png">

### Steps to Reproduce

Visit the vertical blocks playground in [RTL mode](http://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html?dir=rtl&toolbox=categories&side=start).

**Comment by rachel-fenichel** [comment]
Is this an upstream issue?

**Comment by kchadha** [comment]
Resolved with #1668
