### ISSUE TITLE
Horizontal Grammar status/roadmap?

### ISSUE THREAD

**Issue by agurtovoy** [LLK/scratch-blocks#1084]
Hi!

Could someone please share/clarify the status of the horizontal grammar? I *think* I saw somewhere that it's currently on hold, but I might be imagining it. If it's still on the roadmap, is there interest in accepting (significant) external contributions on this? TIA!

**Comment by thisandagain** [comment]
Hello! We are very much still interested in and supporting the horizontal grammar, but have been focusing on the vertical grammar for a little while as we prepare to release Scratch 3.0. That said, many organizations such as Anki and Google have shipped products with the horizontal grammar. The Scratch team will be focusing on the horizontal grammar again later next year.

We are always happy to accept contributions. What sorts of things are you interested in?

**Comment by agurtovoy** [comment]
Hi Andrew! Thanks for the quick response. I'm considering a Scratch Blocks-based group project for my 4-year CS students and was thinking about making the horizontal grammar a part of the requirements. 

I'm still mulling this over and even if I go in this direction, it's a big question whether the outcome of our experiment would be worth anything to you guys, but I at least wanted to make sure that there isn't an active ongoing effort on this front and that there is interest in potential contributions.

**Comment by thisandagain** [comment]
That's great! Please keep us in the loop. 😄
