### ISSUE TITLE
No Generators for Blocks

### ISSUE THREAD

**Issue by smaameri** [LLK/scratch-blocks#1085]
Is there a reasons there are no generators for the different blocks that have been built? 

As in for all the different block types there are no generators, so for example in the verital_playground.html, if you want to convert the blocks to Javascript, you get the error:

`goog.asserts.AssertionError {message: "Assertion failed: Language "JavaScript" does not k…to generate code for block type "control_repeat".", reportErrorToServer: true, messagePattern: "Assertion failed: Language "%s" does not know how to generate code for block type "%s".", stack: "AssertionError↵    at new goog.asserts.AssertionEr…tch-blocks/tests/vertical_playground.html:574:81)"}
goog.asserts.DEFAULT_ERROR_HANDLER @ asserts.js:86
goog.asserts.doAssertFailure_ @ asserts.js:122
goog.asserts.assertFunction @ asserts.js:233
Blockly.Generator.blockToCode @ generator.js:176
Blockly.Generator.workspaceToCode @ generator.js:101
toCode @ vertical_playground.html:156
onclick @ vertical_playground.html:574`

**Comment by thisandagain** [comment]
Scratch does not use generators but rather an interpreter called 'scratch-vm' to execute blocks which has many advantages. I recommend you take a look at the VM codebase here:
https://github.com/llk/scratch-vm 

Generators are still supported, but you would need to implement them yourself.

**Comment by joseeph** [comment]
@smaameri could you teach me how you solve this issue, I'm facing the same issue.

**Comment by flzyup** [comment]
@thisandagain is there any simple tutorial to teach us how-to implements own generators?

**Comment by thisandagain** [comment]
@joseeph @flzyup You can look at the Blockly documentation for how to implement generators, but again this is not something we support:
https://developers.google.com/blockly/guides/configure/web/code-generators

**Comment by flzyup** [comment]
@thisandagain thanks

**Comment by ZooTopiaGG** [comment]
I also encountered the same problem, how did you solve it in the end?
