### ISSUE TITLE
How to get block input_value's for generators

### ISSUE THREAD

**Issue by smaameri** [LLK/scratch-blocks#1086]
How can we access the blocks input values in a generator?

Here is the Motion - Move Steps block definition:

`Blockly.Blocks['motion_movesteps'] = {
  init: function() {
    this.jsonInit({
      "message0": "move %1 steps",
      "args0": [
        {
          "type": "input_value",
          "name": "STEPS"
        }
      ],
      "category": Blockly.Categories.motion,
      "extensions": ["colours_motion", "shape_statement"]
    });
  }
};
`

if we create a generator for this block as:

`Blockly.Python['motion_movesteps'] = function(block) {
  var duration = block.getFieldValue('STEPS');
  return duration + '\n';
};
`

we would want the getFieldValue function to return the input value on the block. However the duration variable returns null.

I noticed in the Scratch block definition the type is 'input_value', as oppose to 'field_value' in Blockly, and that in the xml generated for that block the input value actually appears inside a 'shadow' tag.

So, is there is simple way to access this input value via the generator?

Many thanks for the help...

**Comment by smaameri** [comment]
Sorry, have solved this.

Was using getFieldValue instead of valueToCode.

Changing to valueToCode in the  generator has solved the problem. Final line to get input value looks like:

`  var duration = Blockly.Python.valueToCode(block, 'STEPS', Blockly.JavaScript.ORDER_ATOMIC) || '0'
`

**Comment by joseeph** [comment]
Hi @smaameri, did you implement shadow blocks in your app?  could you please share your xml configuration to me, I've been stuck in this issue for quite a while, thank you.

**Comment by smaameri** [comment]
@joseeph not sure what you mean by implementing shadow blocks. The shodow tags are automatically generated for certain blocks. Here is the XML for the Motion - Move Steps block, with an input value of 5. 

`<xml xmlns="http://www.w3.org/1999/xhtml">
  <variables></variables>
  <block type="motion_movesteps" id=";+k0SY_Vj-joLAFff4" x="235" y="203">
    <value name="STEPS">
      <shadow type="math_number" id="j~fjuvKa1F6EWYFXDLer">
        <field name="NUM">5</field>
      </shadow>
    </value>
  </block>
</xml>`

You see the shadow tag is automatically generated.

To access the input value for that block, the generator code looks like:

`Blockly.Python['motion_movesteps'] = function(block) {
  var duration = Blockly.Python.valueToCode(block, 'STEPS', Blockly.JavaScript.ORDER_ATOMIC) || '0'
  return duration + '\n';
};
`

And you will also need a math_number generator, to parse the code in the shodow tag.

`Blockly.Python['math_number'] = function(block) {
  // Numeric value.
  var code = parseFloat(block.getFieldValue('NUM'));
  var order;
  if (code == Infinity) {
    code = 'float("inf")';
    order = Blockly.Python.ORDER_FUNCTION_CALL;
  } else if (code == -Infinity) {
    code = '-float("inf")';
    order = Blockly.Python.ORDER_UNARY_SIGN;
  } else {
    order = code < 0 ? Blockly.Python.ORDER_UNARY_SIGN :
            Blockly.Python.ORDER_ATOMIC;
  }
  return [code, order];
};
`

**Comment by joseeph** [comment]
@smaameri sorry, I'm still couldn't understand quite well.
a block in scratch's configuration looks like this
```
 <block type="control_repeat">
          <value name="TIMES">
            <shadow type="math_number">
              <field name="control_repeat_times">10</field>
            </shadow>
          </value>
 </block>

```
should I just go like this?

`Blockly.Python['control_repeat'] = function(block) { var duration = Blockly.Python.valueToCode(block, 'TIMES', Blockly.JavaScript.ORDER_ATOMIC) || '0' return duration + '\n'; };`

**Comment by smaameri** [comment]
No, the control repeat is a statementToCode type, and needs a [different kind of generator](https://developers.google.com/blockly/guides/create-custom-blocks/generating-code), which is already written in the [blockly source](https://github.com/google/blockly/blob/master/generators/python/loops.js) code.

If you are not so familiar with that I suggest going through the entire [blockly guide](https://developers.google.com/blockly/guides/overview), and checking out the [blockly block  generator](https://blockly-demo.appspot.com/static/demos/blockfactory/index.html#) to get a better idea of how to configure scratch blocks.

Heres is the code for the control_repeat generator, as written in the blockly source code. You will also need a generator for the math_number part, and you'll see an error specifying 'math_number' for that if you dont have that generator in place.

> Blockly.Python['controls_repeat_ext'] = function(block) {
  // Repeat n times.
  if (block.getField('TIMES')) {
    // Internal number.
    var repeats = String(parseInt(block.getFieldValue('TIMES'), 10));
  } else {
    // External number.
    var repeats = Blockly.Python.valueToCode(block, 'TIMES',
        Blockly.Python.ORDER_NONE) || '0';
  }
  if (Blockly.isNumber(repeats)) {
    repeats = parseInt(repeats, 10);
  } else {
    repeats = 'int(' + repeats + ')';
  }
  var branch = Blockly.Python.statementToCode(block, 'DO');
  branch = Blockly.Python.addLoopTrap(branch, block.id) ||
      Blockly.Python.PASS;
  var loopVar = Blockly.Python.variableDB_.getDistinctName(
      'count', Blockly.Variables.NAME_TYPE);
  var code = 'for ' + loopVar + ' in range(' + repeats + '):\n' + branch;
  return code;
};



Blockly.Python['control_repeat'] = Blockly.Python['controls_repeat_ext'];

**Comment by joseeph** [comment]
@smaameri thank you so much for detailed explanation, in my case I just wanna define a common block with a text input field in horizontal mode, then get the input value.
