### ISSUE TITLE
Scripting Area + Blocks Palette overlapping on window resize

### ISSUE THREAD

**Issue by ttseng** [LLK/scratch-blocks#1088]
![resize_browser](https://user-images.githubusercontent.com/519336/30392196-f0c7263e-9870-11e7-8634-239aaae54a9b.gif)

### Expected Behavior

Expect the scripting area bounding area to resize based on browser window resize

### Actual Behavior

The scripting area starts to overflow into the blocks palette on window resize.

### Steps to Reproduce

Resize browser window and scroll the scripting area all the way to the left to see overflow

### Operating System and Browser

Mac OS 10.11.6 Chrome 60.0.3112.113

**Comment by rachel-fenichel** [comment]
Not a bug.  The blocks in the workspace go under the palette as you scroll.  It's part of having an infinite workspace.

Let `w` be the width of the visible workspace.
Let `boundingBox` be the bounding box of the blocks currently on the workspace.

You can always scroll to `boundingBox.left - w/2` and `boundingBox.right + w/2`.  

Similarly, you can scroll up an extra .5 * screen height above the highest block, and down .5 * screen height below the lowest block.

![ca04a20d-aaaa-401f-bf46-31967106d244](https://user-images.githubusercontent.com/13686399/30718858-44002ace-9ed6-11e7-86ee-c7eb0469670f.gif)
