### ISSUE TITLE
Dragging duplicated blocks onto the vertical category menu breaks dragging

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1089]
### Expected Behavior

Dragging a duplicated block over the category menu and clicking should delete the block and not select the category.

### Actual Behavior

The block is not deleted and the category menu changes.  The Gesture is left in a bad state.  

After that, clicking on the workspace drops the block on the workspace.  I can't start new Gestures.

![87358817-f4ea-464b-9917-5113b80fcf5c](https://user-images.githubusercontent.com/13686399/30406083-6629212e-98a4-11e7-849f-b9f8cb5808fd.gif)

### Steps to Reproduce

Do the following in the vertical playground on develop, or at https://llk.github.io/scratch-gui/develop/
1. Drag a block onto the workspace
2. Right-click the block
3. Select "Duplicate"
4. Move the mouse over the category menu
5. Click to drop/delete the block

### Operating System and Browser

Chrome, but it should happen on all non-touch browsers.

**Comment by paulkaplan** [comment]
It seems to come down to the mousedown handler in the toolbox calling `clearTouchIdentifier`, which seems to break the gesture. https://github.com/LLK/scratch-blocks/blob/develop/core/toolbox.js#L117-L127

@rachel-fenichel could you shed some light on what `clearTouchIdentifier` is used for here, the comment is somewhat cryptic (`// Don't block future drags.`)

**Comment by rachel-fenichel** [comment]
Hm, why would it be the mouse down handler?  The issue is a mouse up on the toolbox, but the mouse down should definitely be somewhere else.

That call to clearTouchIdentifier is because there is no corresponding mouse up handler, so that handler is the end of the click.  If the touch identifier were not cleared, future mouse downs would be ignored (which is what bindEventWithChecks_ does).

**Comment by paulkaplan** [comment]
> The issue is a mouse up on the toolbox

I think it has something to do with that mouse down on the toolbox: when you right-click -> duplicate, the block gets "fake dragged" so it is attached to your mouse, even though your mouse isn't down. Then you mouse down on the toolbox, and if you hold your mouse down and move it around you can see the block is already "stuck" to the toolbox. Here is a gif of that:
![stuck-block](https://user-images.githubusercontent.com/654102/31740592-cf21f58e-b41f-11e7-97c9-75f1fea652da.gif)

**Comment by rachel-fenichel** [comment]
Oh right, from the duplication.

Okay, then the solution is to get the current `Gesture` from the workspace and call `cancel` on it (and not do the normal mouse down behaviour).  You can get it with `workspace.getGesture(e)`.

If there is no current gesture, just run the current behaviour.
