### ISSUE TITLE
Support `flipRtl` as well as `flip_rtl` in block json

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1095]
Scratch-blocks has `flip_rtl` as an option on image fields.  

Blockly will be supporting this option but it will be named `flipRtl` to keep consistency with other JSON properties: https://github.com/google/blockly/issues/1339

Scratch-blocks should check the block definition for `flip_rtl` and `flipRtl`, to keep compatibility with current projects while using camelcase going forward.

**Comment by Clark-E** [comment]
@rachel-fenichel I'd like to help on this issue. Could you please provide me an example of a block json that uses flipRtl?

**Comment by rachel-fenichel** [comment]
Sure.  The `control_forever` [block](https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/control.js#L30) uses `flip_rtl` on the image field.
![image](https://user-images.githubusercontent.com/13686399/37301900-39364d10-25e7-11e8-8111-0968037285f7.png)

You can test your solution in the playground by toggling between LTR and RTL modes.

**Comment by Clark-E** [comment]
Thanks
