### ISSUE TITLE
"Point in direction" and "Point towards" don't have enough left padding

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-blocks#1099]
### Expected Behavior

`point in direction (num)` and `point towards [dropdown]` should have the same amount of padding as other blocks.

### Actual Behavior

They both don't have enough left padding:
![padding](https://user-images.githubusercontent.com/28599280/30916260-9226a918-a3cb-11e7-827b-b017bc2bd047.png)

### Steps to Reproduce

1. Open https://llk.github.io/scratch-gui/develop
2. Drag out a couple of motion blocks. plus the two aforementioned blocks
3. The two blocks don't have as much left padding as the rest

### Operating System and Browser

Chromium 57 Raspbian (Debian Linux) Desktop 8.9

**Comment by thisandagain** [comment]
This appears to be specific to Chromium 57 or Raspbian. Cannot reproduce in Chrome on MacOS or Windows.

**Comment by rachel-fenichel** [comment]
It also could be related to the font that is in use.

I've been looking at rendering code recently and I really don't know where this problem could have come from, but I'll keep an eye out for it.

**Comment by Kenny2github** [comment]
@thisandagain yes, I can't reproduce on Chrome 61 on Windows.
@rachel-fenichel that's probably it - Raspbian has severely limited fonts.

**Comment by rachel-fenichel** [comment]
@Kenny2github if you want to keep trying to repro you could figure out what font it's using on Raspbian, then force the Chrome on windows version to use that specific font and see what happens.

**Comment by Kenny2github** [comment]
@rachel-fenichel Hm, it seems like it doesn't have to do with the Raspbian font - it uses [the Ubuntu font](http://font.ubuntu.com/) and forcing that font with Inspect Element doesn't seem to have this effect:
![image](https://user-images.githubusercontent.com/28599280/31274835-48158e40-aac7-11e7-9107-0ec228f35fa8.png)
It might specifically be an issue with Chromium vs Chrome; or maybe Chrome/Chromium 57 vs latest.
Will continue trying to repro.

**Comment by Kenny2github** [comment]
Closing as this seems to not be reproducible:
![image](https://user-images.githubusercontent.com/28599280/33481668-83daf688-d6d0-11e7-8551-20ba18cca66d.png)
