### ISSUE TITLE
Implement "Define" blocks

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-blocks#1102]
The Define block should look like this: 
![image](https://user-images.githubusercontent.com/1512021/31085338-d3a1cfb6-a764-11e7-94b0-d38abfa8852d.png)

Behavior reference from Scratch 2.0 procedures (unless otherwise noted, 3.0 behavior should match 2.0):

Procedure with no arguments:
![image](https://user-images.githubusercontent.com/1512021/31085418-0be8a5ca-a765-11e7-8582-06d02fff0609.png)

Procedure with only arguments (no label):
![image](https://user-images.githubusercontent.com/1512021/31085424-104a281e-a765-11e7-93c5-15f47324f7ed.png)

Procedure with a label and three arguments, one of each type:
![image](https://user-images.githubusercontent.com/1512021/31085433-18f96164-a765-11e7-9d3e-c36e4ca5d65c.png)

Right-click on “define”:
![image](https://user-images.githubusercontent.com/1512021/31085450-2323d73c-a765-11e7-9c75-852e6fd3649b.png)

Right-click on “foo”:
![image](https://user-images.githubusercontent.com/1512021/31085459-2c525108-a765-11e7-816b-82bcee35b77c.png)

Right-click on empty space next to “foo” (inside the statement block outline):
![image](https://user-images.githubusercontent.com/1512021/31085470-33a1f3c8-a765-11e7-9927-9d9498473251.png)

Right-click on “number1” does nothing (**but in 3.0 should pop up the same context menu as above**): 
![image](https://user-images.githubusercontent.com/1512021/31085481-3e2bbfe0-a765-11e7-8d3d-e3da32462998.png)

Dragging the arguments out duplicates them:
![image14](https://user-images.githubusercontent.com/1512021/31085517-63237dba-a765-11e7-9bd6-7dbb47431a5f.gif)

Dragging from the outline of the defined block (here, “foobar”) moves the “define” block.  It doesn’t create a copy of the new block.
![image9](https://user-images.githubusercontent.com/1512021/31085565-8e07aaf6-a765-11e7-8096-cf93a835c0b2.gif)

**Comment by rachel-fenichel** [comment]
The "define" text is vertically aligned with the text and fields on the inner block, correct?

Are there types of inner blocks that would be taller than the one rendered above?
