### ISSUE TITLE
Custom fields for use within custom procedure definition workspace

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-blocks#1103]
Within the custom procedure definition workspace, we will need a couple of new fields to support the behavior below.

## Field label field
![image](https://user-images.githubusercontent.com/1512021/31087750-3681adde-a76c-11e7-8e82-1b7aed7c6407.png)

## Boolean input field
![image](https://user-images.githubusercontent.com/1512021/31087770-4dac40f0-a76c-11e7-9ad1-b117e839beb2.png)

## Text input field (here for completeness, but previously implemented)
![image](https://user-images.githubusercontent.com/1512021/31087762-467d1dc2-a76c-11e7-8d0b-674620defcce.png)

In addition, each of these fields should display a "delete" icon when they are focused:
![image](https://user-images.githubusercontent.com/1512021/31087858-9fc36b66-a76c-11e7-8fb9-125c7ba817eb.png)
![image](https://user-images.githubusercontent.com/1512021/31087873-b7288002-a76c-11e7-909a-d9b15e9ef2ad.png)
![image](https://user-images.githubusercontent.com/1512021/31087897-cb6bf5d0-a76c-11e7-8bcc-20bd8bcf2222.png)

**Comment by towerofnix** [comment]
Probably related - should these fields be draggable/reorderable, somehow? Reordering inputs and labels in a custom block definition is a bit of a pain right now. (For example, if you want to add a label or input at some spot in the block, you have to delete all labels and inputs positioned after the place you want the new one to be.)

**Comment by towerofnix** [comment]
Also, I believe it makes sense for there to be a way to add default values to inputs. Such default values would show up in the block palette.

Default values for custom block arguments is already a feature in Scratch 2.0, but there's no UI in the editor for it.

Since having default values is *very* useful for documentation, I think that there should be a way to add them into user-defined custom blocks. Take "(hello world) contains (hello)" -- its meaning is obvious because of its inputs. If a user were to define a custom block like this, it could only show as "() contains ()", because there is no way to add default input values.

(edit: I bring this up because it's certainly related to the implementation of these custom fields!)

**Comment by rachel-fenichel** [comment]
Text input field should be a shadow block with a text/number output and single text field (use the existing block, unless adding the delete button becomes an issue).
Boolean input field should be a shadow block with a boolean output and single text field (needs a new block):
```

Blockly.Blocks['boolean_single_field'] = {
  /**
   * Boolean-shaped block for text input, for use in
   * editing custom procedures.
   * @this Blockly.Block
   */
  init: function() {
    this.jsonInit({
      "message0": "%1",
      "args0": [
        {
          "type": "field_input",
          "name": "TEXT"
        }
      ],
      "extensions": ["colours_textfield", "output_boolean"]
    });
  }
};

```

Labels should be a new field type, `field_label_editable`.  (Not to be confused with the current `field_label_serializable`, so I'm open to new names.)  It will have the same `showEditor_` function as text input fields, and it will render the darker background behind the text.

@carljbowman is there a minimum width for each of these?

**Comment by rachel-fenichel** [comment]
The text in each of these fields is stored as a mutation for use in other blocks, so we also need to make sure that it's properly escaped (when I implement this).

**Comment by rachel-fenichel** [comment]
Current status:
![image](https://user-images.githubusercontent.com/13686399/32522184-2d9530bc-c3cb-11e7-8d4d-b305ef1da1fb.png)
![73371c57-e124-4ad0-8757-f2609c88adda](https://user-images.githubusercontent.com/13686399/32522191-32401974-c3cb-11e7-86f6-4e15f88cc751.gif)
![image](https://user-images.githubusercontent.com/13686399/32522219-50c1813a-c3cb-11e7-8e1c-93ebeddf893e.png)

Questions (@carljbowman):
- On the boolean text field, do I need to add more spacing around the text?
- On the boolean text field, does it need to be a hexagon while editing?  (I assume the answer is yes.)

**Comment by carljbowman** [comment]
@rachel-fenichel - Thanks for the update. Sorry I missed your min-width question. Not sure how that email got past me.

1. min-width: The min-width for all these inputs should be 10 grid units (40px)
<img width="579" alt="screen shot 2017-11-08 at 8 21 05 am" src="https://user-images.githubusercontent.com/3409578/32551217-c7cc434a-c45d-11e7-8151-2011836f483d.png">

2. boolean text spacing: Ideally this would be 4 grid units (16px) on each side. The slope of the hexagon is more dramatic than the curve of most other inputs, so it needs little more space.
<img width="423" alt="screen shot 2017-11-08 at 8 19 24 am" src="https://user-images.githubusercontent.com/3409578/32551145-8c787c14-c45d-11e7-8415-d2f8a24a8cc8.png">

3. boolean editing shape: Yes. (Assumed correctly). 👍

**Comment by rachel-fenichel** [comment]
When the user clicks the "add label" button, does it have any default text?

For now I'm going to give it default text because it makes the implementation easy, but I'm open to changing that.

**Comment by rachel-fenichel** [comment]
https://github.com/LLK/scratch-blocks/issues/1231 tracks the label editor + details
