### ISSUE TITLE
Single block workspace mode

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-blocks#1104]
This is needed for the custom procedure definition modal

If possible already through existing configuration please close with explanation of how to accomplish.

* Right clicking on the block in this workspace does nothing
* Horizontal scrolling only
* Single editable block on workspace
* Allow exporting the block definition
* Allow re-rendering based on a new block definition

The single block mode should support the fields defined in https://github.com/LLK/scratch-blocks/issues/1103

**Comment by rachel-fenichel** [comment]
> Single editable block on workspace

Just don't provide any ways to create new blocks (no toolbox or flyout).
You may also need to ignore keyboard copy/paste.
You probably also want to make the root block immovable and undeletable.

> Right-clicking on a block in this workspace does nothing

If defining your blocks with JSON, use:
  "enableContextMenu": false
Example: [text_create_join_item](https://github.com/google/blockly/blob/master/blocks/text.js#L92) block.

If defining it with JavaScript, in your init() use:
   this.contextMenu = false;
Example: [lists_create_with_container](https://github.com/google/blockly/blob/master/blocks/lists.js#L268) block.

Will you want to disable the workspace context menu as well?

> Re-rendering based on a new block definition

Your buttons will add new fields, inputs, etc by calling `mainBlock.appendValueInput(name).appendField(...)`, which will automatically cause a rerender.

> Allow exporting the block definition

You'll probably use [mutators](https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators) for this.  You'll define `domToMutation` and `mutationToDom` to look at all of the fields and inputs on the block and serialize them to XML (saving) or load them from XML.

Note that using mutators doesn't imply using the Blockly [mutation UI](https://developers.google.com/blockly/guides/create-custom-blocks/web/mutators#mutator_editing_ui).

> Horizontal scrolling only

Not yet implemented in the library, but I have a hack that we can use for prototyping.

**Comment by rachel-fenichel** [comment]
Whoa, someone already implemented horizontal scrolling for this?  Can I have the code?

**Comment by paulkaplan** [comment]
> Will you want to disable the workspace context menu as well?

Yes, we will want to disable the workspace context menu. I'll make a separate issue for that. 

> [horizontal scrolling] Not yet implemented in the library, but I have a hack that we can use for prototyping.

I'll create a new issue for that. 

I'm going to close this issue because the other things on this list have been implemented.
