### ISSUE TITLE
Category menu shows default scrollbar

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-blocks#1119]
### Expected Behavior

The category menu should have no scrollbar, except one that stays invisible until scrolling actually happens.

### Actual Behavior

The default scrollbar appears:
![image](https://user-images.githubusercontent.com/28599280/31304333-e1cd48e0-ab51-11e7-9654-dd8fd2051423.png)

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/develop

### Operating System and Browser

Windows 10 Chrome 61 - will try to repro on other OSes to see if it's OS-/browser-specific

**Comment by Kenny2github** [comment]
This seems to have been fixed - only the custom scrollbar appears, and only when needed. Closing.

**Comment by paulkaplan** [comment]
I do not think this was fixed, I'm going to reopen this to track the scrollbar looking strange/overlapping content, as noted at the end of https://github.com/LLK/scratch-blocks/issues/1058.

Different browsers seem to choose where to put the scrollbar differently. I got these two from chrome and firefox respectively on mac, with the system setting for "always show scrollbars" turned on (this is not the default system setting though, but Windows might be different).
![image](https://user-images.githubusercontent.com/654102/35815885-88733e06-0a67-11e8-9f2c-ca5de9546826.png)

![image](https://user-images.githubusercontent.com/654102/35815888-89f48a00-0a67-11e8-906e-733ab20be615.png)

**Comment by rachel-fenichel** [comment]
For debugging scrollbars on a mac, you'll get different behaviour if you do or don't have a physical mouse connected.  That may be why some people are no longer seeing this problem.  

On ubuntu with chrome I get really nasty scrollbars:
![image](https://user-images.githubusercontent.com/13686399/35822459-337b1226-0a61-11e8-9ac2-18d00478b019.png)

And in Firefox: 
![image](https://user-images.githubusercontent.com/13686399/35822503-5b12946c-0a61-11e8-955a-3cfa210a6b5b.png)

This stuff is why Blockly implements its own scrollbars, but they're too linked to the workspace to apply here.

**Comment by Kenny2github** [comment]
As far as I can tell, this is fixed - for one, it's hard to even get scratch-blocks into a situation where the categories might need to scroll (only easy way for me was to add extensions), and for two, the scrollbar doesn't appear at all anymore.
