### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1120]
Users should be able to add comments on blocks and on the workspace.

Scratch 2.0 comments:
- Can be dragged from one block to another
- Can be dragged from a block to the workspace and vice versa
- Are fixed position relative to their parent block
- Can be added (only?) through the context menu
- Can be minimized but not fully hidden
- Can be resized
- Move with their parent blocks during drags
- Can be dragged from any point on the comment except for the resize handle
- Can be duplicated through the context menu
- Do not duplicate when the parent block is duplicated
- Can be deleted through the right-click menu
- Can be deleted by dragging to the toolbox

Some Scratch 2.0 behaviour that we probably don't want to duplicate:
- In Scratch 2.0 multiple comments can be attached to a single block, but they are always stacked so that only one can be read at a time.
- There are no clear drag targets for dragging a comment to a block.  I experimented a bit and comments will attach to a block if the gray arrow on the comment is within the bounds of the first row of the block at the end of the drag.
- Multiple comments on a block stack are very hard to read, because they also stack on top of each other.

**Comment by ateesdalejr** [comment]
Just another thing I'd like to mention here. Currently in Scratch 2.0 when placing a comment on a rather wide stack of blocks the comment will be pushed very far away from the start of the block making it hard to read continuous comments.

**Comment by kchadha** [comment]
Closing as most of this was resolved by #1519, #1544, and #1575, and outstanding issues are being tracked separately.
