### ISSUE TITLE
Internally rendered custom command blocks can be overwritten

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1127]
### Expected Behavior

The internal blocks in custom procedure definitions shouldn't be replaceable (move blocks in this image).

![image](https://user-images.githubusercontent.com/13686399/31415832-a48094c0-adda-11e7-94cf-f0deba274106.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13686399/31415842-b3ca93fe-adda-11e7-8bb2-1f2dfcdbed24.png)

The problem occurs because all of the previous and next connections on existing blocks have the `null` type.  Adding a type check on the `custom_block` input is insufficient because the null type can connect to anything.

### Solutions
One solution is to add type information to every single next and previous connection, and give the define block's `custom_block` connection a different type.

I don't like that solution because if anyone fails to set their corrections correctly (e.g. when making blocks for extensions) they will see this problem reemerge.

Another solution is to add a `strict` or `no-wildcard` tag to connections, and use that tag here.

**Comment by paulkaplan** [comment]
@rachel-fenichel is the plan to wait on the upstream feature needed for this?

**Comment by rachel-fenichel** [comment]
I had been planning to chat about it in the meeting this week, which I forgot was cancelled.

What are your thoughts on the simple solution that I mentioned above?

> One solution is to add type information to every single next and previous connection, and give the define block's custom_block connection a different type.

**Comment by paulkaplan** [comment]
Well, I think the concern you listed is a big one. Particularly because we don't want people to be able to define blocks that would be able to be dropped into there. I would lean more towards the second option.

**Comment by rachel-fenichel** [comment]
I lean that way as well, but I don't have a good way of adding it to the JSON spec.  I'm going to chat with Neil about that today.  It's easy to add for inputs, but hard to add to previous and next connections.

**Comment by rachel-fenichel** [comment]
Whether that second concern is a real problem depends in large part on how you're planning to have people define blocks for extensions, etc.

**Comment by paulkaplan** [comment]
Closed by https://github.com/LLK/scratch-blocks/pull/1158
