### ISSUE TITLE
Custom procedure deletion

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1130]
### Expected Behavior

Scratch 2.0 behaviour:

When to delete:
- [x] Right-clicking on a custom procedure definition shows a "delete" option:
![image](https://user-images.githubusercontent.com/13686399/31470970-50a8e4ee-ae9b-11e7-880a-d3515ffebaad.png)
- [x] If there are no calls to the custom procedure, or if all of the calls are inside the definition, the procedure is deleted.
![image](https://user-images.githubusercontent.com/13686399/31471059-c854ae10-ae9b-11e7-9e34-2e911b1ddb6d.png)
_This function may be deleted_
- [x] If there are any calls to the custom procedure it cannot be deleted.  An error is shown:
![image](https://user-images.githubusercontent.com/13686399/31471099-e7e7a46c-ae9b-11e7-929e-17ecb3b19037.png)

- [ ] Right-clicking on a custom command block shows a "delete" option.  Selecting that option deletes the selected block, but not the custom procedure definition:
![image](https://user-images.githubusercontent.com/13686399/31470977-63b43534-ae9b-11e7-9e7a-989d80685013.png)

How to delete:
- [x] The define block and all of its children are removed from the workspace.
- [ ] The call block is removed from the toolbox.
- [ ] Some work is done in the VM (https://github.com/LLK/scratch-vm/issues/715)

**Comment by thisandagain** [comment]
Tracking remaining work in #1287
