### ISSUE TITLE
Uncaught TypeError: blockToDrag.onMouseMove_ is not a function

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-blocks#1159]
### Expected Behavior

The "Fake some drags!" thing in the [blocks playground](https://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html) should not raise errors

### Actual Behavior

When I click "Fake some drags!", I get the following error message:
```error
Uncaught TypeError: blockToDrag.onMouseMove_ is not a function
```

### Steps to Reproduce

1. Navigate to https://llk.github.io/scratch-blocks/tests/vertical_playground.html
2. Drag some blocks (or just use "Spaghetti")
3. Click "Fake some drags!"
4. Nothing happens - if you look in the console you see that error

### Operating System and Browser

Chromium 57 Raspbian Desktop

**Comment by rachel-fenichel** [comment]
Oops--that button shouldn't be there anymore, since it was for debugging a drag framework that no longer exists.  Want to remove it?

**Comment by Kenny2github** [comment]
@rachel-fenichel oh, I see. Sure, I can remove it if this is `help wanted` - where's the code for it?

**Comment by rachel-fenichel** [comment]
This code and the stuff it touches: https://github.com/LLK/scratch-blocks/blob/develop/tests/vertical_playground.html#L293

Thanks!
