### ISSUE TITLE
Problems occur when compiling blocks

### ISSUE THREAD

**Issue by chaoqinf** [LLK/scratch-blocks#1169]
### Expected Behavior

_Please describe what should happen_

### In Blockly. Generator. BlockToCode var func = in this [block. The type] will produce a undefined.

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by thisandagain** [comment]
We do not provide generators for `scratch-blocks` but rather provide an interpreter called [scratch-vm](https://github.com/llk/scratch-vm). If you would like to use generators, you will need to implement them yourself.
