### ISSUE TITLE
Dynamic population of blocks and flyout

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#119]
I think the capability to do this is mostly already available, but we should maybe think about how it should be generally approached.

I suspect we would like to structure our applications using scratch-blockly such that we can define and inject blocks outside the main Blockly package. For example, we will have Scratch extensions that can define arbitrary blocks. One approach for dealing with this could be injecting new blocks into Blockly.Blocks on runtime. This seems to be how blocks/\* works anyway, but I would like to confirm that this makes sense and won't break any assumptions Blockly may be making.

I also suspect we would like to choose what is populated in the flyout in a format that is not a fixed XML tree. For example, when users will add extensions that have new blocks, we'd like to dynamically feed the flyout the list of injected blocks to display. I believe we could generate a mini XML tree on the fly, and then feed it to `workspace.toolbox_.flyout_.show`, but would also like to confirm that this makes sense or if we should implement some special functionality.

@thisandagain @rachel-fenichel @NeilFraser

**Comment by thisandagain** [comment]
Depends on #21

**Comment by tmickel** [comment]
Better described in #682.
