### ISSUE TITLE
Script area scrolling is very slow in Firefox

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1190]
### Expected Behavior

Scrolling with the scroll wheel happens at the same speed as in the block palette.

### Actual Behavior

Scrolling is much slower.

### Steps to Reproduce

Add a block to the scripting area so that the scrolling speed is clear, then use the scroll wheel to scroll.

### Operating System and Browser

Firefox 57.0 on Debian (Testing).

**Comment by towerofnix** [comment]
It should be noted that scrolling is *generally* captured very slowly on Firefox, in terms of Scratch 3.0 - for example, panning the paint editor with the scrollwheel is very slow, as is zooming in and out (in both the paint editor and scratch-blocks).

**Comment by paulkaplan** [comment]
Ugh, it probably has something to do with this: https://developer.mozilla.org/en-US/docs/Web/API/WheelEvent/deltaMode

Firefox is the only browser that for some reason still uses `line` mode instead of `pixel` mode, and so all scrolling has to be checked against the delta mode. :(

**Comment by towerofnix** [comment]
Relatedly, on Firefox on a MacBook, trackpad scrolling is extremely *fast* **in the palette**. So the block palette has a separate but similar issue. (Perhaps there's code to make the palette scroll faster when on Firefox, but on a MacBook+trackpad that faster scrolling is not necessary?)
