### ISSUE TITLE
`variableType` attribute in XML breaks because of case (in)sensitivity

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1191]
_Note: this is blocking bringing back the `list` blocks_

### Expected Behavior

_Please describe what should happen_

When trying to get the list blocks working, I encountered an error with trying to use `variableType` as an xml attribute. It is automatically downcased to `variabletype` and then cannot be read back using `getAttribute`. 

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Create a variable in the playground and add a `set <var> to` block to the workspace. 
2. Export to XML
3. Note how the xml is generated with lowercase `variabletype=""`
4. Change the `variabletype` to "list" and try to import the XML again. 
5. If you put a break at line 617 of xml.js, you will see that the it tries to read `variableType` from an xml element with `variabletype`, and it fails to read the property. 

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Chrome, Mac

@rachel-fenichel I would expect this might be a problem upstream as well.

**Comment by rachel-fenichel** [comment]
See https://github.com/LLK/scratch-blocks/commit/eed4e33f845f842dfcd001508ddb442ffe55abdb#commitcomment-25202380
