### ISSUE TITLE
Undoing procedure edits

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1194]
Scratch 2.0 can't undo/redo procedure edits.

Should Scratch 3.0 be able to undo/redo procedure edits?  If not, what's the specific reason to avoid it?

**Comment by towerofnix** [comment]
First thoughts are that it definitely should support undoing a procedure edit; after all, it's possible one might accidentally make an edit which *removes* an input, thus messing up old scripts. In that case, being able to undo would be very helpful.
