### ISSUE TITLE
Testing - Automate and update jsunit test suite

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#12]
Test suite will need to be updated to reflect new grammar, blocks, and generators. While doing so, we should automate the `jsunit` and `jslint` testing via [Travis-CI](https://travis-ci.org/) which should help with open source contribution quite a bit.

**Comment by tmickel** [comment]
@thisandagain Do you think we're ready to have eslint run with Travis? I'd be pretty happy if that was working, even if it doesn't yet pass the linter. Seeing the tests failing would be a good motivator to fix it up... :) Don't know how to set it up (or if I can), though.

**Comment by thisandagain** [comment]
@tmickel Agreed. That sounds great. You are an admin so you should be able to enable Travis for this repo from your https://travis-ci.org settings page.

**Comment by tmickel** [comment]
Ok, I did that! Not sure how to do jsunit but I'll look into that also for a bit

**Comment by tmickel** [comment]
Hmmm, given the weirdness of the closure jsunit setup and the small number of tests, I wonder if it might even be worth it just to rewrite the tests using our normal test framework...

**Comment by RoboErikG** [comment]
We're also looking into Travis on the Blockly side. It's not moving very fast, but we'll let you know if we get anything working there.
