### ISSUE TITLE
Add Extension Icon support to block rendering

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#1207]
Splitting from https://github.com/LLK/scratch-gui/issues/815

### Icon on blocks spec
This is a hi-res (300%) PNG for zooming on measurements. Extension Icons on blocks will need some special treatment when it comes to alignment and spacing.

In all cases the Vertical height of extension blocks will be taller than their "standard" block counter-parters. E.g. Command blocks with extension icons are 8px (2units) taller than a Command block without an extension icon.

**Something to Consider**
We will have similar needs to dynamically grow blocks vertically with "[input first](https://github.com/LLK/scratch-blocks/issues/1206)" blocks. Some languages reorder block parameters (e.g. Korean) and place inputs as the first element on a block. In these cases we will need to add addtional vertical padding so that the top notch does not overlap the input.

![r1_extension-icon-spec](https://user-images.githubusercontent.com/3409578/32376958-a8b1d13a-c07c-11e7-9833-e13701a0baf8.png)

**Comment by rachel-fenichel** [comment]
Input first blocks will still have the icon before the first input, right?  If so, the first input on an extension block will be past the notch (based on position of icon + bar).

**Comment by rachel-fenichel** [comment]
Does the vertical bar get taller as the block gets taller?  For instance, in this block would the vertical bar's height be based on a distance from top and bottom, or is it a fixed height?
![image](https://user-images.githubusercontent.com/13686399/32514062-be7e0c90-c3b0-11e7-8796-cafff45e85a7.png)

**Comment by carljbowman** [comment]
@rachel-fenichel - Thanks for the initial thoughts and questions.

1. Extension icons should always be the first element on extension blocks. So the "input first" stuff is not a real issue for anything that is an Extension.

2. Thanks for clarifying. No, the vertical bar does not need to get taller as blocks are nested. That can be a fixed height.

**Comment by rachel-fenichel** [comment]
For a stack block with an extension icon, the icon is moved down by one grid unit from where it would normally be.  Does that one-grid-unit offset remain as the block gets taller?  E.g.
![image](https://user-images.githubusercontent.com/13686399/34015746-4c19ee26-e0d4-11e7-87f9-2810642d2643.png)

Spec:
![image](https://user-images.githubusercontent.com/13686399/34015774-626b9760-e0d4-11e7-80f4-94d54f299428.png)
