### ISSUE TITLE
When replacing number/boolean inputs, new blocks should come to front

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-blocks#1208]
_This issue was reported in scratch-gui: https://github.com/LLK/scratch-gui/issues/765

But I believe it belongs in scratch-blocks instead._

Copying from [jwzimmer](https://github.com/jwzimmer)'s original report:

### Expected Behavior

When number (inputs) are replaced by other blocks, the replaced blocks should pop to the front.

### Actual Behavior

When numbers replaced by other blocks, the replaced blocks should pop to the front. Instead they pop to the back behind the stack of blocks.

### Steps to Reproduce

Introduce a control block which accepts a number or sensing/boolean parameter. 

Add a number or sensing/boolean parameter (not just typed text).

Add several blocks inside/below the control block.

Now drag in a replacement number or sensing/boolean block as a parameter.

Notice how the replaced block is bumped not just in x and y, but also bumped to behind the other blocks.

[fsih](https://github.com/fsih)'s visual example:

![31632258-46a71d9c-b28a-11e7-9ce5-ca40b6e96c47](https://user-images.githubusercontent.com/3431616/32398778-ba0a2234-c0c7-11e7-831c-ece741ed5863.gif)

### Operating System and Browser

Mac OS 10.12.6 Chrome Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by rachel-fenichel** [comment]
Definitely a scratch-blocks issue, but is it specific to number/boolean blocks?

**Comment by rachel-fenichel** [comment]
Also, I suggest closing this and continuing discussion on https://github.com/LLK/scratch-blocks/issues/937

I brought up exactly this issue on there already.

**Comment by benjiwheeler** [comment]
(continuing on #937)
