### ISSUE TITLE
Horizontal block grammar features

### ISSUE THREAD

**Issue by smaameri** [LLK/scratch-blocks#1210]
Regarding the horizontal blocks, would like to know if 'If/Else' blocks are supported? I could not find a way to create an If/Else block.

Also, is it possible to have block inputs in the horizontal version, i.e can we drag a block into another block for it to be an input into that block? For example in the photo below, we have dragged the 'Math +' block into the 'Wait' block. Does the horizontal support such a feature. Again, could not find a way to build such a block.

<img width="226" alt="screen shot 2017-11-05 at 6 19 55 pm" src="https://user-images.githubusercontent.com/1417939/32415629-ff16558e-c255-11e7-9746-9f1d73a6b415.png">

So for example for an 'IF' block, we would need a statment block like the one below, but one that is also able to accept another block as the conditional. Is such a feature supported in the horizontal grammar? If not, could you give an idea of the complexity to build in such a feature. I am guessing that it is not so simple to build in.

<img width="163" alt="screen shot 2017-11-05 at 6 25 39 pm" src="https://user-images.githubusercontent.com/1417939/32415692-07b3ebb0-c257-11e7-842a-ec0ed46fecd5.png">

Also, is it possible to have 2 inputs, or two dropdown inputs on a single block? For example the block below takes a single input. Is it possible to create a 'longer' single block that will take two different inputs?

<img width="126" alt="screen shot 2017-11-05 at 6 22 54 pm" src="https://user-images.githubusercontent.com/1417939/32415650-6163b466-c256-11e7-914f-b461433b408b.png">

**Comment by thisandagain** [comment]
Hi @smaameri we don't have any plans to add conditionals or operators to the horizontal grammar as that seems contrary to some of our design goals for making it work for young children (4-7) but have been exploring introducing reporters / droppable input fields.

**Comment by xboxkh** [comment]
thats kind of surprising, as there ARE operators in the horizontal svg renderer, but they are shaped like a bullet.

**Comment by xboxkh** [comment]
booleans, however don't have anything for them that was coded.

**Comment by xboxkh** [comment]
(join(apple)(banana)) is not supported, as the renderer doesn't support multi-input.

**Comment by Dmitriy8998** [comment]
I have encountered a similar issue with dragging reporter blocks into a parent block, as well as with their rendering. The blocks are displayed incorrectly (misaligned). Has anyone succeeded in achieving the correct rendering for these blocks?

<img width="266" height="85" alt="Image" src="https://github.com/user-attachments/assets/8381826a-dfe6-45d1-bb67-08149d6ddf26" />
