### ISSUE TITLE
Input shapes aren't removed when an input is removed

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1218]
### Expected Behavior

Deleting an input on a block should clean up everything associated with it.

### Actual Behavior

The input, connected block, and shadow block are deleted.  The input shape is not deleted.

In this gif there's only one input, so I know it'll be deleted when I click "remove random input"
![3c310616-0b8c-40f3-a569-a40a99883966](https://user-images.githubusercontent.com/13686399/32582850-af7ca080-c4a5-11e7-9c52-8930d1db3d00.gif)

### Steps to Reproduce

Create a block with input shapes
From the console call `block.removeInput(<inputName>)`

This is exposed by mutators in custom procedures.

### Operating System and Browser

Any

### One solution
  
I can fix this by adding the following code to `Blockly.Input.prototype.dispose`, but I don't know why the input shapes are associated with the block instead of the input.

```
  // If there's an input shape for this, get rid of it.
  var inputShape = this.sourceBlock_.inputShapes_[this.name];
  if (inputShape) {
    goog.dom.removeNode(inputShape);
    delete this.sourceBlock_.inputShapes_[this.name];
  }
```
![de9d4f76-eca3-4767-86da-06f1b48d272a](https://user-images.githubusercontent.com/13686399/32582925-081806e4-c4a6-11e7-9ff4-5f87dfe12dd8.gif)

**Comment by tmickel** [comment]
> I don't know why the input shapes are associated with the block instead of the input

Hmmm, might have been me...perhaps an accident for the lack of knowing better ;p blockly renders its inputs (holes/notches in the blocks) in the block rendering right, so it seemed natural I guess...

**Comment by rachel-fenichel** [comment]
Makes sense, and that was my guess.  It shouldn't be too hard to put in the right place.
