### ISSUE TITLE
If you drop some blocks into the ask and wait text field, it doesn't glow

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#1226]
### Expected Behavior

Ask and wait block glows

### Actual Behavior

It doesn't glow, even though the question prompt is shown.
![image](https://user-images.githubusercontent.com/2855464/32634354-2ebafbfc-c579-11e7-9c22-f5927c3814cb.png)

### Steps to Reproduce

1. Drag ask and wait block to workspace
2. Drop the 'answer' or 'timer' blocks into the text field
3. Click on the stack

### Operating System and Browser

Mac OSX Chrome

**Comment by paulkaplan** [comment]
@fsih we should move this to scratch-vm

**Comment by fsih** [comment]
Made https://github.com/LLK/scratch-vm/issues/786
