### ISSUE TITLE
Monitors for empty fields are shaped weirdly

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#1227]
### Expected Behavior
In Scratch 2.0:
![image](https://user-images.githubusercontent.com/2855464/32733134-7c7b6864-c85c-11e7-9ce6-f7483aa95230.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/2855464/32634142-2f15c4de-c578-11e7-9abe-8ceed8bf69df.png)

### Steps to Reproduce

For example click on the answer block when no answer is stored

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by rachel-fenichel** [comment]
Looks like we want a min width and a min height on the monitor.
