### ISSUE TITLE
Procedures: default argument values

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1233]
What should the default values be for string/number arguments?  Boolean arguments have no default values (and no associated shadow block).

@chrisgarrity since this may need internationalization.
![image](https://user-images.githubusercontent.com/13686399/32917120-096f7576-cad3-11e7-9b29-e8f425f8289f.png)

**Comment by thisandagain** [comment]
We should replicate the Scratch 2.0 functionality which is:
Number Input - Default value of `1`
String Input - Default value of ``
Boolean Input - Default value of `null`

Because string and number inputs are being combined, the default value for these inputs should be `` for Scratch 3.0.

**Comment by rachel-fenichel** [comment]
Are you saying to replicate the scratch 2.0 functionality, or to have the empty string as the default value for string and number inputs?

**Comment by thisandagain** [comment]
Number / String Input - Default value of ``
Boolean Input - Default value of `null`

**Comment by towerofnix** [comment]
Related: Should the default value of a particular custom block text or number input be changeable by the user, through the custom block creation/edit UI? (Of course, there still needs to be a default value for such a default value input, but - you know :) )

**Comment by rachel-fenichel** [comment]
@towerofnix that's https://github.com/LLK/scratch-blocks/issues/1200
