### ISSUE TITLE
Design - Code generation/live execution during drag

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#124]
With the addition of insertion ghosts, dragging blocks means inserting and deleting blocks in the program as you drag.

Neil and I have discussed and concluded that we should not be generating/live executing code during the drag.

This means that code has a pre-drag state and a post-drag state, but will never execute or be generated from an intermediate state.

This also means that dragging away the bottom half of a stack of executing code will not stop it from executing until it is released in the workspace or in a new place--but Scratch continues executing that code anyway.

**Comment by tmickel** [comment]
@rachel-fenichel Is this still a blocks issue? To me this seems resolved by not having events associated with the marker, as is currently implemented. Maybe it's an issue if we reinstate generators?

**Comment by rachel-fenichel** [comment]
Yes, I think this is resolved.
