### ISSUE TITLE
Allow for renaming a message or list to an existing variable name.

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1245]
### Expected Behavior

Messages can share names with variables and lists.
Lists and variables cannot share names.

### Actual Behavior

Currently messages cannot share names with lists and variables.

### Steps to Reproduce

One example of reproducing this error is to create a variable named "x", and then to create a message named "x". A modal pops up that says: 'A variable named "x" already exists.'

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

### Additional comments

Currently variables often get looked up by their names, and since messages are now internally modeled as variables, this will be a big change. We would need to either change variables to get looked up by their unique IDs, or when looking up variables, also ensure that type information matches.

**Comment by mrjacobbloom** [comment]
Note that in 2.0 variables and lists may not share names, though messages may have the same name as a list or variable

**Comment by rachel-fenichel** [comment]
Is the plan to have them all have separate namespaces now?

**Comment by kchadha** [comment]
Hmmm I may have been too eager to file an issue on Friday. For now, we will keep the functionality the same as in 2.0, which means that messages can share names with lists and variables, but lists and variables cannot share names with each other. I am editing the issue to reflect this.

**Comment by rachel-fenichel** [comment]
I'd prefer separate namespaces for each type.  It wouldn't cause problems in loading old projects, and it would make implementation easier.

If you want to preserve the scratch 2.0 behaviour we would need to have a namespace tag on variable declarations and fields, as well as type tags.

**Comment by thisandagain** [comment]
I'm ok with making this behavior more consistent (variables, lists, and messages all have separate namespaces) as long as this doesn't break loading / editing 2.0 projects.

**Comment by rachel-fenichel** [comment]
Awesome.  It shouldn't break loading/editing 2.0 because it's becoming strictly more permissive.

**Comment by rachel-fenichel** [comment]
Er, unless this breaks opening a project in 2.0 after it's been edited in 3.0.  Is that a concern?

**Comment by thisandagain** [comment]
Nope. That isn't a concern. We'll support 2.0 -> 3.0, but not the other way around.

**Comment by kchadha** [comment]
For the sake of complete clarity, are we saying that we want to be able to allow:

1. variables to share names with lists and messages but not themselves,
2. lists to share names with messages and variables but not themselves, and
3. messages to share names with lists and variables but not themselves?

There's overlap in those 3 statements, but I just want to make sure we're all on the same page.

One design concern for allowing variables and lists to share names is that the getters for the two look exactly the same at the moment. There would be no way of visually differentiating a variable getter for the variable 'foo' vs. a list getter for the list 'foo'.

**Comment by rachel-fenichel** [comment]
Scratch 2.0 uses a slight color difference between lists and variables.  We probably should do the same in Scratch 3.0.

**Comment by thisandagain** [comment]
Agreed @kchadha. +1 on @rachel-fenichel's comment that implementing the color differences between lists and variables should help resolve issues with identifying the reporters.

**Comment by kchadha** [comment]
Should procedures also exist in separate namespaces then?

**Comment by kchadha** [comment]
Should procedures also exist in separate namespaces then?

**Comment by rachel-fenichel** [comment]
Yes, procedures are in a separate namespace--but they don't interact with this code path at all.

Procedure arguments are allowed to collide with just about everything and that's handled at runtime.

In Scratch 2.0 procedures can also collide with each other by name, but we're not planning to keep that in Scratch 3.0.

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/pull/1488 removes explicit blockers for this, but it won't be usable until I get all variables to be referenced by ID.
