### ISSUE TITLE
Automatically sort custom procedure category alphabetically

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1250]
### Expected/Requested Behavior

The custom procedure category is sorted alphabetically, by custom block label text. This way, it's easy to navigate: just scroll to the right letter, as you would flip through a dictionary to find a word.

### Actual Behavior

The custom procedure category is [not sorted](https://github.com/LLK/scratch-blocks/blob/f9cd4fa83344341db15c536b0b73971f75ad6ee1/core/procedures.js#L76-L93).

For comparison, here is the behavior in 2.0, as I posted [a while ago](https://github.com/LLK/scratch-vm/issues/717#issuecomment-336951813):

Scratch 2.0 doesn't really do any sorting on the list of custom blocks in this category - it tends to be finicky, sometimes putting the most recently dragged block at the top of the list and sometimes seeming to order the list based on the positions of the procedure definitions in the workspace.

### Steps to Reproduce

View the custom procedure category when multiple custom blocks are defined in it.

(Admittedly, I wasn't certain how to do this myself - I looked at the code, and saw that the procedure list isn't sorted anywhere.)

### Operating System and Browser

Debian (Testing), Firefox 58.0.

**Comment by rachel-fenichel** [comment]
Hey @towerofnix, do you want to implement this one?

The procedure category is created here:
https://github.com/LLK/scratch-blocks/blob/develop/core/procedures.js#L199

The list of procedures is generated here: 
https://github.com/LLK/scratch-blocks/blob/develop/core/procedures.js#L81

You'll want to add a function right [before the for loop](https://github.com/LLK/scratch-blocks/blob/develop/core/procedures.js#L206) to sort the list.  It'll take in the list and return a sorted list.

The mutations are DOM elements with a `proccode` attribute.  For instance, 
`<mutation proccode="say %s %n times if %b"></mutation>`

There are other attributes there but you don't need to worry about them.  To get the `proccode` call `getAttribute('proccode')`

**Comment by towerofnix** [comment]
@rachel-fenichel I'll definitely take a look! I did want to try this myself. I have memories of trouble with getting scratch-blocks to build, but I'm on a different system now; maybe it'll work this time. (Edit: it works :) )

I'm not sure how to test this feature. I see in the gif @paulkaplan made in #1232 using the "import to XML" feature to test the feature. Is there a simple way to generate such XML from, say, the VM? I only saw an "export to JSON" button there.

**Comment by rachel-fenichel** [comment]
I don't have a simple way for you to get that XML yet, but here's some that you can load into the playground:

```
<xml xmlns="http://www.w3.org/1999/xhtml">
  <variables></variables>
  <block type="procedures_call" id="caller_external" x="0" y="0">
    <mutation proccode="play %s %s if %b is true" argumentids="[&quot;arg1&quot;,&quot;arg2&quot;,&quot;arg3&quot;]" warp="false"></mutation>
  </block>
  <block type="procedures_call"  x="100" y="100">
    <mutation proccode="aardvark" argumentids="[]" warp="false"></mutation>
  </block>  

  <block type="procedures_call"  x="200" y="200">
    <mutation proccode="baboon" argumentids="[]" warp="false"></mutation>
  </block>
</xml>
```

It'll create three procedure call blocks, and I think that should be enough for you to get started.  To add more calls, add more copies of 
```
  <block type="procedures_call"  x="200" y="200">
    <mutation proccode="baboon" argumentids="[]" warp="false"></mutation>
  </block>
```

Make sure you change the x and y or they'll end up stacked on top of each other.

**Comment by towerofnix** [comment]
Thanks for the example code!

I made a tiny browser console script to grab the VM workspace as an XML text.. here it is, for future reference:

```js
copy(Blockly.Xml.domToPrettyText(Blockly.Xml.workspaceToDom(Scratch.workspace)))
```
