### ISSUE TITLE
input renders out of the block panel

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1255]
### Expected Behavior

it shouldn't happen

### Actual Behavior

but it happened

### Steps to Reproduce

Write something looooooooooooooooooooooooooooooooooooooooooooong in the inputs

### Operating System and Browser

Windows 8.1, Google Chrome 60.0.3112.78
![default](https://user-images.githubusercontent.com/31377746/33070750-09fcc5d2-cef4-11e7-9d03-b7f172334342.PNG)

---
Moved from LLK/scratch-gui#933
/cc @cyx2015s

**Comment by rachel-fenichel** [comment]
What's the expected behaviour?  The flyout doesn't scroll horizontally.  Blocking them from typing seems like a bad idea.  This seems like the least bad response.

**Comment by cyx2015s** [comment]
It shoud renders under it, but it renders over it

**Comment by Kenny2github** [comment]
Yeah, the input shouldn't overflow into the scripts area.

**Comment by rachel-fenichel** [comment]
I disagree--then we'd get a bug report that you can't see what you're typing in the block menu.  I'd rather show what the user typed.  When you click away from editing that text it stops overflowing, so it's not getting in the way except when you're actively trying to type long text.

![image](https://user-images.githubusercontent.com/13686399/33283082-96e19f94-d35f-11e7-8dbe-e75c2b611dd5.png)

![image](https://user-images.githubusercontent.com/13686399/33283093-9ff3f46a-d35f-11e7-8267-b8112d70564b.png)

**Comment by rachel-fenichel** [comment]
Frequently reported in Scratch 3.0 feedback, but we've agreed that the current behaviour is fine.

The exception is if it gets wide enough to add a scrollbar to the entire page, instead of just going over other elements.
