### ISSUE TITLE
List blocks should be a different color from variable blocks.

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1257]
### Expected Behavior

List blocks and variable blocks should be different colors because lists and variables are able to share names. See discussion in #1245 for more info.

### Actual Behavior

Currently, list blocks and variable blocks are the same color.

### Steps to Reproduce

Create a new variable.
Create a new list.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by mrjacobbloom** [comment]
There's a separate lists color spec'd in #600 but the [colors page](https://github.com/LLK/scratch-blocks/wiki/Colors) has an older picture

**Comment by thisandagain** [comment]
Color is defined in https://github.com/LLK/scratch-blocks/issues/600
