### ISSUE TITLE
VarCreate event does not get fired when default broadcast message is added to the VariableModel

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1258]
### Expected Behavior

Creating the default broadcast message ('message1') by dragging any of the broadcast message blocks out into the blocks editor workspace from the tool palette should fire a new VarCreate event.

### Actual Behavior

VarCreate event does not actually get fired because domToBlock disables events before variable is created.

### Steps to Reproduce

In the vertical playground, enable 'Log events" and "Log flyout events" checkboxes.
Drag any of the broadcast message blocks out into the workspace and see that the VarCreate event does not get fired.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by rachel-fenichel** [comment]
Upstream: https://github.com/google/blockly/issues/1395

Feel free to fix it on blockly!

**Comment by kchadha** [comment]
Fixed in this PR: https://github.com/google/blockly/pull/1477
