### ISSUE TITLE
Broadcast blocks should have input fields

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1268]
### Expected Behavior

'broadcast' and 'broadcast and wait' blocks should have input fields in addition to the drop downs (allowing plugging in blocks as input). 

E.g. 

![image](https://user-images.githubusercontent.com/1786240/33398216-3429b364-d51c-11e7-846b-5a0f46d7feab.png)

### Actual Behavior

The field on these blocks is currently only a field variable dropdown and not a pluggable input.

**Comment by mrjacobbloom** [comment]
I believe this is covered in #1199
