### ISSUE TITLE
Cannot create broadcast message from the toolbox

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1278]
Repro:
Try to create a broadcast message from the dropdown on a broadcast block while it is in the palette. The modal comes up, but submitting the name for the message leaves the checkbox in a strange state because of this error.

```
Uncaught TypeError: Cannot read property 'setCheckboxState' of null
```

The "strange state" looks like this, but it i think it is just because of the error in the creation of the variable. 
![image](https://user-images.githubusercontent.com/654102/33565184-6c028dca-d8ea-11e7-9e61-20a223648187.png)

**Comment by kchadha** [comment]
This is the same as #1270. Closing this issue.
