### ISSUE TITLE
Remove context menu from custom procedure declaration block

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1279]
You should not be able to right-click duplicate/delete the procedure declaration block. I didn't see any way to disable context menus at the workspace level, so I assume this will have to be implemented here in scratch-blocks instead of externally in that which renders the custom procedure editor.

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/blob/master/core/block.js#L1016
