### ISSUE TITLE
Create a way to prevent the custom procedure declaration from being dragged

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1280]
Similar to https://github.com/LLK/scratch-blocks/issues/1279.

This seems like something we might want to do at the workspace level? I couldn't find anything to disable dragging on a block that already existed.

**Comment by rachel-fenichel** [comment]
https://developers.google.com/blockly/guides/create-custom-blocks/define-blocks#movable_state

**Comment by paulkaplan** [comment]
😞  my search abilities are... lowly. thanks!
