### ISSUE TITLE
Deleting a block definition should produce an error if uses of the block are there

### ISSUE THREAD

**Issue by Kenny2github** [LLK/scratch-blocks#1287]
### Expected Behavior

When you attempt to delete a block definition, if the block is used anywhere, an error box should pop up and the deletion should fail.

### Actual Behavior

The definition is deleted, and all uses remain there - they simply don't do anything anymore

### Steps to Reproduce

1. Go to https://llk.github.io/scratch-gui/develop
2. Create a block in the "More" category
3. Drag out an instance of your block
4. Delete the definition

### Operating System and Browser

Probably irrelevant

**Comment by thisandagain** [comment]
We are doing the right thing when you right click on the definition and choose "delete" but not when the definition is deleted by dragging it into the toolbox.
