### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by wenyiweb** [LLK/scratch-blocks#1288]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by Kenny2github** [comment]
Duplicate of #301

**Comment by thisandagain** [comment]
Tracking in upstream Blockly https://github.com/google/blockly/issues/299
