### ISSUE TITLE
Why is the custom procedure editor's remove-input/label button a "no" sign?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1289]
I'm just curious - I would expect to see an X mark.

!["No" sign](https://user-images.githubusercontent.com/9948030/33678286-3db6c24a-dab3-11e7-835c-0f806f31348a.png)

My opinion: X marks are associated with closing things, but also with crossing things out. "No" signs (like the one used in the screenshot above) are more related to halting, preventing, disabling; but not really removing. Maybe scissors are the most intuitive? (I suppose you could argue that scissors are related to cutting things *out*, to be used later (think: cut, paste), but I'm thinking of cutting the input *off* (think: remove), which is also the way Scratch 2.0 uses scissors (i.e., the Delete tool).)

**Comment by mrjacobbloom** [comment]
Not that this is necessarily a great option, but a trash-can icon is sometimes used to mean deleting something too

**Comment by fsih** [comment]
I agree; I didn't realize what the cancel sign did or even that it was a button. It looked like it was indicating that there was some error with that input field.

**Comment by carljbowman** [comment]
Great question. We should update that icon.

Here is a trashcan icon: [delete-arg.zip](https://github.com/LLK/scratch-blocks/files/1575807/delete-arg.zip)

**Comment by thisandagain** [comment]
Adding the `help wanted` label if anyone would like to take this on. 😄
