### ISSUE TITLE
Broadcast message deletion behaviour

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1290]
In Scratch 2.0 broadcast messages are never explicitly deleted.  Removing the last reference to a message on any workspace in the project removes the message from dropdown menus.

In Scratch 3.0
- Will messages have explicit deletion?  _From an implementation perspective this is much better, since it can match variable and list deletion behaviour._
- Can messages be renamed?
- Can the default message ('message1') ever be deleted?
- Are there backwards compatibility concerns?

References:
- Variable deletion discussion: https://github.com/LLK/scratch-blocks/issues/975
- Variable deletion discussion: https://github.com/LLK/scratch-blocks/issues/372#issuecomment-227532505

**Comment by thisandagain** [comment]
Direction for matching Scratch 2.0 behavior was established today. Removing assignments other than @kchadha :-)

**Comment by rachel-fenichel** [comment]
Please confirm: the behaviour for Scratch 3.0 will be to delete all unused broadcast messages when changing sprites.

**Comment by kchadha** [comment]
@rachel-fenichel, unused broadcast messages will be deleted whenever scratch-vm emits a workspace update (so switching sprites or switching to the sound/costume editors and back again).

**Comment by rachel-fenichel** [comment]
What happens with a broadcast message that is on an occluded shadow block?  For instance, message2 here (if it's not used anywhere else).  Is it deleted when you switch sprites?
![cae906d5-a1b9-4301-8383-45b1f36cf739](https://user-images.githubusercontent.com/13686399/34422145-72d52b12-ebc8-11e7-9c8f-6d7886620848.gif)

**Comment by kchadha** [comment]
@rachel-fenichel message2 will not be deleted when you switch sprites, and thus if you unplug `(costume#)` you'll see message2 in the shadow. This is different from Scratch 2, where message2 gets deleted and thus unplugging `(costume#)` would result in the creation of an empty string message. We wanted to avoid empty string message names in Scratch 3 unless a problem arises because of this.

**Comment by rachel-fenichel** [comment]
Okay, so does that mean that the check for used variables includes variables in occluded shadow blocks?  If so, how is that happening?  

When a shadow block is hidden it is serialized and the actual Blockly.BlockSvg object is deleted.  The XML is stored on the connection.  When it's uncovered we deserialize the XML to create a new Blockly.BlockSvg object and connect it.

Searching for variables looks for variable references on existing blocks, so it will not find variables on serialized hidden blocks.
