### ISSUE TITLE
Adding procedure argument emits create event with block instead of shadow

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1291]
To repro:
1. Enable logging in the custom procedure playground for the main workspace (run `definitionWorkspace.addChangeListener(function(e){console.log(e);});`)
2. Right-click -> edit the existing procedure definition in the definition workspace.
3. Click "Add text/number input" button.
4. Click "ok"
5. Check out the events in the console. There should be two "Create" events. The first is the argument on the call block, the second is the new argument on the prototype block. Both of these blocks are shadows, but the events list them as `<block` instead of `<shadow`. The call block event is most important: it leads to https://github.com/LLK/scratch-gui/issues/1005

Because scratch-vm listens to these events to keep in sync, not knowing that these blocks (particularly the first one, in the caller) are actually shadows is a problem. 

@rachel-fenichel Is this a bug with the way events are emitted? Or is this the expected behavior?

**Comment by paulkaplan** [comment]
Looks like these lines are responsible. https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/procedures.js#L303-L320. Using `workspace.newBlock` will always emit a create as a non-shadow.

Alternatively, we could be using `buildShadowDom_` => `domToBlock`, which would reduce code duplication, but that would not give us the ability to do the `isInsertionMarker => do not render` condition (I think?). When I simplify `attachShadow_` down to this:
```
    var blockDom = this.buildShadowDom_(argumentType);
    var newBlock = Blockly.Xml.domToBlock(blockDom, this.workspace);
    newBlock.outputConnection.connect(input.connection);
```

Then I end up with this insertion marker problem:
![insertion-marker-render](https://user-images.githubusercontent.com/654102/33837145-73297efa-de59-11e7-8e9f-0d1766b45081.gif)

**Comment by rachel-fenichel** [comment]
Good sleuthing.  That's exactly the problem.

The create event that's fired in new block is *really* optimistic.  Anywhere that we go through `domToBlock` events are disabled until all of the blocks are created, to sidestep problems like this.  We can do the same here: 

```
Blockly.ScratchBlocks.ProcedureUtils.attachShadow_ = function(input,
    argumentType) {
  if (argumentType == 'n' || argumentType == 's') {
    var blockType = argumentType == 'n' ? 'math_number' : 'text';  
    Blockly.Events.disable(); // NEW
    var newBlock = this.workspace.newBlock(blockType);
    if (argumentType == 'n') {
      newBlock.setFieldValue('1', 'NUM');
    } else {
      newBlock.setFieldValue('', 'TEXT');
    }
    newBlock.setShadow(true);
    if (!this.isInsertionMarker()) {
      newBlock.initSvg();
      newBlock.render(false);
    }
    Blockly.Events.enable();  // NEW
    if (Blockly.Events.isEnabled()) { // NEW
      Blockly.Events.fire(new Blockly.Events.BlockCreate(newBlock)); // NEW
    } // NEW
    newBlock.outputConnection.connect(input.connection);
  }
};
```
