### ISSUE TITLE
Remove "collapse" item from context menu

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1300]
### Expected Behavior

The context menu for the workspace should not include a "collapse" item.

### Actual Behavior

The item exists, and has a broken behavior. We should probably remove it.

**Comment by thisandagain** [comment]
This is an option when creating the workspace. Moving to `scratch-gui`.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#1082
