### ISSUE TITLE
Support scientific notation in numeric inputs

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1301]
### Expected Behavior

In Scratch 2.0, number-only inputs (the rounded ones) allow you to type the letter 'e', in addition to numbers and decimal points. You can for example type 1e6 (to represent one million) into any input, including number-only inputs.  

### Actual Behavior

It appears that Scratch 3.0 generally supports the conversion from scientific notation, and you can type it into fields that are number-or-string, but you cannot type it into number-only fields. This is a bit confusing, because we have removed the visual distinction between these field types, so there is no way to tell by looking which fields have this constraint. So for example, in Scratch 3.0 you can type 1e6 into the "set variable to" block (a number-or-string input) but not into the "change variable by" block (a number-only input). You can, though, drop a reporter with the value 1e6 into the "change variable by" block and it will work as expected. 

It's not obvious to me if we need to support this pattern or not, but as of now this is a difference from Scratch 2.0. So, should we add support for typing the 'e' into number-only inputs?

**Comment by rachel-fenichel** [comment]
And then there's blockly!  
![image](https://user-images.githubusercontent.com/13686399/33962790-8f5883be-e007-11e7-8f95-a9134e2eee7b.png)

If I recall correctly, the number fields don't allow you to type characters that would put it into an invalid state.  Blockly lets you type whatever you want, and if it doesn't validate when you hit enter, Blockly reverts to the value from before the edit was started.  Scratch Blocks avoids that by restricting the set of characters that you can type.

**Comment by joker314** [comment]
Blockly supports validators for numeric inputs. Presumably the 'e' could be added here:

https://github.com/LLK/scratch-blocks/blob/1465a9efe29a18b1983818bced02e39b1ab39e1f/core/field_number.js#L128-L139

**Comment by towerofnix** [comment]
@joker314 Yup, actually I just ninja'd you to making that change on my local clone. It seems to work; just testing in scratch-gui now :P (Update: It does. PR incoming.)
