### ISSUE TITLE
Importing empty-string as message name from SB2

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1304]
Opening this up for discussion so that others can weigh in and I don't go down any rabbit holes unnecessarily...

In Scratch 2, users can create an empty string message by plugging an input into a broadcast block and taking it back out. The empty string message option becomes available in block dropdowns and can then be used as a valid message. Note: it is not possible to explicitly create an empty string message (trying to do so results in a noop).

What should the behavior be for importing empty string messages into scratch 3? Below are some possibilities:

- Should empty string message names be translated into some unique (user-friendly) identifier such as 'messageN' where N is some number such that 'messageN' is a fresh name?
- Should we attempt to allow the empty string message name (only for sb2 imports)?

I have tried the second option above, but it poses some block rendering problems where the size of the option to be selected (the option we are hovering over) is very tiny and the check mark appears to be in between options (see below):

![image](https://user-images.githubusercontent.com/1786240/34017702-cca92ad2-e0f4-11e7-89b9-d8a7a579ca3b.png)

![image](https://user-images.githubusercontent.com/1786240/34017710-d7b130c8-e0f4-11e7-9624-632a57832d06.png)

**Comment by rachel-fenichel** [comment]
In Scratch 2.0 I was able to explicitly create a message with the empty string as the name:
![image](https://user-images.githubusercontent.com/13686399/34018680-e2a3e5da-e0df-11e7-880a-44c2cd782bc2.png)

1. Drag out a "when I receive" block
2. Click the arrow to open the dropdown
3. Click "new message"
4. Type " " and hit enter

Result is the image above.

I can also make multiple different whitespace-only messages:
![image](https://user-images.githubusercontent.com/13686399/34018712-0f1869ec-e0e0-11e7-971d-21c2e62bf87c.png)
_Dropdown with multiple whitespace-only message names._

![image](https://user-images.githubusercontent.com/13686399/34018735-34024084-e0e0-11e7-8c87-b8896ff08a80.png)
_Blocks with two different whitespace-only messages selected, of different lengths._

I cannot do this with variables or lists.

**Comment by rachel-fenichel** [comment]
My bad: I was writing about making names that are whitespace-only.  I can't make the empty string name work at all.  As @kchadha said, it's a no-op when you try.

**Comment by kchadha** [comment]
I've decided to go with option 1 above (e.g. fresh name 'messageN'), at least for the short term, so that this doesn't block changes getting pushed. This (and the rest of broadcast message) functionality can be tested on https://llk.github.io/scratch-gui/broadcast-input/.
Option 1 is included in PR [LLK/scratch-vm#860](https://github.com/LLK/scratch-vm/pull/860)

We can always switch to option 2, but we'll need to figure out how to get the drop down menu to render properly first. There are other issues (e.g. allow whitespace as a message name) that also depend on this dropdown menu rendering issue.
