### ISSUE TITLE
Implement "Go To Definition" context menu option

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1312]
As per feature in Scratch 2.0:
![untitled](https://user-images.githubusercontent.com/747641/34214843-a4967e42-e571-11e7-8e5b-725249e8da7b.gif)

**Comment by thisandagain** [comment]
For reference:
https://github.com/LLK/scratch-blocks/pull/1311/files

**Comment by rachel-fenichel** [comment]
Dupe of https://github.com/LLK/scratch-blocks/issues/1136
