### ISSUE TITLE
Change wording on the "Create ..." buttons for variables and lists

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1314]
Change the wording on the "Create variable..." and "Create list..." buttons to read:

```
Make a Variable
Make a List
```
This is to make the language, capitalization, and phrasing consistent with other parts of the editor.

**Comment by rachel-fenichel** [comment]
Variable:
https://github.com/LLK/scratch-blocks/blob/develop/msg/messages.js#L129

List:
https://github.com/LLK/scratch-blocks/blob/develop/msg/messages.js#L145
