### ISSUE TITLE
Modify layering command blocks to be more flexible

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1317]
Currently our layering controls can be quite frustrating (even for beginners) because they do not allow for the level of flexibility that would be expected. They are also not consistent with the controls that we provide in the paint editor. For this reason we would like to make the following change:

### Current
```
go to front
go back (1) layers
```

### Proposed
```
go to [front / back]
go [forward / backward] (1) layers
```

**Comment by paulkaplan** [comment]
@thisandagain do we want to leave the current block definitions/opcodes in the code for importing, but show the new ones in the palette? Or translate the old blocks into these new blocks when importing (should be easily doable, since the new blocks are a superset of the old blocks)

**Comment by thisandagain** [comment]
@paulkaplan Good question. I should have specified. My inclination would be to update the SB2 spec map to map onto these new blocks rather than have "legacy" blocks / opcodes hanging around.
