### ISSUE TITLE
Modify costume and backdrop reporters to be more consistent / flexible

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1318]
Our current costume and backdrop reporters have a sort of asymmetry that can be frustrating (even for beginners). We currently only allow for reporting a costume *number* and a backdrop *name* rather than allow for getting either value for both. Proposed change:

### Current
```
(costume #)
(backdrop name)
```

### Proposed
```
(costume [number / name])
(backdrop [number / name])
```

**Comment by paulkaplan** [comment]
One issue: we still haven't dealt with the "menus in monitors" and this would make that problem even worse.

**Comment by thisandagain** [comment]
@paulkaplan Thanks for pointing that out. Let's do this and then I'll move https://github.com/LLK/scratch-gui/issues/785 into January for resolution. Does that work for you?

**Comment by thisandagain** [comment]
Minor change to this after looking at the data. Usage statistics from shared projects in the past 30 days:

| Block Name | Opcode | Projects Shared |
| ----------- | ---------- | -------------------- |
| `costume #` | `costumeIndex` | 54,253 |
| `backdrop name` | `sceneName` | 9,167 |

Because of this I recommend we flip the drop-down defaults to be *number* first and *name* second.

**Comment by thisandagain** [comment]
(Original comment updated)
