### ISSUE TITLE
Use different color for extensions and custom blocks

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-blocks#1336]
In Scratch 2.0, custom blocks and extensions are different colors. In Scratch 3.0, they are the same. I think this makes them easier to tell apart:
![](https://user-images.githubusercontent.com/31634240/34456856-f5ba8728-ed6e-11e7-80bd-5fcdb7ca57cc.png)
In this example, extension block fill is `rgb(180, 105, 122)` and stroke is `rgb(180, 51, 85)`.

Same as https://github.com/LLK/scratch-gui/issues/1149

**Comment by thisandagain** [comment]
Please do not create duplicate issues. Tracking in https://github.com/LLK/scratch-gui/issues/1149
