### ISSUE TITLE
Creating duplicate messages

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1351]
#1350 introduces a UX issue where users would see a discrepancy between the first time and additional times they try to create a new message `message1` using any of the broadcast blocks in the flyout.

E.g.
1. Open a new project
2. Use one of the broadcast blocks in the flyout to create a new message `message1`
3. Repeat step 2.

Performing step 2 looks like a no-op to the user, while performing step 3 results in the following pop-up:

![image](https://user-images.githubusercontent.com/1786240/35106380-0f3d3e62-fc3c-11e7-8b81-94509a573b9f.png)

The discrepancy here is confusing to the user. What's happening behind the scenes is that performing step 2 the first time transforms the potential variable (a concept introduced by #1350) into a real variable of the same name (this same thing would happen if any of the broadcast blocks are dragged from the flyout into the workspace). Repeating step 2 yields an error because now, a variable with the same name and type already exists.

----------------------------------------------------------------------------------------------------

### Proposed Solution:
Change validator for broadcast messages to not complain when a user tries to create a new message with the same name as an existing broadcast message. In Scratch 2.0, users can create broadcast messages with the same name as many times as they want. The result of performing this action appears to be a no-op to the user.

**Comment by thisandagain** [comment]
Thanks for detailing this @kchadha. Your proposed solution makes sense to me. :+1: 😄

**Comment by rachel-fenichel** [comment]
**Edit: the comment below is a solution to a problem that you do not have.**

The second time around the "message1" reference in the flyout should refer to the real variable, not a potential variable.  Blocks in the flyout should refer to potential variables only if no real variable with the same name + type exists.  Maybe something is going wrong during the toolbox refresh?

**Comment by kchadha** [comment]
@rachel-fenichel, that's right, the second time around, the 'message1' reference _does_ refer to the real variable, but this introduces the discrepancy between the first time and the second time. From the user's perspective, they don't know what there's a potential variable being turned into a real variable the first time, and an alert popping up subsequent times because a real variable already exists now.
