### ISSUE TITLE
"Stop other scripts in sprite" block changes shape on workspace refresh 

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1356]
### Expected Behavior

The "stop (other scripts in sprite)" block is special because its shape depends on the menu selection. But once you have selected "other scripts in sprite", which causes it to add a next-connection bump at the bottom, it should stay that shape.

### Actual Behavior

The block changes shape when you switch to another sprite and then come back. 

Before:

<img width="203" alt="screen shot 2018-01-22 at 1 12 39 pm" src="https://user-images.githubusercontent.com/567844/35236923-06c096a6-ff77-11e7-898f-48aea25a5f0b.png">

After:

<img width="191" alt="screen shot 2018-01-22 at 1 15 36 pm" src="https://user-images.githubusercontent.com/567844/35236928-0b6af3cc-ff77-11e7-93db-1d0999c56da3.png">

### Steps to Reproduce

- Drag a "stop all" block onto the workspace
- Change it to "stop other scripts in this sprite" 
- Switch to another sprite and back

**Comment by rachel-fenichel** [comment]
This block has a mutation to record whether the block has a next connection.  Is it possible that the `<mutation>` tag is not making it through the roundtrip?
https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/control.js#L206

**Comment by paulkaplan** [comment]
@rachel-fenichel I'm not seeing a change event being fired for the mutation when changing from `stop all` to `stop for this sprite`. I only see a change event for the value of the field.

**Comment by paulkaplan** [comment]
The next connection is modified in the line validator of the menu options, line 194 here https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/control.js#L172-L216

Do you think a BlockChange for the mutation should be emitted at that point as well?

**Comment by cuxdioldacc** [comment]
`code`
