### ISSUE TITLE
Multiple custom procedure arguments shouldn't have the same name

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-blocks#1362]
This should not happen:
![image](https://user-images.githubusercontent.com/31634240/35471827-338d036e-0331-11e8-92dd-b44cabc27064.png)

Also, while running this:
 ![image](https://user-images.githubusercontent.com/31634240/35471834-46fa3002-0331-11e8-92b1-460db2feda6e.png)
"true" is spoken for 10 seconds

**Comment by Kenny2github** [comment]
FYI: the current Scratch 2 method is to add a "2" to the first copy, a "3" to the second and so on.

**Comment by apple502j** [comment]
LLK/scratch-gui#1252

**Comment by thisandagain** [comment]
Tracking in #1252
