### ISSUE TITLE
Using "%s" as an argument name causes unexpected behavior

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1367]
See https://github.com/LLK/scratch-gui/issues/1347 

From a quick look through code, I think the solution is proper escaping in this function:
https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/procedures.js#L529

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1368
