### ISSUE TITLE
Make <key [space] pressed?> input droppable

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1370]
Follow-up from discussion in #1199. From @towerofnix:

... Here's a small example which lets the user type "into" a variable display:

![Text input example](https://user-images.githubusercontent.com/9948030/35632172-593721d2-067c-11e8-8123-d46dfda8f5da.png)

```
when green flag clicked
set [Input content] to [] // Empty
show variable [Input content]

when [any] key pressed
set [keys] to [abcdefghijklmnopqrstuvwxyz]
set [parse] to [1]
repeat (length of (keys))
	if <key (letter (parse) of (keys)) pressed> then // Note that we put a reporter in "key pressed"
		set [Input content] to (join (Input content) (letter (parse) of (keys))
		stop [this script]
	end
	change [parse] by (1)
end
```

Griffpatch's [Word Processor](https://scratch.mit.edu/projects/88564231/) project is a good example of using the "key pressed" sensing block as a way for detecting general keys without using many, many "key pressed" blocks; think "if key a pressed?, append a; if key b pressed?, append b; if key c pressed?, append c...". It also uses the block to detect keys which aren't even in the dropdown menu at all, such as backspace.

**Comment by towerofnix** [comment]
I can probably do this (I already have scratch-blocks updated, doing gui now).

(Edit: and, 🎉, thanks! This makes a bunch of things way more possible and easy to do now. Another example that comes to mind is customizable keyboard controls.)

**Comment by AmazingMech2418** [comment]
This is what I meant when I made the suggestion! It was droppable earlier in the previous version of Scratch 3.0 before some blocks were made undroppable.
