### ISSUE TITLE
Button text looks odd on Microsoft Edge

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-blocks#1376]
### Expected Behavior

Button text should be vertically centered in all browsers.

### Actual Behavior

Text is too far up in Microsoft Edge:
![image](https://user-images.githubusercontent.com/31634240/35882782-481c1d5e-0b53-11e8-93b1-26370e6d512e.png)

### Steps to Reproduce

Test on Edge

### Operating System and Browser

Windows 10 Edge 41.16299.15.0

**Comment by AmazingMech2418** [comment]
This should be moved to scratch-gui.

**Comment by rachel-fenichel** [comment]
@amazinigmech2418 nope, this is a scratch-blocks problem.  The buttons in the toolbox (block palette) are part of scratch-blocks.

**Comment by AmazingMech2418** [comment]
OK. I thought it was part of the GUI since it isn't the actual blocks.

**Comment by thisandagain** [comment]
Likely related to https://github.com/LLK/scratch-blocks/issues/1352
