### ISSUE TITLE
how to run scratch-blocks on mobilephone ?

### ISSUE THREAD

**Issue by hansionit** [LLK/scratch-blocks#1387]
I want use scratch-blocks in my android application,but I don't konw how to start.Please help me.Thanks！

**Comment by thisandagain** [comment]
You will need to load both the [blocks](https://github.com/llk/scratch-blocks) and the [Virtual Machine](https://github.com/llk/scratch-vm) into a [WebView](https://developer.android.com/reference/android/webkit/WebView.html).

**Comment by Ice-Panda** [comment]
> I want use scratch-blocks in my android application,but I don't konw how to start.Please help me.Thanks！

Hi, I have the same need as you. May I ask whether you have solved the problem and whether you can give some guidance?
