### ISSUE TITLE
Drag not registering as outside blocks area when svg group is larger than viewport

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1392]
Try loading this project https://llk.github.io/scratch-gui/develop/#177260519 and dragging a stack to another sprite. It doesn't transition to being "outside" the blocks area until far to the right. 

![drag-outside](https://user-images.githubusercontent.com/654102/36990590-2e10b246-2073-11e8-899b-14a105d41f3e.gif)

It seems that the process for checking `isInsideBlocksArea` isn't working correctly. That svg that it is measuring can be initialized to a size that is different from the actual viewport.

**Comment by paulkaplan** [comment]
@rachel-fenichel I would think we could use the results of `this.getMetrics()` on the workspace svg, but I'm not exactly sure what combination of the metrics would give the same idea?

**Comment by rachel-fenichel** [comment]
Sorry for the delay, and it looks like you've fixed it.

Yes, some combination of results of `this.getMetrics()` would do it, involving the view-related numbers.  If that's still a thing that you want to look at, let me know.
