### ISSUE TITLE
Length of (0/0) equals 3 ("Nan")

### ISSUE THREAD

**Issue by Clark-E** [LLK/scratch-blocks#1396]
### Expected Behavior

_Please describe what should happen_

I've been experimenting with (0/0), which returns the value Nan (not suprising). Plugging in this "Nan" block into numerical inputs treats it as if it were zero. So far, so good.

### Actual Behavior

_Describe what actually happens_

But, when plugging in the (0/0) block into string inputs, it treats it as if it were "Nan". Length of (0/0) is the same as Length of (Nan), which is three. I've also tried it with some other blocks with string inputs, with similar results (e.g. () contains (), say ())

I know this is not a huge bug, but I can imagine quite a few people being confused over this. I know Javascipt, and if someone could point me to where the code for the division block is, I'd be happy to add some basic code to replace "Nan" with 0.

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

Pretty self explanitory. Try these blocks:

length of((0/0))
say ((0/0))
(Nan) contains ((0/0))

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

Win 10, chrome 64.

Though, I'd imagine this being a cross-browser bug. (I've tried firefox. It has similar results). #

**Comment by Clark-E** [comment]
Sorry, I just realized this issue really belongs in scratch/vm. I'll close this one and post it there.

**Comment by towerofnix** [comment]
@Clark-E - Note that this is the same behavior as in Scratch 2.0; may be worth considering that changing this could break compatibility. Also, 5 divided by 0 is not 0, but I don't want to argue about how the behavior of should be myself :P
