### ISSUE TITLE
Use "secs" instead of "seconds"

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-blocks#1410]
This is the way it is in Scratch 2.0, and blocks get really long with seconds.

**Comment by Kenny2github** [comment]
Please search through the repo for a rationale for differences before submitting issues for them. This change was deliberate - see #1316 - because "secs" is awkward to say out loud.

**Comment by towerofnix** [comment]
Along with what @Kenny2github said above - blocks don't get "really long", they get like 20 pixels longer.
