### ISSUE TITLE
Category menu appearance issues

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1417]
General bug for reports from the feedback form on category menu rendering.

The scrollbar shows up when we don't want it to.  This is frequently exposed by adding a few extensions:
- Adding two extensions makes the category list too long, causing the (native) scrollbar to appear for the category menu. It covers the left edge of the blocks and can't be hidden. (#1116)
- If i select both music and pen, a scroll, bar comes up, this gets in the way of blocks and makes it very hard to  do things such as tick and un-tick variables, it can also make it very hard to read some of the names of the blocks.
- When I added music and pen the scroll bar covers the left sided of the blocks in the menu - so you cant see the whole name of the blocks - the scroll bar doesnt seem to auto hide with the additional block sets.
- Left side of the all blocks in the palette is partly cut off. 
- At 100% zoom on my laptop a scroll bar appears on the block selector, stopping me from reading the left side of each block. Changing to 90% zoom cures this.
- The vertical scroll bar partially covers up the block categories.
- _Possibly related_ My block options are too far to the left. They are being covered by the scroll bar for the block categories. 

Scrolling/highlighting/jumping:
- When you scroll down the Variables circle or my blocks circle doesn't highlight like the other

Other:
- The sprites list scroll bar is the browser default instead of the rounded Scratch 3 standards.
- The sprite list scroll bar is missing.
- Scrolling with the touchpad doesn't work, and sprite list cannot be scrolled because the scroll bar is missing.

**Comment by ericrosenbaum** [comment]
Thanks @rachel-fenichel! We now have all the relevant issues filed, so I'm going to close this one
