### ISSUE TITLE
No option for "delete <all> of list"

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1419]
Scratch 2.0 "delete ___ of list" block has options "last" and "all".  Scratch 3.0 does not match this.

### Expected Behavior

![image](https://user-images.githubusercontent.com/13686399/37921569-0fe2898a-30df-11e8-8bc7-7e954aba46d4.png)

### Actual Behavior

![image](https://user-images.githubusercontent.com/13686399/37921606-2c9881a6-30df-11e8-9f0b-1635c2a8b03b.png)

**Comment by rachel-fenichel** [comment]
This works if you import a project with "all" from Scratch 2.0, but you can't create it in Scratch 3.0.

**Comment by Clark-E** [comment]
So I’m guessing this is just a simple case of updating the default block palette to the right thing?

**Comment by thisandagain** [comment]
In general we have moved away from these hybrid numeric / drop-down inputs. I'll log this as a feature for future discussion.

**Comment by apple502j** [comment]
Dupe as #1333

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/1333
