### ISSUE TITLE
python build.py 

### ISSUE THREAD

**Issue by qiansitong** [LLK/scratch-blocks#1423]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by qiansitong** [comment]
![image](https://user-images.githubusercontent.com/24642743/38075557-5002a314-3365-11e8-8199-b54f0989ee23.png)

**Comment by thisandagain** [comment]
@qiansitong This isn't enough information for us to help you. Can you please fill out the issue template? Feel free to re-open once you have done this.

**Comment by qiansitong** [comment]
I downloaded the code from scratch-blocks and ran into the above problem when running python build.py.
