### ISSUE TITLE
Suggestion: Make Data Blocks Droppable

### ISSUE THREAD

**Issue by AmazingMech2418** [LLK/scratch-blocks#1424]
### Expected Behavior

When you load a project with hacked blocks, it should have reporters in the data block variable/list name menu inputs where they were added with hacked blocks.

### Actual Behavior

When you go to https://llk.github.io/scratch-gui/develop/#149385927 and look at the Sprite "Sprite1", the data blocks say something weird in the menu inputs. This is just an example of a project that this happens in.

### Steps to Reproduce

Go to https://llk.github.io/scratch-gui/develop/#149385927 .

### Operating System and Browser

Windows 10 on Chrome

**Comment by apple502j** [comment]
You should discuss about json hack at https://github.com/LLK/scratch-gui/issues/767

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1030
