### ISSUE TITLE
Import and export json

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-blocks#1433]
A similar project is currently being used for this plug-in.
Do you have a detailed API, or how to import and export json?
Please help me，
thank you very much！

**Comment by ghost** [comment]
Use 'ScratchBlocks.Xml.WorkspaceToDom' access to Xml
If you want to get a json format, do you have to encapsulate it yourself? ScratchBlocks doesn't provide the relevant interface.

**Comment by thisandagain** [comment]
We recommend you use the scratch-vm for serialization / deserialization of the blocks. See https://github.com/LLK/scratch-vm/tree/develop/src/serialization for more details.

**Comment by ghost** [comment]
Ok, thanks for your help.
