### ISSUE TITLE
More easy build and compiler.

### ISSUE THREAD

**Issue by kickTec** [LLK/scratch-blocks#1437]
Run python build.py cann't successful because of network connecting,Can you afford a python build script for build local,no network connecting,thank you very much!

**Comment by thisandagain** [comment]
Hi @kickTec, unfortunately Google only supports a network-based build at this type.

**Comment by rachel-fenichel** [comment]
Actually, you can build locally.  It requires you to install the offline version of the closure compiler, but that's all.  Here's a [gist](https://gist.github.com/rachel-fenichel/7368afd0d038c300509af3f5209f27f1) with instructions on how to do an offline build of the vertical version of scratch-blocks.

Note that if you're just trying to tweak the library you may not need the compressed version to check your changes.  In that case you can just use `tests/vertical_playground.html` for testing, which uses `blockly_vertical_uncompressed.js`.  Changes that you make to the JS files will be reflected when you reload the page.
