### ISSUE TITLE
"Undo" is enabled after initially loading a project

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1447]
### Expected Behavior

- The "undo" context menu option should not be available on the workspace immediately after loading a project

### Actual Behavior

- The "undo" context menu option is available. Selecting it will delete all items in the currently active workspace.

### Steps to Reproduce

- Load a project
- Right click on the workspace
- Select "undo"

**Comment by rachel-fenichel** [comment]
Call `workspace.clearUndo`: https://github.com/LLK/scratch-blocks/blob/develop/core/workspace.js#L408

**Comment by mrjacobbloom** [comment]
Should the project remember the undo history from the last time it was loaded?
