### ISSUE TITLE
Vertical Playground to JavaScript error.

### ISSUE THREAD

**Issue by AmazingMech2418** [LLK/scratch-blocks#1448]
### Expected Behavior

It should work.

### Actual Behavior

The console says this:
vertical_playground.html?dir=ltr&toolbox=categories&side=start:133 Uncaught TypeError: Cannot read property 'workspaceToCode' of undefined
    at toCode (vertical_playground.html?dir=ltr&toolbox=categories&side=start:133)
    at HTMLInputElement.onclick (vertical_playground.html?dir=ltr&toolbox=categories&side=start:492)
toCode @ vertical_playground.html?dir=ltr&toolbox=categories&side=start:133
onclick @ vertical_playground.html?dir=ltr&toolbox=categories&side=start:492

### Steps to Reproduce

1. Make a script
2. Click "To JavaScript"

### Operating System and Browser

Chrome, Windows 10

**Comment by thisandagain** [comment]
@amazingmech2418 We currently do not support the use of code generators with Scratch Blocks. We recommend you use the Scratch VM (https://github.com/llk/scratch-vm).
