### ISSUE TITLE
Adjust wording on "go to" Looks block to avoid confusion with "go to" Motion blocks

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1450]
The revised "go to front" block in Looks has a pull-down menu with the options:
go to [front/back] 
This may lead to confusion between the **go to** Motion blocks.

Suggestion to change to:
**go to [front | back] layer**

![image](https://user-images.githubusercontent.com/4721032/38700605-a23c8d84-3e69-11e8-8695-11b910c737ec.png)

---
Moved from LLK/scratch-vm#1051
/cc @ntlrsk

**Comment by kyleplo** [comment]
What about “come” instead of “go to”?

Ex. “come to [back]” or “come [forward] (1) layers”

**Comment by joker314** [comment]
@kyleplo That would resolve the ambiguity, but I prefer thisandagain's idea because it also describes *what* the block does rather than just making it different

**Comment by kyleplo** [comment]
@joker314 What about “come to [back] layer”?

**Comment by joker314** [comment]
That works well, and I think both options work equally well. I would be fine with Scratvh using that terminology -- but I don't see it's superiority to "go"
