### ISSUE TITLE
Some alignment issues in Edge

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#1455]
### Expected Behavior

In Microsoft Edge, the text in the blocks in the blocks list should be aligned correctly

### Actual Behavior

In Microsoft Edge, the text in the blocks in the blocks list is too far to the left, meaning that the text goes off the edge of the block.

This is sometimes, but not always, rectified when the block is dragged to the scripting area and clicked several times.

### Steps to Reproduce
Go to [the preview site](https://preview.scratch.mit.edu) using Microsoft Edge.

### Operating System and Browser

Windows 10 Education, MS Edge 38

---
Moved from LLK/scratch-gui#1807
/cc @python-megapixel

**Comment by thisandagain** [comment]
Thanks for reporting @python-megapixel. This was resolved at one point and appears to be a regression.

**Comment by thisandagain** [comment]
@BryceLTaylor Can you verify / repro?

**Comment by BryceLTaylor** [comment]
Yes I can.  It appears to happen if you are zoomed in at all.
Reproduction Steps:
go to preview.scratch.mit.edu (or to develop) using Microsoft Edge
Click the Try It! button.
Zoom in by pressing ctrl-+
Note that the scroll bar for the category menu covers the left side of the blocks in the block pallete
Zoom back out by pressing ctrl--
Note that it looks like normal now

![blocktextedge041818](https://user-images.githubusercontent.com/1088291/38935828-4ecf014e-42ed-11e8-806c-17e804103e82.png)


You may have to zoom a number of times before you see it depending on your initial zoom level.
If you refresh the page you will still see the issue.

I am seeing this on Windows with Chrome as well, but it is less extreme.  
On Firefox on Windows the scroll bar covers the category menu instead

Chrome:
![chromewindowsblocktext](https://user-images.githubusercontent.com/1088291/38935879-6d3cd4a8-42ed-11e8-9d1f-76933fe06a79.png)

Firefox:
![firefoxwindowsblocktext](https://user-images.githubusercontent.com/1088291/38935889-74f4db6e-42ed-11e8-8c38-c6dbe7febf4c.png)

I am not seeing this on mac with Chrome, Safari, or Chrome.

**Comment by BryceLTaylor** [comment]
I take it back about Chrome on Mac.  At one of the zoom levels it covers the very edge of the blocks but none of the text.
![chromemacblocktext](https://user-images.githubusercontent.com/1088291/38936508-ef38e40a-42ee-11e8-9abe-0657b37581b5.png)

**Comment by BryceLTaylor** [comment]
@thisandagain says that this is a known issue and is documented in a number of other bugs related to being below the screen resolution threshold.
