### ISSUE TITLE
Generate code (Python, Javascript etc.)

### ISSUE THREAD

**Issue by jbmarco** [LLK/scratch-blocks#1466]
Hello,

I would like to translate a program from scratch-blocks to Javascript or Python.
I have seen that there is the function : 

`Blockly.JavaScript.workspaceToCode(workspace)`, but it doesn't work for me.

Is there a possibility to generate code ?

**Comment by thisandagain** [comment]
We do not support Blockly generators in Scratch Blocks.

**Comment by UCYT5040** [comment]
@thisandagain Then what is the point of Scratch Blocks? How should I generate code? The blocks are useless if code can't be generated from them.

I used the blockly web generator (python_compressed.js) but it doesn't work with Scratch Blocks.
