### ISSUE TITLE
Repeat block treats its argument differently than in Scratch 2.0

### ISSUE THREAD

**Issue by Mr-Dave2** [LLK/scratch-blocks#1470]
### Expected Behavior

The repeat block should follow the Scratch 2.0 repeat block behavior of rounding its argument.

### Actual Behavior

The repeat block appears to do a floor (int?) function on its argument.

### Steps to Reproduce

![repeat issue](https://user-images.githubusercontent.com/35544966/39166992-3ab61652-4752-11e8-9878-e324975c0981.png)

### Operating System and Browser

Windows 7 (64 bit), Chrome Version 66.0.3359.117 (Official Build) (64-bit)

The Scratch 3.0 repeat block will break projects like https://scratch.mit.edu/projects/42202752/, which, however wrongly, depend on the rounding of the repeat argument.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#1083
