### ISSUE TITLE
Design - Specialized field editors

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#149]
Breaking out from [Design - Fields / Selectors - Issue 13](https://github.com/LLK/scratch-blockly/issues/13) 

Dropdown Menu Input has been speced here: [Dropdown Input States - Default & Focusing - Issue 148](https://github.com/LLK/scratch-blockly/issues/148) 
The Menu (aside from the input) needs more generalized size specs and behavior (on edge opening and on edge scrolling workspace) specs. 

**Generalized Dropdown Menu - Size / Behavior**
- [x] Variable (Vertical)
- [x] Variable (Horizontal)
- [x] Number Pad (Horizontal Number input)

**Specific UI Dropdown Menus (Depends on Generalized Specs):**
- [ ] Angle
- [ ] Musical note (Keyboard)
- [ ] Color Picker

**Comment by thisandagain** [comment]
@carljbowman Can you split these into an issue for each field editor?

**Comment by carljbowman** [comment]
All remaining specialized menus are being tracked in their own issue.
