### ISSUE TITLE
Variable/broadcast menus sort "name10" before "name2"

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1504]
### Expected Behavior

They should sort "10" after "2", for example "name1", "name2", "name10".

### Actual Behavior

They sort "10" before "2", for example "name1", "name10", "name 2".

![A variables drop-down showing the above](https://user-images.githubusercontent.com/9948030/39717041-764f0794-5208-11e8-9412-6c1fddd5acf5.png) ![A broadcast drop-down](https://user-images.githubusercontent.com/9948030/39717035-7087b48c-5208-11e8-857f-107587247f34.png)

### Steps to Reproduce

Create three variables or broadcasts (or lists) and observe how they're sorted in menus.

### Operating System and Browser

Firefox 61.0b2, Debian (testing).

---

I also noticed the block palette has the same issue, for both variables and custom blocks:

![In the block palette: "variable1", "variable10", "variable2"; "block1", "block10", "block2"](https://user-images.githubusercontent.com/9948030/39717127-abfe73b6-5208-11e8-8516-d007cd294d63.png)

**Comment by mrjacobbloom** [comment]
This might help: https://en.wikipedia.org/wiki/Natural_sort_order
