### ISSUE TITLE
Numpad for number fields shows up in the wrong place

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1506]
### Expected Behavior

Soft number pad (touch devices) should show up near the number field that is focused.

### Actual Behavior

Number pad shows up at the top of the workspace for a block close to the bottom of the page.
![img_0005](https://user-images.githubusercontent.com/1786240/39784295-eb818856-52e5-11e8-8bd9-f6d1c1d62080.PNG)

### Steps to Reproduce

1. On a touch device, drag out a ( () + () ) block to the bottom of the workspace.
2. Focus on a field of the block to type in it.

### Operating System and Browser

iOS 11.2.2 Safari

**Comment by rachel-fenichel** [comment]
The page isn't zoomed, right?

Here's the positioning code: https://github.com/LLK/scratch-blocks/blob/develop/core/field_number.js#L211

**Comment by samelhusseini** [comment]
I have a fix for this here: https://github.com/Microsoft/pxt-blockly/pull/125

**Comment by rachel-fenichel** [comment]
@kchadha this is a good candidate for the bug bash.
