### ISSUE TITLE
Some sound blocks do not have a category label

### ISSUE THREAD

**Issue by ZenithRogue** [LLK/scratch-blocks#1509]
I noticed that a couple of blocks in the Sound category do not have a category label.  I don't know if this actually affects much (other than being unable to properly theme the blocks via custom css), but I though you should be aware.

**These blocks include:**
play sound (sound) until done
change [pitch] effect by (10)
set [pitch] effect to (100)
clear sound effects

I opened a pull request (#1502) that includes a quick fix for this issue.

**Comment by mrjacobbloom** [comment]
Yeah, I think I skipped menus since they were already always directly inside blocks of the same category, but there's no reason that they shouldn't have a category attribute

**Comment by ZenithRogue** [comment]
@mrjacobbloom It is not an issue with menus. Grab [theme3](https://github.com/nitrocipher/theme3) and swap out which color definition line is commented. Scroll to the sound category, and you will see the above stated blocks' color is unaffected. I found that those specific blocks do not have their category defined in the sound.js file

**Comment by mrjacobbloom** [comment]
oh or I just missed some blocks 🙃
