### ISSUE TITLE
Blocks appearing above fixed toolbox/flyout

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#152]
This only seems to happen with the fixed one, not the pop-out show/hide one. Can we just set a z-index or something?

**Comment by tmickel** [comment]
Assigning you @picklesrus as I think you mentioned this problem is fixed by your upcoming changes :)

**Comment by picklesrus** [comment]
Yup, the stuff I'm working on should fix this for "free" :) I'm doing a bit of both of what @drigz mentioned.  I'm splitting everything up in to multiple svgs so the flyout becomes a separate svg which ends up on top.  You can see an early (though now out of date and quite buggy version) here: http://blocktests-1261.appspot.com/bt/tests/flyoutplayground.html.

I'll update that link again once I work through chunks of bugs.  Proper translation and zoom coming soon.

**Comment by tmickel** [comment]
Should be resolved by the Scratch-style toolbox.
