### ISSUE TITLE
Can't run build.py from the command line

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1523]
### Expected Behavior

Running `build.py` from the command line should build the various uncompressed and compressed versions of scratch blocks.

It should use the local compiler if possible, and otherwise fall back to the remote compiler.

### Actual Behavior

Before running `npm install` (so no npm package for google-closure-compiler), or after deleting the contents of `node_modules`:
There are two bugs, fixed by #1512 and #1513

After running `npm install`:
```
./build.py
Traceback (most recent call last):
  File "./build.py", line 595, in <module>
    test_proc = subprocess.Popen(test_args, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

Note that it works as part of the `npm prepublish` command.

I will add more information as I have it.

**Comment by jyh129143** [comment]
I came across the very bug mentioned above for line 595 when running "npm install".There're comments of this problem saying that adding code "shell=True"for line 595.I tried but in vain.

**Comment by EPDUED** [comment]
What is the cause of this problem, other windows system computers can, my computer does not work, have this problem.
