### ISSUE TITLE
Fix when [timer v] > (10)

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-blocks#1525]
### Expected Behavior

The menu on when [timer v] > (10) either has multiple options or doesn't exist. 

### Actual Behavior

Due to things becoming extensions, there is only one option

### Steps to Reproduce

Look at the menu on the when [timer v] > (10)

### Proposal

Remove the menu or brainstorm other option ideas (or add back the loudness option)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/1026 and https://github.com/LLK/scratch-vm/issues/338
