### ISSUE TITLE
Control blocks can be wrapped around procedure prototype blocks

### ISSUE THREAD

**Issue by howettl** [LLK/scratch-blocks#1534]
### Expected Behavior

Procedure prototype blocks should be non-interactive.

### Actual Behavior

If I create a custom procedure, then drag a control block (C-shape) onto the workspace and near to the procedure prototype block inside of the procedure definition block, the grey area appears around the prototype block indicating that I can wrap the control block around it.  Releasing the block at this point causes the prototype block to be duplicated within the control block and draggable around the workspace.
A third, non-draggable copy of the prototype block is also added to the workspace.

### Steps to Reproduce

1. Create a custom procedure
2. Drag a C-shaped control block close to the prototype block within the procedure definition
![screen shot 2018-05-16 at 1 32 50 pm](https://user-images.githubusercontent.com/4719928/40142787-833550a0-590e-11e8-88b6-23c0d6df0c2c.png)

3. Release the control block when the highlight appears
![screen shot 2018-05-16 at 1 32 54 pm](https://user-images.githubusercontent.com/4719928/40142875-bf65e40e-590e-11e8-897a-8c1680697a66.png)

### Operating System and Browser

Mac OS 10.13.4 Chrome 66

**Comment by thisandagain** [comment]
Thanks for finding this @howettl!

**Comment by rachel-fenichel** [comment]
Relevant bits of code:

`Blockly.InsertionMarkerManager.prototype.getCandidate_` calls `myConnection.closest(radius, dxy)`.

`Blockly.Connection.prototype.isConnectionAllowed` gets called.  It calls `canConnectWithReason_`.

`Blockly.Connection.prototype.canConnectWithReason_` has some hacks for handling procedure blocks (gross but got the job done): https://github.com/LLK/scratch-blocks/blob/develop/core/connection.js#L315

If `canConnectWithReason_` passes, there are other checks:
`Blockly.Connection.prototype.canConnectToPrevious_` is probably the relevant check here.  That has a bunch of special cases for various insertion marker and shadow cases.  I've tried to keep the number of extra checks to a minimum, but if you need to hack something in that's probably where it will go.

**Comment by ZenithRogue** [comment]
This will also leave behind a "ghost" that is immobile, and the block picked up into the c will be permanently fused

**Comment by picklesrus** [comment]
whoops. wrong github tab. PR to fix this looks good... will merge.
