### ISSUE TITLE
Undo - Children of removed block sometimes move to the bottom right corner of screen

### ISSUE THREAD

**Issue by Mynini** [LLK/scratch-blocks#1538]
### Expected Behavior
Restore last state

### Actual Behavior
click the undo btn. we find the children blocks that belong to the remove one,move to the right corner of the screem and sometimes they can`t connected with anthor blocks 

### Steps to Reproduce

**Browser environment;**
chrome  66.0.3359.181       Browser environment:
toggle device toolbar    iPhone 6/7  width:736  height:414

Steps:
Drag more than 3 circulation blocks in the workspace and connected them unordered ,them click the undo btn,we find the children blocks that belong to the remove one,move to the right corner of the screem and sometimes they can`t connected with anthor blocks 

**let`s see the deail under the images**：

**step1: drag and connected blocks**
![image](https://user-images.githubusercontent.com/24352270/40228137-01e3900a-5ac3-11e8-8673-9dc0b13d5bf3.png)

**step2:click undo btn** 
![image](https://user-images.githubusercontent.com/24352270/40228436-e0b9b7be-5ac3-11e8-9308-cc1c9cba58c6.png)

**step3:drag the remove block child**
![image](https://user-images.githubusercontent.com/24352270/40228764-c0a966bc-5ac4-11e8-983b-e347d06d6ed5.png)

 **I find  the bug disppear  if I  move workspace before do step2 . there are some video ,you can look the problem detial**
[新建文件夹.zip](https://github.com/LLK/scratch-blocks/files/2048226/default.zip)  

### Operating System and Browser

_e.g. win10  64bit ; chrome  66.0.3359.181

**Comment by thisandagain** [comment]
@BryceLTaylor Could you attempt a repro on this in the vertical and horizontal playgrounds?

**Comment by Mynini** [comment]
@thisandagain

**Comment by Mynini** [comment]
@thisandagain  
I am find undo and redo system has many problem.I maked some video ,you can look the bug through them。I find some anther problem are related width undo and redo ,I will write anther issue .you can look it. scratch-blocks is a very good project,I like it very much ,but it still has many problem. hope it become better and better

**Comment by BryceLTaylor** [comment]
I'm unable to reproduce this on the playground.  Other than some slightly odd repositioning of blocks when placing them back on the workspace.  The blocks are all still functional after undoing/redoing.  All children blocks behave as expected.

![horizontalplaygroundundo](https://user-images.githubusercontent.com/1088291/42534269-4bf5413c-845a-11e8-9113-cec1a872ff7e.gif)
