### ISSUE TITLE
Implement workspace panning by translating the <svg/>, not the group inside

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#154]
@picklesrus @NeilFraser @thisandagain 

I was wondering if any of you have thoughts on this idea.

I've tried playing tricks to improve workspace pan on touch devices without too much success. Even with one block on the workspace, and even hacking the handler to only translate the workspace (and not, for example, keep it within bounds and update scrollbars), there's a perceptible jaggedness to the pan.

Here is my idea:
Instead of applying a CSS translation for the workspace pan, split up the Blockly SVG so that the workspace SVG is separate from other components (the flyout, trash can, etc. can float on top). Then, let the actual workspace SVG be the size of the workspace (when it's large, the SVG is large). Surround the whole thing by a div with `overflow: scroll` and the relevant `-webkit-overflow-scrolling` for touch.

Similar to:
http://jsfiddle.net/L7dsf2dy/5/ (this feels really good on touch devices!)

On desktop, we attach click handlers to the workspace as normal so that click and drag will set the scroll properties of the div. On touch, we let the event fall through to the div and scrolling is handled by the native browser scroller.

We can attach an event to onscroll to adjust the Blockly scrollbars while panning is happening, and hook up those scrollbars to the div scroll properties.

Any thoughts? Does this seem like it could be worth doing, or am I missing something big here?

**Comment by tmickel** [comment]
@picklesrus @rachel-fenichel 

Did some more exploration on this late last week.
We figured out that Safari actually even has this problem in the +X and +Y directions, if you go far enough. Once you exceed the SVG width, the bug appears.

Given this, maybe it would actually make sense to resize the SVG and translate the `blockCanvas` group inside the SVG on the stop of a drag? That I guess would cause a paint and maybe some other things when you finish dragging, but I imagine will still be far better than doing that at every step of the drag?

I hope we can get this change in sometime soon! It's starting to get really noticeable how much workspace panning effects project execution, even on a powerful desktop computer.

**Comment by picklesrus** [comment]
So we'd essentially try and pin the svg's transform to (0,0,0) except during a workspace drag and then at the end of the drag take the svg's transform and apply it to the the block canvas?  

I'm a little worried about the transformations between mouse coordinates and blockly's coordinates, especially if we miss drag ending events (like when you start a workspace drag and end it with your mouse off the window), but this definitely seems worth checking out.  Hack week got delayed so I should have time to work on this again this week.

I had originally been thinking we'd have to update the coordinates of each block at the end of every workspace drag which made me sad. Your idea seems much better. Look at the optimism returning after 2 weeks away from working with coordinates!

**Comment by mrjacobbloom** [comment]
Would this change affect whether or not you guys implement #238?

**Comment by tmickel** [comment]
@picklesrus Yep, exactly :) I'm hopeful that the coordinates won't be too much madness - we'd just need to do (SVG coordinates + blockCanvas coordinates) every time the workspace translation is used. Maybe there's a `workspace.getTranslation` that we can just switch (I forget)? But of course, I think I'm always overoptimistic about how easy these things are to change :P

Missing a drag end event does seem like it could possibly cause very bad results if we did it this way. I suppose we could also make sure that the workspace isn't in "dragging" mode anytime a block starts to drag, etc.? To make sure that's all cleaned up and set to go before we try to do anything. But that might be a lot of checks..any idea about how often these end events are actually dropped?

Yep - that's what I originally thought, too (updating the coordinates of every block). I mean, I guess updating a group's coordinates _is_ updating every block's coordinates, but should be considerably easier (faster?)

Well I'm excited that you'll have time to work on this!! And pretty optimistic about this approach!

@Airhogs777 Actually I'm not sure. Maybe @picklesrus has more ideas about that. I do think it's related. At some point we might have figured out that that _wasn't_ going to give us any significant performance improvement, so we might have been leaning against it. But I don't exactly remember the reasoning now...
