### ISSUE TITLE
I got a TypeError here

### ISSUE THREAD

**Issue by cryanis** [LLK/scratch-blocks#1542]
The TypeError: `Blockly.Generator is not a constructor` .
I don't understand why, please help.

**Comment by cryanis** [comment]
In fact , I want to shim generator javascript file, and I followed steps of [#1033](https://github.com/LLK/scratch-blocks/issues/1033), but it displays an error

**Comment by cryanis** [comment]
@gengshenghong

**Comment by thisandagain** [comment]
Scratch Blocks does not support the use of Blockly generators. We recommend you take a look at the Scratch VM here: https://github.com/llk/scratch-vm
