### ISSUE TITLE
Toolbox is broken in RTL

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1548]
### Expected Behavior

Workspace renders properly in RTL

### Actual Behavior

Switching to RTL in the vertical playground fails with these errors: 
```
flyout_base.js:609 Uncaught TypeError: Cannot set property 'length' of undefined
    at Blockly.VerticalFlyout.Blockly.Flyout.recordCategoryScrollPositions_ (flyout_base.js:609)
    at Blockly.VerticalFlyout.getMetrics_ (flyout_vertical.js:211)
    at Blockly.WorkspaceSvg.getWidth (workspace_svg.js:830)
    at Object.Blockly.Xml.blockToDomWithXY (xml.js:86)
    at new Blockly.Events.Create (block_events.js:226)
    at Object.Blockly.Xml.domToBlock (xml.js:586)
    at Blockly.VerticalFlyout.Blockly.Flyout.show (flyout_base.js:506)
    at Blockly.Toolbox.showAll_ (toolbox.js:209)
    at Blockly.Toolbox.populate_ (toolbox.js:186)
    at Blockly.Toolbox.init (toolbox.js:135)
```
### Steps to Reproduce

Open the vertical playground and switch to RTL mode.

### Operating System and Browser

Any

**Comment by kchadha** [comment]
@ericrosenbaum I just assigned myself to this issue instead since I'm fixing this as part of #1544.

**Comment by rachel-fenichel** [comment]
@kchadha and I dug into this for a bit.

The root problem is that the create event for a block in RTL mode includes a call to `getMetrics`:
```
/**
 * Encode a block subtree as XML with XY coordinates.
 * @param {!Blockly.Block} block The root block to encode.
 * @param {boolean=} opt_noId True if the encoder should skip the block ID.
 * @return {!Element} Tree of XML elements.
 */
Blockly.Xml.blockToDomWithXY = function(block, opt_noId) {
  var width;  // Not used in LTR.
  if (block.workspace.RTL) {
    width = block.workspace.getWidth();  <--------
  }
  var element = Blockly.Xml.blockToDom(block, opt_noId);
  var xy = block.getRelativeToSurfaceXY();
  element.setAttribute('x',
      Math.round(block.workspace.RTL ? width - xy.x : xy.x));
  element.setAttribute('y', Math.round(xy.y));
  return element;
};
```
 This happens as soon as the first block is created, and before layout has happened.  `getMetrics` in the flyout causes a call to `recordCategoryScrollPositions_`, which ~ uses the number of buttons as a count for the number of categories.  At this point no buttons exists, so the list of categories is empty.  This code fails:
`  this.categoryScrollPositions[numCategories - 1].length = 0;`

@kchadha fixed this by adding a check for an empty list of categories, and skipping work in that case. 

As a related problem, the category scroll position code made a simple (no categories) flyout not work.  That should also be fixed by the recent change.

This is more generally symptomatic of way too many calls to `getMetrics` while creating the flyout in RTL, which will definitely cause performance problems.  One solution may be to leave positions off create events on blocks that are in the flyout.
