### ISSUE TITLE
Uncaught TypeError: Cannot read property 'x' of null when duplicating blocks

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1550]
Using right-click to duplicate a block on the workspace causes this error

```
block_dragger.js:393 Uncaught TypeError: Cannot read property 'x' of null
    at Blockly.BlockDragger.pixelsToWorkspaceUnits_ (block_dragger.js:393)
    at Blockly.BlockDragger.dragBlock (block_dragger.js:200)
    at Blockly.Gesture.startDraggingBlock_ (gesture.js:461)
    at Blockly.Gesture.forceStartBlockDrag (gesture.js:974)
    at Blockly.WorkspaceSvg.startDragWithFakeEvent (workspace_svg.js:2209)
    at block_svg.js:752
```

Doesn't _seem_ to cause any big problems, but it is spamming the uncaught error aggregator. :)

---

Update, it also might be a regression because Sentry says it first saw this error 10 days ago. /cc @rachel-fenichel

**Comment by hecor** [comment]
```
Blockly.Gesture.prototype.forceStartBlockDrag = function(fakeEvent, block) {
  this.handleBlockStart(fakeEvent, block);
  this.handleWsStart(fakeEvent, block.workspace);
  this.isDraggingBlock_ = true;
  this.hasExceededDragRadius_ = true;
  // fix this error
  this.updateFromEvent_(fakeEvent);
  this.startDraggingBlock_();
};
```

this will fix the bug in scratch-blocks.

**Comment by rachel-fenichel** [comment]
@hecor Please explain how that fixes the bug--it's not obvious what adding that line does.

**Comment by hecor** [comment]
@rachel-fenichel  It seems that the error is caused by currentDragDeltaXY_ which is not initialized properly, which updateFromEvent_ does.

**Comment by rachel-fenichel** [comment]
Okay, then the solution may be to initialize `currentDragDeltaXY_` in `doStart`.  `updateFromEvent_` is overpowered for this problem.

I would initialize it just after setting `mouseDownXY_` in `doStart`, around line 517.  Please test that and make a pull request.
