### ISSUE TITLE
Use npm packages for selenium/chromedriver so they don't go out-of-date

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1569]
Having the chromedriver and selenium configs in custom scripts is different from our other repos, where we use the npm packages that handle downloading, starting, stopping and correctly setting the path for the respective parts of this system.

If we don't do this, we will have another https://github.com/LLK/scratch-blocks/issues/1567 in a short while

**Comment by rachel-fenichel** [comment]
I'll pull any change for this into Blockly as well.
