### ISSUE TITLE
Workspace Undo should be disabled when workspace is (re-)loaded

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1574]
### Expected Behavior

Undo should always undo the last *user initiated interaction*.

### Actual Behavior

When switching sprites (and switching back) workspace undo is enabled, but using it results in blocks or comments disappearing, even if the creation of the blocks/comments was not the last user initiated interaction on that workspace (see GIF).

Expected behavior for Undo:

![undo_expected](https://user-images.githubusercontent.com/1786240/40981896-10fae13e-68aa-11e8-8580-44663c0d5159.gif)

After sprite switch:

![undo_sprite_switch](https://user-images.githubusercontent.com/1786240/40981993-3ff8dc5c-68aa-11e8-9e2b-8c55fd88bf25.gif)

When dealing with comments, this is even more jarring (undoing on a workspace with comments after a sprite switch will remove random comments, redoing does not get all of their state information back):

![undo_comments_sprite_switch](https://user-images.githubusercontent.com/1786240/41163361-748f221a-6b06-11e8-8288-1beb9c75ae5e.gif)

Proposed solution: Workspace undo should probably get disabled when switching sprites.

**Comment by rachel-fenichel** [comment]
Proposed solution: call `workspace.clearUndo` when switching sprites to flush the queue.
