### ISSUE TITLE
Closure Library link in installation wiki page is not correct

### ISSUE THREAD

**Issue by yami** [LLK/scratch-blocks#1583]
### Expected Behavior

On wiki page https://github.com/LLK/scratch-blocks/wiki, the link to Closure Library should be https://developers.google.com/closure/library/ 

### Actual Behavior

It is https://developers.google.com/closure/compiler/ currently.

### Steps to Reproduce

N/A

### Operating System and Browser

N/A

**Comment by thisandagain** [comment]
Thanks for catching that! Fixed.
