### ISSUE TITLE
Category labels and buttons should right align if the layout is RTL

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-blocks#1584]
### Expected Behavior

_Please describe what should happen_
If the layout is RTL, category labels and flyout buttons should be right aligned.

### Actual Behavior

_Describe what actually happens_
Category labels and buttons are left aligned - for example the Data category in the playground:
<img width="354" alt="screen shot 2018-06-12 at 2 28 54 pm" src="https://user-images.githubusercontent.com/399209/41309661-6239e6d2-6e4d-11e8-987a-644dab874db9.png">

### Steps to Reproduce

In the vertical playground, switch the direction to 'RTL', scroll to the Data category.

**Comment by thisandagain** [comment]
@ericrosenbaum says he can help!
