### ISSUE TITLE
Visible delays when loading block icons in toolbox

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#159]
If I open a toolbox with lots of blocks, the blocks first appear without icons, and the icons are then filled in, going left to right. Due to apparently surprisingly slow serving, I can even observe this when running on my workstation with node's http-server, or when running in a WebView with images built into the APK.

![icon loading](https://cloud.githubusercontent.com/assets/632207/14283193/8aeef232-fb42-11e5-8ef7-0e6e1eb836f2.png)

A couple of possible solutions:
- Sprited, rasterised icons
  - Does (Scratch-)Blockly support sprited block icons?
- Preloading icons on page load
  - Where should this be hooked?
  - Is it better to delay the toolbox opening if the icons haven't been loaded yet?

Any thoughts? Is this something you've considered already?

**Comment by picklesrus** [comment]
I'm going to close this for now since a lot has changed and it was was specific to the app. Any image loading optimizations probably would be done with the whole of scratch & vm in mind now.
