### ISSUE TITLE
Add support for more keys.

### ISSUE THREAD

**Issue by VATstudios** [LLK/scratch-blocks#1595]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by kyleplo** [comment]
I don't understand.

**Comment by thisandagain** [comment]
Please complete the issue template and provide sufficient information for us to understand your issue.
