### ISSUE TITLE
Switching to a sprite focuses on most recent block comment

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-blocks#1601]
### Expected Behavior

Selecting a sprite should not select/focus on any of the comments.

### Actual Behavior

If there are any block comments on a sprite you switch to it will add a blinking cursor to the comment.  If the project is controlled by keyboard keys you could end up typing in the comment.

### Steps to Reproduce

Create a project
Add a second sprite
In one sprite drag a block onto the workspace
right click the block and add a comment
type something in the comment
Switch to the other sprite
switch back
Note: the cursor is on the comment.

Note: This is not the case with workspace comments.
Note: if there is more than one block comment it will highlight the newer one.

### Operating System and Browser

Chrome on Mac

**Comment by kchadha** [comment]
Related to this (I believe) @ericrosenbaum found the following issue in a smoke test on 6/8:
> On android chrome, loading a project with a comment enables the soft keyboard on load (but not 100% of the time?)
