### ISSUE TITLE
Change Extensions' Block Color

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#1612]
### Overview

The current "coral" color that we use for extensions was temporary and is the same color used for More Blocks. Now that Pen has become an extension, the "aqua" color is now up for grabs. We should change all extensions to use the "aqua" color.

### Mock of Some Extension Blocks
![r1 2_extension-color- aqua 2x](https://user-images.githubusercontent.com/3409578/41930642-aca16c70-7949-11e8-90e6-6685f8b42f40.png)

**Primary**
hsla(163, 85%, 40%, 1)
#0FBD8C

**Secondary**
hsla(163, 85%, 35%, 1) 
#0DA57A

**Tertiary** 
hsla(163, 85%, 30%, 1) 
#0B8E69

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#1275
