### ISSUE TITLE
[Lang:JA] Some blocks have a word twice

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-blocks#1616]
### Expected Behavior
The block names should be translated as we did on Transifex.
### Actual Behavior
It seems that some %(num)s are buggy.
![](https://screenshotscdn.firefoxusercontent.com/images/7fc26b26-5044-4670-be68-68677df2a0c2.png)
Like "go forward forward 1 layers"
"costume name name"
"backdrop name name"
"change pitch pitch effect by 10"
"set pitch pitch effect to 100"

### Steps to Reproduce
1. change language to Japanese `?locale=ja`
2. You can find them in block palette
### Operating System and Browser
Windows 10 64bit, Firefox 60.0.2

Thanks for Poteto143 who reported it first!
https://scratch.mit.edu/discuss/post/3156947/

**Comment by Kenny2github** [comment]
It looks like that's just a problem with the people who translated the names. They don't realize that the input can say "costume [name v]" so they thought they were doing "costume (generic input) name".

**Comment by apple502j** [comment]
@Kenny2github I translated. I checked scratch-l10n by myself.

**Comment by Kenny2github** [comment]
Ah, yes, I see. Now it looks like the contents of dropdown menus get duplicated.
