### ISSUE TITLE
Last extension block appears at the top of the flyout  

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#1617]
### Expected Behavior

The blocks should behave themselves.

### Actual Behavior

After adding two different extensions that both show the status indicator button, the last extension block shows up at the very top of the flyout:

<img width="310" alt="screen shot 2018-07-02 at 3 45 31 pm" src="https://user-images.githubusercontent.com/567844/42183404-b26f9f30-7e0f-11e8-9d7c-dc430e08e82d.png">

These errors appear in the console:
`Error: <g> attribute transform: Trailing garbage, "translate(12,NaN)".`
`Error: <rect> attribute y: Expected length, "NaN".`

### Steps to Reproduce

- Add the EV3 extension
- Add the microbit extension
- Scroll to the top of the flyout

Alternately, you can trigger the error in the playground by editing the default toolbox, for example by duplicating the entire extensions category, so there are two categories that both show the status indicator button.

**Comment by paulkaplan** [comment]
Fixed!
