### ISSUE TITLE
Why is there no Micro:bit "button [] pressed?" block

### ISSUE THREAD

**Issue by kyleplo** [LLK/scratch-blocks#1632]
### Expected Behavior

There should be a "button [a/b/any] pressed?" block for micro:bit.

### Actual Behavior

There isn't one.

### Steps to Reproduce

Look at the blocks of the micro:bit extension.

### Operating System and Browser

All.

**Comment by apple502j** [comment]
move to VM?

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#1308
