### ISSUE TITLE
Automate syncing with Transifex and add test

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1635]
Add a task that works for all Scratch Team developers to ensure that everything gets sync'd when a new message is added to the messages file:
* Regenerate the en.json source
* Upload the source file `en/json` to Transifex
* Translation files are downloaded from Transifex (to ensure new key is included for all languages)
* Regenerate the full scratch_msgs file with the new key.

Finally:
* Add a test to ensure that the task to regenerate everything has been run if there's a new message.

### Background from Paul
I encountered an issue in this pr https://github.com/LLK/scratch-blocks/pull/1622 where I added a key to `msg/messages.js` but did not run `npm run translate`, which was able to merged to develop but then couldn't be merged into GUI because it caused the integration tests to fail. 

I'm gonna write out all the things that happened from a developer trying to add a new message:
- I created a PR that added a new msg/messages.js: https://github.com/LLK/scratch-blocks/pull/1622 
- I didn't read the note @thisandagain added to the top of that file about running `npm translate` after adding keys.
- There were no tests to fail on the CI that would have prevented merging without having run that script. 
- When I realized something was wrong, I tried to run `npm run translate`, and it modified two files (en.js/en.json) in a way that looked reasonable, but it seemed to blow up most of the content of scratch_messages, so @kchadha and I didn't know how to proceed.
- Only @chrisgarrity knew what to do to fix it! Thanks for the help fixing it (https://github.com/LLK/scratch-blocks/pull/1634)

**Comment by chrisgarrity** [comment]
Plan to fix this by adding automated translation syncing for scratch-blocks.
