### ISSUE TITLE
Extensions status button not clickable on Edge

### ISSUE THREAD

**Issue by BryceLTaylor** [LLK/scratch-blocks#1660]
### Expected Behavior

Clicking the extension status button on the microbit extension should bring up the connection window

### Actual Behavior

It doesn't.  Nothing happens.  No errors appear in the console

### Steps to Reproduce

Add the microbit extension to a project
Connect to a microbit
Go to the project
Click the extension status button
Note: Nothing happens

### Operating System and Browser

Edge on Windows

**Comment by thisandagain** [comment]
@ericrosenbaum This feels like it should be on the critical path for August given the amount of usage we are seeing on Edge.
