### ISSUE TITLE
Dropping a block over a button in the blocks palette activates it

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1671]
### Expected Behavior

The button is not activated, since it was not clicked.

### Actual Behavior

The button is activated.

### Steps to Reproduce

Drop a block over a button in the block palette, such as "Make a Variable".

### Operating System and Browser

Firefox 62.0b14, Debian (testing).

**Comment by kchadha** [comment]
@ericrosenbaum, I think this could be a regression that was introduced by #1667.

**Comment by BryceLTaylor** [comment]
I'm seeing this too, but you must let up the mouse button in order to click.  You can also click on the workspace and them move the mouse over a button and let it up to activate the button.

You CAN'T put the mouse down on the category menu, then drag it over the button and let it up to click it.
