### ISSUE TITLE
Can't install, ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/...

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#1673]
### Expected Behavior
npm install works on scratch-blocks

### Actual Behavior
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rxjs@5.5.11 (node_modules/rxjs):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/rxjs-7bd7caeb/_esm2015/add/operator/ignoreElements.js.map'
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: rxjs@6.2.2 (node_modules/listr/node_modules/rxjs):
npm WARN enoent SKIPPING OPTIONAL DEPENDENCY: ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/rxjs-7cf85389/_esm5/internal/scheduler/animationFrame.js.map'
npm ERR! Linux 4.4.0-17134-Microsoft
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! path /mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/core-js-267d0b41/es6/function.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall utime

npm ERR! enoent ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/core-js-267d0b41/es6/function.js'
npm ERR! enoent ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/core-js-267d0b41/es6/function.js'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! Please include the following file with any support request:
npm ERR!     /mnt/c/Users/DD/Git/scratch-blocks/npm-debug.log

### Steps to Reproduce
1. Pull LLK/scratch-blocks develop branch
2. Sync to head
3. rm -rf node_modules
4. npm install

### Operating System and Browser
Windows 10

**Comment by fsih** [comment]
The exact error changes every time I run install
ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/core-js-267d0b41/es6/function.js'
ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/pify-e77c4163/license'
ENOENT: no such file or directory, utime '/mnt/c/Users/DD/Git/scratch-blocks/node_modules/.staging/date-fns-184e882e/locale/fi/index.js'

but it always seems to be in the .staging folder

**Comment by fsih** [comment]
Fixed by updating to NPM 5 or higher

**Comment by sunyton** [comment]
delete package-lock.json ,and npm i again
