### ISSUE TITLE
Text in block dropdown menus should be right-aligned in RTL

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1675]
### Expected Behavior

Block dropdown menus in RTL should be a mirror image of how they look in LTR.

### Actual Behavior

LTR dropdown menus:

![image](https://user-images.githubusercontent.com/1786240/43846475-69bfbfa4-9afc-11e8-9347-512f6d6933b1.png)

RTL dropdown menus:

![image](https://user-images.githubusercontent.com/1786240/43846513-888354a0-9afc-11e8-8ab3-deae7984b2c4.png)

<img width="243" alt="screen shot 2018-08-24 at 12 14 18 pm" src="https://user-images.githubusercontent.com/399209/44595544-4daec600-a797-11e8-8c39-c3b93f3d3fd1.png">

**Comment by rachel-fenichel** [comment]
This works properly in Blockly, raising the question of what changed.  One big difference is that scratch blocks uses `.blocklyDropDownDiv` and blockly uses `.blocklyWidgetDiv`.  It looks like most of the CSS applies to both equally, but I am starting to suspect that a class got dropped somewhere.
