### ISSUE TITLE
Some custom block inputs are "invisible"

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1691]
### Expected Behavior

All inputs in calls of the custom block look ordinary, i.e. white and can be typed in.

### Actual Behavior

There are a *lot* of weird issues with calls of this custom block.

Here is what they look like when you open the project:

![Screenshot of three calls of the same custom block which has three inputs; First: "behavior" is empty - Second: "behavior" and "spacing" are empty - Third: "spacing" is empty](https://user-images.githubusercontent.com/9948030/44272262-bbe10f00-a212-11e8-8017-208bbdf8398f.png)

Here is what they look like when you drag out the "pick random" block from the "velocity" input:

![Screenshot of the three calls again; in the first, there is an ordinary empty input, but in the other two, the input is "missing", just a darker red empty input-shaped field](https://user-images.githubusercontent.com/9948030/44272343-e8952680-a212-11e8-9d9d-4e075dcf09e0.png)

**Note that, during the development of the project that used this custom block, I added new inputs to the "Spawn in a Circle" custom block multiple times.** I know I originally created the custom block with just the first input, "behavior:". Later I created the "velocity" and "spacing" inputs, but I'm not sure what order. I think I may have created "spacing" first, but I'm 90% not sure.

### Steps to Reproduce

Download this project and open it in the Scratch 3.0 GUI, and observe the ensuing weirdness as described in "actual behavior": [untitled-project-8_17_2018-11_38_37 AM.zip](https://github.com/LLK/scratch-blocks/files/2297636/untitled-project-8_17_2018-11_38_37.AM.zip)

### Operating System and Browser

Firefox 62.0b17, Debian.

**Comment by rachel-fenichel** [comment]
Are there any errors in the console?

**Comment by towerofnix** [comment]
@rachel-fenichel No, no errors when loading the project nor when removing or putting back the "pick random" blocks.

**Comment by kchadha** [comment]
I haven't looked into the attached project yet, but I wonder if this issue is related to LLK/scratch-vm#1091
