### ISSUE TITLE
Block comments in RTL don't have expected position

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-blocks#1700]
### Expected Behavior

_Please describe what should happen_
Comment is attached just to the right of the block in LTR:
<img width="281" alt="screen shot 2018-08-24 at 11 55 43 am" src="https://user-images.githubusercontent.com/399209/44594648-d11ae800-a794-11e8-91fd-5e54b58e7634.png">

In RTL , it should appear just to the left.

### Actual Behavior
<img width="222" alt="screen shot 2018-08-24 at 11 56 34 am" src="https://user-images.githubusercontent.com/399209/44594701-f90a4b80-a794-11e8-853f-5cf0f0d32419.png">

### Steps to Reproduce

load https://scratch.mit.edu/projects/230672117/

**Comment by kchadha** [comment]
This is specifically an issue for when block comments are loaded from a 2.0 project.
