### ISSUE TITLE
After switching languages, the working area's scaling becomes 100%

### ISSUE THREAD

**Issue by cyx2015s** [LLK/scratch-blocks#1706]
### Expected Behavior
![20180830_164819_20180830164945](https://user-images.githubusercontent.com/31377746/44841073-1ea3c300-ac75-11e8-9c5c-c7fdf6e74256.gif)
### Actual Behavior
![20180830_164442_20180830164704](https://user-images.githubusercontent.com/31377746/44841081-23687700-ac75-11e8-9e70-627a0268895a.gif)
### Steps to Reproduce
Do as the image
### Operating System and Browser

Win8, Chrome 68

**Comment by cyx2015s** [comment]
Maybe I should post it in scratch-gui?

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#3277
