### ISSUE TITLE
Editing number inputs have the minus sign in the wrong place (right) in RTL mode

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-blocks#1708]
### Expected Behavior
Numbers and math in general are still LTR in RTL languages (e.g. Hebrew)

Number inputs should still have the minus sign on the left.

related to https://github.com/google/blockly/issues/1802

### Actual Behavior

When the input is selected, the minus sign switches to the right. 
If you type a new negative value the minus sign is on the right until you hit enter or click outside. 
![2018-08-30 13 47 15](https://user-images.githubusercontent.com/399209/44869573-ed6ac900-ac5b-11e8-8bdb-f3551a2a793c.gif)

### Steps to Reproduce

Switch into Hebrew and then type a negative number in an input

**Comment by epicfaace** [comment]
It seems like `&#8234;` and `&#8236;` are being inserted around the characters when the text is saved, rather than using the `direction="rtl"` attribute, which causes the text to not display properly in RTL mode.

**Comment by chrisgarrity** [comment]
duplicate of #1707
