### ISSUE TITLE
[Cloud] [Suggestion] New block: time since [cloudvar] changed

### ISSUE THREAD

**Issue by TheLogFather** [LLK/scratch-blocks#1711]
### Expected Behavior

Project has a way to tell it's still connected to cloud, and that changes to a cloudvar are not just local.

### Actual Behavior

Project cannot tell if a change to a cloudvar has got through to the cloud to be seen by others.

----

Read here for info on how the "time since [cloudvar v] changed" block behaves, as well as thoughts about implementation:
https://scratch.mit.edu/discuss/post/3242386/

**Comment by kyleplo** [comment]
:+1: Also, maybe a `most recent user to update [cloudvar]`

**Comment by thisandagain** [comment]
Moved to LLK/scratch-gui#3358
