### ISSUE TITLE
Some default values and all image name has no laclization

### ISSUE THREAD

**Issue by guyhed** [LLK/scratch-blocks#1716]
### Expected Behavior

All names and default values should be in the local language.
(In Israel many children do not know how to read English letters before the 4th grade)

### Actual Behavior

Some name and variables are not yet translated:
1. Default costume names are: costume1, costume2,..
   Same for backdrops: backdrop1...

2. All image names in the "choose image" and "choose backdrop" menus are not yet translated.

3.  Some default values:
   
![capture1](https://user-images.githubusercontent.com/1233716/45637064-34f1b180-bab2-11e8-8ee3-3265dce89e59.PNG) ![capture2](https://user-images.githubusercontent.com/1233716/45637147-68344080-bab2-11e8-81a0-1eb10f329889.PNG) ![capture3](https://user-images.githubusercontent.com/1233716/45637195-8ac65980-bab2-11e8-9a82-11a057908cc1.PNG)

**Comment by apple502j** [comment]
The translation will be available on Transifex.

**Comment by thisandagain** [comment]
As @apple502j said, the translations are available on Transifex but simply have not been translated yet.

**Comment by guyhed** [comment]
All available translations on transifex are already translated and reviewed.
The images and backdrops names are not available there 
Please reopen.
