### ISSUE TITLE
setHighlighted function of blocksvg does not exist

### ISSUE THREAD

**Issue by jihuiwang** [LLK/scratch-blocks#1723]
### Actual Behavior

in the function below, the setHighlighted function does not exist
Blockly.WorkspaceSvg.prototype.highlightBlock

### Operating System and Browser

_e.g. Chrome

**Comment by jihuiwang** [comment]
i think it could be changed to setGlowBlock

**Comment by thisandagain** [comment]
Please fully complete the issue template and provide sufficient information and context for us to help you.
