### ISSUE TITLE
Block drag outside not firing when below the toolbox

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#1768]
### Expected Behavior

_Please describe what should happen_

The "drag outside" event should fire when the dragged block leaves the blocks area, including **below the toolbox**. 

### Actual Behavior

_Describe what actually happens_

Dragging over the toolbox and down off the workspace, specifically for dragging into the backpack, does not fire the drag outside event. 

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

![drag-outside](https://user-images.githubusercontent.com/654102/48003259-f05ebb80-e0db-11e8-9d60-b8fe6b134725.gif)

Turn on "log events" in the vertical playground, and watch the events when dragging below the toolbox vs. below the main workspace. 

---

The cause is in this function, [WorkspaceSvg#isInsideBlocksArea](https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_svg.js#L1243-L1249) which returns true if the event is over the delete area OR over the blocks area. The delete area is registering as "infinitely" tall, instead of its normal height. This seems like it was clearly a conscious choice, so I don't want to mess with that without knowing the history. But we do need to be able to drag a block off the workspace into a spot directly below the toolbox, so this logic may need to change. 

/cc @picklesrus or @rachel-fenichel, maybe one of you could shed some historical light on the infinite size of the delete area, and what to consider when fixing this?

**Comment by rachel-fenichel** [comment]
Sounds like you've found all of the relevant code.  Blockly makes the delete area extend up and down to make it easier for users to find, but in this context it's the wrong behaviour.  Changing the delete area for the toolbox/flyout will work fine.

Note that the delete area also extends pretty far to the left of the actual flyout and toolbox.  If you're putting the workspace in a context with more drag targets to the left, you'll also want to change that.
