### ISSUE TITLE
Check boxes don't work after autoclosing

### ISSUE THREAD

**Issue by MaggieLu** [LLK/scratch-blocks#1778]
### Expected Behavior
After autoclosing the vertical flyout, check boxes in it should be clickable.

### Actual Behavior
Check boxes are unclickable after auto closing ~
![animation](https://user-images.githubusercontent.com/10663057/48302821-8f504100-e53c-11e8-9220-7230ac02e49a.gif)

### Steps to Reproduce
1.  In flyout_vertical.js: set ```Blockly.VerticalFlyout.prototype.autoClose``` set to be true
2. Drag any block out from the flyout
3. Click on any checkbox

### Operating System and Browser

Win10 Chrome 70

**Comment by Yezzle** [comment]
You can just close it... I also meet the same problem,can someone give me some suggestions
```javascript
 Blockly.VerticalFlyout.autoClose = false;

```

**Comment by thisandagain** [comment]
@MaggieLu We currently do not support auto-closing the flyout. That said, if you'd like to submit a patch we would be more than happy to take a look and consider landing it.

**Comment by MaggieLu** [comment]
@thisandagain  Sorry for the late apply. Not sure whether I am doing it right, I fixed it by refreshing selections in scrollToCategoryById and scrollToCategoryByName in core/toolbox.js. 
```
Blockly.Toolbox.prototype.scrollToCategoryByName = function(name) {
// start 
 if (!this.flyout_.isVisible_) {
    this.refreshSelection();
  }
// end

  var scrollPositions = this.flyout_.categoryScrollPositions;
  for (var i = 0; i < scrollPositions.length; i++) {
    if (name === scrollPositions[i].categoryName) {
      this.flyout_.setVisible(true);
      this.flyout_.scrollTo(scrollPositions[i].position);
      return;
    }
  }
};

Blockly.Toolbox.prototype.scrollToCategoryById = function(id) {

// start 
 if (!this.flyout_.isVisible_) {
    this.refreshSelection();
  }
// end

  var scrollPositions = this.flyout_.categoryScrollPositions;
  for (var i = 0; i < scrollPositions.length; i++) {
    if (id === scrollPositions[i].categoryId) {
      this.flyout_.setVisible(true);
      this.flyout_.scrollTo(scrollPositions[i].position);
      return;
    }
  }
};
```
