### ISSUE TITLE
Throw Error when switching to the uncompress mode.

### ISSUE THREAD

**Issue by TongDaDa** [LLK/scratch-blocks#1792]
### Expected Behavior
I need to switch to uncompressed mode because I want to modify the internal codes, I switched the entry file to uncompress under the `blockly_compressed_vertical` file. The code is as follows

```javascript
// previous
module.exports = require('imports-loader?this=>window!exports-loader?Blockly&goog!../blockly_compressed_vertical');

// Now that is my modified
module.exports = require('imports-loader?this=>window!exports-loader?Blockly&goog!../blockly_uncompressed_vertical');
```

I want to load the blockly_uncompressed_vertical, no compress.

_Please describe what should happen_
No Errors;

### Actual Behavior

Ok,  Just happened many matters, When My first modify this file that is `blockly_compressed_vertical.js` to change its content as:

```javascript
module.exports = require('imports-loader?this=>window!exports-loader?Blockly&goog!../blockly_uncompressed_vertical');
```
note: Above change that is to modify `blockly_compressed_vertical` to the `blockly_uncompressed_vertical`

So, There has some Errors as follows:

<img width="742" alt="2018-11-26 8 13 59" src="https://user-images.githubusercontent.com/23241188/49013526-08e06400-f1b8-11e8-9840-72a40fa8b9b8.png">

<img width="637" alt="2018-11-26 8 14 53" src="https://user-images.githubusercontent.com/23241188/49013541-1c8bca80-f1b8-11e8-95e1-e3b021c6f5bf.png">

The `isNodeJs` variable is not veracious because the `window is undefined` caused by the window quote is `this` in the scope. no the variable of a window.

And then I fix this bug, so add `var window = this;` in the file. but there have other Errors yet, as follows:

<img width="1053" alt="2018-11-26 8 23 57" src="https://user-images.githubusercontent.com/23241188/49013911-3f6aae80-f1b9-11e8-80e9-644a6a8a7445.png">

<img width="691" alt="2018-11-26 8 24 46" src="https://user-images.githubusercontent.com/23241188/49013939-5c9f7d00-f1b9-11e8-837f-6fc117d2cffa.png">

Above these errors caused by the variable of `Blockly` no statement in the file, I don't know what do I can to do, please you can run this file rather than `compress`?

### Steps to Reproduce

I have run in `scratch-gui` project, and above handles in the scratch-blocks of node_modules of `scratch-gui`, so I have already installed the `scratch-blocks` dependencies.

When I only modify the file of` blockly_compressed_vertical` as 
```
module.exports = require('imports-loader?this=>window!exports-loader?Blockly&goog!../blockly_uncompressed_vertical');
```

It will throw other Errors as follows
```
    ERROR in ./node_modules/scratch-blocks/node_modules/google-closure-library/closure/goog/bootstrap/nodejs.js
    Module not found: Error: Can't resolve 'fs' in '/Users/liutong/Desktop/projects/source_code/scratch-gui/node_modules/scratch-blocks/node_modules/google-closure-library/closure/goog/bootstrap'
     @ ./node_modules/scratch-blocks/node_modules/google-closure-library/closure/goog/bootstrap/nodejs.js 43:9-22
     @ ./node_modules/scratch-blocks/node_modules/imports-loader?this=>window!./node_modules/scratch-blocks/node_modules/exports-loader?Blockly&goog!./node_modules/scratch-blocks/blockly_uncompressed_vertical.js
     @ ./node_modules/scratch-blocks/shim/blockly_compressed_vertical.js
     @ ./node_modules/scratch-blocks/shim/blockly_compressed_vertical.goog.js
     @ ./node_modules/scratch-blocks/node_modules/imports-loader?Blockly=../shim/blocks_compressed_vertical-blockly_compressed_vertical-messages,goog=../shim/blockly_compressed_vertical.goog!./node_modules/scratch-blocks/node_modules/exports-loader?Blockly!./node_modules/scratch-blocks/msg/scratch_msgs.js
     @ ./node_modules/scratch-blocks/shim/vertical.js
     @ ./src/lib/make-toolbox-xml.js
     @ ./src/containers/blocks.jsx
     @ ./src/playground/blocks-only.jsx
     @ multi (webpack)-dev-server/client?http://0.0.0.0:8601 ./src/playground/blocks-only.jsx

```

Maybe caused by the webpack.config not config the target as 'node'? but after set up the option of 'node', It will happend other question.

### Operating System and Browser

Mac OS 10.11.6
Chrome

**Comment by thisandagain** [comment]
@rschamp @picklesrus Any thoughts here?

**Comment by rschamp** [comment]
I don't think it's possible to use the uncompressed version this way. The webpack process requires the compressed version to be able to package everything into a single file.  The uncompressed version includes import statements that require closure-library, and that necessitates a directory structure with closure-library located "one directory above", which isn't really feasible in the way the GUI runs.

To see your changes to scratch-blocks in the GUI, you should re-build after making changes so that the compressed version has your modifications.

**Comment by picklesrus** [comment]
Agreed with @rschamp.  I have wanted to, temporarily, get uncompressed blocks from gui for debugging purposes.  IIRC, I hacked the block's build.py file to add  `("debug",` "true") somewhere around here: https://github.com/LLK/scratch-blocks/blob/develop/build.py#L347 but that was really just to understand my misuse of the blocks inside gui.

**Comment by TongDaDa** [comment]
Thanks everyone's attation.

@picklesrus But, how to solve this error when import the ucompressed file?

**Comment by epicfaace** [comment]
@TongDaDa I've had the same problem, you can't use the uncompressed file. You can use @picklesrus 's workaround, which I think will just make the `blockly_compressed_vertical` file have uncompressed code in it.

**Comment by TongDaDa** [comment]
I just confused about this problem, why don't support uncompressed codes? @epicfaace @picklesrus

**Comment by TongDaDa** [comment]
How do you develop this project when you are changed `Blockly`? @picklesrus

**Comment by noamraph** [comment]
@TongDaDa this is what I did. It caused closure-compiler to generate more readable code.

I cloned scratch-blocks. I modified:

```
diff --git a/build.py b/build.py
index 6ac6869..a0e6a8f 100755
--- a/build.py
+++ b/build.py
@@ -239,6 +239,8 @@ class Gen_compressed(threading.Thread):
       search_paths = self.search_paths_horizontal
     # Define the parameters for the POST request.
     params = [
+      ("debug", "true"),
+      ("formatting", "PRETTY_PRINT"),
       ("compilation_level", "SIMPLE"),
 
       # remote will filter this out
```

And then run

```
npm install
```

And then, in scratch-gui, I run
```
npm install ../scratch-blocks
```
