### ISSUE TITLE
FieldColourSlider: error when brightness from zero to other value 

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-blocks#1808]
### Expected Behavior

Block's color field slider can work well.

### Actual Behavior

Color field get unexpect color when brightness from 0 to other value.

### Steps to Reproduce

See the gif: 
![slide color](https://user-images.githubusercontent.com/15828392/49628339-8d37b000-fa1e-11e8-9090-6acc122dc90a.gif)

### Operating System and Browser

Win10 x64, Google Chrome 70.0.3538.110

**Comment by thisandagain** [comment]
Please don't create duplicate issues. Tracking in https://github.com/LLK/scratch-gui/issues/3985
