### ISSUE TITLE
Blocks in "Echo of the Light - prototype" do not show up

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1822]
### Expected Behavior

The blocks show up (when you have the "Pen Text Engine" sprite selected), looking something like this:

![The scripting area in 2.0, showing a myriad of complex, lengthy scripts](https://user-images.githubusercontent.com/9948030/50038055-bee8e200-ffef-11e8-8d2e-7ede3ffbff16.png)

### Actual Behavior

The blocks don't show up at all! Note that the the scripts *run*, though - if you click the green flag, the project will function correctly. So I think this is a problem in scratch-blocks, preventing the blocks from blocks from showing up, but they exist in the VM properly.

### Steps to Reproduce

Load the project in Scratch 3.0: https://llk.github.io/scratch-gui/develop/#269991846

### Operating System and Browser

I can repro this in Firefox (65.0b2). The original post pointing out this compatibility issue was from done while Chrome 70.0.3538.110.

---

Copied from [a post on the Scratch forums](https://scratch.mit.edu/discuss/topic/324629/), quoted below:

>When I try to load this project in the beta editor, the editor comes up completely blank. It's like all the scripts in the project have been completely deleted by something. Miraculously, the costumes and variables are untouched - the single costume is still there and unchanged, and none of the variables in the project have been deleted. It's only the scripts themselves that have been deleted. I've tried duplicating the project; the duplicate has the same problem. I've also tried backpacking the scripts over to another project - initially, that seems to solve the problem, but after backpacking several scripts over the new project ends up just like the original project. Strangely, I've noticed that if you interact with the project as if it were running and then click the stop button, it displays a snapshot of the project as if it were actually working in the editor.

OP [also said](https://scratch.mit.edu/discuss/post/3347932/) they don't think they used any hacked blocks.

>I'm fairly sure I didn't use any hacked blocks, and I doubt that there are too many scripts given that another project with 31 scripts works fine… (the troublesome one has 18…)

**Comment by towerofnix** [comment]
This might be related to #1380, since it's the same error in the console ("XML Parsing Error: not well-formed"). I didn't see any obviously hacked or suspicious blocks when checking each script in 2.0, though (and definitely no "key () pressed?" with a weird input value), so I don't think it's exactly the same thing.

**Comment by towerofnix** [comment]
From investigation by @Mr-Dave2, it looks like this might be a case of LLK/scratch-vm#1077: https://github.com/LLK/scratch-vm/issues/1077#issuecomment-447148921

**Comment by kchadha** [comment]
The issue with this project has been resolved with (see PRs below).

LLK/scratch-vm#1973
LLK/scratch-gui#4486
LLK/scratch-vm#1983
LLK/scratch-parser#53
