### ISSUE TITLE
Dragging a block over vertical category menu doesn't delete it immediately

### ISSUE THREAD

**Issue by epicfaace** [LLK/scratch-blocks#1830]
### Expected Behavior

When I drag a block over the vertical category menu, it should immediately get deleted.

### Actual Behavior

The block gets "stuck" there for a bit. Only when I click somewhere else does the screen "refresh" and the block actually gets deleted.

![2018-12-18 07 25 26](https://user-images.githubusercontent.com/1689183/50154092-5a02e580-0296-11e9-9d5d-c7ecb1802240.gif)

### Operating System and Browser

Mac OS, Chrome

**Comment by jakel181** [comment]
I tried this out and it only seems to happen when at least 50% or more of the block touches the vertical category.
