### ISSUE TITLE
Delete cursor not appearing when dragging a block over the toolbox

### ISSUE THREAD

**Issue by kchadha** [LLK/scratch-blocks#1836]
@epicfaace and I noticed recently that the delete cursor does not appear when dragging a block over the block toolbox.

The cursor does appear, but only when the block is over the bottom of the category menu: 

![delete-cursor](https://user-images.githubusercontent.com/1786240/50229565-9f97df00-0378-11e9-9ab7-2215e6c68e1d.gif)

_Originally posted by @kchadha in https://github.com/LLK/scratch-blocks/issue_comments#issuecomment-448634688_

**Comment by rachel-fenichel** [comment]
Code pointer: https://github.com/LLK/scratch-blocks/blob/develop/core/block_dragger.js#L358

**Comment by epicfaace** [comment]
This seems to be the same issue as https://github.com/LLK/scratch-gui/issues/2755 and caused by a problem in scratch-gui, not scratch-blocks.

**Comment by kchadha** [comment]
@epicfaace, good catch! I had a feeling I had filed this before... 

Closing this issue and tracking in LLK/scratch-gui#2755.
