### ISSUE TITLE
Are we actually going to do anything about the issues with the blocks?

### ISSUE THREAD

**Issue by Alzter** [LLK/scratch-blocks#1846]
There's been numerous issues concerning the new block design for Scratch 3 on Github and Scratch alike, and yet nothing's been addressed.
Here's a few examples:

The block colours are too bright and not diverse.
[Scratch Forum](https://scratch.mit.edu/discuss/topic/199574/?page=158#post-2761039), LLK/scratch-gui#851, LLK/scratch-gui#3914, #1032, #995

The block text doesn't contrast with blocks and fails WebAIM contrast tests, and it's too thin.
#1492

There's also numerous complaints about 3.0's block thickness, too numerous to reference.

Are any of these being addressed? There's been a lot of disscussion about these issues but nothing much seems to have been really set in motion.

**Comment by thisandagain** [comment]
The short answer is yes. The issues in Github are not an exhaustive list of our roadmap.
