### ISSUE TITLE
Long strings of text bug

### ISSUE THREAD

**Issue by JoshuaLowe1002** [LLK/scratch-blocks#1847]
When a long string of text is entered, it goes over the stage and pushes scratch to the side.
I assume this is a bug?
![image](https://user-images.githubusercontent.com/25752941/50591235-6be3ab80-0e86-11e9-8d5d-a5f105b2f16b.png)

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/940

**Comment by thisandagain** [comment]
Please look for existing issues before filing new ones.
