### ISSUE TITLE
Dragging a block sometimes offsets the whole workspace

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1855]
I can't reproduce this very reliably, but I noticed that sometimes the whole workspace gets offset while you're dragging a block. I've only ever seen this on scratch.mit.edu. I noticed that whenever I open a project, I can almost always repro the whole workspace appearing to be positioned above the backpack, with the flyout extending all the way to the bottom of the entire browser window, i.e. above the backpack.

### Operating System and Browser

Firefox 65.0b7, Linux (Debian).

I think this is Firefox-specific, since I can't repro it on Chromium.

**Comment by BryceLTaylor** [comment]
@towerofnix can you describe what you mean by "offset?"  A screenshot or gif of the workspace would be helpful.  I can't reproduce, or if I am reproducing I'm not sure what you mean.

**Comment by towerofnix** [comment]
@BryceLTaylor I couldn't repro the "offset" behavior per se - it was likely an instance of overflow issue of and related to LLK/scratch-gui#953. Here's a repro video: https://streamable.com/1sqke. I've already made a PR - #1895 - which almost certainly resolves this (it resolves 953).
