### ISSUE TITLE
Editing a procedure should not scroll flyout

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1856]
### Expected Behavior

Editing a procedure spec (the labels/inputs) should never scroll the flyout, since editing a procedure is usually done to change how existing calls to the procedure look, not to create new calls.

### Actual Behavior

Editing a procedure spec does scroll the flyout to the "My Blocks" section.

### Steps to Reproduce

Right-click an existing custom procedure block and press Cancel or OK.

### Operating System and Browser

Firefox 65.0b7, Linux (Debian).

**Comment by kchadha** [comment]
Closing this issue as `won't fix` since it's a very low severity bug with a much higher-risk solution.
