### ISSUE TITLE
Colour slider show the wrong color

### ISSUE THREAD

**Issue by 0x-jerry** [LLK/scratch-blocks#1858]
### Expected Behavior

Show the correct color.

### Actual Behavior

Show the wrong color.

### Steps to Reproduce

The main step is to drag the brightness slider to 0.

![feature](https://user-images.githubusercontent.com/14226737/50809776-c8d8d900-1340-11e9-83d3-1a5f725da75e.gif)

### Operating System and Browser

Win 10 1809

Chrome Version 71.0.3578.98 (Official Build) (64-bit)

----

It seems because `goog.color.hsvToHex(hue, saturation, 0)` always return `#00000`.

So I try to return the hex from hsv

```js
/**
 * Return the current colour.
 * @return {string} Current colour in '#rrggbb' format.
 */
Blockly.FieldColourSlider.prototype.getValue = function() {
  if(this.hue_){
    return goog.color.hsvToHex(this.hue_, this.saturation_, this.brightness_);
  }
  else {
    return this.colour_;
  }
};
```

And it works.

I hope this will be helpful.

**Comment by BrightLin** [comment]
Tracking in [LLK/scratch-gui#3985](https://github.com/LLK/scratch-gui/issues/3985)
