### ISSUE TITLE
Some blocks are not translated

### ISSUE THREAD

**Issue by apple502j** [LLK/scratch-blocks#1886]
### Expected Behavior
All blocks should be translated for 100%-reviewed ones
### Actual Behavior
These blocks are not translated at first. After changing languages or dragging them into code area it's translated.

* next backdrop
* clear graphic effects
* change graphic effect by
* set graphic effect to
* backdrop number/name
* stop all sounds
* clear sound effects
* change sound effects by
* set sound effects to
* change volume by
* set volume to
* when gf clicked
* when key pressed
* when >
* wait seconds
* repeat
* forever
* if
* if else
* wait until
* repeat until
* ask and wait
* answer
* key pressed
* mouse down
* mouse x
* mouse y
* loudness
* timer
* reset timer
* current
* days since 2000
* username
* pick random
* and
* or
* not
* join
* letter of
* length (op)
* contains (op)
* mod
* round
* of (op)
* dropdown of graphic effect
* dropdown of backdrop number/name (costume is OK)
* dropdown of sound effect
* dropdown of keys (event and sensing)
* dropdown of loudness and timer
* dropdown of year/month/day/...
* dropdown of math (abs/sqrt/...)
 
Confirmed in Japanese and Chinese (traditional)
### Steps to Reproduce
go to https://llk.github.io/scratch-gui/develop/?locale=ja

### Operating System and Browser
Windows 7/Firefox 65

sky_77 reported it [at the forums](https://scratch.mit.edu/discuss/post/3422710/)
My browser / operating system: Windows NT 10.0, Chrome 71.0.3578.98, No Flash version detected

**Comment by thisandagain** [comment]
@chrisgarrity Do you mind chiming in here?

**Comment by chrisgarrity** [comment]
@apple502j we noticed that regression this morning. A fix for the bug should be getting deployed very soon (https://github.com/LLK/scratch-gui/pull/4478)
