### ISSUE TITLE
'To JavaScript' button doesn't work

### ISSUE THREAD

**Issue by pmatheusvinhas** [LLK/scratch-blocks#1893]
### Expected Behavior

Output JavaScript code when press 'To JavaScript' on tests/vertical_playground.html

### Actual Behavior

Nothing happens. 
Also tried to follow 'https://developers.google.com/blockly/guides/configure/web/code-generators' using 'javascript_compressed.js' with no success.

### Steps to Reproduce

Just open tests/vertical_playground.html.

### Operating System and Browser

Windows 10, Firefox 65.0

 p.s: No problems with closure-library.

**Comment by thisandagain** [comment]
Thanks for raising this. Because generators were removed from `scratch-blocks` this button should also be removed. I'll mark this as "help wanted" to remove the button from the playground.

**Comment by pmatheusvinhas** [comment]
> Thanks for raising this. Because generators were removed from `scratch-blocks` this button should also be removed. I'll mark this as "help wanted" to remove the button from the playground.

Understand. But can you help me to use a 'generator' on `scratch-blocks`? I'm doing an interface with `scratch-blocks` to control a hardware project. I need this output code to interpret it on MCU.
