### ISSUE TITLE
LEGO Mindstorms NXT support

### ISSUE THREAD

**Issue by TheOneWithTheBraid** [LLK/scratch-blocks#1897]
Lego Mindstroms EV3 Robots are supported by Scratch 3 while the bit older version called NXTs are not supported. Even if NXTs are older, they still make a big part of the market share.
I hope you'll add support soon.

### Steps to Reproduce

Connect an NXT and see that nothing is happening :)

### Operating System and Browser
Not important & still less important.

**Comment by thisandagain** [comment]
Thanks for the suggestion. We are currently not considering support for older LEGO Mindstorms models at this time. In the future we may be open to community supported "unofficial" support for situations like this.
