### ISSUE TITLE
Renaming a custom procedure input should change every use of that input inside the script

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1899]
### Expected Behavior

When you rename an input in a custom procedure, all uses of the old name are automatically changed to match the new name.

### Actual Behavior

They aren't updated! You have to manually drag out the new name for every usage of it in the custom procedure's script.

### Steps to Reproduce

Create a custom procedure with an input and attach a block to its "define" block, then place that input inside the block (e.g. "define jump (amount): change y by (amount)"). Then edit the custom procedure and change the name of the input.

### Operating System and Browser

Linux (Debian), Firefox 66.0b7.

---

Reported by a Scratcher on the forums: https://scratch.mit.edu/discuss/topic/340720/

**Comment by paulkaplan** [comment]
@rachel-fenichel I am trying to remember if there was a reason we didn't want to implement this or if it was just a scoping thing. Do you happen to remember whether we discussed changing the argument_reporter_... blocks in the definition stack after their names are changed?

**Comment by rachel-fenichel** [comment]
I don't remember any discussion of it, and I can't think of any major blockers for doing this.
