### ISSUE TITLE
How to use scratch with vue.js?Is there a example?

### ISSUE THREAD

**Issue by 651778286** [LLK/scratch-blocks#1903]
How to use scratch with vue.js?
Is there a example?
Thank you for the first

**Comment by thisandagain** [comment]
Sorry but we do not have an example for how to use Scratch-Blocks with vue.js. If you come up with an example we'd appreciate if you share it!

**Comment by MGsniper** [comment]
Buddy,have you got any example? I am stuck too T-T

**Comment by 651778286** [comment]
> Buddy,have you got any example? I am stuck too T-T

I've replaced scratch with Blockly，like this:

`import Vue from 'vue'`
`import Blockly from "node-blockly/browser"`
`Vue.prototype.$Blockly = Blockly`

[https://www.npmjs.com/package/node-blockly](url)

I wish can help you

**Comment by MGsniper** [comment]
> > Buddy,have you got any example? I am stuck too T-T
> 
> I've replaced scratch with Blockly，like this:
> 
> `import Vue from 'vue'`
> `import Blockly from "node-blockly/browser"`
> `Vue.prototype.$Blockly = Blockly`
> 
> [https://www.npmjs.com/package/node-blockly](url)
> 
> I wish can help you

------
Thanks,buddy. I make it with node-blockly too,I inserted the javascript interpreter API of blockly into scratch-blocks.So I can use both the core of blockly and the UI of scratch-blocks

**Comment by devin-wang-ni** [comment]
> > > Buddy,have you got any example? I am stuck too T-T
> > 
> > 
> > I've replaced scratch with Blockly，like this:
> > `import Vue from 'vue'`
> > `import Blockly from "node-blockly/browser"`
> > `Vue.prototype.$Blockly = Blockly`
> > [https://www.npmjs.com/package/node-blockly](url)
> > I wish can help you
> 
> Thanks,buddy. I make it with node-blockly too,I inserted the javascript interpreter API of blockly into scratch-blocks.So I can use both the core of blockly and the UI of scratch-blocks

Hi buddy, can you tell me how to set up?

**Comment by MGsniper** [comment]
https://gitee.com/MGsniper/vue_phaser_blockly_init_maze/commit/00ad308c81bd1ba1e23b7e9a269eddd0b0fce19b
Here we go, This is the demo. 🙌
