### ISSUE TITLE
Blocks are not dragged from flyout at accurate position

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#1915]
### Expected Behavior

Dragging a block should always attach it to the mouse according to the position where it was grabbed.

### Actual Behavior

This doesn't happen accurately when the block is dragged from the flyout.

### Steps to Reproduce

Drag a block from the flyout, from various different positions. Note it always starts moving from the same position (slightly to the left of where the block is in the flyout).

### Operating System and Browser

Firefox 67.0b2.

**Comment by NeilFraser** [comment]
Yes, this is absolutely the same issue as #1943.

**Comment by towerofnix** [comment]
@NeilFraser So would making an equivalent commit to google/blockly#2485 resolve it here too?

(Edit - or a pull from blockly master if that's the normal procedure; I don't know much about the way scratch-blocks and blockly's code bases tie together :woman_shrugging: :P)

**Comment by NeilFraser** [comment]
@towerofnix Yes, port that over and you should be good to go.

**Comment by towerofnix** [comment]
'Kay, I'll try that out!
