### ISSUE TITLE
Scratchlink support issues

### ISSUE THREAD

**Issue by TelloSDK** [LLK/scratch-blocks#1916]
Hi Sir：

Tello is a mini-drone designed for young children to learn to fly and code to create with Scratch and Python. It has many cool features including and a 720p camera, Intel Processor and DJI flight tech. We really want this drone can support Scratch 3.0, but it turned out to be that the Scratchlink only support Bluetooth transmission protocols. Tello drone uses wifi module. Can we find another way to support Scratch 3.0？Thanks!

Best Regards
Tello Develop Team

**Comment by wwj718** [comment]
@TelloSDK  https://codelab-adapter-docs.codelab.club/

codelab-adapter have already supported 3 types of drones（[parrot](http://www.parrot.com/)：wifi and Bluetooth)

**Comment by thisandagain** [comment]
@TelloSDK Thanks for your question. We are still exploring other protocol options for [scratch-link](https://github.com/LLK/scratch-link) including wifi. While we still do not have support for 3rd party extensions in Scratch 3.0, this is something we are still interested in supporting in the future.
