### ISSUE TITLE
Duplication triggers block if duplicated block is attached to stack

### ISSUE THREAD

**Issue by ErikMejerHansen** [LLK/scratch-blocks#1935]
### Expected Behavior

Attaching a duplicated block to a stack should not trigger it. 

### Actual Behavior
If you duplicate a block and attach it to a stack the block triggers. 
![duplicate_triggers](https://user-images.githubusercontent.com/620837/56960859-77a05f80-6b52-11e9-89cf-d13674b9221a.gif)
_Describe what actually happens_

### Steps to Reproduce
Add block to canvas
Duplicate block and attach it to a stack. 

### Operating System and Browser

MacOS 10.14.1 (18B75), Version 73.0.3683.103 (Official Build) (64-bit)

**Comment by paulkaplan** [comment]
Tracked https://github.com/LLK/scratch-blocks/issues/1935
