### ISSUE TITLE
Value on horizontal inputs doesn't persist visually

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-blocks#1939]
### Expected Behavior

Blocks should keep their values
![2019-05-15 13 48 26](https://user-images.githubusercontent.com/15675877/57797396-5c1f8200-7718-11e9-95a4-946311ee2725.gif)

### Actual Behavior

When you change the value of a number input in a horizontal block (e.g. the loop block) it goes back to the original value when you unfocus it.
When you focus it again, it has the right value. So does the XML. 

See the attached screen grab.

**Comment by ssavas06** [comment]
Hello;
I have the same problem. Could you find a solution?

**Comment by cwillisf** [comment]
Hi @ssavas06! Sorry, `scratch-blocks` doesn't support horizontal blocks mode. We experimented with it, but never finished it.

**Comment by ssavas06** [comment]
> Hi @ssavas06! Sorry, `scratch-blocks` doesn't support horizontal blocks mode. We experimented with it, but never finished it.

https://github.com/LLK/scratch-blocks/issues/1329#issuecomment-475544268
It works for me.
