### ISSUE TITLE
How to add Costumes, Sounds, Sprites, Result...?

### ISSUE THREAD

**Issue by Tsepu** [LLK/scratch-blocks#1941]
I see blocks. 
![image](https://user-images.githubusercontent.com/9732969/58155660-44637300-7caf-11e9-9101-5ba41158eb90.png)

But i don't know how to add other things like Costumes, Sounds, Sprites, Result ect...
Please give me any advice?

**Comment by Tsepu** [comment]
I want to make a similar thing like Scratch 3.0

![image](https://user-images.githubusercontent.com/9732969/58155785-960bfd80-7caf-11e9-8bab-bcc94934c62a.png)

**Comment by towerofnix** [comment]
You will want to look into running or including [scratch-gui](https://github.com/LLK/scratch-gui/) in your project. scratch-gui is the program which connects scratch-blocks, scratch-vm, scratch-render, etc into the full Scratch 3.0 application.
