### ISSUE TITLE
Dragging from flyout is offset in Firefox 67

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#1943]
See https://github.com/google/blockly/issues/2482

Firefox 67 was released yesterday and we got a very fast bug report on this.

This is a blockly bug, but was only exposed because of a change in how Firefox's style property is formatted.  We cherry-picked the fix (https://github.com/google/blockly/pull/2485) into master.

**Comment by towerofnix** [comment]
Potentially the same issue as #1915, especially since I can't repro on Chromium and that issue was reported just about when version 67 was released on the aurora FF update channel (what I use).

**Comment by rachel-fenichel** [comment]
Yeah, that seems likely.

(I just closed and reopened that one by accident--sorry about that.)
