### ISSUE TITLE
npm install err in windows10

### ISSUE THREAD

**Issue by NeOEBoy** [LLK/scratch-blocks#1945]
### Expected Behavior
npm install success

_Please describe what should happen_

### Actual Behavior
show 命令行太长（the window cmd param is too long）at ps1。

_Describe what actually happens_

### Steps to Reproduce
1, git scratch-blocks develop
2, cd scratch-blocks
3,npm install

i already modify build.py file about subprocess.Popen（... shell=True）

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

windows10

**Comment by NeOEBoy** [comment]
i already fix it，
1，i write a closure-compiler-4py.js for build.py subprocess.Popen to call（node closure-compiler-4py.js）and transfer the args use stdin to node js。
2，in closure-compiler-4py.js use google-closure-compiler java version to compile。

this is workround to fix cmd line too long problem，because the cmd is just 'node closure-compiler-4py.js' not the whole google-closure-compiler cmd。holp to help you。

**Comment by stulwd** [comment]
Could you explain how to fix the '命令行太长' bug clealy or give some specific steps? thank you. i 've been blocked by it for a long time.

**Comment by coreywei** [comment]
@NeOEBoy Could you please share the closure-compiler-4py.js file?

**Comment by NeOEBoy** [comment]
> 
> 
> @NeOEBoy Could you please share the closure-compiler-4py.js file?

[ref.zip](https://github.com/LLK/scratch-blocks/files/3665063/ref.zip)

you can unzip this file, it contain build.py(my modify version) and closure-compiler-4py.js
