### ISSUE TITLE
IOS: Number dropdown not showing on lt, gt, and equals operator blocks

### ISSUE THREAD

**Issue by flemcito** [LLK/scratch-blocks#1972]
### Expected Behavior

On iOS (and touch devices in general), the number dropdown should appear when input is focused on the gt, lt, and equals operator blocks - as shown in screenshot.

![Screenshot 2019-07-30 at 09 34 53](https://user-images.githubusercontent.com/909794/62110188-2bc69900-b2ae-11e9-9b6a-fdfebbf59133.png)

### Actual Behavior

The native keyboard is triggered, as for normal text input
![Screenshot 2019-07-30 at 09 35 14](https://user-images.githubusercontent.com/909794/62110419-a55e8700-b2ae-11e9-8c37-844ac405e598.png)

### Steps to Reproduce

Run the solution on iOS and click the input fields on the gt, lt, and equals operator blocks in the toolbox. 

### Operating System and Browser

iOS 12.4, iPad Air 2

**Comment by aeons** [comment]
These blocks can also operate on text input.

**Comment by flemcito** [comment]
Ah ok, I wasn't aware of that. Non-issue then - closing
Thanks
