### ISSUE TITLE
Focus state of blocks is unexpected, causes unintentional deletes

### ISSUE THREAD

**Issue by benjiwheeler** [LLK/scratch-blocks#1993]
### Expected Behavior

I'm moving blocks around, sometimes clicking in or near their text fields, sometimes hitting delete. I expect my blocks to keep being there.

### Actual Behavior

Sometimes my blocks disappear! What happened? If and only if I'm an experienced user, I may realize that hitting the delete key while the block is focused deletes the block.

### Steps to Reproduce

* drag out a block
* hit delete

or,
* click right next to a block's text input/reporter field, barely missing it
* hit delete

### Operating System and Browser

Mac OS/Chrome

**Comment by rachel-fenichel** [comment]
This is working as intended: clicking on a block focuses it, and hitting delete when a block is focused deletes it.
