### ISSUE TITLE
horizontal_playground.html won't run via wiki instructions

### ISSUE THREAD

**Issue by boneskull** [LLK/scratch-blocks#1999]
### Expected Behavior

`horizontal_playground.html` does not throw an exception--preventing blocks from being displayed--when using instructions in wiki

### Actual Behavior

Screenshot:

![image](https://user-images.githubusercontent.com/924465/65820630-62eaf500-e1e0-11e9-8d1e-cb03209ba0b6.png)

Viewing the console, we see:

```
Uncaught DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    at start (file:///Users/boneskull/projects/LLK/scratch-blocks/tests/horizontal_playground.html:25:9)
    at onload (file:///Users/boneskull/projects/LLK/scratch-blocks/tests/horizontal_playground.html:349:26)
```

Looks like a security feature.

### Steps to Reproduce

1. `git clone` this repo
1. run `npm install`
1. Open `tests/horizontal_playground.html` in chromium-based browser

### Operating System and Browser

- Vivaldi 2.8.1664.40 (Stable channel) (64-bit)
- macOS Version 10.14.6 (Build 18G95)

### Suggested Fix

To avoid the exception, wiki instructions should be updated to instruct users to open `tests/horizontal_playground.html` via a (temporary) web server.  For example, from the project root, running

```shell
$ python -mSimpleHTTPServer
```

allows navigation to `http://localhost:8000/tests/horizontal_playground.html`, which loads without the above exception.

> Note that `SimpleHTTPServer` _cannot_ be run from the `tests` subdirectory, as the `.html` files in here reference files _outside of_ this directory.

Another option would be to add something like [serve](https://www.npmjs.com/package/serve) as a development dependency and use this instead of `SimpleHTTPServer`.

**Comment by Androz2091** [comment]
Yes, you're right. It only works when I use a server.
