### ISSUE TITLE
variable can't be selected after the flyout closes then shows

### ISSUE THREAD

**Issue by cake2000** [LLK/scratch-blocks#2002]
### Expected Behavior

When I set flyout to be autoclose, and then click the category icon to bring out the flyout, I should be able to click the checkbox next to any variable to display its value in the stage.

### Actual Behavior

Currently after the flyout pops out, I can't check any of then checkboxes. 

### Steps to Reproduce

1. Set flyout's autoclose to true.
2. load any project
3. drag any block off the flyout so that the flyout would collapse.
4. click any category icon to bring out the flyout.
5. try to click the checkbox next to any variable.

### Operating System and Browser

Windows 10, Ubuntu
Chrome

![image](https://user-images.githubusercontent.com/2862836/66428790-b7625180-e9e4-11e9-9e25-70454aeb6f78.png)

**Comment by kchadha** [comment]
Auto closing a flyout is not supported in Scratch.
