### ISSUE TITLE
How to use only blocks, not vm, etc. We want to render our own interface, manage rendering by ourselves, how to translate the built block into code, I hope to get help.

### ISSUE THREAD

**Issue by King-hb** [LLK/scratch-blocks#2004]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_
How to use only blocks, not vm, etc. We want to render our own interface, manage rendering by ourselves, how to translate the built block into code, I hope to get help.

**Comment by apple502j** [comment]
scratch-blocks does not have "block to js (or other code)" feature, if that's what you mean.

**Comment by rachel-fenichel** [comment]
Blockly (github.com/google/blockly) does blocks to code without a VM, and is what scratch-blocks is forked from.

**Comment by King-hb** [comment]
> Blockly（github.com/google/blockly）在没有VM的情况下执行代码块，这是从头开始的。

Google's block is not elegant enough, scratch-block is very nice, we share your style, but we need to render our own defined interface, is there any way to read the valid code block in the workspace, is the problem I encountered, thanks your response

**Comment by King-hb** [comment]
> 如果这就是您的意思，那么便笺本没有“阻止js（或其他代码）”功能。

![image](https://user-images.githubusercontent.com/14026774/66532467-14bfe500-eb42-11e9-87a0-7762a6fcc6a1.png)

**Comment by King-hb** [comment]
> > 如果这就是您的意思，那么便笺本没有“阻止js（或其他代码）”功能。
> 
> ![图片](https://user-images.githubusercontent.com/14026774/66532467-14bfe500-eb42-11e9-87a0-7762a6fcc6a1.png)

How to read the workspace code block and bind custom events to make people move？

**Comment by apple502j** [comment]
@rachel-fenichel They took the feature away when forking
@King-whb That's where you use VM! See VM's /blocks/

**Comment by King-whb** [comment]
> @ rachel-fenichel他们在分叉
> @ King-whb时取消了该功能，这就是您使用VM的地方！参见虚拟机的/ blocks /

![image](https://user-images.githubusercontent.com/14026774/66559052-48712e00-eb87-11e9-9832-3e02a7443b66.png)
