### ISSUE TITLE
Support returns in custom blocks

### ISSUE THREAD

**Issue by filips123** [LLK/scratch-blocks#2008]
### Problem

Custom user-defined blocks can only be normal-style block without any return statements.

Although they can be simulated with setting a variable and reading it outside the block, this isn't a good solution. It also doesn't support boolean values. Also, most (all) programming languages have return statement and given that Scratch is made to teach children programming, it should have return statements so children will get a better understanding of what return statement and function actually is.

### Solution

There should be support for custom user-defined blocks with the return statement.

There should be support for both rounded/value blocks, which can be directly used as variables, and hexagon/boolean blocks, which can be directly used as if (or other condition) inputs.

That blocks should be able to return a value using some return statement block.

**Comment by rschamp** [comment]
Tracking in https://github.com/LLK/scratch-vm/issues/79
