### ISSUE TITLE
isTargetInput() in utils.js e.target do not have type attribute

### ISSUE THREAD

**Issue by errenxing** [LLK/scratch-blocks#2021]
### Expected Behavior
isTargetInput() is valid
_Please describe what should happen_

### Actual Behavior
isTargetInput() is invalid
_Describe what actually happens_
e.target.type is invalid ,because e.target do not have type attribute, it hase tagName attribute
and e.target.isContentEditable ia also invalid , because svg dom do not have isContentEditable attribute.
### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by BryceLTaylor** [comment]
There is not enough information to track this as a bug.  If any errors arise, you could add them with some repro steps and reopen this issue.
