### ISSUE TITLE
how to load a js file?

### ISSUE THREAD

**Issue by JackieChan1994** [LLK/scratch-blocks#2027]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
Can you send more info?

**Comment by JackieChan1994** [comment]
> Can you send more info?

here are 2 file I want to import to scratch-gui
```
<link rel="stylesheet" href="https://g.alicdn.com/de/prismplayer/2.8.2/skins/default/aliplayer-min.css" />
<script charset="utf-8" type="text/javascript" src="https://g.alicdn.com/de/prismplayer/2.8.2/aliplayer-min.js"></script>
```
please tell me what to do

**Comment by apple502j** [comment]
Maybe you can put them at scratch-gui's jsx file.
