### ISSUE TITLE
only change toolbox attribute, then updateToolbox not work

### ISSUE THREAD

**Issue by starhu521** [LLK/scratch-blocks#2028]
### Expected Behavior

I think updateToolbox should work when I change the attribute of block.

### Actual Behavior

Not work at all.

### Steps to Reproduce

Initialize toolbox and set attribute disabled false of  blocks, and then update the same toolbox with updateToolbox method, just set the disabled attribute of blocks true.

### Operating System and Browser

mac

### my mind

I think it was your recycled logic goes wrong.

**Comment by BryceLTaylor** [comment]
@starhu521 can you describe what you mean by "work"?  Is this an issue with code you are writing or with the current implementation of scratch-blocks?

**Comment by starhu521** [comment]
> @starhu521 can you describe what you mean by "work"? Is this an issue with code you are writing or with the current implementation of scratch-blocks?

just sample like this:
init toolbox:
```
Blockly.Blocks.defaultToolbox = '<xml id="toolbox-categories" style="display: none">' +
  '<category name="%{BKY_CATEGORY_MOTION}" id="motion" colour="#4C97FF" secondaryColour="#3373CC">' +
    '<block  **disabled="true"** type="motion_movesteps" id="motion_movesteps">' +
      '<value name="STEPS">' +
        '<shadow type="math_number">' +
          '<field name="NUM">10</field>' +
        '</shadow>' +
      '</value>' +
      '<field name="remark"></field>' +
    '</block>' +
'</category>' +
'</xml>';
```

then updateToolbox with method :

```
workspace.updateToolbox('<xml id="toolbox-categories" style="display: none">' +
  '<category name="%{BKY_CATEGORY_MOTION}" id="motion" colour="#4C97FF" secondaryColour="#3373CC">' +
    '<block type="motion_movesteps" id="motion_movesteps">' +
      '<value name="STEPS">' +
        '<shadow type="math_number">' +
          '<field name="NUM">10</field>' +
        '</shadow>' +
      '</value>' +
      '<field name="remark"></field>' +
    '</block>' +
'</category>' +
'</xml>')
```

the block 'motion_movesteps' is always disabled.
