### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by sfederici** [LLK/scratch-blocks#2029]
Several string are not translated in the blocks yet:
- 'backdrop1' - in 'switch to backdrop' block and 'when backdrop switches to' block
- 'meow' - in 'play sound' block (BUT maybe you don't want to translate it?)
- 'my variable' standard variable name

**Comment by apple502j** [comment]
In Japanese locale it's all translated; it's just your language. (Maybe not reviewed?)

**Comment by sfederici** [comment]
I'm the reviewer of the Italian language. The "interface" section of the "Scratch Editor" project is fully translated and reviewed. For example, all "backdrop" strings are correctly translated to "sfondo", "Meow" is translated to "Miao" and "my variable" is translated to "la mia variabile".

**Comment by apple502j** [comment]
On latest version, it was translated. The next release should contain the translation.

**Comment by benjiwheeler** [comment]
It's interesting that the three examples you mentioned that are not translated are all default names of assets (backdrop, sound, etc.).

Maybe there's something that works differently about those?

When I go to the Scratch main page, switch the language to Italiano, create a project, and go to the Variabiles section, I do see "la mia variabile" now. Do you see that? Is the problem solved, or are you talking about something else?

**Comment by apple502j** [comment]
Also, note that if you change the language AFTER you make the project, the name won't change.

**Comment by chrisgarrity** [comment]
As @benjiwheeler said assets are treated differently. Once a project has been created the names of assets do not change unless they are changed by the user, and the names in the block menus are just generated from the current asset names.

When generating the default project, there is a process to change the default asset names if the language is set to something other than English. So the names are correct if your language is set to Italian before creating the project. If you create a project in English, and then switch to another language the asset names will not change. 

I believe this is working correctly, so I'm going to close this issue. All the special handling for assets is in scratch-gui, so if there is still a problem, please reopen in that repository.
