### ISSUE TITLE
Tooltip for field shadow blocks is unhelpful

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#203]
![bad tooltip](https://cloud.githubusercontent.com/assets/632207/14462395/297f9288-00c7-11e6-93de-d12203916e3f.png)

This tooltip only appears when mousing over the background, moving over the text shows nothing.

I'd expect to to see either the tooltip for the parent block (control_repeat). It could be resolved by overwriting the tooltip on field shadow blocks to be the same as the tooltip of the parent block, similar to how field_label.js is "transparent with respect to tooltips". Possibly worth giving the FieldTextInput's <text> element the same tooltip too.

This is not hurting me as I'm not using tooltips, but I thought it was worth recording.

**Comment by picklesrus** [comment]
I think this is obsolete. I don't see tooltips on the blocks in scratch and it is fixed upstream, at least on the lop block.
