### ISSUE TITLE
Can scratch-blocks do the mutator?

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-blocks#2030]
scratch-blocks mutator draw the block by horizontal. But I need the block will draw by vertical. How can I do?

default:
![image](https://user-images.githubusercontent.com/15828392/72198948-f387d100-346f-11ea-8146-46fe2ebe39bc.png)

expect:
![mutator](https://user-images.githubusercontent.com/15828392/72198938-deab3d80-346f-11ea-9f92-00c124901634.png)

I modify the code like the follow picture show, but it's not good for me.
![image](https://user-images.githubusercontent.com/15828392/72198987-58432b80-3470-11ea-9db7-abe78d93d1f7.png)

**Comment by BrightLin** [comment]
May be duplicate with #2019

**Comment by BrightLin** [comment]
I found a good way to implementation the requirement

Here is the way:

Modify function at 'core/block_render_svg_vertical.js'. 

- Add "input.name == 'block.mutator.br'" at the "row = this.createRowForInput_(input);" if-else conditions.

```
Blockly.BlockSvg.prototype.renderCompute_ = function(iconWidth) {
    //... some code...

    // Don't create a new row for the second dummy input on a procedure block.
    // See github.com/LLK/scratch-blocks/issues/1658
    // In all other cases, statement and value inputs catch all preceding dummy
    // inputs, and cause a line break before following inputs.

    if (!isSecondInputOnProcedure &&
        (!lastType || lastType == Blockly.NEXT_STATEMENT ||
        input.type == Blockly.NEXT_STATEMENT) || input.name == 'block.mutator.br') {
      lastType = input.type;
      row = this.createRowForInput_(input);
      inputRows.push(row);
    } else {
      row = inputRows[inputRows.length - 1];
    }
    row.push(input);
```

So do appendDummyInput(‘block.mutator.br’) when define a block，the block will render by multi-rows

Effect：
![image](https://user-images.githubusercontent.com/15828392/72200074-bd524d80-347f-11ea-910b-6041583564dd.png)

**Comment by sansong089** [comment]
兄弟，你的图都挂了啊！

**Comment by sansong089** [comment]
多谢！这个方法确实可以，但是有两个小瑕疵：1、从第二行起，每行右上角有个小圆弧、2：折行的积木连接其他积木时，中间有缝隙。

**Comment by BrightLin** [comment]
@sansong089 圆角和缝隙问题，也可以解决的，熟悉积木块的绘制流程，可以通过下面方式修改：
![image](https://user-images.githubusercontent.com/15828392/76281784-13513f00-62d1-11ea-8185-ca3b476f80b3.png)

原因是积木块绘制时，计算的高度，是通过相对位移的。圆角也需要判断是首行还是非首行

**Comment by BrightLin** [comment]
Found some way to solves it. Close this issue.

**Comment by sansong089** [comment]
"积木块的绘制流程" 这个有文档之类的东西吗?还是只能看代码？

**Comment by mumajxt** [comment]
你好，你的换行实现很赞。不过有第二行的宽度无法撑开整体的宽度，另外修改绘制流程后会导致正常的换行积木高度出错，请问你有更完善的解决方法吗，感谢！
![image](https://user-images.githubusercontent.com/49017220/181691604-56e236f7-33ae-455d-96f5-d02763f3ca15.png)
![image](https://user-images.githubusercontent.com/49017220/181691700-c5511fce-54d9-4f80-b578-f16a4f1ae03a.png)

**Comment by cikichen** [comment]
following
