### ISSUE TITLE
Delete procedure and undo, toolbox didn't refresh

### ISSUE THREAD

**Issue by BrightLin** [LLK/scratch-blocks#2032]
### Expected Behavior

Delete procedure block, and then undo. The toolbox need refresh.

### Actual Behavior

Delete procedure and undo, toolbox didn't refresh

### Steps to Reproduce

1. Create a procedure block(My Blocks)
2. Drag the procedures_definition block to workspace
3. Delete procedures_definition block 
4. Undo.

See the follow gif :

![bugs](https://user-images.githubusercontent.com/15828392/72241704-7d779b80-3622-11ea-9791-50c8bfd35a96.gif)

### Operating System and Browser

Chrome 78.0.3904.108 x64 
Windows 10 x64

**Comment by BrightLin** [comment]
call workspace.toolbox_.refreshSelection() after block create，will refresh toolbox and restore the custom block (procedure block)

**Comment by towerofnix** [comment]
I think this is already being tracked in: #1982

**Comment by benjiwheeler** [comment]
Thanks for filling, @BrightLin , and thanks for pointing out the existing issue, @towerofnix !
