### ISSUE TITLE
stop other scripts ... does not change target when the stage is selected

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratch-blocks#2056]
The option `other scripts in sprite` in the stop block does not switch to `other scripts in stage` when the stage is selected. 

This has been known for a long time, but I didn't see an issue recording it, and it came up again with a translator.

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-gui#3543

**Comment by Kenny2github** [comment]
Is this an issue with gui or blocks though?

**Comment by BryceLTaylor** [comment]
I moved LLK/scratch-gui#3543 into Blocks and I'm going to close this one.
