### ISSUE TITLE
Using the ([x position v] of [Sprite v]) block rearranges code

### ISSUE THREAD

**Issue by Explosion-Scratch** [LLK/scratch-blocks#2081]
### Actual Behavior
When using the mentioned block it will be automatically be set to  backdrop # of backdrop. Selecting a different Sprite makes all the code go to the top left after switching sprites.

### Expected Behavior

Block works normally

### Steps to Reproduce
1: Go to the sensing category in a Sprite with code and find the ([ v] of [ v]) block.
2: It should be set to backdrop #
3: Select a different Sprite in the drop-down without changing the "backdrop #" part.
4: Switch to a different Sprite
5: Switch back. Your code should be reorganized.

### Operating System and Browser

All.

**Comment by apple502j** [comment]
Duplicate of LLK/scratch-gui#4400

**Comment by Explosion-Scratch** [comment]
@Apple502j, okay! Thanks! I'll close this then!
