### ISSUE TITLE
variables -my variable block label cannot change when change language

### ISSUE THREAD

**Issue by jsyzthz** [LLK/scratch-blocks#2098]
### Expected Behavior

block "my variable" should be translate to japanese

### Actual Behavior

still english word "my variable"

### Steps to Reproduce

1. Open https://scratch.mit.edu/ under Chrome,
2. Default language is English. check the Variables-my variable label,
3. Change language to Janpanese, check the previous block's label (still using English) again.

ps but if you refresh the browser then everthing is fine.

### Operating System and Browser

Window 10/Chorme 84.0.4147.105

**Comment by apple502j** [comment]
I think this is working as intended. Once the project is generated, changing the language should not change the project.

**Comment by BryceLTaylor** [comment]
This is by design.
