### ISSUE TITLE
Design - Toolbox

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#21]
We need to design the overall GUI for our initial prototypes with special emphasis on the palette (toolbox) / workspace paradigm. Discussion with the team has suggested that we should quickly explore and prototype a range of options. This is due to the fact that no one solution really seems to be perfect just yet.

#### Benchmarks / Reference
- Scratch
- Scratch Jr
- Blockly
- Blockly Games
- Tickle
- OzoBlockly
- Dash & Dot

**Comment by thisandagain** [comment]
Moving to September milestone.

**Comment by carljbowman** [comment]
@rachel-fenichel - Here is a doc ( [R1_Palette Properties.pdf](https://github.com/LLK/scratch-blocks/files/433120/R1_Palette.Properties.pdf) ) that overviews some examples and concepts based on the properties that we speced. Let me know if you have any addtional questions. I will begin working on a UI spec. 

![r1_desktop-prototype](https://cloud.githubusercontent.com/assets/3409578/17901900/1abcb562-6933-11e6-8b80-e0f75cab03c0.png)

![r1_tablet-prototype](https://cloud.githubusercontent.com/assets/3409578/17902035/a4056be8-6933-11e6-849a-3b84d16de40e.png)

![r1_mobile-concept](https://cloud.githubusercontent.com/assets/3409578/17902038/a8045c4a-6933-11e6-9360-f608a4b3b5d2.png)

![r1_tablet-concept](https://cloud.githubusercontent.com/assets/3409578/17902042/aa17cf4e-6933-11e6-9f5b-635aa56ed2d8.png)

![r1_tablet-concept-rtl](https://cloud.githubusercontent.com/assets/3409578/17902046/ac8c8c2e-6933-11e6-90dd-c2f2e5e0e6dc.png)

**Comment by tmickel** [comment]
The major implementation of this has landed, will be creating sub-issues in the future!
