### ISSUE TITLE
Deleting any block causes thousands of errors in the console (live on scratch.mit.edu!!) 

### ISSUE THREAD

**Issue by paulobarcelos** [LLK/scratch-blocks#2139]
**!!! This bug is currently live on https://scratch.mit.edu/projects/editor !!!**
(But also happening locally on my machine, on a project that uses `LLK/scratch-blocks`)

### Expected Behavior
Deleting a block by dragging it to the trashcan or back to the toolbox should not cause any errors in the console.

### Actual Behavior
If you try to delete any block, the error `Error: <g> attribute transform: Expected number, "translate(NaN,NaN) scale(N…".` will be printed repeatedly in the console.
<img width="610" alt="Screenshot 2020-10-02 at 14 55 29" src="https://user-images.githubusercontent.com/122277/94925334-536f4d80-04bf-11eb-8b99-b2a20a1b395b.png">

Also the deleted block seems to not be fully deleted, but just "placed below the toolbox", see image below.
<img width="645" alt="Screenshot 2020-10-02 at 14 54 46" src="https://user-images.githubusercontent.com/122277/94925283-40f51400-04bf-11eb-98f4-33ed0695bd11.png">

### Steps to Reproduce

Go to https://scratch.mit.edu/projects/editor/ drag a block into the workspace, then try to delete the block by dragging it back to the toolbox.

### Operating System and Browser

MacOS Catalina 10.15.6 - Chrome 85.0.4183.121

**Comment by apple502j** [comment]
Cannot repro on Windows 10, Chrome 85 or Firefox 81

**Comment by paulobarcelos** [comment]
On MacOS Catalina 10.15.6  it also wasn't reproducing on:
- Firefox 81.0.1 (64-bit)
- Safari 14.0 (15610.1.28.1.9, 15610)
- Chrome Canary 87.0.4280.0 (Official Build) canary (x86_64)

So I decided to simply restart my Chrome 85.0.4183.121 and now it works as expected!

I am puzzled here... no idea why the bug consistently happened (been reproducing it for hours). But there was defnetely something up with Chrome...

But anyway, will close this issue for now. 

Thanks for the report @apple502j

**Comment by BryceLTaylor** [comment]
I can't reproduce on Mojave or Catalina on Chrome 85.0.4183.83 or Chrome 85.0.4183.121.  I do see that "Trying to cancel a gesture recursively" message that you are seeing, though.

**Comment by BryceLTaylor** [comment]
Oh, I just saw you closed it.  Thanks, I'm glad it worked out.
