### ISSUE TITLE
dynamic inputs and type check (HELP)

### ISSUE THREAD

**Issue by starhu521** [LLK/scratch-blocks#2151]
### Expected Behavior

I need help to implement a feature. That's like this:

The block with uncertain arguments, it has a argument of field_dropdown. When I change the selection of the field_dropdown, I will change all of the rest arguments of the block, includes number and type check of arguments of the block.

Just like merge some blocks together to defined one That has a main argument what decides the rest arguments of the block. 

thanks a lot.

**Comment by apple502j** [comment]
You should not try to make such blocks. This will cause mess - and you'll regret if you do so.

If you really want to do that, check `sensing_of` block and this source code:
https://github.com/LLK/scratch-gui/blob/develop/src/lib/blocks.js

**Comment by starhu521** [comment]
> You should not try to make such blocks. This will cause mess - and you'll regret if you do so.
> 
> If you really want to do that, check `sensing_of` block and this source code:
> https://github.com/LLK/scratch-gui/blob/develop/src/lib/blocks.js

Thanks for your reply!
I have checked these codes about the block sensing_of. But I think it doesn't suit  my case well.  And I get a idea from this that I can listen the field and call init.  But if  it's complex depends and influence, or the value input connects a lot of blocks. It will be difficult to handle it. Maybe I need a better way.

**Comment by kchadha** [comment]
The use case you're describing is not something that's part of the design of scratch-blocks, so I'll be closing this issue.

I think you might be able to look at how the custom procedure code works (it dynamically creates a block shape based on how the custom procedure definition is shaped). https://github.com/LLK/scratch-blocks/blob/develop/blocks_vertical/procedures.js

That's probably as far as I can help. Good luck!
