### ISSUE TITLE
The shadow of separation when move the block

### ISSUE THREAD

**Issue by starhu521** [LLK/scratch-blocks#2164]
### Expected Behavior

Don't show the seperate shadow of block.

### Actual Behavior

![test](https://user-images.githubusercontent.com/23275495/97399839-eff30700-1928-11eb-99a3-e8329f3780ed.gif)

### Steps to Reproduce
Defined a block, almost like this:

`Blockly.Blocks['project'] = {
  init: function() {
    this.jsonInit({
      "message0": "%1 Project %2",
      "args0": [
        {
          "type": "field_label_serializable",
          "name": "remark",
          "text": ""
        },
        {
          "type": "input_dummy",
          "name": "subproject"
        }
      ],
      "category": "project",
      "extensions": ["colours_more", "shape_statement"]
    });
    this.getInput('subproject').appendField(new Blockly.FieldDropdown(function() {
      var options = [['select', 'select$select']];
      if (Blockly.CustomeGlobalData.subProjectList) {
        options = Blockly.CustomeGlobalData.subProjectList.map(function(item) {
          return [item.name, item.id + '$' + item.name];
        });
      }
      return options;
    }, function(option) {
      var projectName = option.split('$')[1];
      this.sourceBlock_.updateShape_(projectName);
      this.setValue(option);
      return null;
    }), 'subproject');
  },
  currentProject: {},
  mutationToDom: function() {
    var container = document.createElement('mutation');
    var project = this.getFieldValue('subproject');
    var projectName = project.split('$')[1];
    container.setAttribute('project', projectName);
    return container;
  },
  domToMutation: function(xmlElement) {
    var project = xmlElement.getAttribute('project');
    this.updateShape_(project);
  },
  updateShape_: function(projectName) {
    if (projectName === this.currentProject.name) {
      return;
    }
    var that = this;
    if (this.currentProject.varlist) {
      this.currentProject.varlist.forEach(function(item) {
        if (item.local) {
          return;
        }
        that.removeInput(item.varname);
      });
    }
    this.currentProject = {};
    if (Blockly.CustomeGlobalData.subProjectList) {
      var project = Blockly.CustomeGlobalData.subProjectList.find(function(item) {
        return projectName === item.name;
      });
      this.currentProject = project || {};
      if (project && project.varlist) {
        project.varlist.forEach(function(item) {
          if (item.local) {
            return;
          }
          switch (item.vartype) {
            case 'int':
              var inp = that.appendValueInputShadow(item.varname);
              inp.appendField(item.varname);
              var newb = that.workspace.newBlock('math_integer');
              newb.setShadow(true);
              newb.setFieldValue(item.vardefault, 'NUM');
              newb.initSvg();
              newb.render();
              inp.connection.connect(newb.outputConnection);
              inp.setCheck(['Integer', 'Number']);
              break;
            case 'float':
              var inp = that.appendValueInputShadow(item.varname);
              inp.appendField(item.varname);
              var newb = that.workspace.newBlock('math_number');
              newb.setShadow(true);
              newb.setFieldValue(item.vardefault, 'NUM');
              newb.initSvg();
              newb.render();
              inp.connection.connect(newb.outputConnection);
              inp.setCheck(['Integer', 'Number']);
              break;
            case 'string':
              var inp = that.appendValueInputShadow(item.varname);
              inp.appendField(item.varname);
              var newb = that.workspace.newBlock('text');
              newb.setShadow(true);
              newb.setFieldValue(item.vardefault, 'TEXT');
              newb.initSvg();
              newb.render();
              inp.connection.connect(newb.outputConnection);
              inp.setCheck(['String']);
              break;
            case 'boolean':
              var inp = that.appendValueInputShadow(item.varname);
              inp.appendField(item.varname);
              var newb = that.workspace.newBlock('test_boolean_menu');
              newb.setShadow(true);
              newb.setFieldValue(item.vardefault + '', 'VALUE');
              newb.initSvg();
              newb.render();
              inp.connection.connect(newb.outputConnection);
              inp.setCheck(['boolean']);
              break;
            case 'array':
              var inp = that.appendValueInputShadow(item.varname);
              inp.appendField(item.varname);
              var newb = that.workspace.newBlock('test_array');
              newb.setShadow(true);
              newb.initSvg();
              newb.render();
              inp.connection.connect(newb.outputConnection);
              inp.setCheck(['Array']);
              break;
            case 'object':
              var inp = that.appendValueInputShadow(item.varname);
              inp.appendField(item.varname);
              var newb = that.workspace.newBlock('test_object');
              newb.setShadow(true);
              newb.initSvg();
              newb.render();
              inp.connection.connect(newb.outputConnection);
              inp.setCheck(['Object']);
              break;
            default:
              break;
          }
        });
      }
    }
  }
};`

### Operating System and Browser

Mac OS Catalina 10.15.7
chrome 86.0.4240.111

Thanks!

**Comment by starhu521** [comment]
> ### Expected Behavior
> Don't show the seperate shadow of block.
> 
> ### Actual Behavior
> ![test](https://user-images.githubusercontent.com/23275495/97399839-eff30700-1928-11eb-99a3-e8329f3780ed.gif)
> 
> ### Steps to Reproduce
> Defined a block, almost like this:
> 
> `Blockly.Blocks['project'] = { init: function() { this.jsonInit({ "message0": "%1 Project %2", "args0": [ { "type": "field_label_serializable", "name": "remark", "text": "" }, { "type": "input_dummy", "name": "subproject" } ], "category": "project", "extensions": ["colours_more", "shape_statement"] }); this.getInput('subproject').appendField(new Blockly.FieldDropdown(function() { var options = [['select', 'select$select']]; if (Blockly.CustomeGlobalData.subProjectList) { options = Blockly.CustomeGlobalData.subProjectList.map(function(item) { return [item.name, item.id + '$' + item.name]; }); } return options; }, function(option) { var projectName = option.split('$')[1]; this.sourceBlock_.updateShape_(projectName); this.setValue(option); return null; }), 'subproject'); }, currentProject: {}, mutationToDom: function() { var container = document.createElement('mutation'); var project = this.getFieldValue('subproject'); var projectName = project.split('$')[1]; container.setAttribute('project', projectName); return container; }, domToMutation: function(xmlElement) { var project = xmlElement.getAttribute('project'); this.updateShape_(project); }, updateShape_: function(projectName) { if (projectName === this.currentProject.name) { return; } var that = this; if (this.currentProject.varlist) { this.currentProject.varlist.forEach(function(item) { if (item.local) { return; } that.removeInput(item.varname); }); } this.currentProject = {}; if (Blockly.CustomeGlobalData.subProjectList) { var project = Blockly.CustomeGlobalData.subProjectList.find(function(item) { return projectName === item.name; }); this.currentProject = project || {}; if (project && project.varlist) { project.varlist.forEach(function(item) { if (item.local) { return; } switch (item.vartype) { case 'int': var inp = that.appendValueInputShadow(item.varname); inp.appendField(item.varname); var newb = that.workspace.newBlock('math_integer'); newb.setShadow(true); newb.setFieldValue(item.vardefault, 'NUM'); newb.initSvg(); newb.render(); inp.connection.connect(newb.outputConnection); inp.setCheck(['Integer', 'Number']); break; case 'float': var inp = that.appendValueInputShadow(item.varname); inp.appendField(item.varname); var newb = that.workspace.newBlock('math_number'); newb.setShadow(true); newb.setFieldValue(item.vardefault, 'NUM'); newb.initSvg(); newb.render(); inp.connection.connect(newb.outputConnection); inp.setCheck(['Integer', 'Number']); break; case 'string': var inp = that.appendValueInputShadow(item.varname); inp.appendField(item.varname); var newb = that.workspace.newBlock('text'); newb.setShadow(true); newb.setFieldValue(item.vardefault, 'TEXT'); newb.initSvg(); newb.render(); inp.connection.connect(newb.outputConnection); inp.setCheck(['String']); break; case 'boolean': var inp = that.appendValueInputShadow(item.varname); inp.appendField(item.varname); var newb = that.workspace.newBlock('test_boolean_menu'); newb.setShadow(true); newb.setFieldValue(item.vardefault + '', 'VALUE'); newb.initSvg(); newb.render(); inp.connection.connect(newb.outputConnection); inp.setCheck(['boolean']); break; case 'array': var inp = that.appendValueInputShadow(item.varname); inp.appendField(item.varname); var newb = that.workspace.newBlock('test_array'); newb.setShadow(true); newb.initSvg(); newb.render(); inp.connection.connect(newb.outputConnection); inp.setCheck(['Array']); break; case 'object': var inp = that.appendValueInputShadow(item.varname); inp.appendField(item.varname); var newb = that.workspace.newBlock('test_object'); newb.setShadow(true); newb.initSvg(); newb.render(); inp.connection.connect(newb.outputConnection); inp.setCheck(['Object']); break; default: break; } }); } } } };`
> 
> ### Operating System and Browser
> Mac OS Catalina 10.15.7
> chrome 86.0.4240.111
> 
> Thanks!

I'm sorry for that the code format confusion.

**Comment by BryceLTaylor** [comment]
This is outside the scope of scratch-blocks
