### ISSUE TITLE
This is outside the scope of scratch-blocks

### ISSUE THREAD

**Issue by starhu521** [LLK/scratch-blocks#2168]
This is outside the scope of scratch-blocks

_Originally posted by @BryceLTaylor in https://github.com/LLK/scratch-blocks/issues/2164#issuecomment-719003012_

**Comment by starhu521** [comment]
Sorry, I don't know what you mean. So I can't defined blocks by myself in scratch-blocks??

**Comment by BryceLTaylor** [comment]
Please comment on the existing issue rather than creating a new issue.
