### ISSUE TITLE
Pants growing up

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#220]
Sometime we'd like to make it so our horizontal pants "grow up" instead of down - more consistent behavior.

Move a pants block into another empty pants block. The pants block should not stretch down but rather stretch up.

**Comment by tmickel** [comment]
@rachel-fenichel I vote we forget about and close this. It's feeling really good to me now. My only question is if this is related to #340, although I feel like we can fix that separately. any objections?

**Comment by rachel-fenichel** [comment]
Agreed.
