### ISSUE TITLE
npm install returning errors in scratch-blocks

### ISSUE THREAD

**Issue by MarkKocherovsky** [LLK/scratch-blocks#2293]
Expected Behavior

I am trying to run npm install while in the scratch-blocks folder as shown [here](https://github.com/LLK/scratch-gui/wiki/Getting-Started#example-scratch-gui-vm-and-blocks-linked%5D(https://github.com/LLK/scratch-gui/wiki/Getting-Started#example-scratch-gui-vm-and-blocks-linked)). I expect it to run the command without error.

Actual Behavior

The system returns the following error:

```
> scratch-blocks@0.1.0 prepublish
> python build.py && webpack

sh: 1: python: not found
npm ERR! code 127
npm ERR! path <Scratch Path>/scratch-blocks
npm ERR! command failed
npm ERR! command sh -c python build.py && webpack

npm ERR! A complete log of this run can be found in:
npm ERR!     <log path>
```

Steps to Reproduce

I'm not entirely sure, as I was going through the Getting Started Tutorial above.

Operating System and Browser

Windows 10, Ubuntu for Windows 20.04.1, NodeJS version 15.6.0, npm version 7.4.0

My python PATH is defined correctly; it goes to the Visual Studio 2017 build, as defined when using where python on a windows terminal.

**Comment by apple502j** [comment]
Do you have Python 2.7?

**Comment by MarkKocherovsky** [comment]
> Do you have Python 2.7?

I'm using Python 3.7

**Comment by apple502j** [comment]
You need Python 2.7.

**Comment by MarkKocherovsky** [comment]
> You need Python 2.7.

I've downloaded 2.7, put it in my PATH (C:/Python27), and ``npm install`` returns the same error.

**Comment by MarkKocherovsky** [comment]
> You need Python 2.7.

I have also tried ``npm install --python=python2.7``, and it returns the same error.

**Comment by MarkKocherovsky** [comment]
> You need Python 2.7.

I have my ``PYTHONPATH`` env variable in linux set to ``/mnt/c/Python27/:/mnt/c/Python27/DLLs:/usr/bin/python2.7``

The error is still the same.

**Comment by rduman** [comment]
If you use Linux distribution please run the below code in terminal

apt-get install -y nginx git python-setuptools python-dev

Then try again.

**Comment by MarkKocherovsky** [comment]
> If you use Linux distribution please run the below code in terminal
> 
> apt-get install -y nginx git python-setuptools python-dev
> 
> Then try again.

This works better, but it is now returning:

```
> scratch-blocks@0.1.0 prepublish
> python build.py && webpack

Could not find "java" in your PATH.
Using remote compiler: closure-compiler.appspot.com ...

Error: Closure not found.  Read this:
  developers.google.com/blockly/guides/modify/web/closure
npm ERR! code 1
npm ERR! path <Scratch Path>/scratch-blocks
npm ERR! command failed
npm ERR! command sh -c python build.py && webpack

npm ERR! A complete log of this run can be found in:
npm ERR!     <LOG PATH>
```

The guide given says to install the closure library, but it already exists under ``scratch-blocks\node_modules\google-closure-library``.

**Comment by MarkKocherovsky** [comment]
After installing java through ubuntu, it seems to have worked. Thanks to everyone for their help!
