### ISSUE TITLE
[question] Defining variables in the header?

### ISSUE THREAD

**Issue by L3g7** [LLK/scratch-blocks#2303]
### Expected Behavior

In the offical Scratch, when creating a block, its variables are defined in the header. (Idk if that makes sense, see [this vid](https://techgamez.de/sv1.mp4))
I'd like to do this in my own project.

### Actual Behavior

I can't find any way to do this, and the docs don't seem to be containing anything regarding that.
It'd be nice if someone could send me a link / tutorial or explain how to do this 😄

**Comment by towerofnix** [comment]
Whether or not a block is duplicated when dragged [is determined](https://github.com/LLK/scratch-blocks/blob/ce41bb947221e4905701f81ba1c615b134b4dd9a/core/gesture.js#L831-L832) by `isShadowArgumentReporter`, which is a utility function hard-coded to match (in addition to any shadow block) the block types `argument_reporter_boolean` and `argument_reporter_string_number`. You'd want to edit [those lines](https://github.com/LLK/scratch-blocks/blob/ce41bb947221e4905701f81ba1c615b134b4dd9a/core/scratch_blocks_utils.js#L100-L103) and make it match the block you're looking for too - probably by adding its own block type to the conditional there, if it's implemented as a distinct block type.

I haven't tried this myself, but you might also have luck doing `block.getParent()` and checking *its* `.type` property instead, if that's more relevant to your context!

**Comment by L3g7** [comment]
ok thanks, i'll try 👍
