### ISSUE TITLE
Can't access functions from other sprites

### ISSUE THREAD

**Issue by Budschie** [LLK/scratch-blocks#2313]
### Expected Behavior

_You should be able to drag a function block from one sprite to another. It should then appear, and if it is executed, it should invoke the right function in the other sprite from which it was from._

### Actual Behavior

_You can drag a function block from one sprite to another. It even appears there. But you can't invoke it. It will simply not call the function from the other sprite._

### Steps to Reproduce

_1. Create two sprites. Lets call them A and B.
2. Create an own block in A.
3. Drag the block from the section "My Blocks" at the left into B by draging it over B in the outliner at the right. It is important that you don't drag the definition from A into B, as this would copy the function, leading into code duplication, which is massively bad.
4. The function now appears in B.
5. Define some behaviour in A for that function that you can identify by eye (e. g. say Hello for 1 second) and call that very function in A. You should see "Hello" now.
6. After "Hello" disappears, call the same function with the "imported" block in B.
7. Observe that nothing happens._

### (Bad) workaround
A workaround would be to copy the function, but code duplication should be avoided at almost all costs, as you cannot easily change things. As a Java Dev, I am deeply dissapointed of Scratch, as you shouldn't enforce such behaviour like code duplication, especially if your software is about teching people to program.

### Operating System and Browser

Windows 10 Firefox (newest)

**Comment by kchadha** [comment]
This is not a feature we're likely to address in the foreseeable future.
