### ISSUE TITLE
Drag surface showing in the wrong position on iOS

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#237]
Not sure how this is happening or where it got introduced, but it seems to be offset by an entire screen size.

**Comment by tmickel** [comment]
At least part of the problem on OS X Safari appears to be because the workspace has a strange translation around (0,0).

It's being set in the CSS as something in scientific notation, e.g.: `transform: translate3d(153.00000000000068px, 2.9842794901924208e-12px, 0px)scale3d(1,1,1)`

When this is the case, the entire transform of the drag surface acts strangely. It's not clear to me why the transform in the SVG also isn't acting strange. Possibly it's a difference between using `translate` in the SVG, and `translate3d` in the drag surface.

One solution seems like it might be to just round the values before they're set in the drag surface.
For example, we could do:
`Number(x).toFixed(2)` - this seems to force the number to 0.00 while maintaining subpixel accuracy.

**Comment by tmickel** [comment]
@picklesrus I wonder if you have run into anything like the above in your work :)

**Comment by tmickel** [comment]
Confirmed this also fixes the issue on iOS!

**Comment by picklesrus** [comment]
My stuff is still broken enough that it is hard to tell whether this has caused me problems... But thank you for pointing it out! It is quite possible it has.  I also just found a bunch of complaints about using floating point values in translate3d causing fuzzy text and I do have some fuzziness in my stuff.  I haven't investigated whether truncating solves it yet, but something to keep an eye on.
