### ISSUE TITLE
Design - Pan Controls

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#24]
In `blockly` the mouse scroll wheel defaults to controlling zoom level. This feels pretty confusing IMO on Mac OS and we've discussed mapping our pan / zoom behavior to be closer to what is used in Apple Maps. Related to #43

**Comment by towerofnix** [comment]
What's the conclusion on this?

If I try to drag some text from the top of this page into the reply textbox - which can't be seen from where I can see the textbox, by the way - I need to get from the top to the textbox, while holding the text (i.e. the mouse button down). I do this by using the scroll wheel. If it's too far to the right or left and I'm zoomed in, I hold down the shift key while scrolling.

Keep in mind I don't have a touchpad - and I _highly_ doubt very many Scratchers do. It's a pain to bring the blocks to the very edge of a scripts pane to get them to the right spot. I think that it should be possible to scroll using the scroll wheel - I mean, that's what it's called, right? Using the scroll wheel is natural to anybody who browses the internet with a mouse.

Of course, I do agree with @NeilFraser, as scrolling like that is natural to anybody who browses the internet with a touchpad!

And obviously the scrollbars on the bottom and right of script panes shouldn't be removed either.. they're handy for getting quickly to a percentage through the script area. Plus what about people who don't have a scrollwheel _or_ a touchpad? It wouldn't be very obvious to scroll the area by dragging a block! :)
