### ISSUE TITLE
How to prepublish in React project

### ISSUE THREAD

**Issue by VictorHVillanueva** [LLK/scratch-blocks#2429]
I have a project in React and I have installed scratch-blocks with npm install scratch-blocks. The application works correctly. Then I have created custom blocks. When I run 'npm run prepublish' I get an error, it tells me that the clousere compiler is missing. What am I doing wrong?

Thank You.

**Comment by asadgulxar** [comment]
@VictorHVillanueva Could you please provide some insights on how you integrated Scratch-Blocks into a React component? Would you be able to share a code snippet for reference?
