### ISSUE TITLE
i am getting this error Error: Closure not found.  Read this: developers.google.com/blockly/guides/modify/web/closure

### ISSUE THREAD

**Issue by ghazalialshafi** [LLK/scratch-blocks#2433]
### Expected Behavior

_Please describe what should happen_

### Actual Behavior

_Describe what actually happens_

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by apple502j** [comment]
See https://github.com/LLK/scratch-blocks/wiki

**Comment by CST1229** [comment]
> 
> 
> See https://github.com/LLK/scratch-blocks/wiki

It happens with the [llk.github.io playground](https://llk.github.io/scratch-blocks) too.
