### ISSUE TITLE
Deletion behavior on right-clicking the first block

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#245]
Currently, the context menu indicates that only one block will be deleted. In fact, the entire stack is deleted! :( Either we should fix the menu or fix the deletion behavior.

**Comment by towerofnix** [comment]
I'm for fixing the deletion behavior! It's handy to be able to delete one block like that, instead of separate it from the rest of the stack, drag out the block, and then re-attach the bottom of the stack. It's already easy enough to drag a block and everything below it into the trash or block palette.

**Comment by PullJosh** [comment]
@liam4 Agreed! No reason to repeat an already-easy behavior in a different menu. Might as well give people another, different option for deleting. :)

**Comment by thisandagain** [comment]
This is now even more odd:
- Delete a "hat" from a stack: entire stack is deleted
- Delete a block from stack: just that block is deleted

**Comment by rachel-fenichel** [comment]
Code path:
 
[Blockly.ContextMenu.blockDeleteOption = function(block)](https://github.com/LLK/scratch-blocks/blob/develop/core/contextmenu.js#L228)

Calls `block.dispose(true, true)`

[Blockly.BlockSvg.prototype.dispose = function(healStack, animate)](https://github.com/LLK/scratch-blocks/blob/develop/core/block_svg.js#L899)

Calls `this.unplug(healStack)`.

`healStack` is true (passed in from `blockDeleteOption`.

[Blockly.Block.prototype.unplug = function(opt_healStack)](https://github.com/LLK/scratch-blocks/blob/develop/core/block.js#L323)

`unplug` tries to heal the stack by connecting the next block to the previous block, healing the gap where the current block sits.  There's no previous connection, so it doesn't detach anything.  Then deleting the block deletes all connected blocks.

Solution: if there's no previous connection and there is a next block connected, disconnect the next block.  Possibly the same for the output connection case.
