### ISSUE TITLE
Insertion markers don't seem to take on size of rendered block in vertical

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#250]
The height seems to be correct for a block with no internal fields; the width seems to be incorrect even for these. Could this be because I took out rendering of fields for insertion markers? Could we get around this somehow by stealing the metrics from the originating block?
<img width="386" alt="ghosts-vertical" src="https://cloud.githubusercontent.com/assets/120403/14662732/143c8672-0687-11e6-9274-87e0a928e27e.png">

**Comment by thisandagain** [comment]
Resolved in #569
