### ISSUE TITLE
Supporting "infinite scroll" mode flyouts

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#258]
We should add support and a configuration option to support "infinite scroll" flyouts for touch devices.

These flyouts have multiple categories, but all blocks are shown in the flyout at all times. Choosing a category does an animated scroll toward the blocks of that category. Scrolling the flyout updates the selected toolbox category state as you're scrolling.

**Comment by thisandagain** [comment]
Depends on #21

**Comment by tmickel** [comment]
Closing for now since we have a more focused flyout plan.
