### ISSUE TITLE
Support check-boxes for reporters in flyout

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#260]
The flyout should allow blocks to have a check-box property. If this is set, the block is shown with a checkbox to the left of it. When the checkbox is checked or unchecked, a UI event is generated so Scratch can show/hide a value monitor. The check-box should have state on initiation (some projects will have this checked in the saved state).

<img width="148" alt="screen shot 2016-04-20 at 11 54 24 am" src="https://cloud.githubusercontent.com/assets/120403/14681358/bac359f0-06ee-11e6-8e31-bad894644485.png">

**Comment by rachel-fenichel** [comment]
Is this also expected to work in horizontal mode?

**Comment by tmickel** [comment]
Horizontal flyout, I'm assuming (not horizontal blocks, which I think should be irrelevant),

Not clear if we'll ever be using horizontal flyout on the vertical blocks. If it's easy enough to place the checkbox above the block in "top" mode and below the block in "bottom" mode, I think that would be nice :). But definitely not the highest priority.

**Comment by cpseager** [comment]
The checkbox should also update if any drop down within the block on the flyout changes - Scratch 2 is flawed in this regard (with the checkbox checked state getting out of sync with the reporters that are actually currently displayed).

This is easiest seen in Scratch 2 with the 'current minute/month/date' etc. block - check the box and then change the drop down to a different type - the checkbox does not update as it should on the parameter change.

**Comment by tmickel** [comment]
Perhaps let's have the state of the checkbox flow from the VM. When you click it trigger a UI event. And have a some method the VM can use to check/uncheck the checkbox?
