### ISSUE TITLE
Support labels in the flyout

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#262]
Example of when this may be desirable:
<img width="193" alt="screen shot 2016-04-20 at 12 02 51 pm" src="https://cloud.githubusercontent.com/assets/120403/14681616/dfb017d4-06ef-11e6-9ec6-9c4b69742907.png">

Hopefully we may also be able to reuse these labels for something like #258.

With an option we should make these labels/categories "sticky", like the iOS contacts list or like this fiddle: https://jsfiddle.net/yZKea/ (although almost certainly not with that implementation :))

**Comment by thisandagain** [comment]
Depends on #21

**Comment by tmickel** [comment]
@rachel-fenichel The infrastructure for this has landed, right? Assigning @carljbowman for any further design work.

**Comment by rachel-fenichel** [comment]
Yup, you've now got labels and buttons with arbitrary callbacks.  <label text="foo" callbackKey="yourcallbackKey"> can go anywhere blocks can go, and it's styled with CSS.

**Comment by carljbowman** [comment]
Looks like we have the framework for this feature. 

Closing this issue until we have a specific use case, possible something we can explore in the extensions model.

Palette concept sketches that highlight possible use cases: 

<img width="179" alt="screen shot 2017-03-23 at 10 46 45 am" src="https://cloud.githubusercontent.com/assets/3409578/24253218/14641596-0fb6-11e7-9271-20342d2654ba.png">

![00_palette-studies](https://cloud.githubusercontent.com/assets/3409578/24253113/cb961936-0fb5-11e7-8026-c32851f90f62.png)

**Comment by CatsAreFluffy** [comment]
Why is Operators a stamp?

**Comment by carljbowman** [comment]
@CatsAreFluffy - I should have clarified. Those icons were placeholders and the exact icons should not be taken literally. While sketching I used random icons just to get a sense of if the icons created a overwhelming visual complexity. That way I did not have to think about the specific iconography and could sketch quickly.
