### ISSUE TITLE
Bad pants insertion marker placement at start-block connection

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#263]
The insertion logic doesn't seem to recognise the connection to the start block:

![start insertion broken](https://cloud.githubusercontent.com/assets/632207/14681798/f2357916-0722-11e6-929b-79d6eebb0a08.gif)
*insertion by start block at 258a3e4*

Inserting a normal (non-pants) block seems to work normally.

I haven't looked into the cause of this.

**Comment by tmickel** [comment]
@rachel-fenichel This seems like resolved to me, yeah?

**Comment by tmickel** [comment]
Closing as I'm 99% sure this is fixed.

**Comment by drigz** [comment]
Yep, you're right - this issue was fixed by the revert. I've filed #547 to track the (much smaller) original issue.
