### ISSUE TITLE
Traducción automática al español latinoamericano incorrecta.

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-blocks#2650]
https://github.com/LLK/scratch-blocks/blob/3273bb5a78a5befa2c831768a2ec0e6cbe94c37c/msg/scratch_msgs.js#L5464

**Comment by ericrosenbaum** [comment]
Thanks!

Fixed in #2652 (changes should be visible later today)

For clarity, translations of Scratch content (including the blocks) are done by a worldwide network of volunteers. You can learn more here: https://github.com/LLK/scratch-l10n/wiki/Guide-for-Scratch-Translators
