### ISSUE TITLE
How do I create a new block?

### ISSUE THREAD

**Issue by scratchforsccom** [LLK/scratch-blocks#2746]
I need a sequence of steps that allow me to add a new block that runs both in a fork of Scratch online and in a fork of Scratch Desktop. I tried several tutorials, but they all end with red-hat-looking blocks, that is blocks that works when clicked but i) have the wrong look and ii) cannot be embedded in scripts.

Can you please provide a sequence of steps (for a simple, dummy block) as the one available at https://github.com/LLK/scratch-gui#readme?

Thanks a lot in advance

### Operating System and Browser

Mac OS 11.6.1 (20G224), Safari 14.1.2 (16611.3.10.1.6), Chrome 98.0.4758.102 (x86_64)

**Comment by ericrosenbaum** [comment]
Unfortunately we don't have the capacity to provide more documentation for adding a core block.

An alternative that might work for you would be to add your new block in an extension. It's much simpler: create an extension (a single file in scratch-vm, plus add one line to load it in extension-manager), then link your local VM to GUI following that readme. The last step would be to add an item to the extension library in GUI, to add the extension by its id.

**Comment by turbowarpORIG** [comment]
> An alternative that might work for you would be to add your new block in an extension

I know, but it would not work for me. I need to add new blocks to the standard categories.

> Unfortunately we don't have the capacity to provide more documentation for adding a core block.

After a lot of trial and error I can provide a sequence of steps myself that works, derived from one of the tutorials that ended in the wrong red block. The sequence includes a manual step that require to move the content of one folder to another folder. Do the development team have time to, at least, revise the sequence and tell me how to make it fully automatic using the normal npm commands?

Thanks in advance

**Comment by huiye19** [comment]
@turbowarpORIG Hi, I have the same problem (when creating a new block, it appears to be a wrong red had block with no text). May I know your manual sequence of steps to fix it? Thanks in advance.

**Comment by sfederici** [comment]
Hi

> @turbowarpORIG Hi, I have the same problem (when creating a new block, it appears to be a wrong red had block with no text). May I know your manual sequence of steps to fix it? Thanks in advance.

What OS do you use? I have difference sequences for Mac and Win. I have tried the sequence recently, and I found some block. I will revise it during the next weeks. I will let you know if I find again a perfectly working sequence.

**Comment by sfederici** [comment]
> Hi, I have the same problem (when creating a new block, it appears to be a wrong red had block with no text). May I know your manual sequence of steps to fix it? Thanks in advance.

Hi @huiye19, sorry for this very late answer. I just finished creating a new sequence to create new blocks. This is much easier and less error prone than the previous one (that I couldn't replicate unfortunately). Now I'm using extensions and TurboWarp, and the blocks will show up in the palette in the standard Scratch categories (not as an extension, if you want).

Let me know if you still need support. Sorry again if this took so long.
