### ISSUE TITLE
Migrate to ES modules and a modern bundler?

### ISSUE THREAD

**Issue by cshaa** [LLK/scratch-blocks#2768]
### Expected Behavior

Most big projects in the JavaScript ecosystem currently use [ECMAScript modules](https://webpack.js.org/guides/ecma-script-modules/) in combination with a bundler like [Rollup](https://rollupjs.org/guide/en/), [Webpack](https://webpack.js.org/), [Vite](https://vitejs.dev/) or, if they need some extra flexibility, [Gulp](https://gulpjs.com/). The advantages of this approach are significant:
 * good interop with developer tools (type inference, go to definition, JSDoc documentation in tooltips)
 * good availability of the build tools (all of them are on NPM and don't require anything but Node.js)
 * most developers who are familiar with JavaScript are also familiar with these systems

### Actual Behavior

Scratch Blocks, on the other hand, uses Google Closure and a custom 630-line build script in Python. It requires Python 2, Java and apparently [doesn't work on Windows](https://github.com/LLK/scratch-blocks/issues/2080). This seems like a big entry barier for anyone who might want to contribute, because in order to even compile the code, they need to install Python 2, Java and possibly even WSL – and even then they wouldn't even have IntelliSense.

It is my interpretation of the open-source philosophy that projects should strive to lower the entry bariers, so that anyone can participate, contribute, fork. And I think that moving to ES modules would be a step in that direction.

### Question

Does the Scratch Team consider something like this? Would you be open to PRs?

**Comment by ericrosenbaum** [comment]
Thanks @m93a ! We are aware of these concerns, and actively working on how our team will address them. This type of structural change is complex and risky because it affects several of our own projects (including non-public repos), so it really has to be done internally. Generally, we accept PRs from external contributors for issues that have been marked "Help wanted" (see the [contributor guidelines](https://github.com/LLK/scratch-blocks/blob/develop/.github/CONTRIBUTING.md))

**Comment by apple502j** [comment]
@ericrosenbaum I suppose by "non-public repos" you mean things like Scratch on Android (although the GUI part is just a branch of scratch-gui). Are there plans to make them public?

**Comment by cshaa** [comment]
@ericrosenbaum Thank you for your answer! Your stance is understandable – it only makes sense to keep the workflow coordinated across all repositories.

That being said, I want to modify Scratch Blocks and use them in my personal project. For such a project, a simpler build process would be a blessing. Can I expect that your team will address this in the near future, or should I rather _not_ count on that, and make my own fork and migrate to ES modules there?

**Comment by cshaa** [comment]
For anyone interested, I've started working on porting Scratch Blocks to TypeScript + ES modules. It's a huge undertaking, so I can't promise I'll manage to finish it, but you might find the repo useful even if I don't.

https://github.com/m93a/scratch-blocks-modernized
