### ISSUE TITLE
"For each" block should have an arrow at the end, like other loops

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#2804]
Other looping blocks like "forever" and "repeat until" have an upward-facing arrow to indicate they go back to the start of the inside (that is, loop):

![empty "repeat 10" and "forever" loops with upward arrows at the end](https://user-images.githubusercontent.com/9948030/166849519-c9e44de9-b848-4219-98c6-dddf9f11dc93.png)

Since "for each" is another looping block, it should have an arrow to indicate that behavior, too!

This might not be accepted since "for each" is a hacked/obsolete block that isn't formally supported, but since it *is* a real block that scratch-blocks and scratch-vm both understand, there's value in making it more accessible when it does get used, right?

**Comment by ericrosenbaum** [comment]
Thanks- looks like this affects a pretty small number of projects in total, so it's hard for us to prioritize. Closing for now.

**Comment by towerofnix** [comment]
Thank you for the quick reply.

For what it's worth, the solution is copy-pasting the same lines of code used in every other loop block's definition: https://github.com/LLK/scratch-blocks/blob/2e65138322a439d4042d5ab13aa7e833c2900fd2/blocks_vertical/control.js#L49-L58

I definitely don't think it's worth prioritizing a *release* for, but whenever the next push to master does come about, would it be a problem to have these nine lines of code duplicated as-is in one more place? ([Below line 375 in `blocks_vertical/control.js`, that is.](https://github.com/LLK/scratch-blocks/blob/2e65138322a439d4042d5ab13aa7e833c2900fd2/blocks_vertical/control.js#L375)) It's not as though this would accidentally risk any side-effects *besides* doing the same thing all other looping blocks do.

You've practically already reviewed the PR by reading my comment :P

(PS: I noticed "for now" - does this imply the team would actually be revisiting closed issues? To my understanding closing an issue means putting it in the past - leaving it open with the appropriate labels, as you tagged it, would ensure that it *could* be revisited at a later date. Otherwise I don't really see how you can tell it apart from issues which were actually resolved (and so closed).)

**Comment by towerofnix** [comment]
Quick, slightly belated addition: Even though it's also a hacked block, the "while" block has the looping arrow at the end, like other loops (but not "for each" currently). So, even among other hacked blocks, "for each" is the odd one out for appearance consistency :P
