### ISSUE TITLE
Error when creating a block

### ISSUE THREAD

**Issue by UCYT5040** [LLK/scratch-blocks#2810]
### Expected Behavior

Some GUI for making a block.

### Actual Behavior

Alert window pops up:
`External procedure editor must be override Blockly.Procedures.externalProcedureDefCallback`

### Steps to Reproduce

1. Go to My Blocks on the toolbox
2. Click on create block
3. See error

### System Details

Acer ChromeOS, 96.0.4664.111 (Official Build) (64-bit)

**Comment by ericrosenbaum** [comment]
That functionality is implemented in the Scratch-GUI:
https://github.com/LLK/scratch-gui/blob/develop/src/components/custom-procedures/custom-procedures.jsx
https://github.com/LLK/scratch-gui/blob/develop/src/containers/custom-procedures.jsx
