### ISSUE TITLE
Error while running npm run prepublish in scratch-blocks

### ISSUE THREAD

**Issue by PatelManav20** [LLK/scratch-blocks#2925]
I am trying to add hindi language in scratch so i make some changes in scratchmsg.js and because of that i tried running npm run prepublish but it is giving me this error.

ERROR!!

 npm run prepublish

> openblock-blocks@0.1.0-prerelease.20211025152811 prepublish
> python build.py && webpack

Using remote compiler: closure-compiler.appspot.com ...

Error: Closure not found.  Read this:
  developers.google.com/blockly/guides/modify/web/closure

**Comment by benjiwheeler** [comment]
You might need to link `node_modules/google-closure-library` to the directory above `scratch-blocks` as `closure-library`

**Comment by chrisgarrity** [comment]
@PatelManav20 are you intending to submit a PR here with Hindi added or adding it for your own purposes? Translations in Scratch are handled through our translation platform [Transifex](https://www.transifex.com/llk/scratch-editor/dashboard/). Hindi has been translated, and is currently in the review process. Adding a language for Scratch is more than just the editor, so we will not accept translation PRs on this repo.

**Comment by PatelManav20** [comment]
> @PatelManav20 are you intending to submit a PR here with Hindi added or adding it for your own purposes? Translations in Scratch are handled through our translation platform [Transifex](https://www.transifex.com/llk/scratch-editor/dashboard/). Hindi has been translated, and is currently in the review process. Adding a language for Scratch is more than just the editor, so we will not accept translation PRs on this repo.

I am translating for my own purpose.

**Comment by cwillisf** [comment]
Hi there! It looks like you might be running `prepublish` without installing dependencies. In general, it shouldn't be necessary to run the `prepublish` script yourself: it'll automatically run after `npm` installs dependencies. Please run `npm ci` instead.
