### ISSUE TITLE
Horizontal blocks input update

### ISSUE THREAD

**Issue by SeunBrightec** [LLK/scratch-blocks#2941]
### Expected Behavior

For any block that requires a user to input an integer value, the value in the block does not reflect the new value entered.
The expected behaviour should be that the new input value should always be reflected within the workspace

### Actual Behavior

Putting in a new value in any block that requires an integer does not reflect the new value. It is only reflected when the user presses the integer value

### Steps to Reproduce

_Explain what someone needs to do in order to see what's described in *Actual behavior* above_

1. Go to 'https://sheeptester.github.io/scratch-blocks/playgrounds/tests/horizontal_playground.html?dir=ltr&toolbox=simple&side=start'
2. Drag any block that takes in an integer value out of the toolbox into the workspace
3. Type in the new value of your choice and notice that the value doesn't change unless a user clicks on the input value.

### System Details
This occurs on browser Mac OS 12.5 Chrome Version 108.0.5359.124 

**Screenshots**

**Comment by cwillisf** [comment]
Sorry, scratch-blocks doesn't support horizontal blocks mode. We experimented with it, but never finished it.
