### ISSUE TITLE
What is the status of horizontal grammar in scratch-blocks?

### ISSUE THREAD

**Issue by parth-stempedia** [LLK/scratch-blocks#2958]
After going through various files, I found that there is some basic structure present for horizontal blocks in scratch-blocks.But I am unable to use it for development. So far, I have explored that on building scratch-blocks various files are generated like blockly_compressed_vertical.js, blockly_compressed_horizontal.js etc. I have some questions, it would be great if someone can answer it.
1) Currently we use files related to vertical grammar with scratch-vm and scratch-gui.But is there a way to use horizontal grammar currently?
2) I also viewed a file called horizontal_playground.html on a local development server, there I could see some horizontal blocks. But there aren't any blocks related to other categories. If I want to develop other horizontal blocks, is the procedure same as we do for vertical blocks or will we have to implement the logic behind those blocks from scratch?
3) Lastly, I read readme of this doc, where it is stated that scratch has developed horizontal blocks for scratchjr platform, so have they used scratch-blocks or blockly to develop scratchjr ora complete different method, because I could not find any use of scratch-blocks or blockly there?

The gist of all these questions is whether we can use scratch-blocks to convert all the vertical blocks to horizontal blocks.

**Comment by cwillisf** [comment]
Sorry, scratch-blocks doesn't support horizontal blocks mode. We experimented with it, but never finished it. ScratchJr uses a different method to implement horizontal blocks, but we're looking at using Blockly in a future version.
