### ISSUE TITLE
Round corners of hovered dropdown menu items?

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#2982]
Scratch 3.0 has almost no perfectly square corners! Even the corner of a "square" non-shadow dropdown field is rounded:

<img width="188" alt="Screenshot 2023-03-07 at 6 47 48 PM" src="https://user-images.githubusercontent.com/9948030/223571613-91e38be8-c0ac-440c-93b6-955e5b3de81f.png">

Pretty much the only exception to this rule is the hovered dropdown menu item:

<img width="249" alt="Screenshot 2023-03-07 at 6 48 54 PM" src="https://user-images.githubusercontent.com/9948030/223571783-ef652765-1123-4734-8008-48f564e20eac.png">

Yikes, that's sharp! Don't cut your finger on your touchscreen! 🔪

Here are two alternate ideas:

**Round all the corners of every item.**

<img width="262" src="https://user-images.githubusercontent.com/9948030/223573670-420fe07b-66ed-4961-a010-87825f221c80.gif">

This makes a nice subtle effect. None of the edges are sharp, and it fits in with the rest of the Scratch look.

**Round just the top corners of the first item, and just the bottom corners of the last item.**

<img width="262" src="https://user-images.githubusercontent.com/9948030/223573899-40c17c40-3d22-4c03-8870-c8bedaffde5f.gif">

This lends to a bigger effect, giving an extra cue for which items are the top and bottom. It looks like the items are on a track, and emphasizes the whole menu as a list of options together, rather than rounding out each option on its own. I think it gets the creative juices flowing more (especially if menus had divider options to more clearly group related options together), but it may be a more "annoying" change for existing Scratchers.

Just an idea! I can't find any other places in the entire Scratch editor with 90-degree corners, so it might be nice to get this last one rounded off, since there's currently ongoing work on the design of menus in any case!

/cc @aoneill01 @cwillisf since you two are on [the current](https://github.com/LLK/scratch-blocks/pull/2976) dropdowns PR!

**Comment by aoneill01** [comment]
They are quite pointy, @towerofnix. I shared this with the designers. They do agree that they prefer round elements. Sounds like they may consider this in the future as part of a revisit of all dropdowns, but not right now.

**Comment by towerofnix** [comment]
Sounds good, thanks for sharing this along!
