### ISSUE TITLE
Design - Vertical Grammar

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#3]
- [x] Define subset of blocks for initial design pass
- [x] Initial design pass
    - [x] Input Block (Integer)
    - [x] Hat Block
    - [x] Input Block (String)
    - [x] Dropdown Block
    - [x] C-Block (Repeat)
    - [x] Variable Block
    - [x] Dropdown/Input Block (Integer)
    - [x] Boolean Block
- [x] Design review
- [x] Second design pass
- [ ] Handoff for implementation

**Comment by tmickel** [comment]
Closing as this has been broken into a few implementation issues.
