### ISSUE TITLE
Dropdowns from flyout don't disappear when scrolling

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#302]
![dropdown scroll](https://cloud.githubusercontent.com/assets/632207/14860768/835a3472-0caa-11e6-94c2-e0ed8b8ea2ab.gif)

Scrolling via the scrollbar removes the dropdown, but scrolling by the block area doesn't.

PS. Is it intentional that you can open dropdowns / edit fields in the flyout? Our UX guys were surprised by this behaviour.

**Comment by luxaritas** [comment]
It looks like this is still an issue, though with the scroll wheel:

![floating](https://cloud.githubusercontent.com/assets/18635705/20232205/a4a9641a-a834-11e6-9b75-0fffaf36ee85.png)

I'm tempted to say that when using the scroll wheel it should just track the original input.

**Comment by tmickel** [comment]
@LFP6 Yep, thanks for raising that!
