### ISSUE TITLE
Prepare for Open Source Release

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#304]
@thisandagain @rachel-fenichel 
Here are some things I think we should consider stripping out of this codebase before open sourcing:
- [x] appengine/ - We will never support this. Also the cloud storage demo.
- [x] demos/toolbox, until we figure out how we're going to manage the palette
- [x] Maximum block limit demo and this feature, which I consider a bad feature for us to be putting out
- [x] Generate JavaScript demo - until we actually can do this for Scratch
- [x] JS interpreter demo - same issue as above
- [x] Plane demo - this is not how someone would use Scratch-blocks and it's also very "problem-solvy"
- [x] Mirrored blockly demo - remove it or at least remove the "master-slave" terminology which is potentially problematic
- [x] Code editor demo - This mostly demos exporting code to multiple languages, whcih I don't think we want to support.
- [x] We should make a mark on the block factory demo that this is a WIP for Scratch-blocks
- [x] All code marked `@deprecated` - We have no need to maintain these legacy functions in Scratch
- [x] JSHint configurations (jshintrc, in package.json) - we now have eslint which I think should be the one we use
- [x] A few of the _compressed builds haven't been updated in a long time, because they're left over (e.g. python generator)

I'm fine with leaving these in but maybe we should get rid of them since they are cruft:
- [x] Possibly all of the translations in `/msg/`\- we won't be using those, I imagine
- [x] Might consider removing warning.js, mutator.js, icon.js, and all of their intermingled dependencies/usages - I think we will never want to use any of these, ever. Could consider removing bubble.js if we never want to use the current comment bubbles. (Tracking in #316 )
- [x] Fields - 90% of field_colour, field_date, field_dropdown, field_variable will have to be redone for new UI or integrating with Scratch. I think we should consider removing them at this time and pulling back pieces if/when we want them. Similarly, procedures.js? (Tracking in #317 )

**Comment by usandourkids525** [comment]
#313 Sat. MARCH 11TH AT 1:12 am
Shayne Cosner Software Manager and Team
Dakota Cosner, Rhyver Cosner to take over when he is 43,
Cayne Adams, Carl Joseph Cosner, Bryar Willis and whoever else after Talking to my Brothers But for now this is my decision
