### ISSUE TITLE
Touch event on PC should open on-screen keyboard

### ISSUE THREAD

**Issue by cwillisf** [LLK/scratch-blocks#305]
The convention on a Windows computer with a touch-screen is:
- A **click event** in a user-input field should **not** display an on-screen keyboard, but
- A **touch event** in a user-input field **should** display an on-screen keyboard.

We should probably follow this convention when choosing whether to display (for example) our number pad.

**Comment by tmickel** [comment]
@rachel-fenichel Btw I was curious if you tested this?

**Comment by rachel-fenichel** [comment]
Currently touch events on edge on windows are fairly broken--edge and IE don't implement the touch events API, only pointer events.  I need to go back and test it again but I'm not optimistic right now.

**Comment by chexbox** [comment]
@rachel-fenichel - How long until every company/organisation quits using IE/Edge and Microsoft gives up hope in making a browser?

**Comment by rachel-fenichel** [comment]
@chexbox Please keep your comments constructive.

**Comment by picklesrus** [comment]
This is working now on a surface tablet.
