### ISSUE TITLE
Removed Unused Fields

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#317]
From #304:
> 90% of field_colour, field_date, field_dropdown, field_variable will have to be redone for new UI or integrating with Scratch. I think we should consider removing them at this time and pulling back pieces if/when we want them. Similarly, procedures.js?

**Comment by tmickel** [comment]
At this point, actually, might make sense to leave them in and just tweak their designs. Except for field_date, which feels safe to take out.
