### ISSUE TITLE
Clean-up formatting / all eslint tests passing

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#318]
We have eslint integrated but it is currently returning 990 errors. All lint tests should be passing and CI via Travis-CI should be hooked-up.

**Comment by carlosperate** [comment]
Is this a different linter than the one used in blockly? If that is the case we should make sure both projects use exactly the same rules, or PRs to blockly might trigger lint errors here.

**Comment by bates64** [comment]
Have you tried `eslint --fix`? I assume that you have, but it's something to run if you haven't.

**Comment by towerofnix** [comment]
> Have you tried `eslint --fix`? I assume that you have, but it's something to run if you haven't.

For what it's worth, `eslint --fix` has broken my projects before.. :P

**Comment by thisandagain** [comment]
Closing as per work that @rachel-fenichel has done to date. Will break down remaining issues into individual tickets.
