### ISSUE TITLE
Design - mouse cursors

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#327]
I find the current mouse cursor behavior to be a little strange in the context of executing blocks.

The current behavior is to have the "open hand" anytime you're hovering above a block (to indicate that it can be dragged). When you mouse-down on a block, it switches to "closed hand" to indicate a drag is starting.

However, this means when you are just tapping a block to execute it, the hand changes to closed mode, as if you're grabbing the blocks to execute them.

Personally I think it might make more sense if we showed the default mouse cursor at all times, until a drag begins (exceeding DRAG_RADIUS), when the hand might switch to closed/grab.

**Comment by bates64** [comment]
If I might add... maybe the **pointer** mouse cursor should be shown when hovering over a block, until a drag begins as you said. It makes no sense to not _give feedback when hovering over a clickable/dragable element_...

Default = No feedback :(
Pointer = Clickable / Draggable
Grab = Draggable

**Comment by towerofnix** [comment]
@nanalan I agree with this, though it would take me a while to get used to the cursor changing all the time.. :)

**Comment by tmickel** [comment]
@carljbowman Assigning for feedback

**Comment by tmickel** [comment]
I've implemented the originally suggested version:
![demo-cursors](https://cloud.githubusercontent.com/assets/120403/16667620/78cf4388-445b-11e6-9e4e-f70b510a2fb5.gif)
Easy to back-track if we come up with other ideas.
