### ISSUE TITLE
Fix documentation for "Error: Closure not found"

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#338]
After installing the way [the wiki explained](https://github.com/LLK/scratch-blocks/wiki#installation), and opening `tests/horizontal_playground.html`, I got an alert saying:

```
Error: Closure not found.  Read this:
developers.google.com/blockly/hacking/closure
```

It looks like you [need](https://github.com/LLK/scratch-blocks/blob/ae6c715a22c120cd661b33281d6d52491a47e6f2/build.py#L430-L431) to have [closure-library](https://github.com/google/closure-library) installed in the lower directory.

``` python
calcdeps = import_path(os.path.join(
  os.path.pardir, "closure-library", "closure", "bin", "calcdeps.py"))
```

That, honestly, feels like bad design (i.e. I keep _my_ GitHub projects in one directory and other random clones in another, so I don't really want closure-library, which I don't contribute to, in my I-contribute directory).

After getting closure-library installed at `scratch-blocks/..`, running `build.py` again, and opening the example/test file again, it worked.

**Comment by tmickel** [comment]
Thanks for bringing this up. A wiki update seems in order for now. Eventually we'd like to fix this up so you don't need Closure in the parent directory, as you say. That may take some effort, though :)

**Comment by bates64** [comment]
I'm still trying to figure out how to actually get `build.py` running in the first place - any help appreciated...

```
$ npm i
$ cd ../ && npm i closure-library && cd scratch-blocks
$ python build.py
Error: Closure not found.  Read this:
https://developers.google.com/blockly/hacking/closure
```

**Comment by towerofnix** [comment]
Replace `npm i closure-library` with `git clone https://github.com/google/closure-library.git`.

**Comment by cymplecy** [comment]
What is the current work around to try out Scratch Blocks please (in simple step langauge)

**Comment by towerofnix** [comment]
Assuming you've used a terminal before..

``` bash
cd <where you put your github prjoects>
git clone https://github.com/google/closure-library.git
git clone https://github.com/LLK/scratch-blocks.git
cd scratch-blocks
python build.py
# Now you can experiment by opening up
# tests/horizontal_playground.html :)
```

Of course, you'll need `git` and `python` installed.

**Comment by carlosperate** [comment]
No need to build the absolute latest version though, the compressed/uncompressed blockly in the repository is new enough to give it a quick test.

**Comment by cymplecy** [comment]
@liam4 That got rid of error and I can now see the blocks - Ta :)

**Comment by thisandagain** [comment]
![](https://developers.google.com/blockly/images/closure-alert.png)

**Comment by thisandagain** [comment]
Documentation in the Wiki has been updated:
https://github.com/LLK/scratch-blocks/wiki

**Comment by CrazyCactusGuy** [comment]
Hey, this isn;t working for me :/ I am on Windows and after doing these steps:
cd <where you put your github prjoects>
git clone https://github.com/google/closure-library.git
git clone https://github.com/LLK/scratch-blocks.git
cd scratch-blocks
python build.py
# Now you can experiment by opening up
# tests/horizontal_playground.html :)
It still says Closure not found...
