### ISSUE TITLE
[Vertical] Blocks look squashed in the sidebar

### ISSUE THREAD

**Issue by Tymewalk** [LLK/scratch-blocks#339]
Take a look here:
![](http://u.cubeupload.com/Tymewalk/squashedverticalbloc.png)
Notice how the block titles look "squashed" when they're in the block selection sidebar.

Also worth noting that the green flag doesn't center with the text.

**Comment by thisandagain** [comment]
Thanks @Tymewalk the vertical blocks a very much so a work in progress and so we'll address this when we start to implement the vertical grammar.
