### ISSUE TITLE
Add option to save locally

### ISSUE THREAD

**Issue by HardPhoenix33** [LLK/scratch-blocks#343]
This is also suggested on Scratch Forums right here:
https://scratch.mit.edu/discuss/topic/200558/?page=1#post-2002022

---

We probably, all of us, want to save locally, and that's just simple. There are two options available that are publicly used:
Cloud, Randomly-generated code, and Still Variables

Cloud is another thing that's used by Cloud Lists. There are no Cloud Lists on Scratch, but you can make one by using Custom blocks. Again, this is simple to use, however it will require everyone to have Scratcher Rank. This is the easiest to make, just as you need to have Scratcher rank and get the custom block for cloud listing.

Randomly-generated code is one of the most-used saving feature. Just, for those who want to save their progresses, they have to copy the whole numbers and save it to a file text or share it online, let everyone have their progresses, and, finished! This requires some people, a common of sense and better understanding to knowing how to save their progresses. This is the most, hardest to make.

Still Variables are common, and do not change until you refresh the page. This is affected by saving it when updating your project, and anyone who changes this variable will keep it even if they stop or play the project, however it will keep until you refresh the page.

Sorry for the long information, just letting you know...

Now, I'm suggesting to save locally. This one uses the style of saving on one separate text file that includes all variables to be saved. The only thing that can be saved locally is the variable, and, lists, too on the other hand. Now, if we can save locally, we can use it for future references, allowing others to LOAD their projects. Really, this is most well known on Flash for saving their games, and there's no such thing as Randomly-generated code these days since that method is already old. However cloud saving is new, but locally is the popular ones.

**Comment by towerofnix** [comment]
_Probably_ better fit for [scratch-vm](https://github.com/LLK/scratch-vm) or even just the [Scratch discussion forums](https://scratch.mit.edu/discuss/topic/200558/)...

**Comment by tmickel** [comment]
Thanks for the suggestion!

Saving variables seems like an interesting and useful feature for Scratch 3.0 to me. We'll definitely keep it in mind as we're designing and planning new features.

Soon I believe we'll be creating a place specifically for making Scratch 3.0 suggestions. For now, as @liam4 says, we'd like to keep the issues on this repo specifically about the blocks rendering library, so I'm going to close this :)

**Comment by HardPhoenix33** [comment]
Thanks!
