### ISSUE TITLE
Blocks are not deleted when dragged to toolbox

### ISSUE THREAD

**Issue by bates64** [LLK/scratch-blocks#351]
Out of habit (and due to **Scratch 2.0 & below having this feature**) I've been dragging blocks intended for deletion over to the left/upper area of the blockly window, where the toolbox is. I'm not sure if this is intended, but instead of deleting said block, _the blockly window scrolls_. :tada: 

Is this intentional?

**Comment by rachel-fenichel** [comment]
Is this in the vertical playground?  Deleting when dropping on the toolbox is definitely implemented, so I'm very curious what's going on.

Can you fetch the newest version and try this again?

**Comment by bates64** [comment]
Ah! Apologies, it works fine now :sweat_smile:
