### ISSUE TITLE
Can I run the code in horizontal_playground or just connect blocks so far ?

### ISSUE THREAD

**Issue by rhulha** [LLK/scratch-blocks#363]

**Comment by mrjacobbloom** [comment]
The side that runs the code will be in [LLK/scratch-vm](https://github.com/LLK/scratch-vm). IDK how functional it is yet tho

**Comment by rhulha** [comment]
Ah I see, great stuff, looking forward to it!

**Comment by rhulha** [comment]
Unless I am missing something scratch-vm playground is only vertical blocks but I would like to test the horizontal blocks.

**Comment by tmickel** [comment]
@rhulha All of this code -- both in scratch-blocks, and in scratch-vm -- is extremely experimental and unfinished. We're developing it in the open over the course of the next few months, but there is a lot more to do (especially with the VM, which just barely works).

You could try running horizontal blocks in the VM playground by swapping out the compiled scratch-blocks JS it includes (i.e., blocks_compressed_vertical -> blocks_compressed_horizontal, blockly_compressed_vertical -> blockly_compressed_horizontal, etc.) The VM should be basically compatible with running horizontal blocks right now. We made the playground to show vertical blocks, as we have a lot of restructuring to do to get it running that type of block :)

Let us know if you have any questions or run into problems. Eventually, we'll have this all working and documented for people to use.

**Comment by rhulha** [comment]
Thanks for your kind response!
The reason I am trying to get this running is that I have also developed a horizontal semi Visual Language. Now I would like to decide if I should abandon my project and maybe help on Bocks instead:
![VisualLang](https://i.imgur.com/ZrVKzRh.png)

**Comment by rhulha** [comment]
Should I close this ticket or leave it open until it is easy to test and run the new Blocks ?

**Comment by tmickel** [comment]
@rhulha I'll close it for now since I think we've answered the question. But feel free to raise new bugs if you find them, or continue commenting here (or in scratch-vm) if you run into trouble - we'd be happy to try to help.

Your project looks interesting! Does it have some kind of windowing system? I'd also note that it might be more appropriate to use our parent project, Blockly: https://developers.google.com/blockly/ - which is more of a general-purpose toolkit than Scratch Blocks.

**Comment by rhulha** [comment]
It's written in Java and therefore has access to AWT and Swing.
