### ISSUE TITLE
Design - what happens when a block is dragged over an input?

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#370]
In Scratch 2.0, a white "glow" appears around the old text area/block.
In Blockly, the yellow notch is highlighted.
In Scratch Blocks currently, there are two cases:
- If the input is occupied by a shadow block, an insertion marker replaces the shadow.
- If the input is occupied by another block, the other block is bumped out of the position and replaced by the insertion marker. This appears as a bug, because the other block is never replaced if the drag moves somewhere else.

Some options that seem viable:
- Scratch 2.0 behavior for all cases (whether or not there's a shadow). If we do this, it would be great to have a spec for size/color/blur/etc. of a stroke.
- Bump any block in an input, but replace it back in when the drag moves somewhere else.
- Some mix of the two: e.g., use the insertion marker for a shadow block, but some Scratch 2.0-style stroke for regular blocks in inputs.

**Comment by tmickel** [comment]
Demonstration:
https://www.dropbox.com/s/3gc65h2cmmkk9ah/outputs-ghosts-connections.mov?dl=0

@rachel-fenichel

**Comment by rachel-fenichel** [comment]
> If the input is occupied by another block, the other block is bumped out of the position and replaced by the insertion marker. This appears as a bug, because the other block is never replaced if the drag moves somewhere else.

This is definitely a bug.  The insertion marker code was very focused on the horizontal mode, and just happens to work fairly well in vertical mode.  But it doesn't do anything different for value inputs vs. previous/next connections, and in horizontal mode there was no way to connect a block that would cause a bump.  It's completely doable to bump the block away and then put it back, if that's what we want.
