### ISSUE TITLE
Design - variable block

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#372]
In Scratch:
- A variable block shows the name of the variable.
- Clicking on the variable block (it's a reporter) evaluates it and pops up the current value.
- Right clicking brings up a context menu that includes the names of all of the other variables.
- A block with a variable field (usually set, change, etc) shows the name of the variable and a dropdown arrow.
- Clicking on the dropdown arrow shows a dropdown with the names of all the other variables.
- Clicking anywhere else on the block, including the variable name and excluding input fields, runs the block.

In Blockly:
- A variable block shows the name of the variable and a dropdown arrow.
- Clicking on the variable field, including variable name and arrow, brings up a dropdown that includes the names of all of the other variables and the options "rename variable" and "new variable".
- Right clicking anywhere on the block, including not on the variable name, brings up a context menu.  When clicking on a getter, this includes "create set _varname_".  When clicking on a setter this includes "create get _varname_".
- Clicking on the rest of the block selects the block.

This is interesting because there is essentially a different field for the variable name on a getter from the field for the variable name on the setter.  It's not immediately obvious how to implement this using current blockly fields.

**Comment by rachel-fenichel** [comment]
- Making a new variable in Scratch is done with the "Make a Variable" button in the Data category.  Blockly is moving to this as well.
- Renaming a variable in Scratch can be done by right-clicking on a reporter in the toolbox, but not by right clicking on a reporter in the workspace or by right-clicking on a setter anywhere.
- Blockly wants to move away from having rename in the right-click menu, but haven't settled on where it will go.
- In Scratch variables can be deleting by right-clicking on a reporter in the toolbox and selecting "delete variable".  This will get rid of the reporter in the toolbox but not change anything in the workspace.  The reporter will eventually show up in the toolbox again--the next time it inspects the workspace?--as long as there exists a reporter for that variable in the workspace or a setter that uses that variable.
- Blockly doesn't seem to allow right-clicking on blocks in a closeable flyout.  The Scratch-blocks flyout will be a non-closeable Blockly flyout, so that should not be a concern.
- Blockly has no button to delete a variable.  When there are no blocks with that variable left in the workspace, it won't show up in the flyout.  This is because the flyout inspects the workspace for variables when it opens, and non-closing flyouts are generally for simple projects that don't have variables.  Some change will be needed to make a non-closing flyout update when a variable is renamed or deleted.

**Comment by cpseager** [comment]
The extra 'custom' context menu is added for the two different types (set/get) of var block here:

https://github.com/google/blockly/blob/master/blocks/variables.js#L58

**Comment by tmickel** [comment]
My original thought for Scratch was to implement variables using auto-generated separate blocks, rather than a variable field. The VM would inject blocks into the block set and the appropriate part of the flyout, or something.

**Comment by rachel-fenichel** [comment]
Auto-generated separate blocks is what I expected, but I'm trying to understand what those blocks actually are.  Do they just have a label and an output?  Does the label change as a result of right clicking and selecting something different?  Given how complicated the behaviour here is, do we want to exactly replicate it?

**Comment by tmickel** [comment]
Hmm, yes. We'll have some discussion here about what exactly they should do. I'm pretty sure we'd like to replicate the behavior pretty closely.
- Label and output: yes. Sometimes also an image field, for cloud variables (or is that a unicode character?)
- Right click and switch variables: yes, that seems desirable. And it should probably do that by changing the block name...or something... maybe we should actually make a field_variable that just "appears" to be a field_label?
- Clicking on the variable to see the value: that is pretty non-negotiable and also applies to other types of blocks. I think we should make a generic way to show values associated with blocks: https://github.com/LLK/scratch-blocks/issues/254
- Regarding where rename/delete are: I think maybe these options should also appear in the workspace blocks.
- The behavior of not removing variables from the workspace when you choose delete seems weird to me, I don't understand why that was done. But I think we need to have variables even if they don't exist in the workspace. This behavior is different from Blockly because semantically a variable can actually store a value even if it's not in the workspace...if that makes sense.

**Comment by rachel-fenichel** [comment]
> -Clicking on the variable to see the value: that is pretty non-negotiable and also applies to other types of blocks. I think we should make a generic way to show values associated with blocks: #254 

Yup, I'm assuming this sticks around--though I personally think that clicking on the whole variable name in a variable dropdown should open the dropdown, instead of just the arrow.  This is also a touch-target question.

> Right click and switch variables: yes, that seems desirable. 

This really feels like an overloading of the right-click menu, especially if there are a lot of variables.

> And it should probably do that by changing the block name...or something... maybe we should actually make a field_variable that just "appears" to be a field_label?

Why would the block name need to change, instead of just the value of the field giving the variable name?

> But I think we need to have variables even if they don't exist in the workspace. This behavior is different from Blockly because semantically a variable can actually store a value even if it's not in the workspace...if that makes sense.

Makes sense.    Basically, variables can't automatically delete themselves.  That fits with explicitly creating them with the "make a variable" button.  However, we should revisit delete behaviour to try to make it even a little bit more intuitive.  Right now there are some very strange corner cases.

**Comment by tmickel** [comment]
> Why would the block name need to change, instead of just the value of the field giving the variable name?

Right, not thinking :)

> This really feels like an overloading of the right-click menu, especially if there are a lot of variables.

Yeah. However I think it's a feature a lot of Scratchers might use...we'll discuss here.

**Comment by rachel-fenichel** [comment]
Update on deletion: we agreed to make deleting a variable remove all instances of it in the workspace (after confirmation) but not in the backpack.

Importing from the backpack implicitly creates any variables found in the imported code.

Question: what if you've got something complicated like this in a set:
![image](https://cloud.githubusercontent.com/assets/13686399/16241918/c8be2dd2-37a4-11e6-99c6-89a5fdc4ee3c.png)
and you delete that variable?  Does the chunk of operator blocks disappear (seems bad) or just disconnect and bump away (could end up far away in pessimal cases of bumping).

**Comment by tmickel** [comment]
Hmmmmm... what if, the drop-down changes to "blank"?

**Comment by rachel-fenichel** [comment]
That seems non-obvious, especially in a large script.  Also what does it mean for the dropdown to say "blank", from a runtime perspective?

If it were blank I would suggest also turning it red (shouldn't be too hard) but that seems counter to scratch philosophy of no errors.

**Comment by carlosperate** [comment]
If the filosophy is "no errors" I would consider a "blank" variable or "red placeholder" both be error-like situations. It seems like the only viable solution is bump away, but as said, it's difficult to track where they end up.
Does scratch have any "alert" system? do it consider using alerts to display information a viable practice? If so you could alert the user about how many variable blocks are present and letting them know the inner blocks will be bumped, or only allow them to delete the variable if they are not connected to anything (but that forces the user to manually put away all the variable blocks to be deleted, might be a good or bad thing).

**Comment by cpseager** [comment]
Scratch 2 has many examples of where blocks can be left incomplete or with a blank dropdown and hence not work as the student expected - for instance I find that students often forget to place an operator in the if-then block after dragging it out. Highlighting these blocks may help the student find them:

![incompletecommands](https://cloud.githubusercontent.com/assets/7423187/16271627/b0d38624-3892-11e6-98af-9b00bdd85e72.PNG)

**Comment by carlosperate** [comment]
That is the kind of situation where the Blockly shadow blocks do a rather good job, not quite sure they fit the general Scratch design patterns though.

**Comment by rachel-fenichel** [comment]
Blockly's response here is to delete all of the connected blocks--similar to scratch's deleting from a block down the rest of the stack when you select "delete".  Assuming that undo works properly, that _might_ be okay.  It at least avoids error states.

**Comment by rachel-fenichel** [comment]
And just for fun, scratch's procedure (more blocks) deletion occurs when you drag the definition into the trash/flyout--but if you try to do that and the block is in use in the workspace, it bounces it back and tells you to delete all references first.
![image](https://cloud.githubusercontent.com/assets/13686399/16287190/3aae9df4-3896-11e6-9fd8-e8d7c18a3c3e.png)

**Comment by mrjacobbloom** [comment]
This might not be too relevant to this discussion, but I've occasionally used deletion to make a global variable private, by deleting it and then running the project (which generates a private variable for each undefined variable name still in the code). That functionality might be worth keeping

**Comment by rachel-fenichel** [comment]
Closing, as most of this is implemented in #570.  Remaining work will be tracked in separate bugs.
