### ISSUE TITLE
Size of blocks with boolean-type edge shape sometimes needs to be extended

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#376]
This is a two-part problem:
1. The internal padding for boolean-edge shapes is too small per spec. This should be a simple adjustment.
2. Sometimes really ugly things happen with blocks:
   <img width="282" alt="screen shot 2016-06-08 at 12 20 42 pm" src="https://cloud.githubusercontent.com/assets/120403/15901943/7ac8b862-2d73-11e6-9984-72102aa93542.png">

This is also a problem in Scratch 2.0, but doesn't become much of a problem until there are many blocks, because the padding is much smaller:
<img width="129" alt="screen shot 2016-06-08 at 12 22 28 pm" src="https://cloud.githubusercontent.com/assets/120403/15901985/b7f4d59a-2d73-11e6-932e-509a04c9746a.png">

To fix problem #2, we could add more space horizontally _somehow_...

**Comment by tmickel** [comment]
@carljbowman Any further thoughts of what you want to do with this? It looks a little better now:
<img width="164" alt="screen shot 2016-07-06 at 4 51 37 pm" src="https://cloud.githubusercontent.com/assets/120403/16634012/f5c51218-4399-11e6-90e7-220ecbdf44cc.png">

**Comment by tmickel** [comment]
(with rounded corners)

**Comment by luxaritas** [comment]
Would it be possible to add more padding on the left and right still, regardless of the issue with overflow of the reporter itself? Seems really cramped to me, without any space to the side of the input.

**Comment by tmickel** [comment]
Resolved :)

**Comment by LegoBrainBiker** [comment]
this probably isn't an issue, but with an insane amount of stacking, the same thing can actually happen on the other side (as long (as there are no blocks there). it's very silly though, as it requires a huge number of blocks, so it probably doesn't matter

![Image](https://github.com/user-attachments/assets/1dec4bd2-18f8-4e7a-bcfc-f7ad5c4f8b9d)
