### ISSUE TITLE
Drawing holes for boolean inputs

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#377]
Compare:
<img width="166" alt="screen shot 2016-06-08 at 12 24 08 pm" src="https://cloud.githubusercontent.com/assets/120403/15902038/ffad25d6-2d73-11e6-8898-37d61cc065d6.png">

To Scratch 2.0:
<img width="148" alt="screen shot 2016-06-08 at 12 25 02 pm" src="https://cloud.githubusercontent.com/assets/120403/15902045/09788b78-2d74-11e6-98d3-ef167bc2f8e8.png">

and the spec:
<img width="152" alt="screen shot 2016-06-08 at 12 25 24 pm" src="https://cloud.githubusercontent.com/assets/120403/15902058/17d90ac6-2d74-11e6-9396-22e7e55e106b.png">

We need to somehow draw these "holes" for booleans. Two possible approaches:
1. Create a "boolean shadow" block that just gets put into these blocks and is the right size and shape.
2. When a block has an input with the boolean check type, draw a hole for it like this. This could also be extended to other types if we would ever want that, but would be much more difficult to implement (would we add another path to the SVG??? In Blockly, these are holes, so they're part of the same path)

**Comment by tmickel** [comment]
The more I think about option 2, the more I actually like it. We can add an additional thing that gets pushed to in the render methods, something like svgShapes. And then add (x, y, shape, color, etc.) for each input that isn't occupied by a connected output block. That way we could even draw empty slots for string and number inputs. Not sure if this would ever be desirable, but it feels nice and general in a way that just sticking in a special-case shadow block for the boolean doesn't. Any thoughts, @rachel-fenichel?

**Comment by rachel-fenichel** [comment]
Special-case shadow block for the boolean would actually just be the same
as what you're doing for the string/number inputs, but with no listener for
clicks/no editor.

**Comment by tmickel** [comment]
True. Although I would love to _not_ do it that way. It would be great if we could just use styled <input/>s instead of drawing a special-case blocks for the string/number inputs...

**Comment by RoboErikG** [comment]
Adding a shape that gets drawn for empty inputs would be closer to existing Blockly and doesn't have the same model implications as a shadow block. ;)
