### ISSUE TITLE
Vertical text field editor to spec

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#379]
Finish implementing:
https://github.com/LLK/scratch-blocks/issues/146
and
https://github.com/LLK/scratch-blocks/issues/147

A couple of the issues:
- Turn off animated growth of editor and font size for vertical blocks. The growth should only happen in horizontal:
- Editor is in the wrong position for vertical blocks:

<img width="219" alt="screen shot 2016-06-08 at 12 32 08 pm" src="https://cloud.githubusercontent.com/assets/120403/15902268/1d6fd6a8-2d75-11e6-9786-0cdd3f1c41cd.png">

**Comment by mrjacobbloom** [comment]
I'm sure you're aware, but there's still a max width on the blocklyHtmlInput:
![](http://i.cubeupload.com/3tPnIw.png)

**Comment by tmickel** [comment]
Ah - I actually didn't notice that, thanks. I'll raise an issue for that.
