### ISSUE TITLE
Uncaught AssertionError: Failure: Shadow block cannot be a top-level block.

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#381]
To reproduce:
- Create a "repeat X times" block.
- Drag in an add block ("_ + _")
- Undo

Why does this happen in scratch-blocks, but not in Blockly? Could it have to do with insertion markers?

**Comment by tmickel** [comment]
Full stack trace:

> goog.debug.Error  @   error.js:38
> goog.asserts.AssertionError   @   asserts.js:62
> goog.asserts.fail @   asserts.js:179
> Blockly.Xml.domToWorkspace    @   xml.js:307
> Blockly.Events.Delete.run @   events.js:468
> Blockly.Workspace.undo    @   workspace.js:250
> Blockly.onKeyDown_    @   blockly.js:315

**Comment by tmickel** [comment]
Also, after the undo, if you drag the add block out of the repeat, the shadow block is gone :(

<img width="249" alt="screen shot 2016-06-08 at 12 49 21 pm" src="https://cloud.githubusercontent.com/assets/120403/15902734/7810807e-2d77-11e6-947d-e220f3ec23d5.png">

@rachel-fenichel

**Comment by tmickel** [comment]
I think it might be an upstream issue: https://github.com/google/blockly/issues/415

**Comment by NeilFraser** [comment]
Fixed in Blockly develop branch.

**Comment by tmickel** [comment]
Thanks @NeilFraser !
