### ISSUE TITLE
Strings should have a smaller minimum X

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#384]
They should fit in the block:
<img width="145" alt="screen shot 2016-06-08 at 6 00 19 pm" src="https://cloud.githubusercontent.com/assets/120403/15912522/ec0138c2-2da2-11e6-9151-bd8e454532fa.png">

**Comment by towerofnix** [comment]
Is it possible for the block width function to account for the wide string inputs?

(Though I do think that the inputs should probably be a bit smaller!)

**Comment by tmickel** [comment]
Yep - in this case, both the shadow block (where you type in the value) and the outer boolean block should (and do) grow to stretch to wider values. But, the calculation isn't quite right yet :) In this bug I meant that the default should be smaller, at least in the boolean comparator blocks.

**Comment by tmickel** [comment]
@carljbowman 

I think these are actually at the desired min:
<img width="246" alt="screen shot 2016-07-06 at 5 20 41 pm" src="https://cloud.githubusercontent.com/assets/120403/16634967/28f1f724-439e-11e6-8abd-8c4ada720c21.png">
<img width="138" alt="screen shot 2016-07-06 at 5 20 28 pm" src="https://cloud.githubusercontent.com/assets/120403/16634969/2c1f8c86-439e-11e6-955c-837c77d32f1f.png">
<img width="164" alt="screen shot 2016-07-06 at 4 51 37 pm" src="https://cloud.githubusercontent.com/assets/120403/16634970/2d63ab4a-439e-11e6-943b-fe0d963eb180.png">

...and we should address the boolean problem separately. Carl, if you disagree/want to spec a different min, feel free to reopen.
