### ISSUE TITLE
block_svg.js:1168 Uncaught insertionMarkerConnection still connected at the end of disconnectInsertionMarker

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#390]
Sprinkles seems to trigger this. Just logging the issue so we don't forget :)

**Comment by rachel-fenichel** [comment]
I haven't been able to get this to happen in the horizontal playground with sprinkles.  Are you only seeing it in the vertical playground?  If so, it may be related to the fact that there is no explicit code for dealing with value inputs with insertion markers at this point.

**Comment by tmickel** [comment]
This seems particularly to happen with value inputs that are unoccupied by a block.

For a consistent reproduction:
Drag a "_ and _" or any other boolean-type output block to the workspace.
Drag an "if-then" block (which currently has an empty boolean value input that has no visible rendering) over it. In the midst of the drag, the error occurs.

**Comment by tmickel** [comment]
However I'm pretty sure we don't want the "if" block to pick up the other block in this scenario anyway. Hmmm...

**Comment by tmickel** [comment]
See #404 for a helpful screenshot (thanks @Airhogs777)
