### ISSUE TITLE
Safari redownloads sounds every time they are played

### ISSUE THREAD

**Issue by as-com** [LLK/scratch-blocks#396]
1. Sprinkles
2. Right click -> Delete All

<img width="841" alt="screen shot 2016-06-10 at 5 22 04 pm" src="https://cloud.githubusercontent.com/assets/3819625/15979076/e268218e-2f2f-11e6-8cf7-53dafa0605a0.png">

**Comment by tmickel** [comment]
Yep, I'm also seeing this on the Blockly playground (https://blockly-demo.appspot.com/static/tests/playground.html).

@picklesrus This is a known problem, right? A Safari problem?

**Comment by picklesrus** [comment]
There were a couple of commits to upstream blockly try and mitigate some sound problems recently (006bb36b89ab3e9cd4aa3b0cf3143e0f8c4b0ae3 and 0242238a4457f776c2055d3e7101c750dd8a94c1),  but I'm not sure they have been pushed to the playground yet. They also probably won't resolve this?  Assigning to myself for further investigation.

**Comment by as-com** [comment]
I think using the Web Audio API would fix this issue (and make the sounds
play with less latency).

**Comment by tmickel** [comment]
Using Web Audio API by default might be a good idea, if we can make the implementation simple enough. Unfortunately it looks like no version of Internet Explorer supports it, so it would be good to have a fall-back to the current method.

**Comment by thisandagain** [comment]
Resolving in new audio engine. Tracking in https://github.com/llk/scratch-audio
