### ISSUE TITLE
Insertion marker eats boolean input

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-blocks#404]
Everything freezes, and you can't complete the drag
![](http://i.cubeupload.com/2woM0u.png)

Steps to reproduce:
1. drag a boolean block from the flyout into the workspace
2. drag a block with a boolean input over the boolean block

**Comment by tmickel** [comment]
Thanks for the report! I think this is a duplicate of https://github.com/LLK/scratch-blocks/issues/390
