### ISSUE TITLE
Text field editor lag

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#416]
(copied)

There's a weird "lag" between when a character is typed and when the block grows. In Scratch 2.0 this happens in the same frame, which is really nice. Blockly addresses the lag by adding a little bit of space after the typed characters (the field editor is slightly bigger than the text, and it grows after the space is filled in). I wonder how or if we could address the lag? Will raise a new bug for that.

**Comment by tmickel** [comment]
@picklesrus

**Comment by picklesrus** [comment]
Caveat: I looked at blockly, not scratch blocks. 

The the keypress events I looked at were coming in under the frame budget on my mac, but there is a call to getBBox on the <g> tag around the field.  We might be able to calculate that directly instead. 

I'll take a look at scratch blocks too.  I'm curious though - was it blowing past the frame budget on a laptop or was this noticed on mobile?

**Comment by tmickel** [comment]
On a laptop. Not sure if it's a perf issue or some weird visual effect with the ordering of when the block is resized vs. when the character shows up. Definitely compare scratch-blocks to scratch-flash, it's a notable difference I think :)

**Comment by picklesrus** [comment]
Ah, yeah, I just looked in scratch blocks.  That's no good. I think I might have fixed this inadvertently in blockly.  I got rid of the asyncResize function which was fired on a timer so I think it is happening immediately now. When I compare scratch-blocks to blockly playground there is a noticeable difference I think.

**Comment by picklesrus** [comment]
@tmickel How do you feel about the delay on https://blockly-demo.appspot.com/static/tests/playground.html.  Does it feel better than the scratch-blocks one? 

After looking again today I'm tempted to say it does but it isn't fixed yet. Maybe should keep this issue open, but look at it again after we merge in the latest blockly changes.  I did file a bug with details on what we're probably doing wrong in blockly: https://github.com/google/blockly/issues/437

**Comment by tmickel** [comment]
Can't tell if that delay feels better or not. I think something funny is still going on. I took a video and pulled some frames out. Here is the problem:

Field unfocused:
<img width="353" alt="screen shot 2016-06-16 at 12 44 34 pm" src="https://cloud.githubusercontent.com/assets/120403/16125135/3db91da6-33c0-11e6-839c-371a0651d662.png">

Field focused (text moves to the left, with space on the right):
<img width="362" alt="screen shot 2016-06-16 at 12 44 40 pm" src="https://cloud.githubusercontent.com/assets/120403/16125137/4547183e-33c0-11e6-8b8c-5d33b020ba06.png">

Character typed, step one (the text fills the open space):
<img width="356" alt="screen shot 2016-06-16 at 12 44 49 pm" src="https://cloud.githubusercontent.com/assets/120403/16125142/4eaae52c-33c0-11e6-9d01-695be802d90c.png">

Character typed, step two (the box expands to give more open space):
<img width="371" alt="screen shot 2016-06-16 at 12 44 54 pm" src="https://cloud.githubusercontent.com/assets/120403/16125149/5583da3e-33c0-11e6-99aa-cbb6ea999f87.png">

Second character typed, step one:
<img width="351" alt="screen shot 2016-06-16 at 12 44 59 pm" src="https://cloud.githubusercontent.com/assets/120403/16125161/6756d4a0-33c0-11e6-8ae5-70c0afade299.png">

Step two:
<img width="376" alt="screen shot 2016-06-16 at 12 45 03 pm" src="https://cloud.githubusercontent.com/assets/120403/16125164/6b32a6c6-33c0-11e6-9de3-451eca440db0.png">

**Comment by picklesrus** [comment]
Oh!  I now understand the code I was looking at much better.  Thanks!  I think blockly is handling the keypress and keyup events separately, adding the trailing space on the keyup. If we can fit it all in one frame (and I think we could), we could just process it all in the key press. I'm guessing we still might need to fix some of the inefficiencies from the timelines in google/blockly#437.

If all the resizing happened in one frame, would you want the trailing space?
Another slight behavior difference - scratch 2.0 doesn't have a width limit, but scratch-blocks (and blockly do)

**Comment by tmickel** [comment]
Oh interesting!! I didn't notice that those were corresponding to keypress vs. keyup.

At least in scratch-blocks, I think it would be visually preferable to do both on keypress, like in Scratch 2.0 and like this: https://jsfiddle.net/YZPmC/ ... definitely wouldn't want the trailing space. I don't think this needs to change in Blockly necessarily as there might be some reasoning for it?

The width limit is something we'd like to eliminate here. At least numbers, it requires #380 first. Otherwise, long numbers always get parsed into a float (1e+20) for example which resizes the block and therefore the editor.

**Comment by tmickel** [comment]
Interesting: https://stackoverflow.com/questions/10911047/keydown-event-new-value

**Comment by picklesrus** [comment]
Cool! I'm not 100% sure about the keypress & keyup thing, but I do see blockly doing things on both events and if I hold down a key and let it repeat, the block sizing feels much better. 

I commented out the binding of the [keyup listener in field_textinput.js](https://github.com/LLK/scratch-blocks/blob/develop/core/field_textinput.js#L155) to see what would happen.  It breaks a lot (good luck unfocusing)... but also gives a preview of what it feels like without that keyup event doing extra work and it is much closer to scratch 2.0 in speed feel.

**Comment by tmickel** [comment]
Believe this is fixed up to a usable extent - closing for now :)
