### ISSUE TITLE
Internet Explorer and Edge testing

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#421]
We need to define what version of IE we want to support (IE11? Unfortunately the rest of Scratch probably won't support less than that because of WebGL, WebWorkers, etc.) and start doing some testing for IE and Edge.

Up to this point we've pretty much neglected that. Blockly has very good compatibility, though, so hopefully we won't have too bad of a time.

cc: @jwzimmer @thisandagain

**Comment by rachel-fenichel** [comment]
@NeilFraser how far back is Blockly compatible?

**Comment by tmickel** [comment]
Neil says: Blockly has no IE8 compatibility (no SVG support), probable IE9 compatibility, and definite-yes IE10 compatibility.

My opinion is Scratch Blocks should probably aim for IE10 or IE11, given our other system constraints. But, we could likely also do IE9.

**Comment by thisandagain** [comment]
Given our use of WebGL for the rendering engine, our current usage statistics for Scratch 2.0, and our timeline my inclination is to target IE 11 or Edge 13:
http://caniuse.com/#search=webgl

![image](https://cloud.githubusercontent.com/assets/747641/16269731/82259e24-3861-11e6-98bc-3917b542a3a5.png)

**Comment by tmickel** [comment]
Yep. P.S. I recently stumbled upon this unfortunate fact:
http://caniuse.com/#feat=audio-api
