### ISSUE TITLE
Will the two grammars be compatible?

### ISSUE THREAD

**Issue by NoMod-Programming** [LLK/scratch-blocks#426]
By the looks of it, the two grammars (horizontal and vertical) will not be compatible. For example: in the vertical playground, drag a "when I receive" block out from the palette. Now export it to XML and load it in the horizontal playground. The block loads, but the arg seems to be broken, as there is no way to change the message. Now export it to XML again and load it back into the vertical playground. The block is broken and the arg is not saved to the XML. Will these two grammars ever be compatible with each other, or will they be separate?

**Comment by tmickel** [comment]
@thisandagain @carljbowman may be able to comment. My understanding is that we still haven't worked out just how compatible they will be.

One idea I've heard is a "one-way compatibility": projects created in the horizontal grammar would work in the vertical grammar, but projects in the vertical grammar might not be able to work with the horizontal...

To have a "two-way compatibility", a lot of design work would need to be done with how to deal with things like reporters, conditionals, etc.

**Comment by thisandagain** [comment]
At some point we will support compatibility from the horizontal grammar to the vertical grammar but we will not support conversion in the opposite direction.
