### ISSUE TITLE
Flyout appears to scroll too quickly on Firefox wheel event

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#433]
I remember something in the code about Firefox's events being 10x in magnitude of other browsers. Maybe this got lost on the flyout implementation of wheel?

**Comment by rachel-fenichel** [comment]
I think this one got fixed by an upstream change.

**Comment by tmickel** [comment]
It still scrolls noticeably faster for me in FF, so that it basically jumps from top of the flyout to bottom of the flyout in a couple of frames. To be precise, it's with the trackpad scroll on a macbook pro using Firefox 52. It does have the same behavior in upstream, so either it's broken everywhere or maybe that's "how it's suppose to be" or could just be my laptop :)

this is what I suspected was relevant: https://github.com/LLK/scratch-blocks/blob/fb51d1a0784e23f817b4588d1cf4c422646ffced/core/flyout_vertical.js#L321

Hope things are going well!!!

**Comment by rachel-fenichel** [comment]
Fixed here (as part of a PR) and upstream: https://github.com/google/blockly/pull/1324
