### ISSUE TITLE
Flipping operators in RTL

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#438]
See: https://github.com/google/blockly/blob/master/blocks/logic.js#L274

For example, when you have "5 < 10", in RTL, this must flip to "10 > 5".

If we use an icon for the LT/GT as Carl planned, then it's as simple as setting the flipRTL option on the ImageField. Otherwise, if we use text, we should do something like the above.

**Comment by thisandagain** [comment]
@RoboErikG reports that this may be resolved in upstream blockly.

**Comment by RoboErikG** [comment]
Also being tracked in https://github.com/google/blockly-android/issues/295

**Comment by chrisgarrity** [comment]
Marking this with compatibility as currently Scratch 2 does not switch the order of arguments. It also looks like in at least some RTL languages mathematical operations are still LTR (e.g. Hebrew)

**Comment by chrisgarrity** [comment]
I think we' may let this get handled by translators. With the new messages `%1 < %2`, the arguments are unique and can be reordered as needed. This will allow RTL language translators to make things look right. In hebrew, math operators are actually LTR even though the language is RTL.
