### ISSUE TITLE
Define compatibility matrix

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#440]
This cuts across all of the various components needed for Scratch 3.0, but I'm tracking here as to make the discussion open and because the blocks are furthest along:

We need to define the compatibility matrix for Scratch 3.0 in terms of browsers and operating systems / platforms. Couple items to consider:
- [x] Current usage analytics (and trends) for Scratch 2.0
- [x] Anticipated technology requirements for various aspects of 3.0
  - Blocks
  - Virtual Machine
  - Rendering Engine (WebGL)
  - Audio Engine (WebAudio)
  - etc.
- [x] Timeline for release

Related to #421 

/cc @tmickel @cwillisf @jwzimmer @kaschm

**Comment by cpseager** [comment]
It would also be fantastic if scratch-blocks also worked within Chrome **_apps_** out of the box.

Blockly is already 99% compatible, if I remember correctly the only main thing we had to do to run Blockly as a Chrome app was alter some of the incompatible dialogs (such as the 'Rename Var' dialog - which scratch-blocks probably isn't using anyway).

The main advantage of compiling to a Chrome app (in addition to running offline) is to allow immediate cross-platform (win/mac/linux/cros) access to real-life devices (such as WeDo etc.) via the chrome serial, HID and bluetooth/bluetoothLowEnergy APIs.

**Comment by jwzimmer-zz** [comment]
Re transition and support plans for 2.0, here's the compatibility matrix for the Scratch Website in its current state: 

![image](https://cloud.githubusercontent.com/assets/747641/16272607/6766f9f6-386c-11e6-93de-5168f3ab483c.png)

![image](https://cloud.githubusercontent.com/assets/747641/16272627/7f54aefa-386c-11e6-8c15-8d20ee0d7bc2.png)

![image](https://cloud.githubusercontent.com/assets/747641/16272630/83d94706-386c-11e6-9b62-d5b296355b92.png)

**Comment by thisandagain** [comment]
Expanding from wiki as that is not public:

![image](https://cloud.githubusercontent.com/assets/747641/16272607/6766f9f6-386c-11e6-93de-5168f3ab483c.png)

![image](https://cloud.githubusercontent.com/assets/747641/16272627/7f54aefa-386c-11e6-8c15-8d20ee0d7bc2.png)

![image](https://cloud.githubusercontent.com/assets/747641/16272630/83d94706-386c-11e6-9b62-d5b296355b92.png)

**Comment by thisandagain** [comment]
## Anticipated Technology Requirements

Technology requirements can be difficult to predict (the details are critically important), but based on current active development and ongoing design conversations the following technologies seem to be likely for inclusion in Scratch 3.0. The data listed here is based on `caniuse.com` with a cross-reference to Scratch usage (June 19th, 2016 to July 19th, 2016) pulled from Google Analytics. Based on these findings, the major limiting factor is our plans to use the [Web Audio API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Audio_API) which results in a complete loss of support for Microsoft Internet Explorer. That said, some [polyfills](https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#audio) do exist which we may want to evaluate. If we remove the dependency on the Web Audio API, our compatibility rate for existing Scratchers is greater than 96% based on the technologies listed here. With Web Audio our compatibility rate for drops substantially to 82.3%. This also doesn't take into account Scratch's rate of growth in regions outside of North America and Europe where use of Internet Explorer is more pronounced. 

#### WebGL

| IE | Edge | Chrome | Firefox | Safari | Android | iOS |
| --- | --- | --- | --- | --- | --- | --- |
| 11 | 13 | 29 | 46 | 9.1 | 5.0 | 9.2 |

```
Global:    87.35%
USA:       94.95%
Scratch:   96.72%
Reference: http://caniuse.com/#feat=webgl
```

#### Web Audio

| IE | Edge | Chrome | Firefox | Safari | Android | iOS |
| --- | --- | --- | --- | --- | --- | --- |
| - | 13 | 29 | 46 | 9.1 | 5.0 | 9.2 |

```
Global:    74.91%
USA:       84.5%
Scratch:   82.3%
Reference: http://caniuse.com/#feat=audio-api
```

#### Web Workers

| IE | Edge | Chrome | Firefox | Safari | Android | iOS |
| --- | --- | --- | --- | --- | --- | --- |
| 11 | 13 | 29 | 46 | 9.1 | 4.4 | 9.2 |

```
Global:    91.04%
USA:       97.02%
Scratch:   97.88%
Reference: http://caniuse.com/#feat=webworkers
```

#### High Resolution Time

| IE | Edge | Chrome | Firefox | Safari | Android | iOS |
| --- | --- | --- | --- | --- | --- | --- |
| 11 | 13 | 29 | 46 | 9.1 | 4.4 | 9.2 |

```
Global:    89.46%
USA:       94.66%
Scratch:   96.67%
Reference: http://caniuse.com/#feat=high-resolution-time
```

#### SVG

| IE | Edge | Chrome | Firefox | Safari | Android | iOS |
| --- | --- | --- | --- | --- | --- | --- |
| 11 | 13 | 29 | 46 | 9.1 | 4.3 | 9.2 |

```
Global:    97.25%
USA:       97.89%
Scratch:   98.69%
Reference: http://caniuse.com/#feat=svg
```

#### CSS3 3D Transforms

| IE | Edge | Chrome | Firefox | Safari | Android | iOS |
| --- | --- | --- | --- | --- | --- | --- |
| 10 | 13 | 29 | 46 | 9.1 | 4.3 | 9.2 |

```
Global:    91.72%
USA:       97.18%
Scratch:   97.85%
Reference: http://caniuse.com/#feat=transforms3d
```

## Usage Trends

#### Desktop

![image](https://cloud.githubusercontent.com/assets/747641/16958575/0da1e022-4daf-11e6-81f8-280136f835a3.png)

The largest browser by Scratch session volume is Chrome with roughly 59% of active Scratchers as of the past 30 days. Internet Explorer rounds out the next largest cohort at 16.3% (of which 85.2% are running IE 11). Importantly, Edge has a session share of 5.3% for the past 30 days. The is tremendous growth, as Edge's session share for the preceding 30 days was only 3.86%. This seems to track to global trends as Microsoft continues to push users towards Windows 10, though the [sustainability of this growth rate seems unclear](http://www.siliconbeat.com/2016/07/18/microsoft-says-wont-meet-timeline-1-billion-devices-goal/).

#### Tablet

![image](https://cloud.githubusercontent.com/assets/747641/16958563/013b7262-4daf-11e6-8622-add4466fe7ba.png)

Based on ScratchJr usage for the past 30 days, iOS accounts for nearly two thirds of active sessions. Of this, roughly 80% are running greater than or equal to iOS 9.2. In Android, our usage by operating system is much more fragmented with a large % of active sessions still using 4.4 and less than 5% using the latest Android operating system (6.0).

## Recommendations

#### Desktop

Based on our technology requirements it looks like we may need to leave behind Internet Explorer. This would certainly necessitate a transition plan and smooth long-term deprecation for Scratch 2.0 as it may be disruptive for nearly 20% of our active user base. That said, we should seriously investigate options for polyfilling the Web Audio APIs specific to Internet Explorer 11 which could greatly minimize the disruption (<4% of the active user base).

#### Tablet

Globally, more than 87% of iOS users are running 9.0 or greater. Based on this and the rate of adoption I recommend that we target iOS 9.2 which will give us access to the APIs we need and should have sufficient adoption by the time we are ready to release. For Android, version 4.4.X still has huge market share and this is less likely to shift dramatically over the next 12 to 24 months due to the dynamics of OS updates on the Android platform. Because of this, I recommend that we target Android 4.4.0 via the [Crosswalk](https://crosswalk-project.org/) runtime. This will increase the size of our APK, but provide the APIs we need for the project and normalize our target environment.

**Comment by thisandagain** [comment]
I'm going to leave this open for discussion / comment through the next iteration.

**Comment by PullJosh** [comment]
Would it be at all helpful if I were to test Scratch 3 on different browser/OS combos or is it easier for you (the Scratch Team) to just handle it yourselves?

**Comment by thisandagain** [comment]
@PullJosh It's a little early for that at this point, but it absolutely will be helpful as we get closer to release!

**Comment by tmickel** [comment]
It should be pretty helpful to have all this info in one place! Thanks @thisandagain.

Tablet recommendations sound good to me.

Given that the only thing we need to drop IE for is audio, maybe it would make sense to support IE 11 and consider a Web Audio API fallback, or dropping audio with a warning message in IE 11?

**Comment by thisandagain** [comment]
@tmickel Agreed. Looping in @ericrosenbaum to this thread as per discussions.

**Comment by RoboErikG** [comment]
Btw, is the plan to target all the Scratch components to the max of required versions or would you consider keeping scratch-blocks targeted to IE10 so it's compatible for anyone using Blockly?
