### ISSUE TITLE
Make SB2 -> Blockly XML tool

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#444]
Maybe this tool should live in the VM. For now, it would be really helpful to have a tool that reads an SB2 and turns it into Blockly XML. This will help us get a sense for how projects are going to look when loaded into scratch-blocks.

**Comment by thisandagain** [comment]
I think this should be within the VM

**Comment by tmickel** [comment]
If this should be within the VM, it seems like we should work out how the VM will create blocks, categories, etc., in scratch-blocks. Then it seems like we should do this before #443, then? since we'll otherwise be duplicating a lot of work.

**Comment by tmickel** [comment]
Moving to VM
