### ISSUE TITLE
workspace.horizontalLayout broken

### ISSUE THREAD

**Issue by mrjacobbloom** [LLK/scratch-blocks#453]
It always returns false now in the horizontal playground. I think it's because you switched to having the flyout on the left

**Comment by tmickel** [comment]
I'm not sure I understand. When you switch the layout to top/bottom, it looks to me like `workspace.horizontalLayout` is true. That property refers to whether the toolbox/flyout/palette is displayed horizontally, not whether the blocks are rendered horizontally - is that what you mean?

**Comment by tmickel** [comment]
<img width="756" alt="screen shot 2016-06-24 at 11 22 03 am" src="https://cloud.githubusercontent.com/assets/120403/16341995/e3bab208-39fd-11e6-8e80-ed0d81ad1079.png">

**Comment by mrjacobbloom** [comment]
Oh whoops, my mistake. Is there a way to check which grammar we're using?

**Comment by tmickel** [comment]
Hmm, I don't think there's a good way to check that from the outside right now. One "hack" way you could do it for now is checking properties that are defined in core/block_render_svg_horizontal.js but not core/block_render_svg_vertical.js.

E.g.,

`var isHorizontalRendering = typeof Blockly.BlockSvg.IMAGE_FIELD_WIDTH !== 'undefined';`

I warn you that this is pretty fragile, and any of these properties are subject to change at any time! Hope that helps.
