### ISSUE TITLE
Choose behavior of replacing blocks with compatible inputs

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#454]
As we talked about with Brian today.

Currently in Scratch 2.0, when you replace a block in that has a compatible input, it bumps out.

![jun-27-2016 23-15-09](https://cloud.githubusercontent.com/assets/120403/16402783/2abc72b0-3cbd-11e6-8f7a-8625d2810a9d.gif)

In scratch-blocks currently, it will usually bump out, except if there is exactly one compatible input, in which case it "accepts the input:"

![jun-27-2016 23-13-31](https://cloud.githubusercontent.com/assets/120403/16402787/2f89e8d6-3cbd-11e6-9967-d6ebf6a60e7b.gif)

We should likely either switch to Scratch 2.0 behavior, or go the full way with the second behavior, and accept it anytime there is at least one compatible input (e.g., replacing in <_ and _> could put the pre-existing predicate in the first input).

**Comment by towerofnix** [comment]
If you go with the second version, which I think I like (though it could use some extra things to get perfect, e.g. a context menu item "bump parent block out"), it would probably be good if the input of the NOT block was highlighted, as well as the AND block.

**Comment by rachel-fenichel** [comment]
The nice thing about the Blockly approach is that if it's ambiguous (multiple possible inputs) it unambiguously bumps away.

I favor always bumping over always accepting.

Agreed that if bumping remains, we should highlight the input on the dragging block that the other block will connect to.
