### ISSUE TITLE
Consider moving a block's output connection to dragging X?

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#456]
When you drag a block with an output, it can be unintuitive that the output connection is on the left of the block. Instead it could make sense to move the X of the output connection to where the dragging finger/mouse pointer is during the drag. This might be terrible to implement.

**Comment by tmickel** [comment]
After playing with it, seems intuitive to have it be at the center left/right to me.

**Comment by benjiwheeler** [comment]
I'm going to reopen this as a valid design question!

**Comment by cwillisf** [comment]
I'm closing this one as a duplicate (ish) of #1156. Usually, we'd leave the older issue open and close the newer one. In this case, though, the newer one provides more context, including screenshots. I'll update the title of the other issue to reflect the merge.
