### ISSUE TITLE
Minimal/text-only rendering and language translation

### ISSUE THREAD

**Issue by luxaritas** [LLK/scratch-blocks#457]
This of course has significant implications, but I figured I'd bring it up for discussion purposes.

The primary reason why I considered bringing this up is due to readability. While the graphical adjustments from Scratch 2 (removing texturing) do help, especially as c-blocks get nested the amount of color/graphics on the screen at one time can make readability hard. So, there's a couple things I thought might be interesting.
- Could there be a mode which simply removes the background coloring from blocks, and instead the text is colored (perhaps with parenthesis around arguments to clarify order precedence)?
- As an extension, maybe have a "wireframe" view mode, where the block backgrounds are removed, but in addition to or instead of colored text, there would be a colored border and/or only things like c-block "containers" (the long bars on the outside containing the other blocks, not sure what they would be called) would be rendered?
- Maybe even have a mode where there is no coloring at all, only text?
- If it goes that far, what about making this "text mode" able to be directly written, perhaps with tools like autocomplete?
- Perhaps do something like Alice, or the [Blockly demo](https://developers.google.com/blockly/#try-blockly) where you can translate the Scratch code into other languages (albeit simplified)?

I'm mentioning a lot of this out of curiosity. I have no idea to what extent this has been discussed internally, but I would be interested to hear about any design discussions you could share in relation to this.

**Comment by AnmAtAnm** [comment]
It should relatively trivial to implement a Blockly demo that renders block colors as transparent white or light grey unless the block is currently selected, somewhat similar to your wireframe mode or text only mode. The primary interactions will remain dragging blocks (though [Blind Blockly](https://github.com/google/blockly/tree/blind) is an example of alternative keyboard driven interaction).

Writing code directly is probably outside the realm of Blockly (and thus Scratch Blocks).  You might want to explore the code-to-blocks-and-back behavior of [Pencil Code](https://github.com/PencilCode/)

Tangentially related: Its probably worth pointing out that in the course of building Scratch Blocks, [Blockly](https://github.com/google/blockly) has decoupled much of [the rendering](https://github.com/google/blockly/blob/master/core/block_svg.js) from the rest of the code.  This should facilitate exploring these sorts of ideas.  This separation is even more true in [Blockly for Android](https://github.com/google/blockly-android), where the block rendering and layout is [a wholly separate Android library](https://github.com/google/blockly-android/tree/master/blocklylib-vertical).

**Comment by luxaritas** [comment]
I'm assuming you were referencing [this Pencil Code](https://github.com/PencilCode). I'll definitely want to take a look at that, thanks.

Could be an interesting external tool, which I might look into out of my own interest at some point.

**Comment by tmickel** [comment]
It looks like @Airhogs777 has implemented a user-style that already does basically this:
https://github.com/Airhogs777/sb3-theme/wiki/Themes-Library#plaintext-vertical-only

<img width="322" alt="screen shot 2016-07-26 at 12 53 57 pm" src="https://cloud.githubusercontent.com/assets/120403/17147264/10938778-5330-11e6-8bf0-7e5aed6f22a3.png">

I think we'd like to keep this type of major design changes to scratch-blocks mods and user-styles, and not bake them into the default experience. We'd like the default experience to be as consistent as possible for new users :)

So for now I'm going to close this!
