### ISSUE TITLE
Specialized Menu — Musical Note Picker

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#459]
Breaking out from [Design - Specialized field editors - Issue #149](https://github.com/LLK/scratch-blocks/issues/149)

For example, this will be used in places like 'play note (   ) for (   ) beats'
<img width="331" alt="screen shot 2016-06-29 at 9 24 55 am" src="https://cloud.githubusercontent.com/assets/3409578/16453607/671884be-3ddb-11e6-9ec9-0473de1ca204.png">

**Comment by tmickel** [comment]
Q: maybe it would make note picking much easier if you could hear the note on hover. Not sure about touch.

**Comment by rachel-fenichel** [comment]
On touch this will also just need to be bigger--at that point, maybe it pops up and doesn't close until you explicitly close it, which also lets you play notes to see what they sound like.

**Comment by rachel-fenichel** [comment]
*hear what they sound like

**Comment by carljbowman** [comment]
My thought was inline with @rachel-fenichel 's suggestion - the user could continue to touch keys until they find the one they would like to use and then tap away or confirm selection. Meanwhile the input would update the value with the most recent tapped note.

**Comment by towerofnix** [comment]
Pretty small enhancement, but would it be good if people could press a key to select a note from the menu?

**Comment by carljbowman** [comment]
## Round 1 - Note Picker
![r1_note-picker](https://cloud.githubusercontent.com/assets/3409578/25196049/68c4b16a-250d-11e7-9197-1010fe1ee099.png)

### Functionality
1. Click/Tap field on 'play note' block to gain focus of the field
2. Click/Tap on key to update the field. The last clicked/tapped key will occupy the field and remain highlighted in blue
3. User can navigate scales by using the arrows at the top of the menu
4. User can also type a value into the field rather than using the keyboard picker
5. Clicking/Tapping away to lose focus on the field will result in the picker closing

### Version Variation
Overall I lean towards Version 2.2, but wanted to include a few variations. 
- Single key width: we may need to dial this in further for touch environments.
- Full scale: @ericrosenbaum asked we explore a version with a full scale. 
- Key Labels: Including labels on the keys of C along with their numeric counter part
- Scale navigation style: There are two different versions here, but we could explore addtional styles if needed.

### Things to Consider
- @ericrosenbaum - At one point we were debating how to display the value in the field? Did you want to do something other than the numeric value?
- Responsive: Not sure if these is even technically feasible with in Blockly, but rather than making the menu have a fixed set of keys, we could imagine displaying as many keys as possible relative to the work size space. We would want a minimum size which could be 1 scale.

**Comment by RoboErikG** [comment]
How do you know which which key is which note? For example, how would I do e d# e d# e b d c a if I don't know what e sounds like?

**Comment by carljbowman** [comment]
@RoboErikG - Good question. @ericrosenbaum had some thoughts on how the field on the block might update to display this information in the field upon click/tap. 

Alternatively we could do something similar to Scratch 2.0 and display this info within the menu. If we go this route, I would suggest not relying on hover to display the info, but rather display last clicked/tapped.

**2.0 Hover Example**
![screen-shot-2017-04-20-at-11 32 52-am](https://cloud.githubusercontent.com/assets/3409578/25239242/78bce85c-25bd-11e7-90cd-a07e8d3d9ed3.png)

**Quick sketch**

<img width="316" alt="screen shot 2017-04-20 at 11 40 20 am" src="https://cloud.githubusercontent.com/assets/3409578/25239505/2dc4dc5a-25be-11e7-8167-492f9970aa85.png">

**Comment by rachel-fenichel** [comment]
I'm a fan of avoiding hover whenever possible.

**Comment by carljbowman** [comment]
### Sizing Spec
![r1_note-picker](https://user-images.githubusercontent.com/3409578/44346303-a4e52b80-a463-11e8-954d-ff2923ce13c2.png)
