### ISSUE TITLE
Page breaks with very long drop-downs

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#470]
<img width="979" alt="screen shot 2016-07-05 at 10 11 18 am" src="https://cloud.githubusercontent.com/assets/120403/16587492/d5a29408-4298-11e6-92a1-50544d1c17cb.png">

**Comment by rachel-fenichel** [comment]
Have you considered a different selector here?  The dropdown doesn't feel like the correct UI for this many items anyway.

**Comment by rachel-fenichel** [comment]
See also https://github.com/google/blockly/issues/289

**Comment by tmickel** [comment]
Possibly a better selector would be good. But, we probably need to fix this case anyway - e.g., if there are 100 variables...

**Comment by mrjacobbloom** [comment]
> we probably need to fix this case anyway - e.g., if there are 100 variables...

How about a searchable dropdown/combo-box?

**Comment by tmickel** [comment]
@Airhogs777 That's a great idea. I hope it makes it in eventually!

**Comment by tmickel** [comment]
Not a fun problem - even with size-limiting CSS, the drop-down pushes the page:
<img width="855" alt="screen shot 2016-07-07 at 1 39 51 pm" src="https://cloud.githubusercontent.com/assets/120403/16663002/56a0224a-4448-11e6-9fd3-82fd4832ad6c.png">
