### ISSUE TITLE
Separate empty input shapes from type checking system

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#471]
Currently when you don't occupy an input with a block, an input shape is drawn based on its type check (i.e. the "check" property on the input). But, there's a distinct possibility we might want to have these shaped differently from their type check (e.g., if we want a shape but no enforced type check). To support this, inputs should also have an associated outputShape just like blocks.

**Comment by mrjacobbloom** [comment]
Will that include substacks, or just inputs that take reporters?

**Comment by tmickel** [comment]
The shape of substacks comes from the fact that the input is a "statement input" - distinct from a "value input" (the type that takes reporters).

This is only about unoccupied value inputs:
<img width="218" alt="screen shot 2016-07-05 at 1 11 46 pm" src="https://cloud.githubusercontent.com/assets/120403/16593152/0c550152-42b2-11e6-9cbc-e0c29a63a0be.png">
That shape comes from the "check" property on the if's value input, but I'd like it to be a separate property.

**Comment by tmickel** [comment]
Actually, it looks like the need for this is not in the cards. Closing for now!
