### ISSUE TITLE
Disabled menu items have the same style as normal menu items

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#474]
In this picture, there's no way to distinguish between disabled menu items and enabled menu items:

![Menu](https://cloud.githubusercontent.com/assets/9948030/16589212/815c98de-42a8-11e6-8ed1-794a44e0bcc6.png)

The "clean up blocks" and "redo" options are disabled but you can't tell without hovering over them (they won't have a blue background fill like enabled menu items).

Perhaps disabled menu items should have a light grey background?

**Comment by tmickel** [comment]
Thanks for the report - we must have broken the CSS somewhere...

**Comment by PullJosh** [comment]
IMHO instead of a grey background it should be the text that becomes grey. That way it's very clearly _disabled_, as opposed to just being _different_.

**Comment by Tymewalk** [comment]
@PullJosh I agree with that. Probably a light grey background, too, so it can stand out...

**Comment by tmickel** [comment]
Fixed up with what there was previously (#ccc).
