### ISSUE TITLE
You can type v,a,c and x at a Number Field

### ISSUE THREAD

**Issue by ghost** [LLK/scratch-blocks#503]
Here's a image of the issue:
![bug](https://cloud.githubusercontent.com/assets/7559492/16702987/3f93fa42-4540-11e6-9cb6-a8c005805878.PNG)

**Comment by cpseager** [comment]
Same letters as caught here, firefox?

https://github.com/LLK/scratch-blocks/commit/0d91c15b310e983008ea9b07b9afbcf9d7b76a0f

**Comment by ghost** [comment]
No, i'm using chrome

**Comment by tmickel** [comment]
The problem seems to be a conflict between Chrome/WebKit's key codes and Firefox's. I'll make an exception.

**Comment by tmickel** [comment]
Actually - you will note that these are the letters for the special operations (ctrl-C, ctrl-A, ctrl-X, ctrl-V) as @cpseager notes...will investigate what to do with this...
