### ISSUE TITLE
The right click panel became empty after compressed

### ISSUE THREAD

**Issue by xmeow** [LLK/scratch-blocks#504]
Before compressed:
![image](https://cloud.githubusercontent.com/assets/3390845/16707738/ddc1fbb2-460b-11e6-9f9c-354062ca7f81.png)
After compressed:
![image](https://cloud.githubusercontent.com/assets/3390845/16707739/f6069cdc-460b-11e6-8ec7-7fe633c677c6.png)

What I do is use build.py in the directory, and change js include to

```
<script src="../blockly_compressed_vertical.js"></script>
<script src="../blocks_compressed.js"></script>
<script src="../blocks_compressed_vertical.js"></script>
```

Or I may make mistake?

**Comment by ghost** [comment]
I Think you made a mistake

**Comment by xmeow** [comment]
solved after include the language file.. ignore me

**Comment by tmickel** [comment]
@xmeow Thanks for this report! I was actually seeing the same problem with one of my demos, and didn't investigate what was going on. We should probably document the issue somewhere in our wiki.
