### ISSUE TITLE
Add math_integer block

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#509]
That has:
- no min
- int precision

For blocks like "go back _ layers"

**Comment by PullJosh** [comment]
Do you mean input? Or is this really going to be a block?

**Comment by tmickel** [comment]
Input - technically, our inputs in scratch-blocks are "shadow blocks" in Blockly terms. That means they're a default "block" that's rendered to look like an input, on top of which other blocks can be placed/inserted. A bit hard to explain :)

**Comment by PullJosh** [comment]
Ah, I see. I haven't been looking at the code much. ;)
