### ISSUE TITLE
Drop-down arrows have a black stroke

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#518]
<img width="84" alt="screen shot 2016-07-14 at 11 46 51 am" src="https://cloud.githubusercontent.com/assets/120403/16845960/b26b54a8-49b8-11e6-9934-8c9ec37c8d4a.png">

**Comment by mrjacobbloom** [comment]
My bad. The easiest fix would be to change the CSS to `border-color: inherit !important;`. The other option is to change the CSS for `arrowBottom` and `arrowTop` to also include the inherit keyword.

**Comment by tmickel** [comment]
I think the second is preferable :)
