### ISSUE TITLE
Spacing between fields

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#521]
We need a plan/spec for the distance between fields in a particular block.

**Comment by tmickel** [comment]
_Always_ use 2 grid units

**Comment by tmickel** [comment]
Resolved

**Comment by carljbowman** [comment]
Overviews all spacing

![r4 3_vert-block-sketches](https://cloud.githubusercontent.com/assets/3409578/17145365/d7dfcb38-5327-11e6-93b6-0a330a3b0d4c.png)
