### ISSUE TITLE
Sizing and shape of blocks with outputs (reporters)

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#522]
How should these blocks be sized? Currently, they look like this:
<img width="266" alt="screen shot 2016-07-14 at 3 24 28 pm" src="https://cloud.githubusercontent.com/assets/120403/16852700/1711db48-49d7-11e6-9ec0-93956b4824de.png">

**Comment by towerofnix** [comment]
My first thoughts are that the text is too low, and there isn't enough horizontal padding.

Here's the same blocks in Scratch 2.0, for comparison:

![Normal size](https://cloud.githubusercontent.com/assets/9948030/16896356/6e0fb226-4b67-11e6-880a-acdf8041147a.png)

![Scaled up](https://cloud.githubusercontent.com/assets/9948030/16896355/6c2c7a3e-4b67-11e6-9633-57dda8928ebd.png)

~~You can see that the text never goes (far) into the triangle/"cap" parts of the blocks, but inputs will:~~

Actually, text labels that are the first child of the block will always have a fixed amount of space between them and the edge of the block, but input fields don't have that rule:

![Showing "caps"](https://cloud.githubusercontent.com/assets/9948030/16896372/d81be950-4b67-11e6-95a3-8e146050e77d.png)

That's clearer with nested blocks:

![Showing the space between text and edge of block](https://cloud.githubusercontent.com/assets/9948030/16896390/88a61d54-4b68-11e6-8922-4c4dd140a577.png)

I like the way Scratch 2.0 renders it now - it feels like there's enough space for the text. Just adding a bit of horizontal padding to the Scratch 3.0 blocks should make it the same, from my observations.

**Comment by tmickel** [comment]
Resolved in latest

**Comment by carljbowman** [comment]
Resolved with V4.3

![r1_reporters-boolean-variable_size](https://cloud.githubusercontent.com/assets/3409578/17145309/afb6bc2a-5327-11e6-8966-1ee5581d5483.png)

![r4 3_vert-block-sketches](https://cloud.githubusercontent.com/assets/3409578/17145337/c0f792a2-5327-11e6-93e7-ff430c25c567.png)
