### ISSUE TITLE
Full color spec for vertical blocks

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#523]
Missing:
Pen secondary and tertiary.
Sensing secondary and tertiary.
Operators secondary and tertiary.
Data secondary and tertiary.
More secondary and tertiary (and complaints from community about red blocks).

**Comment by carljbowman** [comment]
![r2_vertical-colors](https://cloud.githubusercontent.com/assets/3409578/16879025/d17b4a50-4a7c-11e6-8340-a7bd2cd0b28e.png)

[R2_Vertical-Colors.pdf](https://github.com/LLK/scratch-blocks/files/366287/R2_Vertical-Colors.pdf)

**Comment by carljbowman** [comment]
Re: More Blocks Color - The 'Coral' is a temporary exploration into. Will need some further exploration the More Blocks experience. We could even explore a 'Gray' as a color for More Blocks.

**Comment by tmickel** [comment]
all set!
