### ISSUE TITLE
Design for reporter checkbox

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#524]
Currently, Rachel put in a red/blue switch:
<img width="28" alt="screen shot 2016-07-14 at 3 26 59 pm" src="https://cloud.githubusercontent.com/assets/120403/16852783/83479afa-49d7-11e6-82b9-9e4afefa0753.png">

**Comment by tmickel** [comment]
@carljbowman Maybe something like the teacher accounts registration would work? Note that we can't 
<img width="69" alt="screen shot 2016-10-11 at 4 54 22 pm" src="https://cloud.githubusercontent.com/assets/120403/19288292/6c3c4454-8fd3-11e6-8bb1-34271f471cba.png">
<img width="65" alt="screen shot 2016-10-11 at 4 54 11 pm" src="https://cloud.githubusercontent.com/assets/120403/19288293/6de4346a-8fd3-11e6-9951-2e7535b3c2b2.png">
I could make an SVG for each state.

**Comment by carljbowman** [comment]
We should use the same checkbox that we use in WWW (same example as @tmickel suggested within the Teacher Join Flow) in the GUI.

![r1 4_gui_checkboxes](https://cloud.githubusercontent.com/assets/3409578/22650506/7e74050e-ec4d-11e6-828b-595fc0093f73.png)
**Blocks are displayed at 60%**

<img width="245" alt="screen shot 2017-02-06 at 9 23 21 am" src="https://cloud.githubusercontent.com/assets/3409578/22650600/f14e2546-ec4d-11e6-8cde-3951f9856075.png">

<img width="296" alt="screen shot 2017-02-06 at 11 46 09 am" src="https://cloud.githubusercontent.com/assets/3409578/22656600/dfa5ded8-ec61-11e6-867a-76e983136bde.png">


**Assets**
[checkbox-svgs.zip](https://github.com/LLK/scratch-blocks/files/754855/checkbox-svgs.zip)

**Comment by PullJosh** [comment]
Wouldn't it be beneficial to have more states than a simple on/off? A hover state would be a nice addition, I think. Focused states shouldn't be too much of an issue in the Scratch editor, but should definitely be considered for use on webpages. (This would be useful when tabbing to certain inputs, for instance.)

**Comment by carljbowman** [comment]
@PullJosh - Sure thing. Good call. We have those checkbox states built out on Scratch-WWW, hoping to reuse what we can from those designs.

**Comment by mrjacobbloom** [comment]
Would it always be blue, or correspond to the color of the block is modifying? It's hard to tell in your design pic since it's modifying blocks that are already blue

**Comment by carljbowman** [comment]
@Airhogs777 - Just added another image to help clarify. The thought would be to use one color within the UI for active states, but you raise a great point about the blue. 

As we continue to rough in more in the UI we should explore more color options for these states.

**Comment by dekrain** [comment]
I'm wondering how do you doing these sketches. SVG or something else?

**Comment by Tymewalk** [comment]
@PullJosh I don't exactly know what you mean by "hover state".

I agree though, more states is definitely a possibility we should think about.

**Comment by towerofnix** [comment]
@Tymewalk A hover state means the state of something when you put your mouse cursor over it.

**Comment by Tymewalk** [comment]
@liam4 Oh, that. I thought it was some variable display state :sweat_smile: 

Maybe a lighter color of blue (enabled) and a white-ish color (disabled) for that?

**Comment by mrjacobbloom** [comment]
When I first read through this convo I thought we were talking about different states of the checkbox representing the different kinds of var watchers, which is a bad idea (I've never seen one button with >2 states read very well)
