### ISSUE TITLE
Final design for value reports

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#525]
We put in a basic implementation so it could start being used in the VM:

<img width="111" alt="screen shot 2016-07-14 at 3 28 20 pm" src="https://cloud.githubusercontent.com/assets/120403/16852842/c52daf0e-49d7-11e6-8f46-89adc851977b.png">

You can play with this as there's a widget in the playground.
This is a bug in case we want any final design.

**Comment by thisandagain** [comment]
Moving to September milestone.

**Comment by tmickel** [comment]
@carljbowman Did we decide not to do this? I'm pretty happy with the current design.

**Comment by carljbowman** [comment]
@tmickel - This seems fine for now. As we start to think more about the 'Monitor' UI. Closing for now.
