### ISSUE TITLE
Final block icon assets

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#526]
Currently in the vertical implementation we have the "forever" icon on loop C-blocks:
<img width="271" alt="screen shot 2016-07-14 at 3 30 29 pm" src="https://cloud.githubusercontent.com/assets/120403/16852880/f1e600aa-49d7-11e6-8a12-b042d764305f.png">

The motion blocks that traditionally have icons are iconless:
<img width="237" alt="screen shot 2016-07-14 at 3 31 11 pm" src="https://cloud.githubusercontent.com/assets/120403/16852903/09b85520-49d8-11e6-97cf-6c826297cafc.png">

If we want icons here or in other places, need to figure them out.

**Comment by tmickel** [comment]
Maybe the final icon for text drop-downs, too:
<img width="209" alt="screen shot 2016-07-14 at 3 33 51 pm" src="https://cloud.githubusercontent.com/assets/120403/16852980/67969012-49d8-11e6-8564-e45eb126a96a.png">

**Comment by tmickel** [comment]
And there was some desire to have these be icons, not text:
<img width="136" alt="screen shot 2016-07-14 at 3 35 34 pm" src="https://cloud.githubusercontent.com/assets/120403/16853028/a3d2058e-49d8-11e6-8a5a-02f54cb36e41.png">

**Comment by PullJosh** [comment]
What if drop-downs which allowed you to select sprites (like in the `go to` block) had little thumbnails of the sprite next to them to make it easier to find the sprite you're looking for?

**Comment by tmickel** [comment]
@PullJosh sounds like a really nice idea. Would you like to make a separate issue for it?

**Comment by tmickel** [comment]
Everything should be set now except all of these arrows:
<img width="190" alt="screen shot 2016-10-11 at 4 59 55 pm" src="https://cloud.githubusercontent.com/assets/120403/19288467/285a3baa-8fd4-11e6-86a1-0b0d71609d21.png">

**Comment by carljbowman** [comment]
## Overview
![r1_vert-icon-size-sketches](https://cloud.githubusercontent.com/assets/3409578/22756934/e2d9c414-ee16-11e6-892c-e476a427b88d.png)

## Sizing
- [ ] Update icon size from 4x4 grid units to 6x6 grid units
- [ ] Adjust vertical alignment to account for new size

### With Icon (400% scale)
<img width="1066" alt="screen shot 2017-02-08 at 4 00 10 pm" src="https://cloud.githubusercontent.com/assets/3409578/22757137/b07dbf60-ee17-11e6-900d-0ac60fe5759f.png">

### Without icon for reference (400% scale)
<img width="1052" alt="screen shot 2017-02-08 at 4 01 05 pm" src="https://cloud.githubusercontent.com/assets/3409578/22757165/d11a742a-ee17-11e6-87b1-22b6db7ed256.png">

## Assets
[vertical-icons.zip](https://github.com/LLK/scratch-blocks/files/762043/vertical-icons.zip)
