### ISSUE TITLE
Raw fields on blocks should draw rectangles

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#527]
Tweaks:
- No blocks should be able to be dropped into them.
- Shape of the drop-down should be square to indicate it can't be dropped into.
- Color of the drop-down should be the primary block color (not tertiary) to further indicate it can't be dropped into.

This should apply to the current set that can't be dropped into (e.g., stop _ block).

**Comment by rachel-fenichel** [comment]
Why does the stop __ block have a separate [control_stop_menu](https://github.com/LLK/scratch-blocks/blame/develop/blocks_vertical/control.js#L186) block as a connected input, instead of just having a dropdown in the definition of the block?

**Comment by tmickel** [comment]
We made the decision at some point to have "all inputs" be blocks, in case we want them to be dropped over. The outline/shape of the control_stop_menu block is drawn by the shadow block itself (not the drop-down). If we want to switch to having it as a dropdown in the definition of the block, I think we'd have to have the field draw the outline/shape, and have the shadow block not render in this case. One thing has to not render itself (the field or the block). I think it shouldn't be that hard to disable dragging blocks into the dropdown by setting the check to something nonsense (e.g., "dont_drop_here"). But thoughts welcome.

**Comment by rachel-fenichel** [comment]
> We made the decision at some point to have "all inputs" be blocks, in case we want them to be dropped over
> 
> Fix drop-downs that shouldn't be dropped into

If the dropdown shouldn't ever be dropped into, the case you originally designed for is no longer relevant.  Yes,it would be easy to set the check to nonsense--but I dont understand the objection to moving to a single block instead of multiple.

**Comment by tmickel** [comment]
Then should we have shadow blocks not render anything? we need to support both cases- dropdowns that can be dropped into, and those that don't.

**Comment by tmickel** [comment]
We hashed out a compromise offline:

> having the field deal with the outline when it's not in a shadow
> but letting the shadow block deal with it otherwise
