### ISSUE TITLE
Implementation of text-editing/dropdown combo

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#531]
Scratch 2.0:
<img width="173" alt="94d32b2e-2d6f-11e6-8536-974e7fb9de83" src="https://cloud.githubusercontent.com/assets/120403/16853453/626135a0-49da-11e6-824e-a9270b42769a.png">

I think best to implement this as an extension to field_textinput. Maybe we should separate out the functionality in field_dropdown so it can be shared between the two?

**Comment by rachel-fenichel** [comment]
Does that one get a dropdown or an angle picker?  Right now it seems to do
the correct thing: opens the angle picker, lets you edit the number
directly, and keeps the angle picker in sync with whatever you've typed.

**Comment by tmickel** [comment]
Correct - actually my mistake with the screenshot.
The relevant blocks are actually the ones with no angle, but a few options in addition to typing:
<img width="138" alt="screen shot 2016-07-14 at 4 01 36 pm" src="https://cloud.githubusercontent.com/assets/120403/16853853/48a9d782-49dc-11e6-835f-7f3ed8bb6fa2.png">
(other options include random, last, etc.)

**Comment by tmickel** [comment]
It's apparently tricky to draw an image as the drop-down icon. The width of the text drop-down field isn't calculated until the text is rendered; then the block is sized according to the calculated size of the field. `goog.style.getSize` returns 0 at the point the image needs to be positioned. Previously, for the text drop-down, the icon was just text, preventing the problem.
