### ISSUE TITLE
Behavior of text drop-downs after reaching maximum height

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#532]
What should this look like?

<img width="126" alt="screen shot 2016-07-14 at 3 47 11 pm" src="https://cloud.githubusercontent.com/assets/120403/16853504/8ea6134c-49da-11e6-81fe-f55f3076f291.png">

**Comment by towerofnix** [comment]
I was sure I made an issue on this somewhere..

My idea is basically like everything else on your computer - have a scrollbar, let it be draggable, and also allow the user to use their mouse scrollwheel to scroll. CSS overflow content (`overflow-y: scroll`) shouldn't make that too hard to implement (maybe?).

**Comment by tmickel** [comment]
Yep - sorry - this got broken out from a different issue where I think you mentioned that. Scrollbar and draggable are pretty much already implemented. Check out the latest (ignoring the check-mark which is broken in the wrong place), using the scrollwheel:
![scroll-menu](https://cloud.githubusercontent.com/assets/120403/16861595/246b1dca-4a10-11e6-8a93-54e2b14c9bd4.gif)

The scrollbar only shows up currently when scrolling actually occurs. In many browsers (at least mine) this is the behavior of `overflow: scroll` (not to always show the bars, as advertised). So to me it seems desirable to have an additional indication to show that "there's more content here."

**Comment by tmickel** [comment]
@carljbowman I'm happy with the scrolling mode, please feel free to reopen if you'd like changes!
