### ISSUE TITLE
Sometimes blocks seem to "push" the scroll wheel

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#543]
This is hard to reproduce. I've been able to get it to happen most reliably by doing sprinkles.

In Chrome, after doing Sprinkles, try to scroll with the mouse wheel to the upper left of the workspace. The workspace is always "pushed back" to the center, after a scroll completes. Also seems to happen in Safari.

**Comment by tmickel** [comment]
Seems to be basically happening because sprinkles/spaghetti/domToBlock don't update the workspace metrics, but the wheel handler was using those. Adding `workspace.resizeContents();` to the end of each of the playground methods seems to fix the problem. Not sure if that's the right solution, though. @picklesrus

**Comment by picklesrus** [comment]
That kind of makes sense except that the call to resize on https://github.com/LLK/scratch-blocks/blob/develop/core/xml.js#L362 should be doing that for you.

**Comment by tmickel** [comment]
Oh strange...hmmmm...

**Comment by tmickel** [comment]
Hmm, maybe:
https://github.com/LLK/scratch-blocks/blob/develop/core/xml.js#L306
happens after `domToBlock`. Could this be a problem?

**Comment by picklesrus** [comment]
Ah, yeah. Looks like moveBy didn't get merged properly from mainline.  It needs this line: https://github.com/google/blockly/blob/ab0e847f41c7758fe583e5f07a797aa6669f2384/core/block_svg.js#L349

**Comment by tmickel** [comment]
Oh neat! I will add that in, thanks! :)
