### ISSUE TITLE
Pen Size Limit?

### ISSUE THREAD

**Issue by PullJosh** [LLK/scratch-blocks#552]
_Does this belong in scratch-vm?_

In Scratch 2.0, pen size was limited to 255 due to a technical limitation of Flash (see [here](https://github.com/LLK/scratch-flash/blob/5cff62b909856b7d7b3d116a5dcc2b4f03de8482/src/scratch/ScratchSprite.as#L264)). This limit was not imposed in Scratch 1.4. Has any consideration been made as to whether this limit will remain in Scratch 3? The only real reason it could be desired is for backwards-compatibility. Is that reason enough to keep the limit?

**Comment by tmickel** [comment]
Hey @PullJosh!

I think this question is more for scratch-vm, yes.

But anyway. It looks like canvas doesn't have this same implementation. So, for Scratch 3 we will likely make the choice down the road based on both desired functionality and backwards compatibility.

Some questions I have in mind are:
- Is there a real use case for projects with lines > 255?
- What projects will break/change if we lift the limit? This might be hard to determine.

**Comment by PullJosh** [comment]
To answer the first question, I one wanted to recreate this gif in Scratch but could not due to the limit:
![dot inversion](https://d13yacurqjgara.cloudfront.net/users/583436/screenshots/1927104/dotinversion.gif)
It would also be good for things like aragio clones or outer space simulators, where you need to "zoom in" on pen-rendered circles.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#97
