### ISSUE TITLE
Text in horizontal fields not vertically aligned

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#555]
![block text alignment](https://cloud.githubusercontent.com/assets/632207/17514268/fa7fec58-5e31-11e6-848d-f901ddd927c5.png)
_before and after 3f3862a_

The text is closer to the bottom of the field after the change. Was this intentional?

**Comment by tmickel** [comment]
Hmmm, not intentional. Guess the fix for vertical alignment broke horizontal a bit.
