### ISSUE TITLE
Large spacing in horizontal toolboxes

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#556]
![block spacing](https://cloud.githubusercontent.com/assets/632207/17514492/3019123a-5e33-11e6-9df2-d43fe4c0444a.png)
_changes in horizontal spacing, old (top), new (bottom)_

Two commits have changed the horizontal spacing in the toolbox, 991dba0 and 6539a63. Were these changes intentional?

If so, is it possible to adjust this? Changing Flyout.prototype.MARGIN affects the spacing from the top/side as well.

**Comment by rachel-fenichel** [comment]
Yes, it's possible to add a new variable (Flyout.prototype.BLOCK_SPACING_X/Y?) to separate the margin and the inter-block spacing.  It looks like 6539a63 changed the margin from 8 to 12, leading to the noticeable change in size.

To make this change you would modify the isNan case on this line: https://github.com/LLK/scratch-blocks/blob/develop/core/flyout.js#L658

No, I don't recall any intent to move the blocks that far apart.

**Comment by tmickel** [comment]
@drigz looks to me like this is fixed?

**Comment by drigz** [comment]
It's now customizable by applications, so as long as you're happy with the default spacing being larger than before, this is fixed.
