### ISSUE TITLE
Invalid values like "...." allowed in math_positive_number

### ISSUE THREAD

**Issue by drigz** [LLK/scratch-blocks#560]
![image](https://cloud.githubusercontent.com/assets/632207/17548281/77b9bff0-5eeb-11e6-808f-64543cca48b7.png)

Is this intended behaviour?

It was introduced by 2fa746d, which disabled the old validators, which worked like this:

![validator](https://cloud.githubusercontent.com/assets/632207/17548385/f901e68c-5eeb-11e6-8ca9-b50df5e0ff1e.gif)
_before 2fa746d, the validators discarded the invalid value_

**Comment by tmickel** [comment]
@drigz No real intended behavior here. It matches Scratch 1.4/2.0, although clearly it's pretty meaningless when you type a number like "...." or ".-.-.-". I think we'd be happy to accept a change that makes it so you can only type one ".", and a "-" only at the beginning of a number, but this seems like it would require some substantial change.

**Comment by RoboErikG** [comment]
You'd still have the corner cases ".", "-", and "-.". It might be easier to just put the validator logic back in addition to the input restrictions.

**Comment by tmickel** [comment]
Don't see a real problem with having invalid values in there either, though.

**Comment by drigz** [comment]
For me, it means the code generator has to handle the case of invalid values and try to generate sensible code. For example, when we sent this to the tester we got bugs like "Pauses forever when sleep contains just '.'" because it was parsing as a NaN.

Would you accept a change with the old "discarding" behaviour for these values, was that UX intentionally dropped? If so, what behaviour would you expect when running a "sleep" with an invalid value?

**Comment by tmickel** [comment]
That UX was intentionally dropped because it was jarring to have your value change after you've typed it...I'd expect whatever's doing execution (or generation) to deal well with the invalid value; e.g., "sleep .... -> sleep 0"

**Comment by jeandrek** [comment]
> You'd still have the corner cases ".", "-", and "-.".

Isn't . the same as 0.0? In Scratch 1.x and 2.0 then .1 is the same as 0.1 and 1. is the same as 1.0

**Comment by drigz** [comment]
In most languages I'm aware of, "." is a syntax error, eg JS: https://repl.it/Clzf

However, there's no reason Scratch shouldn't be different, so I'm ok with this as intended behaviour.

**Comment by tmickel** [comment]
@drigz Did you figure out how to deal with this in the generators?

**Comment by RoboErikG** [comment]
Should Scratch Blocks allow the Blockly style validation as an option to support generators?
