### ISSUE TITLE
Chrome complains about `KeyboardEvent.keyIdentifier`

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#562]
> 'KeyboardEvent.keyIdentifier' is deprecated and will be removed in M53, around September 2016. See https://www.chromestatus.com/features/5316065118650368 for more details.

**Comment by tmickel** [comment]
seems like it might be something internal to Closure library

**Comment by tmickel** [comment]
also exists upstream - @NeilFraser.

To reproduce:
Select/click a block, then hit "control." (e.g., as if you're about to do CTRL-Z).

**Comment by rachel-fenichel** [comment]
I suspect that this will go away if you update closure.

**Comment by tmickel** [comment]
ah, ok - will re-open if still doing it after that!
