### ISSUE TITLE
Closing mobile keyboard when trying to enter text

### ISSUE THREAD

**Issue by scratchyone** [LLK/scratch-blocks#564]
When I try to enter text into a text input on mobile (tested with chrome on iOS) the keyboard closes immediately. I can't enter anything into text inputs.

**Comment by CatsAreFluffy** [comment]
This also sometimes happens a lot for the Wikia search box on Chrome (iOS 9).

**Comment by paulkaplan** [comment]
@BryceLTaylor I could use a hand reproducing this, I'm not exactly sure what is going on.

**Comment by scratchyone** [comment]
I think this is fixed... I just tested and I’m no longer having that issue.

**Comment by picklesrus** [comment]
@paulkaplan  This seems like the same issue as https://github.com/LLK/scratch-blocks/issues/1345?

If so, I can repro by opening up preview on chrome on Android and trying to change the value in any text block (e.g. the say block)

**Comment by scratchyone** [comment]
Huh... I think it's a duplicate. Should I reopen this or should we use that one instead? Not happening on chrome on iOS 11.

**Comment by paulkaplan** [comment]
@scratchyone sounds like it might be android only, we can track it over on that other issue.
