### ISSUE TITLE
"No variable selected" option in variable dropdown

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#572]
- [ ] option added to dropdown
- [ ] option automatically set when deleting a variable

**Comment by tmickel** [comment]
Btw, I'd guess we wouldn't actually want this option to be in the dropdown itself/selectable, if that makes sense.

**Comment by towerofnix** [comment]
If, for example, the "no variable selected" option literally has the value of `"NOT_SELECTED"`, if I try to set a variable called `NOT_SELECTED` what will happen? Nothing?

**Comment by CatsAreFluffy** [comment]
The current behavior is ok, except for the fact that it will prioritize local variables. Also deleting a variable and running a script using the variable is the only way to never generate a variable watcher.

**Comment by towerofnix** [comment]
> The current behavior is ok, except for the fact that it will prioritize local variables.

How is that good, or bad, or worse than anything else?

**Comment by CatsAreFluffy** [comment]
Well, you usually create a variable to immediately use it. As long as there are no local variables, or the newest is a local variable, then you an use it directly. However, if it's a global variable and there's a preexisting local variable, then the "set" and "change" and other blocks will show the local variable instead of the global variable, forcing you to use the dropdown.

**Comment by rachel-fenichel** [comment]
@liam4 raises a good point about disallowed names.  We can internationalize the "no variable selected" text, but then we also have to have a variable name that's not allowed that varies by language.

Another option could be to use the empty string for this, since that's not a legal variable name and since the variable value becomes 0 or the empty string when used.

**Comment by CatsAreFluffy** [comment]
> > The current behavior is ok, except for the fact that it will prioritize local variables.

> How is that good, or bad, or worse than anything else?

Convenience. When you create a variable, you usually use it immediately.

**Comment by Tymewalk** [comment]
> Another option could be to use the empty string for this, since that's not a legal variable name and since the variable value becomes 0 or the empty string when used.

@rachel-fenichel That sounds like a good idea. In addition, are there any special characters not allowed in variable names we could use? Is all whitespace allowed?
