### ISSUE TITLE
Drop radius changes

### ISSUE THREAD

**Issue by MegaApuTurkUltra** [LLK/scratch-blocks#577]
![scratch-3-drag-drop](https://cloud.githubusercontent.com/assets/8547938/17941737/a97149a6-6a02-11e6-8c1a-11290edb4ec1.gif)

The drop radius gets bigger as a block is pulled away. I'm not sure if this is by design, but I think drop radius should be constant. This happens for all types of blocks.

**Comment by tmickel** [comment]
We did it intentionally, here: https://github.com/LLK/scratch-blocks/commit/fa992e9f863df2c9b25bcfc140e6105cf41e26b0

To fix this bug: https://github.com/LLK/scratch-blocks/issues/290 (video in there).

There might be a way to fix that some other way. I think we need to consider reducing `SNAP_RADIUS` in general, too... @rachel-fenichel

**Comment by plastpappa** [comment]
> There might be a way to fix that some other way. I think we need to consider reducing DRAG_RADIUS in general, too... @rachel-fenichel  

Yes, I agree with this. I'm fine with the drop radius increasing as long as it's not by _that_ much. Might make it very annoying for greatly nested operators.  
EDIT: Perhaps also do it only for "pants" blocks, which seem to be the only type of block where this is a problem?

**Comment by MegaApuTurkUltra** [comment]
Also some way to disable snapping (eg shift-drag) would be helpful with such a large drop radius

**Comment by tmickel** [comment]
@MegaApuTurkUltra We're addressing this in #635 - give it another try sometime, please!
