### ISSUE TITLE
Direction input slot takes input while fading out

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#581]
Just move your mouse around where the direction input is while the input is closed. Kind of unexpected results!

**Comment by rachel-fenichel** [comment]
Input stays active until the fade-out is finished (and maybe an extra frame past that)--manifests as the jump from 90 to 105 in this gif after I've tapped the background to close the angle picker.
![73138e46-58ee-4364-8a28-d104ea56efe3](https://cloud.githubusercontent.com/assets/13686399/18145720/3d5b1c22-6f81-11e6-9e95-84b6d5905e4c.gif)

**Comment by towerofnix** [comment]
This is really more of a general issue - you can get the same general result from using a dropdown (though it's tricky, because you need to click twice during the close animation).

**Comment by paulkaplan** [comment]
The change to click+drag angle picker makes this no longer possible. Closing.
