### ISSUE TITLE
blocklyTreeRoot keeps focused after the toolbox is closed

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#582]
This is causing some weird results trying to deal with keyboard inputs in Scratch. It's nice that you can page through categories with the keyboard, but as soon as the flyout is closed, I'd expect it to release focus from keyboard events, or something. @rachel-fenichel Have you and @carljbowman  thought at all about how keyboard should work with the Scratch-style toolbox?

**Comment by rachel-fenichel** [comment]
Unless I explicitly add this back in, we lose this behaviour when we switch away from the closure tree anyway.

Carl and I have discussed this briefly.  So far the conclusion is that the toolbox should not handle keyboard events, since scratch needs to get keyboard inputs for games, etc.

**Comment by tmickel** [comment]
^ sounds good, thanks :)
