### ISSUE TITLE
"Stop" block needs to accept next connections on certain dropdown selection

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#592]
<img width="164" alt="screen shot 2016-09-12 at 2 32 14 pm" src="https://cloud.githubusercontent.com/assets/120403/18447785/243a5d2e-78f6-11e6-93e6-5bf77e249220.png">
Current render:
<img width="227" alt="screen shot 2016-09-12 at 2 32 53 pm" src="https://cloud.githubusercontent.com/assets/120403/18447787/26b52778-78f6-11e6-8fe0-2b5d997e38cf.png">

**Comment by tmickel** [comment]
@rachel-fenichel If you have any ideas about how to accomplish this, that would be great. Mutators???

**Comment by rachel-fenichel** [comment]
You don't need an explicit mutator, since it should change when they select
a different item from the dropdown.  See
https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus#change_handler

**Comment by tmickel** [comment]
Hmm, cool, thanks!
- This means we can't define the block in JSON, right? Because we need to attach a custom validator to the dropdown.
- "Change handlers on fields are not called when a block is instantiated from XML (created, loaded, duplicated)." - why not, actually? This makes it sound like we'll need `mutationToDom`/`domToMutation` for saving/loading the block. And generating the `<mutation>` in the VM?
- Relatedly, this block seems like it's going to be gross:
  <img width="163" alt="screen shot 2016-09-13 at 12 28 30 pm" src="https://cloud.githubusercontent.com/assets/120403/18482308/9d709ab6-79ad-11e6-874a-e6d4e0a631ec.png">
  The second dropdown is a shadow block, but changing its value in the UI could possibly change the options of the first dropdown. Hmmmmm...

**Comment by rachel-fenichel** [comment]
1 and 3: correct.

2: Not sure, but I can look into it.
