### ISSUE TITLE
Input shapes likely need to add some width during rendering

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#596]
<img width="259" alt="screen shot 2016-09-15 at 3 39 42 pm" src="https://cloud.githubusercontent.com/assets/120403/18564690/ac55d574-7b5a-11e6-9d57-4844aeeca2d9.png">

**Comment by rachel-fenichel** [comment]
Is this procedure-specific?

**Comment by tmickel** [comment]
It might be "square-type input" specific, even. We don't have any of these in the blocks other than boolean-type. Ofc, these probably shouldn't appear in the final implementation of procedures, either.

**Comment by tmickel** [comment]
fixed in #651
