### ISSUE TITLE
Lists color

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#600]
In Scratch 1.4 and 2.0, list blocks are a different color from variables. In the current spec they are all the same color. Is that wanted?

**Comment by towerofnix** [comment]
IMO they're totally different data types and should have different colors to reflect this.

**Comment by jeandrek** [comment]
@liam4 I agree that they should have different colours, but I don't think variables are data types. Text strings and numbers are data types.

How about having "variables" and "lists" as categories in the palette?

**Comment by towerofnix** [comment]
Yeah, they're rather different data _containers_, not types, oops!

> How about having "variables" and "lists" as categories in the palette?

But then we'd need another category, because nine categories is.. a sad number. :P

edit: actually, _eleven_ categories! Wow.

**Comment by carljbowman** [comment]
Updated the blocks color spec to include a Lists color among the Data Category

![r3_vertical-colors](https://cloud.githubusercontent.com/assets/3409578/21144386/70d41c78-c118-11e6-9cd4-2ffff8e58e58.png)

<img width="413" alt="data colors" src="https://cloud.githubusercontent.com/assets/3409578/21144392/734bc906-c118-11e6-93a3-4c46b721f3a3.png">

### Data - Vars
Primary: `#FF8C1A`
Secondary: `#FF8000 `
Tertiary: `#DB6E00 `

### Data - Lists
Primary: `#FF661A `
Secondary: `#FF5500 `
Tertiary: `#E64D00 `

**Comment by thisandagain** [comment]
Looks great. Thanks @carljbowman

**Comment by mrjacobbloom** [comment]
Whenever this is implemented, remember to update `Blockly.Categories` in [core/constants.js](https://github.com/LLK/scratch-blocks/blob/d7745b12fdb5ee9a4761b7e99fd201673e0e7a8e/core/constants.js#L252) so that lists can be styled separately from variable blocks with CSS

**Comment by thisandagain** [comment]
Tracking implementation in https://github.com/LLK/scratch-blocks/issues/1257
