### ISSUE TITLE
Rename blocks_vertical/more.js

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#603]
procedures.js? functions.js? custom-blocks.js?

**Comment by ed-cooper** [comment]
custom-blocks.js - that way you know that it is definitely about blocks

eg. functions.js could just look like a file containing a few general useful functions

**Comment by rachel-fenichel** [comment]
It's in blocks_vertical, so it doesn't need "blocks" in the name.

**Comment by tmickel** [comment]
Went with procedures.js for consistency with Blockly, for now.
