### ISSUE TITLE
UI issues with procedure blocks

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#605]
Here's Some Issues I Found With The UI in procedure blocks/custom blocks
- [ ] Need Space Between Blocks In Block Palate
- [ ] Input Block Is Offset From Curser
- [ ] No Background For Warning About Standalone report block Needing To Be Used In a custom block definition
- [ ] Needs Proper UI for input Selection
- [ ] Gear And Warning Triangles should be maybe should be the same color as the blocks
- [ ] Use Define Instead of to
- [x] Bottom of define with report is longer than top

**Comment by tmickel** [comment]
Thanks for this write-up - that should be helpful! Just to keep these all in the same place, I'm going to move your post to #607.
