### ISSUE TITLE
Procedure blocks connection/insertion marker issue

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#610]
From @dekrain:
`blockly_compressed_vertical.js:1262 Uncaught TypeError: Cannot read property 'sourceBlock_' of null`

Appears to happen with the "define and report" block. Something about it is causing it to make strange connections when dragged over existing stacks:
<img width="240" alt="screen shot 2016-09-18 at 12 15 20 pm" src="https://cloud.githubusercontent.com/assets/120403/18617257/9d09c3a0-7d99-11e6-98d5-8f239dab03aa.png">

@rachel-fenichel I'm assigning you as an FYI - obviously this is not high priority :)

**Comment by rachel-fenichel** [comment]
I noticed this as well over the weekend.

Here's what I emailed to myself about it:
Insertion markers break on C-shaped blocks with hats.

Relevant code in block_svg.js:

```
  // Inside of a C-block, first statement connection.
  else if (Blockly.insertionMarkerConnection_.type == Blockly.NEXT_STATEMENT &&
      Blockly.insertionMarkerConnection_ !=
      Blockly.insertionMarker_.nextConnection) {
    var innerConnection = Blockly.insertionMarkerConnection_.targetConnection;
    innerConnection.sourceBlock_.unplug(false);
    var previousBlockNextConnection =
        Blockly.insertionMarker_.previousConnection.targetConnection;   <-------------
    Blockly.insertionMarker_.unplug(true);
    if (previousBlockNextConnection) {
      previousBlockNextConnection.connect(innerConnection);
    }
  }
```

Blockly.insertionMarker_.previousConnection is null.

The procedure blocks are the first blocks where we've had both a C-shape and a hat.

**Comment by tmickel** [comment]
Hmmmm yeah. I guess when `previousConnection` is null, we need to either not connect (e.g., like in the screenshot case) if the top of the stack is a hat or it needs to snap to the top of the stack, or something...

**Comment by CosmicWebServices** [comment]
Yeah I got a problem because of this in https://github.com/LLK/scratch-vm/issues/245
