### ISSUE TITLE
Close dropdown menus on workspace clear

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#611]
Noticeable in scratch-vm when you switch sprites with a dropdown menu open.

**Comment by tmickel** [comment]
Also the WidgetDiv needs to "close without animation"  - currently it animates out.

**Comment by tmickel** [comment]
In fact I think this should be on field disposal.

**Comment by rachel-fenichel** [comment]
Is there a reason to do it on field disposal?  Can you enumerate when we'll need to close dropdown menus?

Workspace clear
(maybe) undo/redo?
delete block stack--but right-clicking should have closed it anyway.

Trying to avoid slowing down operations where we may be disposing of a lot of blocks (such as clear).  This may be premature optimization.

**Comment by tmickel** [comment]
Just seemed to make sense given the existing model - `workspace.clear` is not a method on WorkspaceSvg, but it's on Workspace (and just calls all the block disposal methods, which in turn call field disposal...)
