### ISSUE TITLE
Custom Blocks are hard to read.

### ISSUE THREAD

**Issue by CosmicWebServices** [LLK/scratch-blocks#631]
![image](https://cloud.githubusercontent.com/assets/10731781/18887337/9df51f9c-84c1-11e6-9eb6-d884cac3ffbe.png)

The define part is hard to read because of the color of the text.

[I do not know if this should be in VM or here because I got that image in VM]

**Comment by tmickel** [comment]
We're tracking issues related to design of custom blocks in #607 - would you mind moving this there? Thanks!

**Comment by CosmicWebServices** [comment]
Whoops sorry about that!

**Comment by tmickel** [comment]
Thanks!
