### ISSUE TITLE
Statement inputs don't calculate their width

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#637]
Try this XML:
http://pastebin.com/LZJZNmhG

It won't let you scroll right?

@rachel-fenichel @picklesrus

**Comment by tmickel** [comment]
As soon as you pull the blocks out of the input, the workspace is sized correctly.

**Comment by towerofnix** [comment]
And note putting the blocks back into the input brings the issue back, so it's clearly not calculating the width of the point-in-direction block when it contains such a huge operator.

<sup>The fact that I can drag the huge block without lagging _at all_ really shows how great Scratch 3 is.....</sup>

**Comment by rachel-fenichel** [comment]
Looks like the forever block doesn't calculate the width of its contents, not that it's a problem with the point-in-direction block.  True for other statement inputs as well.

**Comment by tmickel** [comment]
Good catch - didn't realize it works fine outside the statement!
