### ISSUE TITLE
Scrolling is basically broken

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#639]
I'm not sure how to explain.. but it's really, _really_ obvious that it isn't working, when you try.

Sorry for the vague issue.

The same issue is on Firefox Nightly 52 and Chrome 53. On OS X 10.11.6.

Both Y and X scrolling are broken in general. They always want to scroll down/left. Even when you scroll down or up on your mousewheel, it'll pan left a bit (and if you don't scroll enough, down).

**Comment by rachel-fenichel** [comment]
That's exciting!

Exposed on https://llk.github.io/scratch-vm/

I'm only seeing it for x-scrolling.  Mousewheeling up/down makes the workspace slowly scroll left.  Dragging is fine.

**Comment by rachel-fenichel** [comment]
And just to make it worse, this goes away in chrome if I open the console.

**Comment by picklesrus** [comment]
Actually, that's a clue! Opening the console triggers a window resize. Dragging to resize the window fixes it too (on https://llk.github.io/scratch-vm/ at least)

Looks like there's something wrong with the initial setup. Maybe the underlying div size is being altered without calling Blockly.svgResize(workspace) when loading the page?  Is it broken on the playground too?

**Comment by towerofnix** [comment]
> And just to make it worse, this goes away in chrome if I open the console.

Oh, I noticed that it did fix itself at one point.. but I wasn't sure why, glad we know now!

**Comment by tmickel** [comment]
For the curious, we think we figured it out: https://github.com/LLK/scratch-blocks/blob/6edc1b4ba0992a4d61b663a86285f67f051169d5/core/block_svg.js#L448 needs to be moved out of the `if`. Thanks for the report, @liam4!
