### ISSUE TITLE
Let "fields" in procedures tab be real fields

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-blocks#665]
For now, It's only fields for reporters, inputs.

**Comment by tmickel** [comment]
Can you describe a bit more what you mean by this?

**Comment by dekrain** [comment]
For example, report block hasn't got a field. Value can only be a reporter.
![pseudo-fields](https://cloud.githubusercontent.com/assets/19158291/19125062/f11e2838-8b35-11e6-9a20-d5f3a7f10e6f.png)

**Comment by tmickel** [comment]
I see, thanks! Yeah we need to fix that so that procedures generate the relevant shadow blocks at some point. Since we're tracking issues related at #607, I'll move this there!
