### ISSUE TITLE
Allow clicking on blocks in the block palette

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#666]
A useful feature of previous Scratch palettes is the ability to quickly use a block from the block palette.

For example, hiding or showing a sprite, in Scratch 2.0:
1. Click on "looks" category
2. Click on "show" or "hide" blocks

In Scratch 3.0:
1. Click on "looks" category
2. Click (and/or drag) out the "show" or "hide" block
3. Click on the block you dragged out
4. Drag blocks back into palette

For this to be implemented, there'd probably need to be some kind of drag threshold where a block isn't considered to be being dragged until the mouse has moved that many pixels - though that looks to already be implemented with blocks in the workspace anyways. (As it is now, palette [source?] blocks are considered to be being dragged as soon as you mouse-down on them.)

**Comment by rachel-fenichel** [comment]
Yup, this is on the road map.  I'm currently working on the scratch-style palette, with the always open block menu stacked below the category menu.  The threshold for dragging/not dragging a block is already implemented for always-open block menus, just not for ones that auto-close.

**Comment by tmickel** [comment]
I think at this point it's entirely a Scratch VM bug: https://github.com/LLK/scratch-vm/issues/90

If you turn on flyout listeners in the vertical playground, you can see that click events are coming from block palette blocks already. It's a matter of receiving those events and then running the blocks.
