### ISSUE TITLE
You can select lists with variable blocks and variables with list blocks

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#671]
The Title Explains It

**Comment by dekrain** [comment]
So I creating request for use mutations instead of fields

**Comment by jeandrek** [comment]
...Why is there a "feature" tag?

**Comment by TheBrokenRail** [comment]
I don't know It is clearly a bug

**Comment by TheBrokenRail** [comment]
@tmickel Thanks for fixing the tag!

**Comment by paulkaplan** [comment]
Closed by typed variables work.
