### ISSUE TITLE
Warning: Work in Progress

### ISSUE THREAD

**Issue by yonghuming** [LLK/scratch-blocks#673]
[http://langxm.cn/scratch-blocks/tests/vertical_playground.html](my scratch blocks copy)
when i vist my web vertical_playground.html, it warns me that msg "vertical_playground"

**Comment by dekrain** [comment]
B/c it is WiP

**Comment by yonghuming** [comment]
@dekrain thank you very much but i could not undersand you meanings,
is it a bug ? 
if i vist [http://langxm.cn/scratch-blocks/tests/horizontal_playground.html](horizontal_playground)i did not get that msg

**Comment by dekrain** [comment]
That link doesn't work

**Comment by dekrain** [comment]
Did you downloaded archive of this repo by Github? If yes, delete this and use `git clone git@github.com/llk/scratch-blocks`

**Comment by tmickel** [comment]
"Warning: Work in Progress" is an intentional notice that the implementation/design in scratch-blocks is incomplete. We're still actively working on a lot of large decisions, so we are likely to have many breaking changes in the future.

**Comment by yonghuming** [comment]
@dekrain i am sorry i have removed it last night and i have use `git clone git@github.com/llk/scratch-blocks` and then go to `tests/horizontal_playground.html`,but it does not work

**Comment by yonghuming** [comment]
@tmickel got it i just say scratch-blocks is incomplete,there is no problem with my projects
