### ISSUE TITLE
[Q] How to build

### ISSUE THREAD

**Issue by dekrain** [LLK/scratch-blocks#676]
I want to test minor changes for Scratch Blocks in Scratch VM. When I use `build.py`, it generates some scripts for me, but not in `dest/`. Scratch VM requires `dest/vertical.js`, but it doesn't change.

**Comment by rschamp** [comment]
Sorry, we made some changes when we started publishing to npm.  For now, you want to use `npm run prepublish` to get the files that scratch-vm needs.

I'll make building less obtuse and document this.

**Comment by dekrain** [comment]
Thanks.

**Comment by dekrain** [comment]
For now, I testing it on experimental playground. I'm working on shadows in procedures
