### ISSUE TITLE
Block visibility depending on target

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#682]
Basically a fancy way for saying:
- Motion blocks should not be visible at all in the stage - in Scratch 2.0, the blocks-part of the palette is actually replaced with text ("Stage selected: no motion blocks").
- "When I start as a clone" and "delete this clone" should not be visible in the stage.
- Many looks blocks shouldn't be visible in the stage, I won't bother making a list.
- "(color) Touching (color/sprite)" and "distance-to", should not be visible in the stage.
- The only pen block in the stage that should be visible is "clear".
- ~~"When this sprite clicked" should be "When Stage clicked" in the Stage. (#634)~~ (better to keep this issue only for block visibility)

Also -- in Scratch 2.0, "switch backdrop and wait" isn't visible when a non-stage is selected, but that doesn't make much sense to me. Though it's something to note.

@(managers), may be handy to have this as a task list instead of a generic list..

edit: sorry if any of this has been brought up before, I don't think any of these have specific issues though.

**Comment by tmickel** [comment]
agreed, thanks for the write-up! This was one of the sub-issues we discussed in #541, but seems significant enough to me to give it space here.

**Comment by rachel-fenichel** [comment]
This will be implemented with 
https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_svg.js#L1883

See google/blockly variables and procedure categories for examples:
https://github.com/google/blockly/blob/develop/core/workspace_svg.js#L93
https://github.com/google/blockly/blob/develop/core/variables.js#L99

**Comment by jwzimmer-zz** [comment]
During the Catch Game internal playtest (6/2/17), Shruti reported:
> In the backdrops, instead of the block 'When Stage Clicked', there is 'When this sprite clicked', but it works when you click on the backdrop.

In 2.0, the block shows up as When Stage Clicked, but in 3.0, it will still say "sprite". (It does seem to work, though.)
