### ISSUE TITLE
Blockly.JavaScript.workspaceToCode is missing

### ISSUE THREAD

**Issue by mishoboss** [LLK/scratch-blocks#683]
How to generate JavaScript code from Scratch? I see that toCode() function in tests doesn't work, and there is no `Blockly.JavaScript.workspaceToCode` object.

**Comment by dekrain** [comment]
This isn't clear blockly. This is Scratch 3.0 block runtime. It can't generate JS code.

**Comment by mishoboss** [comment]
I see. What it can generate?

**Comment by dekrain** [comment]
Look at Scratch VM playground: https://github.com/LLK/scratch-vm and http://llk.github.io/scratch-vm

**Comment by tmickel** [comment]
We aren't supporting Blockly code generators right now, because they would likely be a large amount of work to maintain and we only have so much time! Our focus for scratch-blocks is generating events and data structures that can be consumed by a Scratch interpreter. But I have heard rumors that if you're brave and copy the Blockly generator code into scratch-blocks, it might not be too hard to get working...

**Comment by mishoboss** [comment]
Actually scratch-vm may be the exact thing I need. I'm doing kinda rules engine, so I just need to define some logic and execute it. I don't need explicitly JS code.

**Comment by mishoboss** [comment]
Is there any example how to run code in scratch-vm separately from the visual workspace? Example in https://github.com/LLK/scratch-vm presumes workspace there, right?

**Comment by dekrain** [comment]
No, you must load `/src/blocks/*` for working

**Comment by dekrain** [comment]
But you can open issue on scratch VM repo

**Comment by tmickel** [comment]
@mishoboss You shouldn't need the visual workspace to run code. But, you need to find some way to load blocks into the VM if you don't have the visual workspace. One way that is currently possible is to import an SB2.

**Comment by mishoboss** [comment]
Please excuse me, but I'm not sure I fully understand what you mean. SB2 = Scratch Blocks 2? What to do with it?

Here's in short the whole stuff - I need to store the blocks as XML and then load it somehow into a node.js server that executes the logic. I already made it saving as string into a DB, then loading this XML string into the visual workspace and blocks are rendered nicely. So far it's awesome. Now, how can I load this same XML string into the scratch-vm that is on node.js and execute the logic server-side?

**Comment by dekrain** [comment]
SB2 is format for Scratch 2.0

**Comment by dekrain** [comment]
And node program **doesn't** execute the logic. it's only server that "translates" code to browser-specific format, just like this:

``` javascript
var a = require('./a.js') // module.exports = 'Hello, '
var b = require('./b.js') // module.exports = 'world.'
console.log(a + b);
```

to:

``` javascript
(function(...){
...
})([
function(...) {
var a = _webpack_require_(1);
...
], function(/* module */...){
module.exports = 'Hello, '
}/*, ...*/ ])
```

**Comment by tmickel** [comment]
@mishoboss We currently don't have infrastructure for loading XML into the VM. The only things the VM can load right now are SB2-format JSON projects (created by Scratch 2.0) and events generated by scratch-blocks.

**Comment by tmickel** [comment]
You could try to do this by emulating an event. Check out the CREATE events generated by scratch-blocks, which contain an XML block string that the VM knows how to process. But overall I can't recommend this approach.

**Comment by mishoboss** [comment]
OK, seems I'm totally lost now :( Here is what I understood so far:
- SB2 is a JSON format used by Scratch 2.0
- scratch-vm consumes only SB2
- scratch-blocks can't export SB2, but only XML
- I have no idea what are these "CREATE events generated by scratch-blocks" :(

Where can I read more about the whole picture of import/export/execute?

**Comment by dekrain** [comment]
In `scratch-vm/src/engine/execute.js`. [Here](https://github.com/LLK/scratch-vm/blob/develop/src/engine/execute.js).

**Comment by mishoboss** [comment]
No docs?

**Comment by dekrain** [comment]
You can read [Wiki](https://github.com/LLK/scratch-vm/wiki) and some JSDocs in some scripts.

**Comment by tmickel** [comment]
To add to the confusion, here is some documentation about the events generated by scratch-blocks: https://developers.google.com/blockly/guides/configure/web/events

The current flow for import/export/execute looks like this:
- scratch-vm loads SB2 into a block representation.
- scratch-vm pushes data to scratch-blocks.
- When blocks change in scratch-blocks from UI actions, scratch-blocks tells VM to update its block representation.
- scratch-vm executes the blocks.

There is no export. The XML export that scratch-blocks can do can't be readily consumed by the VM, except the same format _is_ used to process the UI actions (events) from step 3 above.

Here is the handler in scratch-vm for scratch-blocks events:
https://github.com/LLK/scratch-vm/blob/develop/src/engine/blocks.js

I'm sorry but this project is under heavy development (it's existed for only a few months now), so we don't support your use case and probably won't for several months.

**Comment by mishoboss** [comment]
Thanks! 
So it is something like this:
1. scratch-vm loads SB2 
2. it does some conversion magic and pushes the produced stuff to scratch-blocks internally (not using XML)
3. on scratch-blocks UI event (like a new block attached) it pushes this data internally again to scratch-vm

So, that said, could I use this approach and store SB2 data into DB from scratch-vm? Then load it and its rendered OK in scratch-blocks?

**Comment by tmickel** [comment]
That is more or less correct. The "internal" pushing back and forth does contain some XML to represent the blocks, but not precisely.

From scratch-vm to scratch-blocks, XML is emitted when first loaded and when switching sprites: https://github.com/LLK/scratch-vm/blob/develop/src/engine/blocks.js#L383

When scratch-blocks emits certain XML-containing events like CREATE, scratch-vm parses and loads it into its own structure: https://github.com/LLK/scratch-vm/blob/develop/src/engine/blocks.js#L203

That approach could work, but we _don't_ currently have a way to export SB2 data from scratch-vm or anywhere else.

**Comment by dekrain** [comment]
@tmickel Look here: LLK/scratch-vm#266 and LLK/scratch-vm#259

**Comment by mishoboss** [comment]
Last question that is too far from the initial question, but I would be thankful of an answer. :)
What would be the easiest way to transcode the XML produced from scratch-blocks to [json-logic-js](https://github.com/jwadhams/json-logic-js) JSON code. Can I grab some part of `scratch-blocks` or maybe `scratch-vm` and use it as a base to build the conversion logic above it? Can you point me the most right way doing this? Or maybe this idea is not worth investing in, because it will take a lot of time? I know I'm going out the scope of this project, but will appreciate a little help. Thanks in advance!
