### ISSUE TITLE
i just fellow the wiki,but it does not work for me

### ISSUE THREAD

**Issue by yonghuming** [LLK/scratch-blocks#684]
i checkout the repo use git clone
then i run the symblink command
then i run npm install 
but i does not work
os:ubuntu 14.04,i have tried dozens of times and i have try this problems for days

**Comment by tmickel** [comment]
Did you try running the symlink command _after_ `npm install`? The purpose of the symlink command is to link a copy of closure-library to the one installed by npm.

**Comment by yonghuming** [comment]
@tmickel yes, i have run the symlink command fater `npm install`,i my brosewr does not get any alert,i think i have installed closure-library properly

**Comment by thisandagain** [comment]
Hi @yonghuming can you please provide more info so we can help debug this for you? Specially we need to know:
- OS
- Node version (`node -v`)
- NPM version (`npm -v`)
- Full NPM debug log after attempting `npm install` (look for `npm-debug.log`)

**Comment by thisandagain** [comment]
Closing pending information.
