### ISSUE TITLE
Scroll to top of flyout on category switch

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#690]
This seems to me like it would be the right behavior, since the scroll doesn't feel like it should follow from category to category.

**Comment by towerofnix** [comment]
A unique scroll-position for each category might be nice.. I end up needing to scroll way back down the variables category because of the number of variables I have far too often..

**Comment by PullJosh** [comment]
> A unique scroll-position for each category might be nice.. I end up needing to scroll way back down the variables category because of the number of variables I have far too often..

This makes a lot of sense... On that topic, what if it was possible to rearrange variables in the editor?
