### ISSUE TITLE
Workspace scrolling is shared between sprites

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#693]
Scroll/pan position should probably be stored with a value for each target, so that switching between sprites won't make you need to go back to where your far-way scripts are. (That's a huge problem I have with multiple sprites having [tons](http://i.imgur.com/1FZQJ82.png) [of](http://i.imgur.com/U6iYBZJ.png) [scripts](http://i.imgur.com/WvNtVkY.png) in Scratch 2!)

(Probably has a bit to do with scratch-vm..)

Kind of similar to #690.

**Comment by rschamp** [comment]
Moved to LLK/scratch-gui#6

**Comment by rschamp** [comment]
Thanks @liam4 — this will be something to keep in mind as we build the GUI, which will control the communication between the blocks, renderer and VM.

**Comment by towerofnix** [comment]
> Moved to LLK/scratch-gui#6

I can't wait for this to be published.. :P

**Comment by rschamp** [comment]
Soon!

**Comment by rachel-fenichel** [comment]
Tracking bug in blockly: https://github.com/google/blockly/issues/1052
