### ISSUE TITLE
Number input pad freeze after first input on mobile devices.

### ISSUE THREAD

**Issue by xmeow** [LLK/scratch-blocks#694]
Every UI components freeze up after any number input via the number pad, including toolbox and flyout. 
Tested on llk.github.io/scratch-vm under ipad safari and phonegap enclosure.
![qq20161019-0](https://cloud.githubusercontent.com/assets/3390845/19516370/4ad2478a-962e-11e6-839e-ba7d3eb84a16.png)

**Comment by rachel-fenichel** [comment]
Dupe of #658
