### ISSUE TITLE
Deleting the contents of a number field and clicking away leaves it empty

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#696]
Expected behaviour: it returns to "0"
Clicking on a block to run it after this acts as though there were a 0 there.
![e4ec8d84-236f-4d74-b3b6-d33c17097f78](https://cloud.githubusercontent.com/assets/13686399/19536780/3d1a087a-9602-11e6-9d7a-ad63772fb1a0.gif)

**Comment by tmickel** [comment]
Why is this the expected behavior - seems consistent with Scratch?

**Comment by rachel-fenichel** [comment]
Huh, I guess it is.

It feels super weird to me to have "move by " when we know that "move by 0" is the correct thing to coerce it to after validation.  Feel free to close if the goal is purely consistency with current scratch for this.

**Comment by tmickel** [comment]
Hmm, yeah. no a strong preference from me, we can discuss

**Comment by PullJosh** [comment]
I'd agree that a zero makes more sense. I'm having a hard time envisioning a situation where "move by _" would make more sense than "move by 0" (seeing as a blank will be evaluated as a zero).

**Comment by towerofnix** [comment]
Yep.

The only place where I can only see empty number input slots being particularly useful is actually in Snap_!_, where ["run { move (_) steps } with inputs (45)" behaves like "move (45) steps"](http://snap.berkeley.edu/snapsource/snap.html#cloud:Username=liam4%20snap&ProjectName=Blank%20Input).. and that's obviously not applicable to Scratch 3.0!

**Comment by thisandagain** [comment]
In the case of numeric inputs this should act the same as the sprite info area: clicking outside of the block or confirming via "enter" should transform the empty value to the default value. We aren't sure if "default value" is correct or if it should be "0" but we'll try this for now.

/cc @carljbowman

**Comment by mrjacobbloom** [comment]
I'm not sure this discussion should end yet (even though nobody's touched it for a while)... sure scratch-blocks matches 2.0's functionality, but I think there's some value in exploring how to portray what value empty number (and boolean?) inputs return. This tripped Rachel up and I wouldn't be surprised if kids would be caught off-guard too (unless you've already tested this and they don't care 😛)

For whatever reason I keep thinking about grayed-out input placeholders as a solution to this. It doesn't look like there's a value in the input but there is some indication of what the block is doing
