### ISSUE TITLE
Repeatedly clicking on a toolbox category scrolls the flyout up

### ISSUE THREAD

**Issue by tmickel** [LLK/scratch-blocks#704]
![oct-21-2016 12-16-51](https://cloud.githubusercontent.com/assets/120403/19605477/471ed5a8-9788-11e6-8342-38b32e78e327.gif)

**Comment by rachel-fenichel** [comment]
What's the desired behaviour: leave scroll in the same place, or reset to the start of the category?

If it's the second, it'll be fixed when I fix #690.
