### ISSUE TITLE
Design Extensions Interface

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#706]
What should the format be?
### A Working Implementation

I made a implementation that works if you choose to use otherwise it is here to base yours off of.
### Clone It At:

https://github.com/TheBrokenRail/scratch-blocks.git Branch: feature/extensions
### How To Load Extension

Push the JSON to Blockly.Extensions.EXTENSIONS
### JSON Block Example

``` json
{
    "xml":"<block></block>",
    "jsonSpec": {
        "message0": "if on edge, bounce",
        "previousStatement": null,
        "nextStatement": null
    },
    "id":"example_block",
    "run":"console.log('Do Stuff');"
}
```

Extensions are arrays containing JSON blocks
### Example Implementation For Scratch-VM

``` js
var block = Blockly.Extentions.lookupBlock(args.mutation.id);
eval(block.run);
```

**Comment by TheBrokenRail** [comment]
Is there any way for me to put my implementation and it's documentation elsewhere like a design example pull request?

**Comment by TheBrokenRail** [comment]
Updated example to use json init and toolbox xml instead of parsing a string.

**Comment by thisandagain** [comment]
The best option for things like this is to put up a branch (e.g. `feature/extensions`) in your fork and then post a link to it in this issue. Example PRs are hard for us to work with a can be very noisy / intrusive.

**Comment by TheBrokenRail** [comment]
There: https://github.com/TheBrokenRail/scratch-blocks.git Branch: feature/extensions

**Comment by TheBrokenRail** [comment]
Updated with proper example.

**Comment by TheBrokenRail** [comment]
Any comments on the example implementation?

**Comment by thisandagain** [comment]
Tracking in scratch-vm. Current direction documented here:
https://github.com/LLK/scratch-vm/wiki/Extensions-Proposal
