### ISSUE TITLE
Add Multiple Ifs in one block like in blockly [FEATURE] [REQUEST]

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#708]
![untitled](https://cloud.githubusercontent.com/assets/17478432/19626823/3c74b9ee-9907-11e6-9da6-fd8dcaf3acd3.png)

**Comment by ed-cooper** [comment]
I feel like this would be a lot of work for something that is really easy to work around
Moreover, I suspect being able to drag and drop "else if" and "else" blocks might cause confusion for younger scratchers

**Comment by thisandagain** [comment]
Hi @TheBrokenRail . Thanks for the suggestion.

In Blockly these are refered to as [Mutators](https://developers.google.com/blockly/guides/create-custom-blocks/mutators) and have explicitly dropped support for them in Scratch Blocks as we have found them to add complexity and confusion to the language (particularly when first getting started). While they have some interesting uses, we would prefer not to support them at this time.
