### ISSUE TITLE
Dragging a block out of a Scratch 2.0 dropdown leaves the block spec as the input

### ISSUE THREAD

**Issue by towerofnix** [LLK/scratch-blocks#709]
![The issue](https://cloud.githubusercontent.com/assets/9948030/19667340/b846bbc4-9a26-11e6-899c-b862c9efa133.gif)

As seen above.

When you drag out a block from a Scratch 2.0 dropdown, a stringified version of the block spec tree is left in the input.

Probably the fix here would be setting the input values to some default value during an SB2 import, but I'm not totally sure what the best way to go about doing that would be.

**Comment by tmickel** [comment]
Hmm, good catch. It's definitely a bug with the SB2 importer, although I'm not immediately sure what the default value should be. In Scratch 2.0 it looks like the default behavior is to set the drop-down to "blank" in this situation. We could do something similar here.

**Comment by tmickel** [comment]
Also - this is more relevant to scratch-vm, so moving it there!
