### ISSUE TITLE
Color effect

### ISSUE THREAD

**Issue by itselijahciali** [LLK/scratch-blocks#710]
![image](https://cloud.githubusercontent.com/assets/16740188/19695851/610f1f5c-9aaa-11e6-943d-a8ba70357736.png)
I personally think it should be "set [color v] effect to (0)", because that's like Scratch 2.0 and it's usual to the users.
![image](https://cloud.githubusercontent.com/assets/16740188/19695933/ab9fa3b6-9aaa-11e6-964e-fa3e4f761f43.png)
like that ^

**Comment by dekrain** [comment]
I don't understand you. This block is on the pallet

**Comment by thisandagain** [comment]
Hi @eliapplethetech we have both "set" and "change" available in the blocks palette (look under "looks") here: http://llk.github.io/scratch-vm/#. 

This is the same as Scratch 2.0. Let us know if you see any other inconsistencies! 😄

**Comment by itselijahciali** [comment]
I was talking about the grammar & syntax.

**Comment by luxaritas** [comment]
Assuming you're referencing this:

![seteffect](https://cloud.githubusercontent.com/assets/18635705/20234515/a114d8dc-a84a-11e6-8ccf-53ad94ac9168.png)

**Comment by ghost** [comment]
He means that the block says "effect [color v]" instead of "[color v] effect"

**Comment by luxaritas** [comment]
@jupiterio Yes, just clarifying that this wasn't an issue of set/change, as the screenshots were of different blocks.

**Comment by ghost** [comment]
@LFP6 Sure, no worries, I was also clarifying.
