### ISSUE TITLE
Clicking on Lists Category in Vertical Playground causes error

### ISSUE THREAD

**Issue by MichaelZawadzki** [LLK/scratch-blocks#721]
In the current vertical playground on develop (as well as in the hosted version here: https://utils.asun.co/scratch-blocks/tests/vertical_playground.html) as soon as the "List" category is clicked there is a console error and the app doesn't show the category correctly.

**Comment by tmickel** [comment]
@rachel-fenichel This appears to have been caused by this clean-up of fieldnumber: https://github.com/LLK/scratch-blocks/commit/3bcea6b6feb0328c1752671ae6f0459f1a7362d6

Would you mind taking a look?
