### ISSUE TITLE
Replacement marker filter breaks scratch-blocks on IE

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#736]
https://github.com/LLK/scratch-blocks/blame/develop/core/inject.js#L137

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/repeat#Browser_compatibility

This is simple enough to fix that we should explicitly work around it.

**Comment by tmickel** [comment]
Was this fixed by https://github.com/LLK/scratch-blocks/pull/737 ?

**Comment by rachel-fenichel** [comment]
Yes, but that's against a different branch.  I need to rebase it against develop and then make a request against develop in order to close this.
