### ISSUE TITLE
Support for importing Scratch projects in SB2 format?

### ISSUE THREAD

**Issue by Domiii** [LLK/scratch-blocks#743]
Is there any way or any plan for allowing importing of legacy projects? It appears that they should be fully compatible, however I don't see any references to "SB2" in the repository? (I used the Github search function, maybe I am looking for the wrong key word?)

**Comment by dekrain** [comment]
https://llk.github.com/scratch-gui/#projectid
Checkout the llk/scratch-vm repo

**Comment by dekrain** [comment]
**Pro Tip**: You can close issues that you open if main problem was resolved.

**Comment by Domiii** [comment]
Not sure how the `scratch-gui` project answers my question? I understand that it can be used to ultimately display the contents of SB2 files, but there is no importer either, is there?

Are you saying that I should remove this here and file it as a feature request in [scratch-gui](https://github.com/LLK/scratch-gui)? Or maybe I only overlooked it?

**Comment by Domiii** [comment]
Oh! I finally found it in the [scratch-vm repository](https://github.com/LLK/scratch-vm) : 

https://github.com/LLK/scratch-vm/blob/develop/src/import/sb2import.js

PS: Great job btw! I am looking forward to make use of these libraries in the future :)

**Comment by Domiii** [comment]
May I ask another stupid/somewhat unrelated question?

How do all these projects relate? [The official developer page](https://scratch.mit.edu/developers) does not quite clarify this. Specifically, it does not mention:

1. https://github.com/LLK/scratch-vm/
2. https://github.com/LLK/scratch-gui/
 
Can anyone explain? And if not, where should I ask? Again: Sorry for being a bit off-topic, just trying to get an idea of the big picture here!

**Comment by dekrain** [comment]
Scratch VM _was_ main project in development but now GUI has got main design. In short:
- Scratch Blocks - Main blocks' design
- Scratch VM - all the work of blocks
- Scratch GUI - Design of the playground
- Scratch Audio - Sound system

**Comment by Domiii** [comment]
Really awesome. Sorry for going off-topic in this issue! I think, I'm not the only one who is going so far as to say that updating the wiki + Scratch developers main page with this information would be super valuable! :)

Again: Thanks a dozen!

PS: Is `scratch-vm` going to be phased out in favor of `scratch-gui`?

**Comment by rschamp** [comment]
@Domiii Thanks for bringing up the gaps in the developer page, we'll try to fill those soon.

The `scratch-gui` project is dependent on `scratch-vm` so it cannot phase out `scratch-vm`. All of these repos, `scratch-blocks`, `scratch-vm`, `scratch-render`, `scratch-audio` and `scratch-gui` are all parts of one thing so there is no "main" project. However our focus may shift across them depending on which piece we're working on.  This is different from the way we built `scratch-flash`, which had all of those components stored in a single code base.
