### ISSUE TITLE
Implement drop-down menus

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#749]
- [x] All motion (and sensing of object (except for preset stage and sprite1)) menus that have sprites in them don't show sprites
(Was Using This iv VM with Sprites)
![first](https://cloud.githubusercontent.com/assets/17478432/21412972/265737e2-c7c2-11e6-8e7b-883d07330fc5.PNG)
- [ ] Broadcast Menu new broadcast doesn't do anything
![two](https://cloud.githubusercontent.com/assets/17478432/21412982/2da121f2-c7c2-11e6-8d5b-fec9ba583a65.PNG)
- [ ] Broadcast menu doesn't show broadcasts except the preset ones
![three](https://cloud.githubusercontent.com/assets/17478432/21412988/334c2dd6-c7c2-11e6-8537-b5316f645403.PNG)
- [ ] Sensing of block property menu does not show variables
![thing](https://cloud.githubusercontent.com/assets/17478432/21413067/c549ffec-c7c2-11e6-8214-14753afb5063.PNG)

**Comment by TheBrokenRail** [comment]
Added screenshots to demonstrate problem.

**Comment by TheBrokenRail** [comment]
I think this should be ready by the prototype cause menus need to work.

**Comment by tmickel** [comment]
Thanks for the screenshots - that should be helpful when this is implemented!

Regarding your last point:
The "squared" menus with block-colored backgrounds are intentional; no reporters can be dropped into those menus.

**Comment by TheBrokenRail** [comment]
What about circular menus with block colored backgrounds?

**Comment by tmickel** [comment]
Those shouldn't exist- either it's a mistake, or the color palette is too subtle to see the difference. Which blocks appear that way?

**Comment by TheBrokenRail** [comment]
some reporters, sensing of menus, variable getter

**Comment by TheBrokenRail** [comment]
Why is variable getter shadow round and list getter shadow square?

**Comment by TheBrokenRail** [comment]
I have a implementation for this that uses Blockly.Blocks.Sprite to hold sprite names and is set by vm on targets update, see closed PRs above.

**Comment by TheBrokenRail** [comment]
The sensing variable menu is easily done by doubling the workspaces variable list and concaving it to the menu.

**Comment by TheBrokenRail** [comment]
Should I make a PR to fix the sensing block?

**Comment by TheBrokenRail** [comment]
Note, At the current way menus are implemented the menus won't be updated until they are re-rendered.

**Comment by TheBrokenRail** [comment]
Though this could be solved by reloading the workspace, workspace to xml, xml to workspace:
```js
Blockly.Xml.domToWorkspace(
    Blockly.Xml.workspaceToDom(
        Blockly.getMainWorkspace()
    ), 
    Blockly.getMainWorkspace()
);
```

**Comment by TheBrokenRail** [comment]
Seeing how sounds has ben fixed in LLK/scratch-gui#76 should I make a PR to fix this for sprites?

**Comment by TheBrokenRail** [comment]
I have a implementation for the sensing of block

**Comment by TheBrokenRail** [comment]
Should I make a PR to fix the sensing of property menu.
