### ISSUE TITLE
Blocks Need to be Grouped in Palette

### ISSUE THREAD

**Issue by PullJosh** [LLK/scratch-blocks#752]
In Scratch 2.0 (and below), blocks are grouped into sections within the palette. For instance, `move 10 steps`, `turn right`, and `turn left` are all grouped together, with a space before `point in direction` (and the rest of the blocks). This is not yet the case in Scratch 3.0.

**Comment by luxaritas** [comment]
I was actually thinking that there should be collapsible menus, to help clean things up (especially since blocks are so big with Scratch 3): https://lfp6.github.io/scratch3/mockup/blocks-accordion
