### ISSUE TITLE
Add 'undefined' block

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#756]
![obsolete_block](https://cloud.githubusercontent.com/assets/17478432/21546215/3a2a6c64-cdab-11e6-8a5c-b79d9be225e1.png)
Currently Unknown blocks will load but be invisible I think we need to implement this so things like modded projects don't break, or broken json, I think it should also preserve shadow blocks.

**Comment by TheBrokenRail** [comment]
I think inputs and block ID should be kept and the VM will still try to execute it so you don't completely break vertical projects by loading them in horizontal mode, it won't be editable but it would be a placeholdee to allow vertical projects to be edited on horizontal editor, or so modded projects don't fall apart.

**Comment by Tymewalk** [comment]
We definitely need something like this. Same colors as the current undefined custom block?

**Comment by TheBrokenRail** [comment]
[Here](https://github.com/LLK/scratch-blocks/blob/develop/core/block.js#L167) is where It grabs data from Blockly.Blocks, adding the undefined block would mean adding a init function as an undefined block that uses inputs defined in it and changes it's output check and shape to adapt for where it is and stores that as an "undefined data" parameter for later use.

**Comment by TheBrokenRail** [comment]
For output shapes Scratch-Blocks should store the output shape in xml so it can be imported properly inside blocks.
