### ISSUE TITLE
What is the multi playground?

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#758]

**Comment by tmickel** [comment]
The idea is to display a rendered instance of the blocks in many different configurations: LTR, RTL, toolbox on the left, on the right, etc., all on the same page. It's a good test that all of those configurations are working, and that they can all be used simultaneously. It looks like our multi-playground is not doing great, but here is the Blockly equivalent to give the idea:
https://blockly-demo.appspot.com/static/tests/multi_playground.html

**Comment by TheBrokenRail** [comment]
Souldn't there be vertical blocks two though?

**Comment by rachel-fenichel** [comment]
Yes, and I've created an issue for that: #764.  I've closed this issue because the question it asked was answered, and there are no code changes associated with that answer.
