### ISSUE TITLE
Number pop up menu doesn't move when scrolling

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#759]
![image](https://cloud.githubusercontent.com/assets/17478432/21666433/a3585c32-d2bf-11e6-9ecc-4871a787f3b3.png)

**Comment by Tymewalk** [comment]
Where did you find this, and what blocks did you use? I can't seem to replicate it.

**Comment by picklesrus** [comment]
I can't test in scratch-blocks directly on a touch device at the moment, but in scratch-gui, the menu gets closed before we scroll and I vaguely remember fixing this when the snowflake activity was made.
