### ISSUE TITLE
Blocks in the vertical workspace can be scroll off view when the height is too large.

### ISSUE THREAD

**Issue by cdeng-amplify** [LLK/scratch-blocks#771]
### Expected Behavior

blocks should remain inside the view when scrolled.

### Actual Behavior

when there are too many blocks connected, then scrolling the workspace can cause the blocks to scroll past the view.
![correct_scroll](https://cloud.githubusercontent.com/assets/3731340/22115488/2e262f52-de3b-11e6-8b91-6667d566b00a.png)
![incorrect_scroll](https://cloud.githubusercontent.com/assets/3731340/22115486/2e1dbee4-de3b-11e6-8dd4-2557f52dfa29.png)
![large_height](https://cloud.githubusercontent.com/assets/3731340/22115487/2e25d976-de3b-11e6-8f3b-faf7d03cf584.png)

The number of blocks to make this bug occur depends on the height of the view.

### Steps to Reproduce

Please see the attached images.
1. load the vertical playground.
2. add a few blocks and scroll to see the blocks are clamped inside the view.
3. add more blocks to the workspace like in the third image attached above, and scroll the workspace, notice the top blocks are scrolled off view.

### Operating System and Browser

_e.g. Mac OS 10.11.6 chrome 55.0.2883.95

**Comment by rachel-fenichel** [comment]
This is the intended behaviour.  The workspace is always sized to have a buffer around the blocks.
