### ISSUE TITLE
Delete & Rename Variable Functionality Not Working

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-blocks#777]
### Expected Behavior

_Delete the "<name>" variable_ should delete variable
_Rename variable..._ show rename variable everywhere

### Actual Behavior

Delete doesn't remove from list or destroy current copies
Rename only effects variable currently in list, and doesn't change variables already in stage

### Steps to Reproduce

Create variable, click drop down, click delete
Drag variable to workspace, rename variable

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.76 

I am sure you're already working on this, just adding an issue so I can share our first play test findings / complaints.

**Comment by Tymewalk** [comment]
Just tested [here](https://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html). Firefox 50.1.0, Ubuntu 16.04 LTS. Both issues have been confirmed and described here.

## Renaming

### Steps I used

- Create a variable called "a"
- Drag that variable reporter to the stage
- Drag a "set (a) to ()" block onto the stage
- Rename "a" to "b"

The "set (a) to ()" block properly becomes "set (b) to ()", but the variables list (under the variable blocks category) doesn't update, it remains as "a" there.

If you drag the "a" reporter onto the stage, it will create a new variable called "a" in addition to "b". (Deleting the "a" variable doesn't seem to work afterwards, and neither does renaming it.)

After renaming, selecting another block category and then going back to the variables category updates it, so I think we just need to re-call whatever happens then to update the list.

## Deleting

### Steps I used

- Create a variable
- Drag a few reporters of it onto the stage
- Right-click and use "Delete"

It asks if you want to delete it, but when you click "OK", nothing seems to happen. Selecting another block category and going back to the variables category updates the variables list and shows that the variable has been deleted, but the reporters still stay there.

## The (Potential) Solution

When a variable is deleted/renamed, we re-call whatever updates the list of variables (such as when categories are changed).

**Comment by rachel-fenichel** [comment]
Depends on #825

**Comment by fsih** [comment]
Both delete and rename are working now for the repro steps in this bug, so I'm closing this bug.

There are some leftover issues however, which I've filed in https://github.com/LLK/scratch-blocks/issues/1215 and https://github.com/LLK/scratch-blocks/issues/1216
