### ISSUE TITLE
Select Color From Hover Over

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-blocks#778]
### Expected Behavior

Would like to be able to click color drop down, then hover over area and select color under mouse. This may make it easier for students to select the exact color of another sprite or stage.

**Comment by thisandagain** [comment]
This may end up not being possible in HTML5. Flagging for discussion (we've already talked about it, but good to have documented).

**Comment by SillyInventor** [comment]
The more I think about this, the more it seems doable to me.

Could you add a mouse move event listener on drop down open that moves through allDrawables grabs the webGLRenderingContexts and calls readPixels at the event location, until it finds one that doesn't have alpha == 0?

**Comment by rachel-fenichel** [comment]
How long do you expect that to take, per mouse move?

**Comment by SillyInventor** [comment]
Fairly long. Though I haven't tried / measured.

**Comment by SillyInventor** [comment]
Based on a quick test, 6-7ms?

**Comment by rachel-fenichel** [comment]
On what hardware, OS, and browser?

**Comment by SillyInventor** [comment]
Ubuntu 16.0.4, Chrome 56.0.2924.87, Lenovo W540.

**Comment by rachel-fenichel** [comment]
Hm yeah, I would expect that to be a significant performance issue on an older computer such as you might find in a school computer lab.  W-series laptops may not be representative.  At a minimum this would need to be tested in Edge and IE, which tend to be much slower.  Safari is probably performant enough to not be the bottleneck.
