### ISSUE TITLE
Tan Function Rounding Error

### ISSUE THREAD

**Issue by SillyInventor** [LLK/scratch-blocks#779]
### Expected Behavior

Tan of 90 returns infinite, NaN, or similar. Tan of 180 should give 0.

### Actual Behavior

Because we're converting from degrees to radians, there is a rounding error. Such that you get to nearly 0, and large numbers, but not the exact number / result desired.

### Steps to Reproduce

Input values into mather operation, set to tan, click.

### Operating System and Browser

Ubuntu 16.04, chrome 56.0.2924.76 

I am sure you're already working on this, just adding an issue so I can share our first play test findings / complaints.

**Comment by thisandagain** [comment]
Moved to LLK/scratch-vm#420
