### ISSUE TITLE
Opening dropdown in a block in the flyout and switching categories causes js error

### ISSUE THREAD

**Issue by picklesrus** [LLK/scratch-blocks#783]
When switching categories when a dropdown is open you get the following js error: 

vertical.js:2842 Uncaught TypeError: Cannot read property 'isShadow' of null
    at Blockly.FieldDropdown.onHide (vertical.js:2842)
    at Function.Blockly.DropDownDiv.hide (vertical.js:2462)
    at Blockly.Toolbox.<anonymous> (vertical.js:2973)
    at HTMLDivElement.g (vertical.js:2784)

### Steps to Reproduce
0. open js console.
1. Open motion category
2. Open dropdown in the "point toward" block
3. Without closing the dropdown , click on the "Events" category (probably others too).
4. see error.

### Operating System and Browser
Chrome MacOS

**Comment by Tymewalk** [comment]
Just confirmed it [here](https://llk.github.io/scratch-blocks/playgrounds/tests/vertical_playground.html). Firefox 50.1.0, Ubuntu 16.04 LTS.

JS console dump:
```
TypeError: this.sourceBlock_ is null[Learn More] field_dropdown.js:240:1
	Blockly.FieldDropdown.prototype.onHide https://llk.github.io/scratch-blocks/playgrounds/core/field_dropdown.js:240:1
	bound  self-hosted
	Blockly.DropDownDiv.hide https://llk.github.io/scratch-blocks/playgrounds/core/dropdowndiv.js:381:5
	Blockly.Toolbox.prototype.init/< https://llk.github.io/scratch-blocks/playgrounds/core/toolbox.js:119:9
	Blockly.bindEventWithChecks_/wrapFunc https://llk.github.io/scratch-blocks/playgrounds/core/blockly.js:455:9
```

It happens across all categories and also happens with the color selection tool (on some of the pen and sensing blocks).

I haven't actually looked, but I think this is because the "hide" function is trying to reference an object which no longer exists (due to it being removed when the other category was opened).

**Comment by mrjacobbloom** [comment]
This does not happen with the dropdown when you click a reporter to see its value

**Comment by Tymewalk** [comment]
@Airhogs777 It happens for me. What OS/Browser are you using?

(Console dump upon trying it:)
```
Blockly.FieldDropdown.prototype.onHide https://llk.github.io/scratch-blocks/playgrounds/core/field_dropdown.js:240:1
	bound  self-hosted
	Blockly.DropDownDiv.hideWithoutAnimation https://llk.github.io/scratch-blocks/playgrounds/core/dropdowndiv.js:402:5
	Blockly.DropDownDiv.hide/Blockly.DropDownDiv.animateOutTimer_< https://llk.github.io/scratch-blocks/playgrounds/core/dropdowndiv.js:378:5
```

When the blocks are dragged onto the workspace, changing categories causes them to close, as expected.

We probably need a check to see if the object is still visible before attempting to hide it.

**Comment by mrjacobbloom** [comment]
@Tymewalk Chrome on Win10 on scratch-gui

**Comment by Tymewalk** [comment]
@Airhogs777 Strange, I just tested there, and it still happens.

Might be something to do with Firefox?

**Comment by Tymewalk** [comment]
Not sure if that commit was actually intended to be referenced, but the problem still exists on the vertical playground. (Unless that hasn't been updated.)

**Comment by Tymewalk** [comment]
[This](https://github.com/LLK/scratch-blocks/blob/develop/core/field_dropdown.js#L240) is where the error is happening: `    if (this.sourceBlock_.isShadow()) {`

I'm looking to see if I can get a more detailed message now.

EDIT: [This](https://github.com/LLK/scratch-blocks/blob/develop/core/toolbox.js#L119) may also help in the event we need to add a check to see if the block still exists.

**Comment by Tymewalk** [comment]
After replicating this glitch, another one happens:

## How to Replicate

- Replicate this glitch as described above.
- Drag a block onto the playground.
- Attempt to drag the background.

## Expected Output

The stage pans so you can see other blocks.

## What Actually Happens

This error is thrown:
```
TypeError: this.sourceBlock_ is null[Learn More] field_dropdown.js:240:1
	Blockly.FieldDropdown.prototype.onHide https://llk.github.io/scratch-blocks/playgrounds/core/field_dropdown.js:240:1
	bound  self-hosted
	Blockly.DropDownDiv.hide https://llk.github.io/scratch-blocks/playgrounds/core/dropdowndiv.js:381:5
	Blockly.WorkspaceSvg.prototype.onMouseDown_ https://llk.github.io/scratch-blocks/playgrounds/core/workspace_svg.js:1007:3
	Blockly.bindEventWithChecks_/wrapFunc https://llk.github.io/scratch-blocks/playgrounds/core/blockly.js:455:9
```

and the stage does not pan.
