### ISSUE TITLE
Check boxes Don't Work

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#794]
### Expected Behavior

_They should change from red to blue._

### Actual Behavior

_It does not and throws a js error:_
```js
Blockly.addClass_ is not a function
```
### Steps to Reproduce

_Open up playground and click checkbox._

### Operating System and Browser

_Windows 10 Chrome_

**Comment by thisandagain** [comment]
Monitors (and the checkboxes that control them) have not yet been implemented. While they shouldn't throw an error, I'm going to backlog this for now.

**Comment by rachel-fenichel** [comment]
This is just that we missed a spot when moving to Blockly.utils.  It's
fixed in my merge pr.
