### ISSUE TITLE
Loading a new toolbox without categories through updateToolbox causes console error

### ISSUE THREAD

**Issue by MichaelZawadzki** [LLK/scratch-blocks#796]
### Expected Behavior

When the workspace is initialized with a non-category toolbox it is expected to be able to load other non-category toolboxes through workspace.updateToolbox without causing console errors. 

### Actual Behavior

With the latest merge of **bugfix/updateToolbox**, this now causes a console error. Before (at SHA 1cf79eed97015b5bddcc628cc24a1be079a4d3f1) this did not occur. 

### Steps to Reproduce

To reproduce, add a method like the following to the playground to trigger a toolbox refresh:

`function setToolbox() {
          var emptyToolbox = '<xml><toolbox></toolbox></xml>';
          workspace.updateToolbox(emptyToolbox);
      };
`

This method can then be trigged by any button, for example the "To JavaScript" button.

Note that you need to first make sure to set the toolbox option to "Simple" in order to have the toolbox with no categories loaded initially (to avoid switching between category toolboxes and non-category toolboxes).

Also note that the toolbox does not need to be empty, its just like this in the example to keep it simple. 

### Operating System and Browser

Reproduced on Chrome on Mac but pretty sure its not isolated to any specific platform and is a general issue.

**Comment by MichaelZawadzki** [comment]
Seems this might simply need a 'if (this.toolbox_)' check around that position call.

**Comment by rschamp** [comment]
Fixed in #858
