### ISSUE TITLE
Build - Update package.json and publish to NPM

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#8]
The Scratch team uses NPM as the dependency management system for new JS projects. Because of this, it would be nice to have a clear process for release "tagging" and publishing to NPM.

Looks like this has been explored quite a bit already by the `blockly` community: 
- https://github.com/google/blockly/pull/136 
- https://github.com/google/blockly/issues/177

**Comment by tmickel** [comment]
I believe this has been done!
