### ISSUE TITLE
Blocks jump to workspace when deleting in palette

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#804]
Breaking out this issue from: https://github.com/LLK/scratch-blocks/issues/675

### Expected Behavior – as seen in scratch-vm as of 2/21/17

![expected deletion behavior mov](https://cloud.githubusercontent.com/assets/3409578/23169124/879004cc-f818-11e6-8960-4ee8984190df.gif)

When the user drags the block over the palette and drops the block to delete, the block should drop into z-space and remain over the palette. 

### Actual Behavior – as seen in scratch-gui as of 2/21/17

![current behavior mov](https://cloud.githubusercontent.com/assets/3409578/23169629/7d005d8e-f81a-11e6-9409-da078efa0b62.gif)

When the user drags the block over the palette and drops the block to delete, the block jumps horizontally back over the workspace and then animates back. 

### Operating System and Browser

Browser: Chrome Version 56.0.2924.87 (64-bit)
OS: macOS 10.11.6 (15G31)

**Comment by Tymewalk** [comment]
Confirmed just now on Firefox 50.1.0, Ubuntu 16.04 LTS.

When half-moving a block onto the flyout (without it being deleted), it gets pushed off back to the workspace. That code probably interfered with this, pushing it off to the workspace and then deleting it.

**Comment by rachel-fenichel** [comment]
My new dragging code fixes this; it's a pain to fix with the current code.

**Comment by rachel-fenichel** [comment]
Fixed by https://github.com/google/blockly/pull/1078

**Comment by rachel-fenichel** [comment]
Fixed in scratch-blocks by #891
