### ISSUE TITLE
Very Low Sensitivity On Touch

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#807]
### Expected Behavior

_When you try to move the block it moves._

### Actual Behavior

_It rarely moves and sometimes a context menu pops up._

### Steps to Reproduce

_Get a touch screen windows device._

### Operating System and Browser

_Windows 10 Microsoft Edge_

**Comment by rachel-fenichel** [comment]
Blockly doesn't work on edge or IE with touch screens.  This is because neither one implements the TouchEvents API (they use the PointerEventA API instead).

Eventually I'll probably be able to make it work in Blockly, but I have no time frame for that.

**Comment by thisandagain** [comment]
@rachel-fenichel Do you have a bug in google/blockly where you are tracking this?

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/issues/943

**Comment by thisandagain** [comment]
Tracking in https://github.com/google/blockly/issues/943
