### ISSUE TITLE
Dropdown menu indicator appears in between words

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#811]
### Expected Behavior

The dropdown menu indicator triangle should appear at the end of the name of the current selection on the block.

### Actual Behavior

In some cases, the indicator shows up in between words. Also, the dropdown menu itself is missing the non-unique part of each name.

<img width="205" alt="screen shot 2017-02-27 at 3 09 13 pm" src="https://cloud.githubusercontent.com/assets/567844/23377741/1bbf8c4a-fcff-11e6-9aae-2fa2ab41a20f.png">

It happens when all the items in the menu have a word in common, such as the "guitar" in "C guitar", "D guitar", "E guitar", etc.

I'm guessing that this is due to a clever feature of Blockly called Prefix/Suffix Matching, documented [here](https://developers.google.com/blockly/guides/create-custom-blocks/dropdown-menus), which factors out repeated words in menu items. Probably we can simply disable it for cases where the menu items come from user generated content.

It's worth considering using this feature to reduce the number of translation strings, if we have any menus with a fixed set of items containing repeated words- in that case, though, we would still want the menu indicator to appear at the end. 

### Steps to Reproduce

Open https://llk.github.io/scratch-gui/
Add a musical instrument sprite like Bass or Guitar
Look at the Play Sound block

### Operating System and Browser

Mac OS 10.11.6 Chrome 56

**Comment by rachel-fenichel** [comment]
Is this issue new since the most recent merge?

**Comment by towerofnix** [comment]
Looks like this is fixed, now?

![Screenshot of "start sound" block in "Guitar-Bass" sprite](https://user-images.githubusercontent.com/9948030/30742639-5f44982a-9f70-11e7-80b7-dfb6c759de36.png)

I'm using Firefox 52.3.0 (on Debian Testing).

Still maybe worth it to bring up this (from top post), though:

> It's worth considering using this feature to reduce the number of translation strings, if we have any menus with a fixed set of items containing repeated words- in that case, though, we would still want the menu indicator to appear at the end.

**Comment by ericrosenbaum** [comment]
Thanks @towerofnix- it does seem to be fixed. Looks like we will not need the Prefix/Suffix Matching feature.
