### ISSUE TITLE
IE & Edge - Block Text Is Offset

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#820]
### Expected Behavior

_Text is aligned._

### Actual Behavior

_It is offset._

### Steps to Reproduce

_Launch Edge and look at the blocks._

### Operating System and Browser

_Windows 10 Edge_

### Screenshot

![capture](https://cloud.githubusercontent.com/assets/17478432/23593801/8ef6b242-01e1-11e7-80b0-259c1b65248d.PNG)

**Comment by rachel-fenichel** [comment]
May be similar to/related to this discussion: https://groups.google.com/forum/#!topic/blockly/T8IR4t4xAIY

**Comment by TheBrokenRail** [comment]
Oh, and it fixes itself when you put the mouse over it.

**Comment by paulkaplan** [comment]
I believe this was fixed by https://github.com/LLK/scratch-blocks/pull/1340
