### ISSUE TITLE
IE & Edge - Workspace not "cleaned up"

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#821]
### Expected Behavior

_You do not see residue from previous actions/animations._

### Actual Behavior

_You do._

### Steps to Reproduce

_Run a reporter or delete a bock with the toolbox._

### Operating System and Browser

_Windows 10 Edge_

### Screenshot

![bu](https://cloud.githubusercontent.com/assets/17478432/23593777/5cdb66fe-01e1-11e7-8c61-4374060bac22.PNG)

**Comment by rachel-fenichel** [comment]
This looks like a missing call to hideChaff.

**Comment by TheBrokenRail** [comment]
also happens with deleting:
![capture](https://cloud.githubusercontent.com/assets/17478432/23632198/ee6fb18a-028e-11e7-8eca-4dcd97a3b9cb.PNG)

**Comment by TheBrokenRail** [comment]
look at the grey streak, that was left over from deleteing.

**Comment by cwillisf** [comment]
This appears to have been fixed upstream
