### ISSUE TITLE
Match duplication behavior from Scratch 2.0

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#823]
### Expected Behavior

- I expect to be able to duplicate a stack of blocks (e.g. Scratch 2.0)
- When selecting "duplicate" while right clicking a block, that block plus all blocks connected below it (regardless or nesting) should be duplicated (e.g. Scratch 2.0)

### Actual Behavior

- Upon selected "Duplicate" from the context (right click) menu, a single block is duplicated. This duplicated block is not connected to my mouse cursor but is rather added to the workspace directly

### Repro

I am able to repro this by creating a stack of blocks with a loop and other blocks, e.g. screenshot below. I can duplicate each block and the contents of the for-loop, but not the whole stack.

<img width="283" alt="screen shot 2017-03-03 at 2 55 23 pm" src="https://cloud.githubusercontent.com/assets/1320456/23566802/749ec2de-0021-11e7-963d-f5b4636cda7c.png">

### Operating System and Browser

_Mac OS X El Capitan 10.11.6, Chrome Version 56.0.2924.87 (64-bit)_

---
Moved from LLK/scratch-gui#165
/cc @jwzimmer

**Comment by RoboErikG** [comment]
This is also something we want in Blockly and relates to [this issue](https://github.com/google/blockly/issues/384) around Hat Blocks wrapping the blocks below them for code generation.

**Comment by thisandagain** [comment]
@rschamp @carljbowman @RoboErikG @picklesrus @rachel-fenichel I made some refinements to the description above to clarify what I think is the desired behavior. Any thoughts?

**Comment by rachel-fenichel** [comment]
Can we separate out the issue of attaching duplicated blocks to the mouse cursor?

**Comment by thisandagain** [comment]
## Example

<img width="1280" alt="screen shot 2017-03-07 at 3 02 20 pm" src="https://cloud.githubusercontent.com/assets/747641/23675504/95ff109a-0347-11e7-8dfc-ecef69d71b7a.png">
<img width="1392" alt="screen shot 2017-03-07 at 3 02 26 pm" src="https://cloud.githubusercontent.com/assets/747641/23675503/95fe0d8a-0347-11e7-8384-7937a0b8a366.png">
<img width="1392" alt="screen shot 2017-03-07 at 3 02 31 pm" src="https://cloud.githubusercontent.com/assets/747641/23675505/95ff4f4c-0347-11e7-9f6a-bae693954082.png">
<img width="1392" alt="screen shot 2017-03-07 at 3 02 37 pm" src="https://cloud.githubusercontent.com/assets/747641/23675507/9600b1ac-0347-11e7-8777-c3da9ae99ffe.png">
<img width="1392" alt="screen shot 2017-03-07 at 3 02 44 pm" src="https://cloud.githubusercontent.com/assets/747641/23675509/96085754-0347-11e7-9c5e-73a8c3aee138.png">
<img width="1392" alt="screen shot 2017-03-07 at 3 02 48 pm" src="https://cloud.githubusercontent.com/assets/747641/23675506/96003f74-0347-11e7-8ef1-35fed452b189.png">
<img width="1392" alt="screen shot 2017-03-07 at 3 02 54 pm" src="https://cloud.githubusercontent.com/assets/747641/23675508/9601a792-0347-11e7-80d4-46018c40e5a1.png">

**Comment by thisandagain** [comment]
@rachel-fenichel Sure! I'll move it out.
https://github.com/LLK/scratch-blocks/issues/828

**Comment by rachel-fenichel** [comment]
And what is the expected behaviour for "duplicate" on a non-hat-block in a stack?  On an if block with blocks connected inside it?  On a reporter block inside another block?

Implementation-wise, we can change showContextMenu to be more aware of the type of the block it's on, and call a different function that duplicates the whole stack.  That change point is around here: https://github.com/LLK/scratch-blocks/blob/develop/core/block_svg.js#L917

**Comment by thisandagain** [comment]
Take a look at the screenshots above. I tried to show how we expect each of those scenarios to work.

**Comment by rachel-fenichel** [comment]
This is the code that's deleting all but the top blocks during the copy: https://github.com/LLK/scratch-blocks/blob/develop/core/blockly.js#L295

Getting rid of that if clause may fix this entirely for you.
