### ISSUE TITLE
Separate types for data, messages, and lists

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#825]
### Expected Behavior

Dropdowns for each category should only show items in that category.

### Actual Behavior

There's one global list of variables, with no type information.

Depends on typed variables in Blockly.

**Comment by rachel-fenichel** [comment]
https://github.com/google/blockly/issues/957

**Comment by thisandagain** [comment]
Related to: https://github.com/google/blockly/pull/1230

**Comment by paulkaplan** [comment]
This is done on the scratch-blocks side. Going to combine variables + lists into a single "typed variable" in the VM now.
