### ISSUE TITLE
Visual effects shouldn't take random as input to type

### ISSUE THREAD

**Issue by morantsur** [LLK/scratch-blocks#827]
### Expected Behavior

Visual effects blocks should not take a random block as input on the effect type. 

### Actual Behavior

![image](https://cloud.githubusercontent.com/assets/15109618/23673795/94559224-0341-11e7-8d7e-b45964f8dcb1.png)

### Steps to Reproduce

Add a random/join/operation block inside a visual effects block.

**Comment by rachel-fenichel** [comment]
Are there any blocks that should be droppable there?

**Comment by thisandagain** [comment]
No. This was just an oversight on our part I think. This menu should have been implemented as a "rectangle" (non droppable).

**Comment by thisandagain** [comment]
The following blocks have drop-downs that should not accept an input:

### Looks
- `change effect [x] by [n]`
- `set effect [x] to [n]`

### Sound
- `change effect [x] by [n]`
- `set effect [x] to [n]`

### Operators
- `[x] of [n]`

**Comment by PullJosh** [comment]
Would it be possible that a block input for `[x] of [n]` could be useful in the context of a calculator project? (Making it easier to provide built-in calculator functions.)

Probably not a common enough use case to be worth changing the input, but it's at least worth considering.

**Comment by TheBrokenRail** [comment]
Wouldn't keeping them circular make some things easier to code for scratcher, (using variables to set effect, using random to choose a random effect (add access via index support to the blocks), etc).
