### ISSUE TITLE
Hat blocks should not overlap in the block pane

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#838]
We should probably fix this before the playtest on March 16.

### Expected Behavior

Hat blocks should not overlap in the block pane.

### Actual Behavior

Hat blocks do overlap slightly. @paulkaplan, I think this may have happened when the spacing was reduced between the blocks in https://github.com/LLK/scratch-gui/issues/164, https://github.com/LLK/scratch-blocks/pull/834.

<img width="277" alt="screen shot 2017-03-10 at 5 24 05 pm" src="https://cloud.githubusercontent.com/assets/1320456/23815606/ce3c3d90-05b6-11e7-8b62-557ac26ddb25.png">

### Operating System and Browser

_Mac El Capitan & Chrome 56_

**Comment by thisandagain** [comment]
@rachel-fenichel @picklesrus Any thoughts on this one? Something about the hat blocks seems to be askew.

**Comment by rachel-fenichel** [comment]
Interesting.  I'd expect that to be handled by
https://github.com/LLK/scratch-blocks/blob/develop/core/flyout_vertical.js#L417

**Comment by picklesrus** [comment]
Hah. I just typed the same as @rachel-fenichel :)

Potential quick work around for play testing if the functionality was ported from blockly:
You might be able to use the sep tag with a gap attribute in the toolbox xml to increase the spacing just for these these blocks https://developers.google.com/blockly/guides/configure/web/toolbox#separators

But, we should figure out why that line in flyout_vertical.js isn't doing the right thing.

**Comment by paulkaplan** [comment]
@rachel-fenichel I think it was a small bug in that logic a few lines down where it moves the cursorY down. Let me know if the fix in #840 seems right.

**Comment by rachel-fenichel** [comment]
@paulkaplan that fix looks right, but it will also need to go into upstream blockly.
