### ISSUE TITLE
Change in block wording from 2.0 to 3.0 - "effect color" vs. "color effect"

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#841]
I am not sure if this was intentionally changed from 2.0 to 3.0?

### Expected Behavior

In 2.0, the block is called "change [color] effect by (25)".

### Actual Behavior

In 3.0, the block is called "change effect (color) by (25)". I am not sure if the re-ordering of color & effect was intended.

### Operating System and Browser

_Mac El Capitan & Chrome 56_

**Comment by thisandagain** [comment]
Good catch!

**Comment by navignaw** [comment]
Should the sound block:
"Change effect [pitch] by (10)"
also be changed to
"Change [pitch] effect by (10)" for consistency?

**Comment by ed-cooper** [comment]
"Change [pitch] effect by (10)" reads better imo

**Comment by thisandagain** [comment]
Resolved in #847
