### ISSUE TITLE
horizontal_playground.html reference javascript_compressed.js，"getFieldValue('NUM')" is null

### ISSUE THREAD

**Issue by zhlella** [LLK/scratch-blocks#846]
### Expected Behavior
xml:
`<block type="control_repeat"><value name="TIMES"><shadow type="math_whole_number"><field name="NUM">1</field></shadow></value></block>`
json:
      {
          "type": "input_value",
          "name": "TIMES",
          "check": "Number"
        }
I think generating Javascript Code  is "1"
### Actual Behavior

But result is " null" 

### Operating System and Browser

windows 7 & chrome 56.0.2924.87

**Comment by thisandagain** [comment]
Hi @zhlella . We'll need more information to help. Can you please share a link to your code?

**Comment by zhlella** [comment]
Thank you !  Solved,when I get the Javascript code with the wrong syntax !

**Comment by joseeph** [comment]
@zhlella I still getting "null" by implementing "getFieldValue" method, could you show your code in detail so I could reference it, thank you :P

**Comment by simeon-dobrikov-3D-depth** [comment]
In your case will look like this:
thisBlock.getFieldShadowBlock_().getFieldValue("TIMES");
