### ISSUE TITLE
horizontal's blocks "message0" implementation style?

### ISSUE THREAD

**Issue by zhlella** [LLK/scratch-blocks#852]
### Expected Behavior

![1](https://cloud.githubusercontent.com/assets/16182857/24134460/64625d28-0e3f-11e7-95fe-877dea5883a4.png)

### Actual Behavior

![3](https://cloud.githubusercontent.com/assets/16182857/24134585/4fc0656c-0e40-11e7-82db-2ec4a3e07d05.png)

### Steps to Reproduce

`"message0": "%1 Right",
      "args0": [
        {
          "type": "field_image",
          "src": Blockly.mainWorkspace.options.pathToMedia + "icons/event_whenflagclicked.svg",
          "width": 40,
          "height": 40,
          "alt": "When green flag clicked",
          "flip_rtl": true
        }
      ],`

style implementation!
"Right" in "message0"! 
How to realize？

### Operating System and Browser

windows 7 & chrome 56.0.2924.87

**Comment by rachel-fenichel** [comment]
In the horizontal playground that block is actually two blocks: one block with the icon (the red one) and one block with a text field (the white one that says "Right").  You'll want to set the text of the field on the white block.

Scratch-blocks is using shadow blocks to make it possible to create a project in horizontal mode and use it in vertical mode.  In vertical mode you want to either be able to type into that number input or drag a block in, so it needs to be a shadow block.  In horizontal mode, shadow blocks are rendered below the block and pretend to be simple fields.

**Comment by zhlella** [comment]
But shadow blocks are editable , is there  any way to make the shadow cannot be edited?

**Comment by cwillisf** [comment]
Closing this for now: we plan to work on horizontal blocks some time next year.
