### ISSUE TITLE
"More Blocks Flyout" and procedure hat XML export are brokem

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#860]
### Expected Behavior

_The flyout just shows created procedures (until a way to add a procedure is implemented) and a hat can be exported and imported through XML without resetting._

### Actual Behavior

_The flyout shows a undefined procedure hat and nothing else and procedure hats cannot be exported properly._

### Steps to Reproduce

_Open up the VM and load a project with a custom block, check the more blocks category and try to import and export the project with XML._

**Comment by paulkaplan** [comment]
Closed by recent custom procedures work.
