### ISSUE TITLE
Block text being selectable causes weird interactions

### ISSUE THREAD

**Issue by carljbowman** [LLK/scratch-blocks#861]
### Expected Behavior
Block text not being selectable by default

### Actual Behavior
Easy to accidentally open macOS dictionary on text
![highlight-block-text](https://cloud.githubusercontent.com/assets/3409578/24659841/e24aa182-191b-11e7-97ce-6fd0eff4427d.gif)

Easy to right click and open the macOS context menu
![context-menu-select-text mov](https://cloud.githubusercontent.com/assets/3409578/24660112/ae45e094-191c-11e7-8a05-0b7491655044.gif)

### Operating System and Browser

Browser: Chrome 57.0.2987.133 (64-bit)
OS: macOS 10.11.6

@rachel-fenichel @picklesrus  - I'd be curious to hear any reason, if any, that blockly allows text to be selected. At quick glance this became a major pain point during our playtest, but also can understand there may be use cases. Would love to hear your thoughts.

**Comment by picklesrus** [comment]
Nope, I don't think so.  I think it is just a bug. I can repro the context menu problem in blockly.
For text selection, I can only highlight blockly text if I start by highlighting text outside of the blockly div and draw inside of it. That's harder to prevent.  But it looks like you can just double click on text and it selects/shows the dictionary?  Come to think of it though, I've never seen the dictionary thing in macOS so maybe I have it turned off? Is there a setting somewhere?

**Comment by rachel-fenichel** [comment]
Context menu: that's a bug.  See #795.  I figured out what's causing it yesterday but haven't patched it yet.

**Comment by rachel-fenichel** [comment]
Block text shouldn't be selectable--that's probably a mistake in our css somewhere.  But I also can't get it just by clicking or double-clicking.  As a sanity check, do you see that in both the block palette and the workspace, or just in the block palette?

**Comment by rachel-fenichel** [comment]
Definitely a css thing.  In mainline blockly, text on blocks in the workspace have the following styles:
```
.blocklySvg text, .blocklyBlockDragSurface text {
    user-select: none;
    -moz-user-select: none;
    -webkit-user-select: none;
    cursor: inherit;
}
.blocklyText {
    cursor: default;
    fill: #fff;
    font-family: sans-serif;
    font-size: 11pt;
}
```

but text on blocks in the flyout have
```
.blocklyText {
    cursor: default;
    fill: #fff;
    font-family: sans-serif;
    font-size: 11pt;
}
```
As with the cursor problem, this is probably from when we restructured our DOM for performance reasons.  The main workspace svg has `.blocklySvg`, but the toolbox, flyout, and parent injection div don't.

**Comment by rachel-fenichel** [comment]
For the block palette, this can probably be fixed by changing this part of css.js:
https://github.com/LLK/scratch-blocks/blob/develop/core/css.js#L472

```
  '.blocklySvg text, .blocklyBlockDragSurface text {',
    'user-select: none;',
    '-moz-user-select: none;',
    '-webkit-user-select: none;',
    'cursor: inherit;',
  '}',
```
to

```
  '.blocklySvg text, .blocklyBlockDragSurface text, .blocklyFlyout text {',
    'user-select: none;',
    '-moz-user-select: none;',
    '-webkit-user-select: none;',
    'cursor: inherit;',
  '}',
```

and for the category menu, add `.blocklyToolboxDiv text`

but I haven't tested that.

**Comment by thisandagain** [comment]
@paulkaplan do you want to take a look at this one next iteration? We've noticed this come up as an issue a few times during testing.
