### ISSUE TITLE
Add Copy & Paste

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#863]
### Why

_While you could use the backpack on the online versions, copy & paste would be useful for running scratch offline, or as a quick way to transfer a script._

**Comment by towerofnix** [comment]
[Here's an old write-up/issue I made about copy/paste.](https://github.com/LLK/scratch-blocks/issues/455) It might be interesting to you.

**Comment by rachel-fenichel** [comment]
@thisandagain What's the scope of this issue?  Blockly implements copy and paste from right click menus and with keyboard shortcuts.

**Comment by thisandagain** [comment]
Sorry @rachel-fenichel, while I was triaging this I think I saw this as being part of the GUI (which doesn't not yet support copy/paste). Closing.

**Comment by thisandagain** [comment]
Because in Scratch blocks execute on click, we don't have a "selection state" which makes implementing something like copy/paste require some design effort. Leaving this open as a feature request, but it's likely not something we'll get to in the short term.

**Comment by thisandagain** [comment]
Tracking in https://github.com/LLK/scratch-blocks/issues/455
