### ISSUE TITLE
No visual confirmation when running commands

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-blocks#865]
Unlike is 2.0, where clicking on a block to run it would make it glow, that doesn't exist in 3.0.

**Comment by thisandagain** [comment]
Can you please share a screenshot from the GUI? I am not able to reproduce:
https://llk.github.io/scratch-gui/

![image](https://cloud.githubusercontent.com/assets/747641/25152636/a0fee5ac-2457-11e7-97f1-77c8d311df6d.png)
