### ISSUE TITLE
Scrolling toolbox upwards through dragging is broken

### ISSUE THREAD

**Issue by MichaelZawadzki** [LLK/scratch-blocks#873]
### Expected Behavior

When dragging on the background of the toolbox, it is expected that the toolbox properly scrolls up and down. 

### Actual Behavior

Scrolling down works fine. But once the toolbox is scrolled down, it can no longer be scrolled up (by dragging on the background). Additionally, the scrolling behavior gets wonky in general and its hard to navigate the toolbox by the user. 

### Steps to Reproduce

We can reproduce this in the vertical playground on develop:

1) Checkout develop branch
2) Open the vertical playground
3) Start a drag operation on the toolbox: click-down on any empty space in the toolbox and drag the mouse down -> toolbox will properly scroll downwards. Scroll all the way down and release.
4) Now we will want to perform the same operation and simply drag back up. So: click on any empty space in the toolbox, drag upwards -> nothing happens! BUG
5) Additionally, at this point these operations, dragging the toolbox to scroll it become very wonky. 

This bug got introduced with this commit: https://github.com/LLK/scratch-blocks/commit/06fa507dbbb989df09e7f18b8dfed475d8af664d. It is the 1st commit on which this bug occurs, any previous SHA's on develop do not have this bug. Any way to tag user bigeyex on this here?

### Operating System and Browser

Mac OS, both on Safari and Chrome

**Comment by rachel-fenichel** [comment]
@bigeyex 
@thisandagain I would recommend reverting that commit for now.

**Comment by bigeyex** [comment]
Hmm, interesting. Sorry for introducing this bug.
I proposed another solution in [pr874](https://github.com/LLK/scratch-blocks/pull/874), 
using the scrollTop instead of viewTop when calculating scrollbar position when dragging.
This will solve the "nudge a little when refreshing" without introducing new scroll problems.
How about that? Return what belongs to Caesar back to Caesar...

**Comment by thisandagain** [comment]
Thanks for reporting @MichaelZawadzki and thanks for the quick turnaround on a patch @bigeyex. 

@rschamp do you mind taking a look at this today? I am also able to reproduce the issue by attempting to scroll the blocks palette using two finger (drag) scroll on a MacBook Pro.

**Comment by rschamp** [comment]
Fixed in #874

**Comment by MichaelZawadzki** [comment]
Yup seems fixed now (even with that original offending line in there). So looks good from a quick test. We'll report if we see any issues as we use/test more with the latest version. Thanks!
