### ISSUE TITLE
Hacked blocks?

### ISSUE THREAD

**Issue by CatsAreFluffy** [LLK/scratch-blocks#875]
Sometimes, you want a block combination that isn't possible in the Scratch editor, like detecting a variable keypress or making a custom block with a color input. This issue has been brought up a few times on the forums, but those threads do not seem to be read by the ST (correct me if I'm wrong). What I'm suggesting is allowing the creation of hacked blocks in 3.0. For no-block dropdowns, the solution is obvious, for custom blocks, I would suggest adding a color input, a direction input, a variable input (like in [set [var] to (0)]), and a list input (like in (item (1 v) of [list])) (The other input types are less frequently useful, but could be added). That way, people can make custom blocks affecting variables ([multiply [var v] by (1)]), or blocks using colors ([draw text [text] with color [color]]) without hacking.

**Comment by chexbox** [comment]
The ability to define function in javascript would eliminate the need to use "hacked blocks".

**Comment by mrjacobbloom** [comment]
If extensions have any kind of Blockly access this would be pretty straightforward, otherwise we'll have to wait and see
