### ISSUE TITLE
Generators when imported in Node.js require ScratchBlocks be imported with the name Blockly

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#878]
### Expected Behavior

_This should work:_
```js
var ScratchBlocks = require("scratch-blocks");
require("scratch-blocks/javascript_compressed");
```

### Actual Behavior

_I need to do this:_
```js
var ScratchBlocks = require("scratch-blocks");
var Blockly = ScratchBlocks;
require("scratch-blocks/javascript_compressed");
```

### Steps to Reproduce

_Run above code in Node.js_

### Possible Fix

_As you can see in https://github.com/mo4islona/node-blockly they use a version of Blockly where javascript_compressed.js is a function that gets given the Blockly Object, you could build a javascript_compressed_node.js file that is a function instead of a script._

**Comment by thisandagain** [comment]
We don't formally support generators for `scratch-blocks`. We include them as a service to those who are interested in generators as an alternative to the VM, but we likely won't be making changes to packaging to make this easier.
