### ISSUE TITLE
Dragging from flyout when zoomed all the way out

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#880]
### Expected Behavior

Block starts out approximately where the cursor is.

### Actual Behavior

Block is offset from the cursor by an amount that is related to the zoom level.

### Steps to Reproduce

Open llk.github.io/scratch-gui
Zoom out all the way
Drag a block from the flyout

### Operating System and Browser
Any and all

**Comment by rachel-fenichel** [comment]
Probably not fixed by that merge.

**Comment by mrjacobbloom** [comment]
Closed by the merge again

**Comment by rachel-fenichel** [comment]
Nope, almost certainly not closed.  @mrjacobbloom why do you think this is closed?

**Comment by mrjacobbloom** [comment]
It was closed at the time I said it (not sure if you're joking)

**Comment by rachel-fenichel** [comment]
Ah, I thought that you were stating that the merge had fixed it, not that the merge had erroneously closed it.

Cheers,
Rachel

**Comment by towerofnix** [comment]
> Looks like this was accidentally closed by the merge/06-28 (the commit that "fixes" this was targeting an issue in google/blockly, not the issue with the same ID in LLK/scratch-blocks.)

edit: it looks like this one has already been automatically (and mistakenly) closed by a commit earlier, too.. :)
