### ISSUE TITLE
Reporter block with menu at the end does not render correctly

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#885]
### Expected Behavior

I should be able to create a reporter block with a menu following the text label that renders normally. 

### Actual Behavior

If I include a character after the menu (here, a period), the block renders as usual:

<img width="135" alt="screen shot 2017-05-11 at 3 57 19 pm" src="https://cloud.githubusercontent.com/assets/567844/25969426/d41b7050-3662-11e7-8efd-9a66ca392228.png">

If I omit the period (i.e. the intended design of the block), the block does not render correctly:

<img width="182" alt="screen shot 2017-05-11 at 3 58 09 pm" src="https://cloud.githubusercontent.com/assets/567844/25969470/f8135d10-3662-11e7-8193-cc71cd0f405a.png">

Weirdly, though, there are existing reporter blocks with menus at the end that render just fine (such as "current [year]" in sensing), so I could be describing this incorrectly. 

### Steps to Reproduce

Here are the [block definition](https://github.com/LLK/scratch-gui/blob/2e376dcbbba19ea0e1809858f10b91b4d892aa80/src/lib/blocks.js#L475-L494) and [toolbox xml](https://github.com/LLK/scratch-gui/blob/2e376dcbbba19ea0e1809858f10b91b4d892aa80/src/lib/toolbox-xml.js#L156-L160). 

### Operating System and Browser

Mac OS 10.11.6 Chrome 57.0.2987.133

**Comment by ericrosenbaum** [comment]
any ideas @tmickel ?

**Comment by tmickel** [comment]
Hey Eric!! happy to give a hint :P

Right now `Blocks.wedo2_dropdown_tilt` has an output, but it doesn't have an outputShape defined. Try adding this to the JSON definition (of wedo2_dropdown_tilt):

`outputShape: Blockly.OUTPUT_SHAPE_ROUND`

---

Why I suspect this might help:

First I inspected the block and saw this:
<img width="976" alt="screen shot 2017-05-16 at 11 45 10 pm" src="https://cloud.githubusercontent.com/assets/120403/26137858/18b23d96-3a93-11e7-8713-a8f02801afd0.png">
The first few path commands there are `m 0,0 m 20,0 H NaN`. Basically, it moves the SVG cursor to (0,0), then over 20 to make room for the left curve of the reporter. Then, H draws a horizontal line for the top of the block. In this case, it was NaN! That's pretty bad, and SVG stops trying at that point.

So why was it NaN? The most relevant functions are all in block_render_svg_vertical.js, which does all the computation and drawing for the vertical blocks. Most of the code here is `renderDraw` functions, which just assemble the SVG. The NaN is unlikely to be generated there (although in this case, if it was, it would be in renderTop). The first place to look with this kind of "math failure" is `renderCompute_`. `renderCompute_` goes through all the inputs/fields of a block and computes their sizes, padding, etc., and organizes them into "rows" (most blocks in Scratch have 1 row; exceptions include C-blocks, for example - basically, rows extend downward...). I put a debug breakpoint at the end of `renderCompute_` after stripping down the toolbox to only contain the relevant block. I noticed `NaN` showing up in a `row.paddingEnd`.

`row.paddingStart` and `row.paddingEnd` are a Scratch Blocks specific feature we did last year. Basically, they deal with situations like this:
<img width="103" alt="screen shot 2017-05-17 at 12 06 52 am" src="https://cloud.githubusercontent.com/assets/120403/26138114/c3dae30c-3a94-11e7-9118-c544f89556d3.png">
In the bottom block, the input is lined up with the parent block. In the top block, it's padded/offset farther to the right (`paddingStart`). Carl can tell you a lot more about the system we worked on for these. The rules are encoded in `Blockly.BlockSvg.prototype.computeOutputPadding_` and `Blockly.BlockSvg.SHAPE_IN_SHAPE_PADDING` here: https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L439

_A problem here is that the code assumes every output block has an outputShape defined_. This code ran: https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L933, but there was no outputShape for the dropdown menu, so it was looking up [null] and returning NaN for the padding. In the case with the period after the dropdown menu, the code detects that there's a text field there at the end, so there's no problem. Only the first and last input of the row are relevant to determining the padding.

you may want to:
- Detect when there's no outputShape defined and throw.
- Assume that no outputShape defined means square (this is true for drop-downs, but not true for other types like text inputs...)
- Just return 0 padding in this situation...
- Something else

Hope that makes a little bit of sense, it's a bit thorny to explain. The code is pretty documented, though, so you might have a better grasp of it by looking there and tracing the NaN yourself :)

let me know if you have any more questions...!

**Comment by ericrosenbaum** [comment]
Thanks @tmickel !!! That totally wins the prize for simple fix with thorough explanation :) Much appreciated!

As far as handling this situation in the future, my hope is that we can totally prevent it with our new extension system (proposal in progress [here](https://github.com/LLK/scratch-vm/wiki/Extensions-Proposal)). That includes a much more compact way of defining blocks that we'll use to generate the blockly-style block definitions, so we won't have to worry about this kind of copy-paste error.

**Comment by ericrosenbaum** [comment]
Fixed by https://github.com/LLK/scratch-gui/commit/e8f4dadf5f6251ddee7130ba14e14e9f49ae70bd
