### ISSUE TITLE
Performance: Creating blocks that refer to variables

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#887]
### Expected Behavior

DomToBlock on a block with a variable reference (FieldVariable or FieldVariableGetter) should not take much longer than creating a block with a FieldDropdown or FieldTextInput.

### Actual Behavior

Approximate benchmarking, by switching sprites in a project with lots of variables.  Here's a sample FieldTextInput.init call, taking 0.23ms:
![image](https://cloud.githubusercontent.com/assets/13686399/26008943/a3600126-36fb-11e7-87e9-474d1559994b.png)

And here is a sample FieldVariable.init call.  It takes 213ms, with 212ms of that spent refreshing the toolbox unnecessarily.
![image](https://cloud.githubusercontent.com/assets/13686399/26009011/dc0891e6-36fb-11e7-8524-d8670460ea49.png)

Slowdown mechanism:
WorkspaceSvg.createVariable is called for every field that references a variable, which causes the flyout to be refreshed.  

In Blockly, projects with variables usually have an auto-closing flyout, so it doesn't refresh.  In scratch-blocks the flyout is almost always open.  In Blockly createVariable 

Relevant code: https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_svg.js#L1004
```
Blockly.WorkspaceSvg.prototype.createVariable = function(name) {
  Blockly.WorkspaceSvg.superClass_.createVariable.call(this, name);
  // Don't refresh the toolbox if there's a drag in progress.
  if (this.toolbox_ && this.toolbox_.flyout_ && !Blockly.Flyout.startFlyout_) {
    this.toolbox_.refreshSelection();
  }
};
```

refreshSelection on the toolbox can take some time due to layout passes (tracked in #879).  But the problem here is that we're calling refreshSelection too many times.

### Steps to Reproduce

Load a workspace with plenty of variable references (see https://github.com/LLK/scratch-gui/issues/329).

### Operating System and Browser

All

### Possible Solutions

- Only refresh the toolbox if it's open to a category with variables (data, extensions, ?).  There are some pretty easy ways to backfire here--it would make changing sprites change speed depending on which category you have open.
- Block toolbox refreshing while loading new workspaces--this could be similar to how we block workspace resizing during a load
- Batch variable creation at the beginning of a workspace load.  This should be happening with the new typed variable work.

**Comment by picklesrus** [comment]
Another, not fully fleshed out, idea to throw out there:
What if we always kicked the refresh of the toolbox to the end of the frame? Even when we're just creating one variable via the flyout button.  I have some hope (thanks afternoon cup of coffee!) that the model and view might be disconnected enough for this to be a viable option. 
If we designed the mechanism right, perhaps we could use it for procedures and also to help with updating the flyout/toolbox for #1059.
