### ISSUE TITLE
Focused block field appears after setting visibility to hidden

### ISSUE THREAD

**Issue by fsih** [LLK/scratch-blocks#893]
Branched from https://github.com/LLK/scratch-gui/issues/358 (visible in gui when switching tabs)

Expected Behavior

Should not leave behind weird eyeball-like ghost-remnants of block input fields for .25 seconds after hiding the workspace

Actual Behavior

They do.

Steps to Reproduce

In vertical playground
Click on an input field in the flyout, e.g. 10 of 'move 10 steps'
Click hide.

**Comment by rachel-fenichel** [comment]
Can I get a gif of this?  I'm struggling to reproduce it in the vertical playground.

At a guess, Blockly.hideChaff is missing something.

**Comment by rachel-fenichel** [comment]
No gif needed, actually--I think I understand it now.

**Comment by fsih** [comment]
This will be fixed by https://github.com/LLK/scratch-blocks/pull/891/files#diff-5b6a36b94fcf664e4f8481d6a12eee63R279
