### ISSUE TITLE
Toolbox separator tag should add gap between blocks

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#894]
### Expected Behavior

In Blockly, the toolbox XML spec includes a convenient tag for adding [separators](https://developers.google.com/blockly/guides/configure/web/toolbox#separators).  We are likely to want to use this feature.

### Actual Behavior

The separators tag does not currently work. It looks like it was removed from the scratch-blocks code for laying out the toolbox.

### Steps to Reproduce

Include in the toolbox XML a tag like this between blocks:

`<sep gap="32"></sep>`

For the moment, I found a workaround by digging through the Blockly code. There's a deprecated feature mentioned in a code comment that allows you to add a gap attribute to a block tag, causing the gap to appear after that block:

`<block type="motion_movesteps" gap="32">`

### Operating System and Browser

Mac OS 10.11.6 Chrome 58.0

**Comment by rachel-fenichel** [comment]
Do you want separators, or just gaps?  Separators are styleable elements in the toolbox (in the example, it's a little white line).

**Comment by rachel-fenichel** [comment]
Sorry--that's not quite right.

Separator tags can go between categories, in which case they make those little white lines, or between blocks, in which case they add gaps.

**Comment by rachel-fenichel** [comment]
Aha, this works in the simple flyout but not the toolbox with categories, but it's a super simple fix.  

https://github.com/LLK/scratch-blocks/blob/develop/core/toolbox.js#L520

This isn't passing through 'SEP' tags.    Just add `case 'SEP':` after line 519 and you should be good to go.
