### ISSUE TITLE
Angle bracket character in block menu gets converted to HTML entity

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#899]
(Not sure if I am putting this issue in the correct repo)

### Expected Behavior

Characters in menu blocks should not change to HTML entities.

### Actual Behavior

In Lego Wedo extension, there is a hat block like this:

"When distance [<, >] [50]" 

Where the less than and greater than symbols are choices in a menu (block definition is [here](https://github.com/LLK/scratch-gui/blob/556b665e41209ae21d5730eac55967db91721392/src/lib/blocks.js#L429-L456)). When one of these blocks is on the workspace, and you switch to a different sprite and then back to it, the block the displays the HTML entity `&lt;`. 

![char-conversion](https://cloud.githubusercontent.com/assets/567844/26377654/2bbca57e-3fdf-11e7-9bcb-452c03e050eb.gif)

Note that symbols still display correctly in the drop-down menu, and also display correctly again after you select one of them from the menu.

The symbols display incorrectly when you load a json project file containing this block. 

There are blocks that include these same symbols (the operator blocks "[] < []" and "[] > []") but they do not have this issue, though the symbols in that case are not in menus.

All this could be related to the hacky way I'm using in the extension prototype to regenerate the toolbox. 

### Steps to Reproduce

Load a version of the scratch gui that uses the extension prototyping branches ([here](https://github.com/LLK/scratch-gui/tree/feature/extension-prototype) and [here](https://github.com/LLK/scratch-vm/tree/feature/extensions-prototype)).

Click the Lego brick button to add a Lego Wedo extension sprite.

Drag a "When distance [<, >] [50]" block onto the workspace.

Switch to another sprite, and then back to the Wedo sprite.

### Operating System and Browser

Mac OS 10.11.6 Chrome 58.0.3029.110

**Comment by chrisgarrity** [comment]
Moved to LLK/scratch-vm#580
