### ISSUE TITLE
Block menu opens and immediately closes on click

### ISSUE THREAD

**Issue by ericrosenbaum** [LLK/scratch-blocks#901]
### Expected Behavior

Clicking on the menu in a block in the workspace should cause it to open (and stay open).

### Actual Behavior

The menu immediately closes again.

Note that this occurs only in the workspace, not in the toolbox.

![menu-bug](https://cloud.githubusercontent.com/assets/567844/26425495/f52a8c32-40a2-11e7-80cd-55c3e5f104c5.gif)

Weirdly, clicking for a longer time (maybe half a second) causes the expected behavior. 

### Steps to Reproduce

Drag a block with a menu onto the workspace, such as "point towards [mouse pointer]".

Click on its menu to open it.

### Operating System and Browser

Mac OS 10.11.6 Chrome 58.0.3029.110

**Comment by rachel-fenichel** [comment]
Probably mine

**Comment by rachel-fenichel** [comment]
We're probably calling hide() on the dropdown div at the beginning of a gesture, but it's waiting to animate out.  So the dropdown div is shown on mouse up and then the timer fires and it's hidden again.  Waiting longer before the mouse up would exceed the timer.
