### ISSUE TITLE
Suggestion: Dynamic procedures block in toolbox

### ISSUE THREAD

**Issue by greenSnot** [LLK/scratch-blocks#904]
![image](https://cloud.githubusercontent.com/assets/11901882/26479076/3e8154d6-4203-11e7-889d-fb2742f6e45a.png)

**Comment by luxaritas** [comment]
Out of curiosity, where is the screenshot from? There's some neat UI decisions.

**Comment by greenSnot** [comment]
@LFP6  box.game/#219563

**Comment by mrjacobbloom** [comment]
Pretty sure this was closed unintentionally by the merge

**Comment by greenSnot** [comment]
@mrjacobbloom Yeah, I didn't see any codes related to so.
@paulkaplan Can you reopen it?

**Comment by rschamp** [comment]
Thanks for the suggestion — would you mind dropping this into where we're tracking custom reporters? https://github.com/LLK/scratch-vm/issues/79
