### ISSUE TITLE
Blockly.Flyout.createBlockFunc_ not found from core/flyout_base.js Blockly.Flyout.prototype.addBlockListeners_

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#905]
### Expected Behavior

core/flyout_base.js Blockly.Flyout.prototype.addBlockListeners_ should find method Blockly.Flyout.createBlockFunc_.

### Actual Behavior

core/flyout_base.js method Blockly.Flyout.prototype.addBlockListeners_ cannot find method Blockly.Flyout.createBlockFunc_. (But I see prototype.createBlockFunc_ in gh-pages/playgrounds/core/flyout_base.js.)

### Steps to Reproduce

I have a project that loads a workspace that uses a flyout that autoCloses and doesn't use playgrounds.

### Operating System and Browser

Mac OS 10.11.6 Safari 10.0_

**Comment by rachel-fenichel** [comment]
https://github.com/LLK/scratch-blocks/blob/develop/core/flyout_base.js#L538

```
  if (this.autoClose) {
    this.listeners_.push(Blockly.bindEventWithChecks_(root, 'mousedown', null,
        this.createBlockFunc_(block)));
    this.listeners_.push(Blockly.bindEventWithChecks_(rect, 'mousedown', null,
        this.createBlockFunc_(block)));
  } else {
    this.listeners_.push(Blockly.bindEventWithChecks_(root, 'mousedown', null,
        this.blockMouseDown_(block)));
    this.listeners_.push(Blockly.bindEventWithChecks_(rect, 'mousedown', null,
        this.blockMouseDown_(block)));
  }
```

**Comment by rschamp** [comment]
@rachel-fenichel @paulkaplan Is this due to a bad merge?

**Comment by rachel-fenichel** [comment]
No, I think I just missed a spot while updating dragging--it probably also happens in blockly as well.  I will not get to it this week, but I'll take a look next week.

**Comment by rachel-fenichel** [comment]
Fixed by https://github.com/LLK/scratch-blocks/pull/1056
