### ISSUE TITLE
Sound doesn't play when connecting blocks in the workspace

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#906]
### Expected Behavior

When blocks connect in the workspace, the connect sound should play.

### Actual Behavior

No sound plays when blocks are connected in the workspace.

### Steps to Reproduce

In horizontal_playground.html or vertical_playground, connect blocks on the workspace.

Note that the dispose sound plays when throwing a block/script in the trashcan.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Chrome Version 58.0.3029.110

**Comment by rachel-fenichel** [comment]
On Blockly: https://github.com/google/blockly/issues/1160

**Comment by thisandagain** [comment]
Tracking in google/blockly#1160

**Comment by rachel-fenichel** [comment]
Fixed upstream.

**Comment by msintov** [comment]
Thanks @rachel-fenichel !

I believe that in scratch-blocks, the same fix that was applied upstream to dragged_connection_manager.js also needs to be applied to insertion_marker_manager.js Blockly.InsertionMarkerManager.prototype.applyConnections.

**Comment by msintov** [comment]
@paulkaplan Please see my note above about this also needing to be applied to insertion_marker_manager.js Blockly.InsertionMarkerManager.prototype.applyConnections. Does that sound right?

**Comment by rachel-fenichel** [comment]
Yes, that sounds right.
