### ISSUE TITLE
Hit area of dropdown button under horizontal blocks is smaller than before

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#907]
### Expected Behavior

In horizontal_playground.html, when the user taps any part of the dropdown button under the envelope blocks, the dropdown should display.

### Actual Behavior

If the user taps on the white down arrow in the middle of the dropdown button under the envelope blocks, the dropdown displays. If the user taps anywhere else on the button, the dropdown does not display.

This new behavior appears to have been introduced with 6275e11, the new dragging commit. Is the smaller hit area intentional?

### Steps to Reproduce

1. Load horizontal_playground.html.
2. Tap the dropdown button under either of the envelope blocks without tapping on the white down arrow. The blocks can be either in the flyout or in the workspace.

### Operating System and Browser

_e.g. Mac OS 10.11.6 Chrome Version 58.0.3029.110

**Comment by rachel-fenichel** [comment]
Nope, that's not intentional.  Thanks for noting which commit it came in on.  I'll take a look.

**Comment by msintov** [comment]
This issue also applies to other dropdowns such as those containing a number with numpad dropdown.

**Comment by rachel-fenichel** [comment]
Fixed by #927
