### ISSUE TITLE
Categories Layout: hardcoded 2 categories per row 

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-blocks#914]
Toolbox.js hard-codes the two categories per row layout. Make it so a CSS file can override the categories panel layout to 1 column.

---
Moved from LLK/scratch-www#1327
/cc @paulabonta

**Comment by rachel-fenichel** [comment]
How important (1-10) is it that this configuration be in CSS?

**Comment by thisandagain** [comment]
@rachel-fenichel @rschamp Not super important that it be in CSS (I'd say a 3?).

**Comment by picklesrus** [comment]
Is this for smaller screens?  Theoretically we should be able to make it responsive, though I don't know how much work that would be... Or is it really just something you'd want to explicitly set?

**Comment by thisandagain** [comment]
Not so much for smaller screens but rather for microworlds or other experiences where we have a small number of categories.

**Comment by picklesrus** [comment]
Makes sense. You can just close up that can of worms I tried to open.  Not really sure where that Monday morning optimism came from :)

**Comment by thisandagain** [comment]
LOL. It never happened.

![x-all-the-things-template jpg](https://cloud.githubusercontent.com/assets/747641/26787005/7301fe1a-49d6-11e7-9c6e-4872af41c0fc.png)
