### ISSUE TITLE
Using domToText output produces an error when trying to deserialize

### ISSUE THREAD

**Issue by MichaelZawadzki** [LLK/scratch-blocks#918]
### Expected Behavior

Calling: Blockly.Xml.domToText(xml) should produce text that is valid, meaning that later it can be deserialized using:
```
var xml = Blockly.Xml.textToDom(input.value);
Blockly.Xml.domToWorkspace(xml, workspace);
``` 
        
### Actual Behavior

Currently is serialization is done through domToText (meaning the XML is not-pretty, aka on a single line), then the matching deserialization, specifically domToWorkspace will throw an error:
```
Uncaught Error: 'variables' tag must be the first element in theworkspace XML, but it was found in another location.
    at Object.Blockly.Xml.domToWorkspace (xml.js:358)
    at fromXml (vertical_playground.html:126)
    at HTMLInputElement.onclick (vertical_playground.html:544)
```
### Steps to Reproduce

There are 2 simple (and similar) ways to reproduce this bug:

1) In the vertical playground, replace domToPrettyText (on line 117) with domToText.
2) Launch the modified playground
3) Place any block on the workspace
4) Hit "Export to XML" (so you'll get a non-pretty XML text in the text field)
5) Delete the block from the workspace (optional)
6) Hit "Import from XML"
7) Error in console (as pasted above) and the block is not loaded

Alternatively, without replacing domToPrettyText with domToText, another way to do this would be to:
1) Launch the default playground
2) Place any block on the workspace
3) Hit "Export to XML" 
4) Delete the block from the workspace (optional)
5) In the text field, edit the text by removing the new line before the <variables> text (so that this appears on the first line). 
6) Hit "Import from XML"
7) Error in console (as pasted above) and the block is not loaded

### Operating System and Browser

Chrome on Mac

### Workaround

Just don't use domToText but instead use domToPrettyText. This is not ideal I guess as it includes non-essential characters but its no big deal.

**Comment by marisaleung** [comment]
Bug is fixed here!
https://github.com/google/blockly/commit/f7f664063b4358fd9df985fc66f6fd8679a54efa
