### ISSUE TITLE
Top half of block cut off when using a statement input inside a square reporter

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#919]
### Expected Behavior

_You see the whole block_

### Actual Behavior

_The top half is cut off, statements offset, and bottom has no padding_

### Steps to Reproduce

_Add my code to blocks_vertical/motion.js and and create the block_

### My Code

```js
Blockly.Blocks['motion_lambda'] = {
  init: function() {
    this.jsonInit({
      "message0": "do %1",
      "message1": "and return %1",
      "args0": [
        {
          "type": "input_statement",
          "name": "FUNCTION"
        }
      ],
      "args1": [
        {
          "type": "input_value",
          "name": "RETURN"
        }
      ],
      "inputsInline": false,
      "category": Blockly.Categories.motion,
      "output": "String",
      "outputShape": Blockly.OUTPUT_SHAPE_SQUARE,
      "colour": Blockly.Colours.motion.primary,
      "colourSecondary": Blockly.Colours.motion.secondary,
      "colourTertiary": Blockly.Colours.motion.tertiary
    });
  }
};
```

### Screenshot
![block](https://cloud.githubusercontent.com/assets/17478432/26744900/1c4d6284-47b6-11e7-9313-5b3b43177714.PNG)

### Operating System and Browser

_Google Chrome and Windows 10_

**Comment by rachel-fenichel** [comment]
Long shot: @tmickel do you know what's going on here?

**Comment by tmickel** [comment]
Hmmm... well...not precisely...but I think it is safe to say we did the rendering code for blocks with outputs (i.e. reporters) assuming that the shape would be a single row.

To start imagining reporters with multiple rows is a lot of work. It might be intuitive for a "square"-shaped reporter like the one above (just don't render notches?) but for rounded ones and "hexagonal" boolean ones, it's very strange to think about having statement inputs like above...

maybe it could be considered to add a check that a block with output contains no statement inputs and only a single row; if this is not the case, it's not currently supported by the rendering.
