### ISSUE TITLE
Field selection targets are too small

### ISSUE THREAD

**Issue by thisandagain** [LLK/scratch-blocks#920]
### Expected Behavior

- Clicking anywhere on a selection field should trigger the drop-down

### Actual Behavior

- Only clicking in the very center of the field will produce the drop-down

### Steps to Reproduce

![untitled](https://cloud.githubusercontent.com/assets/747641/26784161/1244e3b4-49ca-11e7-8159-81562d4ad6ce.gif)

### Operating System and Browser

MacOS 10.12.4 | Chrome Version 58.0.3029.110 (64-bit)

/cc @paulkaplan @rschamp

**Comment by paulkaplan** [comment]
Field selection issues came up for many people during our most recent playtest. I'm not sure if this has the same root cause, but sounds very similar. Here are some example quotes.

> It's hard to click the text box to add [a number], most of the area drags. It's also hard to click on drop down arrows...

> Am I imagining that it's kinda hard to click in the field inputs & pull up the dropdown menus in the blocks?

> When trying to click to enter a number in a block (e.g., set y to _) it triggered block instead.

> Clicking on the variable circles is really particular... you have to be on the exact right spot to input a number.

**Comment by thisandagain** [comment]
Interesting. I'm guessing it's the same issue (I would also guess it's a recent regression). Thanks for the context @paulkaplan. I'll expand the scope here.

**Comment by thisandagain** [comment]
@rschamp @carljbowman This feels like a blocker for the next play test. Assigning to @paulkaplan for this iteration.

**Comment by picklesrus** [comment]
@paulkaplan Do you happen to know if the play test you're referring to was before or after @rachel-fenichel's rewrite of the drag code?

**Comment by thisandagain** [comment]
@picklesrus After. The internal play test was on Friday 6/2.

**Comment by picklesrus** [comment]
Cool. Thanks! Then it is probably related to #907.

**Comment by rachel-fenichel** [comment]
It looks like previously all touches on a single-field shadow block were treated as touches on that field.  The fields themselves aren't the full size of the block, so clicks on the actual fields are showing the editors but clicks on the background of the shadow block are treated as block clicks.

I can fix this, but I think it's a scratch-blocks specific bit of behaviour.
