### ISSUE TITLE
Block edge & block dropdown menu too close together

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#921]
### Expected Behavior

More space in between the edges of the blocks & block parts.

### Actual Behavior

Saskia, Shruti and I independently noticed during the Catch Game internal playtest (6/2/17) that the spacing between the blocks & the dropdown menu border looked strange.

<img width="330" alt="screen shot 2017-06-05 at 9 42 19 am" src="https://cloud.githubusercontent.com/assets/1320456/26786106/727886ba-49d3-11e7-8131-c002be911a64.png">

### Steps to Reproduce

Drag out & connect the blocks shown in the screenshot above.

### Operating System and Browser

_Chrome, Mac OS_

**Comment by thisandagain** [comment]
Blocks should be implemented to spec
/cc @carljbowman

**Comment by thisandagain** [comment]
Resolved in https://github.com/LLK/scratch-blocks/pull/1018
