### ISSUE TITLE
Wrong shape & colour in math_number

### ISSUE THREAD

**Issue by greenSnot** [LLK/scratch-blocks#933]
### Expected Behavior
![image](https://user-images.githubusercontent.com/11901882/26936529-88e4791a-4ca1-11e7-927d-c6a364d0c2cc.png)

### Actual Behavior
![image](https://user-images.githubusercontent.com/11901882/26936498-6f7f329e-4ca1-11e7-8d5c-f0c1ab17e4a2.png)

Wrong shape in math_number, wrong block colour and text colour when it's shadow block but its shape is correct.

### Steps to Reproduce
I am trying to override default math_number by jsonInit. Something like this
```
  {
    type: 'math_number',
    message0: '%1',
    args0: [{
      type: 'field_number',
      name: 'NUM',
    }],
    output: 'Number',
    category: 'data',
  },

```
Then get result above.
Later, I found it has nothing to do with overriding. I use another name, such as 'my_math_number', the result is the same.

### Operating System and Browser

Mac OS Chrome

**Comment by thisandagain** [comment]
Hi @greenSnot we can't really understand what you are trying to do here. Can you please provide more context and a description of exactly what you are trying to do?

**Comment by greenSnot** [comment]
@thisandagain Well, I am trying to apply single math_num, empty_array, logic_bool, empty_string block into toolbox.  Your examples seem lack of them.
