### ISSUE TITLE
Undo/Redo functionality is broken

### ISSUE THREAD

**Issue by MichaelZawadzki** [LLK/scratch-blocks#934]
### Expected Behavior

Using undo should undo 1 user action. Pressing redo should redo the last undo action.

### Actual Behavior

Lots of strange things are happening. In the simplest example of just placing some blocks pressing undo removes some of the inner shadow blocks, and also places blocks in the upper-left.

### Steps to Reproduce

1) Launch the playground from current sources
2) Drag several blocks onto the stage: say 1 move block + 1 turn left block + 1 turn right block
3) Right-click on the workspace and click undo
4) Bug -> notice the last placed blocked is not removed but instead the inner shadow block disappears. 

Further undo actions after this create more buggy behavior:
5) Next undo seems to actually remove the block
6) Next 2 undo's behave like the 1st 2
7) 5th undo makes a block appear in the upper-left

Additionally, clicking Redo does not redo the actions (bugged or not). It might not be worth commenting more about this given undo is broken. 

### Operating System and Browser

Chrome on Mac

**Comment by rachel-fenichel** [comment]
At first glance this looks like a problem with event grouping.  Hopefully onlt during drags, possibly in other places.

**Comment by paulkaplan** [comment]
I just noticed this also, here is a really simple one:

1. Connect a block to an input
2. Undo

![undo-shadow-broken](https://user-images.githubusercontent.com/654102/26974110-d85de7f6-4ce7-11e7-899f-a017be19af9a.gif)

@rachel-fenichel I noticed this while trying to debug the issue with shadow blocks we discussed. Does my example have something to do with that?

**Comment by rachel-fenichel** [comment]
@paulkaplan this is a problem with event grouping during drags.  You're seeing it undo one event at a time instead of undoing multiple events as a group.  You can see this by turning on event logging in the playground.

**Comment by jwzimmer-zz** [comment]
This came up during Catch Game internal playtest II (6/12/17):
I noticed undo delete gives me each block in a stack one at a time, not the entire stack.

**Comment by rachel-fenichel** [comment]
Last time I checked in, fixing this was not a requirement for the play test.  Let me know if that changes.
