### ISSUE TITLE
Do blocks need to know what category they belong to?

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#939]
Block category is set in jsonInit, but I don't see it being used anywhere.  Is it just a legacy?

**Comment by mrjacobbloom** [comment]
It's for CSS styling, see #638

**Comment by rachel-fenichel** [comment]
Right--I can see that it's adding to the styles on the blocks, but I haven't found any definitions of those styles in the scratch-blocks CSS.  Are they for use by people who are styling scratch-blocks above and beyond what's contained in the core library?

**Comment by mrjacobbloom** [comment]
Yeah that's the idea, for users to theme the blocks themselves
