### ISSUE TITLE
"Create variable" button click is only on the button text, not the button rect

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#941]
### Expected Behavior

Clicking anywhere on the "create variable" button makes the modal appear.

### Actual Behavior

Only clicking on the text makes the modal appear.

### Steps to Reproduce

Open the vertical playground
Go to the "Data" category
Click on the background of the "create variable" button

### Operating System and Browser

Ubuntu, Chrome

**Comment by thisandagain** [comment]
Can't repro on MacOS, Chrome (latest) but we should try to repro on Ubuntu.

**Comment by paulkaplan** [comment]
There is some funky behavior on that button. Sometimes clicking the whole button works, but sometimes it doesn't. Here is a gif of what I saw. Note that cursor style correlates directly with clickability, so any time you see the hand it was possible to click.

![funky-click-behavior](https://user-images.githubusercontent.com/654102/27186634-f1c84c30-51b6-11e7-8218-790877301b52.gif)

**Comment by rachel-fenichel** [comment]
@paulkaplan that matches what I was seeing.  It seems like once you hit the text it becomes clickable, and then stays clickable to the edge of the button, but I'm not sure.

I quickly checked the Blockly playground and couldn't repro, but that button is styled pretty differently.

**Comment by ateesdalejr** [comment]
@paulkaplan I'm seeing this behavior as well.

**Comment by msintov** [comment]
We fixed this issue internally (at least for Android) by adding a transparent background to the flyout label attributes in the call to create the background rectangle in Blockly.FlyoutButton.prototype.createDom.

**Comment by AmazingMech2418** [comment]
@rachel-fenichel I can hover over the text and then click anywhere in the box, but it seems like the event listener is only attached to the text with a mouseover event with a mouseout on the rectangle.

**Comment by ericrosenbaum** [comment]
On touch on chrome OS this problem makes the buttons very difficult to click (usually takes six or seven tries).
