### ISSUE TITLE
Should the green flag hat block be more prominent at the top of a stack?

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#943]
- Green flag block is smaller in 3.0 than 2.0
- Colors of Events blocks stand out less in 3.0 than 2.0
- Colors of Events/ Control are closer to each other in 3.0 than 2.0

Split-off from https://github.com/LLK/scratch-gui/issues/409:
@jwzimmer reported: "Width of green flag hat block being so small compared to other blocks makes it hard to read"
If you compare the width of the hat block in 3.0 versus in the 2.0 cards, the hat block does not stick out as far at the top of the stack (in 3.0). I think this makes it a little harder to read/ identify each stack. Also, the colors of control/ events are closer to each other in 3.0 than 2.0. (And their relative light/ dark -ness switched.)

**Comment by chrisgarrity** [comment]
Moved to LLK/observations#29
