### ISSUE TITLE
Dropdown menus should not be droppable

### ISSUE THREAD

**Issue by jwzimmer-zz** [LLK/scratch-blocks#952]
### Expected Behavior

I think the menu should not be droppable (right, @carljbowman?)

### Actual Behavior

Current 3.0 behaviour when combining unexpected inputs/ blocks - @ericrosenbaum & I were trying out the speech & wedo extensions and noticed that currently we can drop the reporter "speech"  into the dropdown menu of "set voice to" and that we could drop "tilt angle [up]" into the "tilt angle [up]" block (this yielded "undefined").

### Steps to Reproduce

Add the WeDo 2.0 & Speech extensions, then drag "tilt angle [up]" into itself, and put that in the speak block. It should say "undefined".
<img width="267" alt="screen shot 2017-06-15 at 3 23 20 pm" src="https://user-images.githubusercontent.com/1320456/27198033-9649ed64-51de-11e7-9e6a-1e45668bf994.png">

### Operating System and Browser

_Mac, Chrome 59_

**Comment by RoboErikG** [comment]
@paulkaplan similar to the variable dropdown issue you just fixed.

**Comment by rachel-fenichel** [comment]
Some dropdowns can accept blocks, and some can't.  

![image](https://user-images.githubusercontent.com/13686399/27209279-b1b2ce38-51ff-11e7-8bdb-d38f9be0088d.png)
The first block in this screenshot can accept a block, but the second one can't.

A dropdown that can be overridden by a dragged block should be implemented as an input with a shadow block (in the toolbox).  

A dropdown that cannot be overridden by a dragged block should be implemented as a field.

**Comment by paulkaplan** [comment]
Yup, those probably shouldn't be droppable. @ericrosenbaum I can help you fix this on your extensions branch, but I'm going to close this issue here because it can't be fixed on scratch-blocks repo right now.
