### ISSUE TITLE
Hacky %m.(thing) not implemented

### ISSUE THREAD

**Issue by TheBrokenRail** [LLK/scratch-blocks#957]
### Expected Behavior

_It is implemented and shows a custom menu_

### Actual Behavior

_It just shows text_

### Steps to Reproduce

_Create a hacked custom block and add a % (List found here https://docs.google.com/spreadsheets/d/1uT1vHi6IUUaUix5y3k4p28p2No6pvLNKF_yrtrajEY4/edit#gid=0)_

**Comment by rschamp** [comment]
We won't be explicitly supporting 2.0-style hacked blocks. But this kind of thing should be possible with extensions once they're implemented.

**Comment by towerofnix** [comment]
@rschamp It may be best to consider implementing support for rendering those blocks correctly (when custom blocks themselves are implemented), though. I can't imagine it would be good if a bunch of old 2.0 projects' scripts (visually) broke, even though they're technically using hacks.
