### ISSUE TITLE
Right-click on variable blocks is broken

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#964]
### Expected Behavior

Right-clicking on a variable getter should show a menu with all of the other variable names in the workspace.

### Actual Behavior

Right-clicking does nothing.

### Steps to Reproduce

Create two variables.
Drag a variable getter block into the workspace.
Right-click on the variable getter block.

### Operating System and Browser

Chrome on Ubuntu.

**Comment by carljbowman** [comment]
@rachel-fenichel - We should take a look at this as apart of the Variable spec.

**Comment by rachel-fenichel** [comment]
Okay.  It used to do what Scratch 2.0 did, and the change that broke it is straightforward.
