### ISSUE TITLE
Broadcast <message> blocks should not accept dropped blocks

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#971]
![image](https://user-images.githubusercontent.com/13686399/27310378-b72d860c-550e-11e7-87b5-8952290da7e6.png)

The bottom two blocks should look like the first block (square, non-shadowed field instead of rounded input with a shadow block).

**Comment by towerofnix** [comment]
This would be a step back from 2.0 – and even 1.4 – which both have support for dropping blocks in the "broadcast" and "broadcast and wait" blocks; it would undoubtedly break some projects (in fact, I've used reporters in broadcasts myself).

**Comment by rachel-fenichel** [comment]
@liam4 I didn't realize that was in 2.0.  Not an issue here then.
