### ISSUE TITLE
How can i define a function block!

### ISSUE THREAD

**Issue by lixiaocheng18** [LLK/scratch-blocks#973]
Hello!
        How can i define a function block, like blockly, thanks!

### Operating System and Browser

_e.g. Mac OS 10.11.6 Safari 10.0_

**Comment by carljbowman** [comment]
@lixiaocheng18 - Could you be a little more specific with what you are attempting to do?

If you are trying to create a 'Custom Block' like in 2.0, we have not implemented that feature yet.

**Comment by RoboErikG** [comment]
@lixiaocheng18 Here's the issue tracking 'Custom Blocks' https://github.com/LLK/scratch-blocks/issues/607 . Is that what you're looking for?
