### ISSUE TITLE
Variable Deletion Spec

### ISSUE THREAD

**Issue by marisaleung** [LLK/scratch-blocks#975]
There are two options for when variables should come back that we are discussing and would like your input or specification.

1. Letting it come back next time the toolbox is refreshed.

2. Explicitly comes back when a block with that variable runs.

I understand the second one is how scratch 2 works. The first option is  easier to implement since we can just do a light version of delete by just removing variable blocks from the flyout instead of removing them from the variable map.

**Comment by mrjacobbloom** [comment]
Potentially relevant: https://github.com/LLK/scratch-blocks/issues/372#issuecomment-227532505
> Update on deletion: we agreed to make deleting a variable remove all instances of it in the workspace (after confirmation) but not in the backpack.

> Hmmmmm... what if, the drop-down changes to "blank"?

>That seems non-obvious, especially in a large script. Also what does it mean for the dropdown to say "blank", from a runtime perspective? ... If it were blank I would suggest also turning it red (shouldn't be too hard) but that seems counter to scratch philosophy of no errors.

**Comment by RoboErikG** [comment]
The Scratch team has been revisiting that discussion. We're waiting for confirmation from Carl on the exact behavior they want to move forward with.

**Comment by RoboErikG** [comment]
Per in person discussion, we'll move forward with 1. which is easier to implement and try it out. If we don't like the behavior we can move to a more involved solution.
