### ISSUE TITLE
Confirmation dialog for deleting blocks is inconsistent with right-click menu.

### ISSUE THREAD

**Issue by rschamp** [LLK/scratch-blocks#978]
### Expected Behavior

When you right click and choose "Delete X blocks", the confirmation dialog should say "Delete all X blocks?"

### Actual Behavior

_Well_, it instead adds one to the number, it seems:
![scratch-gui bug](https://user-images.githubusercontent.com/28599280/27383110-174c8458-56bc-11e7-97d9-574a810213cc.PNG)

### Steps to Reproduce

Have 3 or more blocks in the editor, right click, choose "Delete X blocks". This will give you "Delete all X+1 blocks?"

### Operating System and Browser

Windows 10 Chrome 58

---
Moved from LLK/scratch-gui#464
/cc @Kenny2github

**Comment by rachel-fenichel** [comment]
Not adding one to the number--it's counting all of the blocks, including shadow blocks.

**Comment by marisaleung** [comment]
Is the current plan to reintegrate shadow blocks?
With this fix this shouldn't be a problem https://github.com/LLK/scratch-blocks/pull/948

**Comment by rachel-fenichel** [comment]
There are plenty of uses of shadow blocks outside of variables.  Those will continue to exist.  In the example above the "10" block is a shadow block, which is why it's adding 1.

**Comment by RoboErikG** [comment]
We could probably not count shadow blocks in Blockly as well.

**Comment by rachel-fenichel** [comment]
In Blockly they are clearly blocks.  In scratch-blocks they look like fields instead of blocks, so the user shouldn't know about them.  I think Blockly should keep the current behaviour.

**Comment by rachel-fenichel** [comment]
To fix, just replace `deleteList.length` with `String(deleteCount)` on line 1374 of `workspace_svg.js`
https://github.com/LLK/scratch-blocks/blob/develop/core/workspace_svg.js#L1374

Then it will match line 1364.

**Comment by mrjacobbloom** [comment]
This should be resolved now
