### ISSUE TITLE
Min spacing not being respected for short blocks with dropdowns

### ISSUE THREAD

**Issue by paulkaplan** [LLK/scratch-blocks#983]
![image](https://user-images.githubusercontent.com/654102/27498662-1fef1990-582e-11e7-9b7c-16f7d12a24d8.png)

Carl mentioned that there should be a minimum length that forces things to come after the notch, per this diagram: 
![image](https://user-images.githubusercontent.com/654102/27498679-378115f4-582e-11e7-978d-838f9331ecdb.png)

It looks like the relevant variable is `Blockly.BlockSvg.NO_PREVIOUS_INPUT_X_MIN` in `block_render_svg_vertical.js`. It doesn't seem to be used when there are dropdowns, but I'm not familiar enough with the blockly terminology to understand why :( halp.

**Comment by rachel-fenichel** [comment]
> It doesn't seem to be used when there are dropdowns

Not quite.  It's being used only for inputs where you can drop a block.  

![image](https://user-images.githubusercontent.com/13686399/27500960-8fd87760-581f-11e7-8c8b-3e5d3aa4f000.png)

**Comment by rachel-fenichel** [comment]
The difference is that where you can drop a block there's a Blockly.Input with a block attached, and that block has a dropdown field inside it.  Where you can't drop a block it's just a Blockly.Field.  So it's hitting different code paths.

**Comment by paulkaplan** [comment]
Ah good example, thanks for the clarification. I think I see that code path now, [here](https://github.com/LLK/scratch-blocks/blob/develop/core/block_render_svg_vertical.js#L1130-L1135).
