### ISSUE TITLE
Right-click on variable getter in palette should show rename, delete, and help.

### ISSUE THREAD

**Issue by rachel-fenichel** [LLK/scratch-blocks#985]
### Expected Behavior

Right-clicking on the variable getter in the palette should show "rename", "delete", and "help." 

### Actual Behavior

It only shows "Help."

### Steps to Reproduce

1. Create a variable 'a'.
2. Right click the getter in the palette.

### Operating System and Browser

All

**Comment by towerofnix** [comment]
(..I accidentally interpreted this title as "variable getters in the palette" "should only show delete option" 🙃 ..)

**Comment by marisaleung** [comment]
Quick note: When right clicking a variable in the getter block in the palette, nothing shows up in the context menu.

**Comment by marisaleung** [comment]
Update: Rename Variable currently is not an option for either of these context menus.
