### ISSUE TITLE
Data category "Create variable" button doesn't bring up text entry or keyboard on mobile

### ISSUE THREAD

**Issue by msintov** [LLK/scratch-blocks#987]
### Expected Behavior

Pressing "Create Variable..." button in vertical_playground.html should bring up a text entry area and keyboard on iOS.

### Actual Behavior

No text area or keyboard displays.

After pressing "Create Variable...", the code ends up calling `Blockly.prompt`:

/**
 * Wrapper to window.prompt() that app developers may override to provide
 * alternatives to the modal browser window. Built-in browser prompts are
 * often used for better text input experience on mobile device. We strongly
 * recommend testing mobile when overriding this.
 * @param {string} message The message to display to the user.
 * @param {string} defaultValue The value to initialize the prompt with.
 * @param {!function(string)} callback The callback for handling user response.
 */
Blockly.prompt = function(message, defaultValue, callback) {
  callback(window.prompt(message, defaultValue));
};

I believe Blockly has the same issue.

### Steps to Reproduce

In a mobile webview (like iOS WKWebView), load vertical_playground.html. Select the "Data" category and press "Create Variable...".

### Operating System and Browser

iOS 10.3 WKWebView

**Comment by rachel-fenichel** [comment]
Interesting.  The current Blockly playground doesn't have this problem on Android in a web view.  Nor does llk.github.io/scratch-gui in a webview on iOS*

My first thought is that you should try it on a different device.  On some devices you have the option of disabling all popups if the web page is showing too many of them, and then you never see prompts again.


*though it has a different problem: It doesn't close the prompt after you hit OK.  @rschamp does that belong in scratch-blocks or scratch-gui?

**Comment by msintov** [comment]
Actually I do see it working on Android (tested Android 6.0). A dialog box is displayed with title "The page at file:// says:" at the top, followed by "New variable name:"  and then the prompt for the variable name below.

**Comment by rachel-fenichel** [comment]
Interesting.  Does that mean that it's only an issue on iOS, or only on a specific device?

**Comment by msintov** [comment]
We find that it is an issue on iOS in general, at least with WKWebView. Clicking the button seems to do nothing.

**Comment by msintov** [comment]
Actually the solution for iOS WKWebView is to do something like the following, where the WKUIDelegate is set and can respond to the window.prompt request from JavaScript with a UIAlertController containing a text field for entry:

https://gist.github.com/davbeck/8613f2e74e8fc335c14d

**Comment by carljbowman** [comment]
@msintov Does that resolve the issue for you or is there something we should plan to support within `scratch-blocks`?

**Comment by msintov** [comment]
@carljbowman Yes, the issue is resolved for me. Thank you!
